### ISSUE TITLE
Trains will not show. They can place and are there, they won't show.

### ISSUE THREAD

**Issue by DanTDMJace** [TeamOpenIndustry/ImmersiveRailroading#1001]
So, I have been using IR for a while and have never seen something like this. Here is what I did:

I went into my inventory and got an SD40-2 (ive tried others) and placed it.
It was not showing, but it was there. I placed it on the tracks and nothing happened. 

IR version 1.12.2

**Comment by km00700** [comment]
- 1.12.2 is an MC version. Are you using the latest IR release for that MC version? 

- Is that on a server, or in single player?

- System specs? (total RAM, graphics card, and Allocated RAM) 

- Could you post "latest.log" from your ".minecraft/logs" folder from a session where you try and place the stock?
