### ISSUE TITLE
Trains bug on server

### ISSUE THREAD

**Issue by Bogdan7200** [TeamOpenIndustry/ImmersiveRailroading#1002]
### Mods:
_Immersive Railroading
Better animals +
Create-mc
Quark
OptiFine
MrCraifish Vehicle mod
Siple voice chat
Security Craft
MrCraifish gun mod
MrCraifish furniture mod
Chisels and bits
Cretive Core
UniversalModCore
City Blocks
Obufscate
Backpaked
Cosmetic Armor reworked
AutoRegLib
Item physic
Backpaker
Track API_

### System Information
 OS: Windows 10 pro
 System Memory: 8.0 GB
Alocated Memory: 6556 MB
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
        Base speed: 2.59 GHz
	Cores: 6
	Logical processors:	12
 **GPU:** 
### GPU 0
        Intel(R) UHD Graphics 630

	Driver version:	27.20.100.8729
	Driver date:	12/10/2020
        GPU Memory 3.9 GB
        DirectX version: 12 (FL 12.1)
### GPU 1

	NVIDIA GeForce GTX 1050

	Driver version:	30.0.14.7111
	Driver date:	21/06/2021
	DirectX version: 12 (FL 12.1)
	GPU Memory	6.9 GB
        

**VERSIONS:**
        IR-Version: 1.16.5
        Forge-Version: 1.16.5-36.1.31
        Mohist-Version(SERVER): 1.16.5 (645)-(689)

If I wrote something wrong, sorry for being Romanian!
I translated in ENGLISH with GOOGLE TRADUCERE
LINK :
_[https://translate.google.ro](url)     FOR ROMANIA
[https://translate.google.com](url)   FOR ENGLISH_

**Comment by Larky2k** [comment]
Remove quark that causing your issue

**Comment by Bogdan7200** [comment]
ok

**Comment by Bogdan7200** [comment]
> 
> 
> Remove quark that causing your issue

Not working
