### ISSUE TITLE
Broken Horn on Rodgers Ten Wheeler

### ISSUE THREAD

**Issue by ericsire** [TeamOpenIndustry/ImmersiveRailroading#1003]
**Describe the bug**  
The horn on the Rodgers Ten Wheeler does not work, there is no sound (or if there Is, it's very quiet and I cannot hear it.) when you press the horn button (In my case 0). I know that the horn is supposed to be working because of the smoke that comes from it with you press the horn button.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Spawn the 
 2. Press the horn button 
 
**Expected behavior**  
 I expected that the horn would be working and loud.

**System Information**  
 OS: Windows
 Forge-Version: 1.16.4

**Modlist**  
- Immersive Engineering
- Immersive Railroading
- Optifine
- Track API
- Universal Mod Core
- WorldEdit
 
**Additional context**  
I am playing on 1.16.4 with the 1.16.4 mod.

**Comment by Saladgaming** [comment]
Did you let us gather steam pressure first ?

**Comment by ericsire** [comment]
Yeah, and again I tried and the horn did work, but only once. Once I did it again the horn didn't work, I could hear it but it sounded like the was horn coming from somewhere far in the distance.

**Comment by ericsire** [comment]
Now that I'm driving it seems to be a little louder, but with the sound of the train, you can hardly hear the horn.
