### ISSUE TITLE
Custom user scripts

### ISSUE THREAD

**Issue by Masiu121** [TeamOpenIndustry/ImmersiveRailroading#1004]
**Describe the suggestion**  
I suggest to add a possibility to create a custom scripts for the trains in packs. You could create a simple library for a programming language (For example lua - It's very simple, but have a lot of possibilities) and content creators can write some scripts for their trains with that library.

**Applications of the suggestion**  
The simple scripts coded by users could move objects of model (So for example user can write a script to open the train doors) by a button, attach or detach a train when player is in the cabin, etc.

**Comment by cam72cam** [comment]
That's an interesting idea

**Comment by cam72cam** [comment]
This can now all be done in-model
