### ISSUE TITLE
Server Crash if a Dimension unloads with a Player in it

### ISSUE THREAD

**Issue by Philipp766** [TeamOpenIndustry/ImmersiveRailroading#1007]
Me and some friends are playing with IR and rftools Dimensions.
One of us was in a dimension that didnt get any power anymore and after the power ran out of that dimension, the server crashed.

My thought is: The algo which computes the next node ( `java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)` ) crashes the server if a dimension unloads on a not normal way ( probably shutting it down ) while a player is still in that dimension. 
We don´t have any rails yet, so i suspect that the algo is checking around the player even if nothing is there and a short time after the player left/died. This way it could have happened that it checked a non existing dim and crashed.
[crash.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6784545/crash.log)

If you don´t know how rftools Dimensions works: you can create your own dimensions with that mod which have to be powered. If the power runs out on that dimension, you´ll get killed and the dimension is getting shut down to save server resources.

**Comment by WrongWeekend** [comment]
According to your crash report, neither TrackAPI, Immersive Railroading, or Universal Mod Core are installed and therefore are not factors in the crash.

**Comment by cam72cam** [comment]
Upgrade to the latest UniversalModCore, I fixed the bug in there: https://www.curseforge.com/minecraft/mc-mods/universal-mod-core/files/3141762

**Comment by Philipp766** [comment]
Fixed the Issue, thank you all
