### ISSUE TITLE
1.16.5 Rail crash

### ISSUE THREAD

**Issue by homsusy** [TeamOpenIndustry/ImmersiveRailroading#1011]
Hello, distinguished author. When I was playing with the mod you made, I found a problem. Whenever I take out the track blueprint and right click to place the railway, the game will crash.
In addition, the type of rails cannot be changed. I have tried many times, but I have not been able to change them, and when placing the rails, it always crashes. I hope you can read this post and reply and modify this "little question" in time.
Thank you very much and wish you a happy life

**Comment by cam72cam** [comment]
Are you using a java version newer than 1.8?  IR has issues with newer java versions.

Also could you post a crash/latest log?  It's hard to diagnose otherwise

**Comment by homsusy** [comment]
Yes, I use java14 to play 
So, I need to change to a lower version of JAVA?
Yes, but need to wait

**Comment by cam72cam** [comment]
Yes, downgrade to java 1.8

**Comment by homsusy** [comment]
Thank you, thank you very much. I downgraded to the JAVA1.8 version, and it was fine. Thank you very much for solving the problem that has troubled me for a long time
I wish you a happy life! ! !
