### ISSUE TITLE
How do I install my add-on bag into the Immersive Railroad?

### ISSUE THREAD

**Issue by homsusy** [TeamOpenIndustry/ImmersiveRailroading#1012]
I downloaded a lot of add-on packages, but I tried to install them but it didn't work.Does the author know this method?

**Comment by Larky2k** [comment]
drop them into the Immersive Railroading config folder, make sure you have enough RAM allocated to use them 6-8gb depending how much RAM the system has

**Comment by homsusy** [comment]
Where's the Immersive Railroading Config folder?

**Comment by homsusy** [comment]
Is that the immersiverailroading in config?

**Comment by Larky2k** [comment]
yes

**Comment by homsusy** [comment]
ok !Thank you so much 
I wish you good health
