### ISSUE TITLE
Inverse Frame Wheel Code

### ISSUE THREAD

**Issue by Nathan-TheSteelMann** [TeamOpenIndustry/ImmersiveRailroading#1017]
**Describe the suggestion**  
Quoted right from Immersive Railroading's Dev Channel:

"Not sure if I can just suggestions for development here, rather than model suggestions, but the ability to have like 
"FRAME-WHEEL-1-IV" where it inverts the rotations of the wheel, theoretically you could animate Geared or Traction engines then using Frame Wheels as gears.
I don't think this would be too terribly hard from the concept, maybe just a duplicate of the frame wheel reading code with inverted rotational maths? But I am far from a programmer so I could be over simplifying it."

To expand on this, I figure considering the rendering/animation overhauls that have come in the most recent release of Immersive Railroading (well, soon to be release 1.9, still InDev versions as of now), and while not a major feature it would be pretty cool to see what people would do with something like this.

**Comment by robot256** [comment]
For geared locomotives, allowing parts to rotate with a multiple of wheel speed would be best.  For example, a 3:2 drive gear could be set to "-1.5".

**Comment by cam72cam** [comment]
This can now be done with Animatrix.
