### ISSUE TITLE
1.16.5 Forge | Railbed Glitching Because Of Optifine

### ISSUE THREAD

**Issue by TachyonXCIX** [TeamOpenIndustry/ImmersiveRailroading#1019]
When using optifine the railbed of tracks glitch and do no look like they're supposed to, Forming triangle like structures

Steps to reproduce the unwanted behavior:

 1. Load game with Optifine mod and Immersive Railroading
 2. Open a world up
 3. Pull out a Track Blueprint
 4. Open properties menu of Track Blueprint
 5. Select any block for Railbed option (I choose gravel)
 6. Place tracks down
 7. Railbed will be glitched and look wrong
 
The railbed is supposed to be flat and parallel to the tracks placed with it

**Screenshots**  
![image](https://user-images.githubusercontent.com/80319623/127652846-1008cf32-63fb-448c-9808-a012fa6d2546.png)

![image](https://user-images.githubusercontent.com/80319623/127652808-bb8571f2-17c4-4ef8-8dd2-f17307ba1a31.png)

**System Information**  
 OS: Windows 10
 <br>System Memory: 48GB
 <br>Allocated Memory: 10GB
 <br>CPU: Ryzen 2600x
 <br>GPU: 2080TI
 <br>IR-Version: 1.16.5 forge 1.8.0.1
 <br>Forge-Version: 1.16.5 forge 36.2.0

**Modlist**  
﻿alexsmobs-1.11.1.jar
appleskin-forge-mc1.16.x-2.1.0.jar 
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.2.jar
Camels-1.16.5-1.0.0.jar 
citadel-1.7.2-1.16.5.jar
collective-1.16.5-2.38.jar
ElenaiDodge2-1.16.X-1.1.0.jar
Happy Trails-1.16.5-1.36.0.8.jar 
healingcampfire_1.16.5-3.2.jar 
ImmersiveEngineering-1.16.5-5.0.0-135.jar 
ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar 
jei-1.16.4-7.6.1.74.jar 
Mantle-1.16.5-1.6.115.jar 
mgui-1.16.5-3.2.0.jar 
musketmod-1.16.5-forge-1.2.1.jar 
MutantBeasts-1.16.4-1.1.3.jar 
nohostilesaroundcampfire_1.16.5-3.3.jar 
OptiFine_1.16.5_HD_U_G8_MOD.jar 
presencefootsteps-r29-1.16.4.jar 
randomloot-1.16.5-2.3.9.jar 
rare-ice-0.2.2.jar 
rpgbackpacks-1.16.5-1.1.5.jar 
sit-1.16.5-v1.3.1.jar 
smallships-1.16.5-1.9.1.jar
SoundFilters-0.14_for_1.16.2.jar
Construct-1.16.5-3.1.0.231.jar 
TerraForged-1.16.5-0.2.13.jar 
tetra-1.16.5-3.14.1.jar 
TrackAPI-1.16.4-forge-1.2.1.jar 
Universal ModCore-1.16.4-forge-1.0.1.jar 
worldedit-mod-7.2.5-dist.jar 
Xaeros_Minimap_21.14.1_Forge_1.16.5.jar
XaerosWorldMap_1.16.0_Forge_1.16.5.jar 
YungsApi-1.16.4-Forge-11.jar

 
**latest.log**
[2021-07-30-1.log.gz](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6907569/2021-07-30-1.log.gz)

**Additional context**  
As soon as I removed Optifine from the modpack the Railbed glitch went away so I am certain having all these mods was not the problem.

**Comment by cam72cam** [comment]
This has been fixed in the test build which will be released in a few days.  You can download it from the pinned link in #test-builds in discord.  You will need both IR and UMC for 1.16.5

**Comment by TachyonXCIX** [comment]
> This has been fixed in the test build which will be released in a few days. You can download it from the pinned link in #test-builds in discord. You will need both IR and UMC for 1.16.5

Will Do, Thanks!
