### ISSUE TITLE
The Trains controls are not making our job!

### ISSUE THREAD

**Issue by TheBlackCatBR** [TeamOpenIndustry/ImmersiveRailroading#1023]
**Describe the bug**  
When i try make something with the locomotive, nothing happens, no keys work, I've tried everything, but nothing.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to the Train
 2. Try use
 3. impossible.
 
**Expected behavior**  
 I myself expected the train to move after it had completely warmed up.

**Screenshots**  

**System Information**

**Comment by km00700** [comment]
steam locomotive? If so, your pressure may still be 0 after it's warmed up. Center the throttle with numpad 5 and see if pressure builds up first. If the throttle slider doesn't move at all with any of the numpad bindings, then your numlock may be turned off and needs to be on.
