### ISSUE TITLE
Visual bug. Trains hang in the air.Minecraft (1.12.2)Mod version 1.9.0

### ISSUE THREAD

**Issue by Dolboklim** [TeamOpenIndustry/ImmersiveRailroading#1024]
**Describe the bug**  
When i place any train from this mod on the rails, it literally doesen't touch the rails. I mean train just hang in the air at 1 block distance from the rails. It's just a visual bug, nothing more, but i can't normally control train from inside because of this bug(i can't look out the windows because they're too high!) Nothing more, trains work pretty fine with this bug. It's just a visual problem. 

**Screenshots**  
![Screenshot_3](https://user-images.githubusercontent.com/88422085/128133511-e368ce3a-ff6c-4b22-95c4-5a7a4739b642.png)  
![Screenshot_1](https://user-images.githubusercontent.com/88422085/128132379-a9e9d8e7-e079-4129-8490-a622bec3a081.png)

**Modlist**  
i did a screenshots with my mods.
 ![Screenshot_4](https://user-images.githubusercontent.com/88422085/128134805-2ad05e61-277c-4e65-9bf0-6e9ccf529448.png)
![Screenshot_5](https://user-images.githubusercontent.com/88422085/128134812-fddebe77-7078-41b7-a14b-5143f306b734.png)

**Additional context**  
Nothing helped me to solve this problem. I tried to place trains on the track in creative and survival. I also tried to place them on the different types of rails. Maybe some mods conflicts idk. Please help!

**Comment by km00700** [comment]
ValkyrienWarfare does that. It rewrites some coordinate stuff and breaks IR entity handling.

**Comment by Dolboklim** [comment]
Thanks, i deleted ValkyrienWarfare and it helped!
