### ISSUE TITLE
Hoses and fuel line connections when coupling to another rolling stock

### ISSUE THREAD

**Issue by Bossk160** [TeamOpenIndustry/ImmersiveRailroading#1028]
So you would have a part that is for the hoses and fuel line that are in the unconnected state, and you would have a part for when it's in a connected state. When you would couple to a rolling stock, the unconnected part would turn invisible and the other would appear(the part for when the fuel line is connected). This could also be used for steam loco and tender, EMU, Multi-unit diesels, auxiliary tender, and passenger connections. And for people who already do this via texture variants, it would greatly reduce their variants for easier use.

It would just be a great addition for more immersive gameplay and give way more power to the modelers

**Comment by cam72cam** [comment]
You can now do this with COUPLED_{POSITION}_{NUMBER}_HIDE
