### ISSUE TITLE
I can't place the majority of the locomotives

### ISSUE THREAD

**Issue by CrunchyNF** [TeamOpenIndustry/ImmersiveRailroading#1030]
Whenever I try and place any of them it says "Rolling Stock does not exist on the server. Can not place. Ensure you have the resource pack in the server's config/immersiverailroading folder. I have seen others ask this question but the answers were "put the resource packs in the config folder". I am not sure what resource packs I am meant to be moving so could someone please explain it to mean in more depth? Thanks.

 
**latest.log**
 https://pastebin.com/bXGmnFqr

**Comment by CrunchyNF** [comment]
I am using the Voxel Trains IR Pack, which is the trains that don't work are from.

**Comment by Larky2k** [comment]
It's not a bug, the pack must be on the server end as well.

**Comment by cam72cam** [comment]
If you are still having trouble, come ask for help in the IR discord.
