### ISSUE TITLE
Track placement; from 16 to 32

### ISSUE THREAD

**Issue by Ash-0666** [TeamOpenIndustry/ImmersiveRailroading#1037]
When placing track, namely custom curves and switches, you can place said track in one of sixteen different orientations along the XZ plane. This is great for getting those gentle curves in your switches for most of your longer locomotives, but it could be made even smoother by doubling the orientation count to thirty-two.

For instance, I prefer to utilize the Minecraft gauge. I've found that a track placement of thirteen long by three wide, utilizing four 22.5 degree switches convening at the center point, makes for a smooth crossover track. It's aesthetically pleasing, but by increasing the orientation count, you could construct longer switches that don't suffer from aesthetic hiccups due to track placement.

Perhaps I'm rambling, it is mostly an issue of aesthetics, but this would also allow for more advanced track placement, such as double-slip crossovers. Regardless, these are just my thoughts, what do you guys think?

**Comment by Ash-0666** [comment]
I now realize it would probably be wise to mention that I utilize version 1.6.1_1.12-1138. Perhaps it holds no true weight, but on the off chance it does, then here you go.

**Comment by Larky2k** [comment]
Update IR

**Comment by Ash-0666** [comment]
Any version in particular?

**Comment by Larky2k** [comment]
latest

**Comment by Larky2k** [comment]
your on a very old version

**Comment by Ash-0666** [comment]
Got it, thank you!

**Comment by Ash-0666** [comment]
So I've updated to the latest 1.12.2 update, yet I note that track placement is still restricted to 16 orientations along the XZ plane. My original suggestion still stands, although I now question if I've properly explained my concept...

**Comment by MasterDragon575** [comment]
You can increase it in the config

**Comment by cam72cam** [comment]
There is a config option in new versions that allow you to change the "orientations". AnglePlacementSegmentation = 8 will get you to 32

**Comment by Ash-0666** [comment]
Thank you! That will be wonderful!
