### ISSUE TITLE
[1.16.5] Crash with item rendering (I think)

### ISSUE THREAD

**Issue by TheSnowyChickens** [TeamOpenIndustry/ImmersiveRailroading#1039]
**Describe the bug**
Hello,
I get some random crashes with railroading items in the creative inventory.

I search as example (the first crash) "wrench" (for your big wrench) and I could not even see the results, so the game crashed.
(with normal MC creative search)
The second crash was with "rail".

I can't give you crash reports from the crash, because Minecraft doesn't created a crash log.
(the crash log below is from F3 + C, so you can see all mods)

[crash-2021-08-12_00.02.38-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6971667/crash-2021-08-12_00.02.38-client.txt)

Last logs:
[2021-08-11-3.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6971694/2021-08-11-3.log)
[2021-08-11-2.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6971696/2021-08-11-2.log)

**How to reproduce**
Randomly search for IR items, can take a while

**Expected behavior**
No crashes with items

**Screenshots**
- If I get the situation again and MC turn white, I try to screenshot that and add it here

MC: 1.16.5
Forge:  36.2.2
IR: 1.9.0
IE: 137
IPetro: 3.3.0-4 
IPosts: 4.1.0
Track API: 1.2.1
UMC: 1.1.2
EntityCulling: 1.3.0 (maybe that mod could do something wrong ?)
No Optifine

**Comment by FrannDzs** [comment]
Same problem here.

**Comment by cam72cam** [comment]
@TheSnowyChickens does it also crash when you type in another name that contains a "c" ?
Like coal or chicken?

**Comment by TheSnowyChickens** [comment]
ohhmmmm, that I don't know.

During searching for other items, I used maybe 6/8 of all letters and only sometimes it crashes.
(maybe it is fixed with your new UMC version, but dk)

**Comment by TheSnowyChickens** [comment]
Okay, it is not only with words with "c", it can crash with "book" or "disk" too.

**Comment by Fuggschen** [comment]
I got the same problems here. Searching anything will randomly cause a crash. Searched in the first log for "book" and in the second for "disk" in JEI.


Here the logs:
[crash-2021-09-23_22.10.22-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7220929/crash-2021-09-23_22.10.22-client.txt)
[crash-2021-09-23_23.14.37-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7220931/crash-2021-09-23_23.14.37-client.txt)
