### ISSUE TITLE
Compatibility With Vanilla-style Minecarts

### ISSUE THREAD

**Issue by kiloPascal-a** [TeamOpenIndustry/ImmersiveRailroading#1045]
**Describe the suggestion**  
Make vanilla minecarts compatible with IR track. "Minecraft gauge" rails already exist in IR, and IR trains can even be made compatible with vanilla rails. It makes sense for the reverse to be true as well.

**Applications of the suggestion**  
- I believe this addition would allow Create mod cart contraptions to run on IR rails with no additional coding. Create is a hugely popular and growing mod, and one of its biggest drawbacks is that block-built trains cannot smoothly navigate Minecraft rails. Compatibility would make IR (or the Track API) an indispensable part of Create modpacks.
- Gives newer players an easier way to start using IR rails
- Caters to the nostalgic experience of creating minecart networks across a map

**Comment by cam72cam** [comment]
I am not planning on supporting integration with standard minecarts.

If you want this functionality, you could ask Create to add optional support for TrackAPI.  It's a simple library for following track, without having to depend on any train mods directly.

https://github.com/TeamOpenIndustry/TrackAPI/tree/forge_1.16.5
