### ISSUE TITLE
slopes don't work

### ISSUE THREAD

**Issue by MCCAIN1337** [TeamOpenIndustry/ImmersiveRailroading#1048]
When I drive in a train, or on a handcar, then i can't drive about the upper part of a slope... it's equal if i drive from which side i drive the train or locomotive will stop at the upper part/end/begin. after that i can't drive in reverse or accelerate. I added a video were i show the problem ingame on this link: https://www.transfernow.net/dl/20210815sqNP6og2 (this link will exist for 7 days)

**How to reproduce**  

 1. place a slope (no matter how long)
 2. place train on an track (no matter which side)
 3. drive with the train, or only the locomotive, above the upper part of the slope(track) 
 
**Expected behavior**  
 that i can drive without stoping.

**Screenshots**  

**System Information**  
 OS: Windows 10
 <br>System Memory: 8gb
 <br>Allocated Memory: maybe 4gb (standart)a
 <br>CPU: Intel I7 7700k
 <br>GPU: Nvidia Gforce GTX 1050TI
 <br>IR-Version: 1.16.5
 <br>Forge-Version: 36.2.2

**Modlist**  
Better Hoppers
Chissle
Chissle & Bits
ConectedTexturesMod
Immersive Engineering
Immersive Petrolium
Immersive Railroding
JourneyMap
LandOfSignals
Macaw's Bridges
MrCrayfish's Vehicle Mod
Obfuscate
Speedy Hoppers
Track API
Univesal Mod Core

**Comment by cam72cam** [comment]
that does look like a bug, though you can probably work around it by increasing the slope length

**Comment by MCCAIN1337** [comment]
> 
> 
> that does look like a bug, though you can probably work around it by increasing the slope length

now i tryed to increase the length to 200 blocks and it happend noting... [here the video with the 200 bklocks slope: https://www.transfernow.net/dl/20210817TWJMnr0v ]
