### ISSUE TITLE
Suggestion: Capstans, Horses, and other non-mechanical switching mechanisms.

### ISSUE THREAD

**Issue by ConnieCommie** [TeamOpenIndustry/ImmersiveRailroading#1054]
IR is a good mod, but the way i see it - particularly for smaller industrial setups or European railroads - is that there's not really any means to shunt stuff without using a locomotive or big handcart. 

This isn't a problem for America, where locomotive shunting is the standard, but outside of it - particularly in Europe - there were longstanding tradition of using cheaper options.

-Shunting Horses - Ideally, these would be horses with a specialized saddle, which would use IR coupling and simply allow them to pull trains by moving in the direction of the coupler. These would be attached and detached via the shunting hook; a horse would roughly be able to pull 25 tons? If there's a better figure please let me go.

-Hand Shunting - A towbar tool would be craftable for either Minecraft or Narrow Gauge. Using it would position you near the coupler; you'd then be able to manipulate the car. A rough estimate would be a few smaller 4 wheel cars, with the returns diminishing.

-Capstans - The fun one. A capstan would be cast and placed in the world like a block. They'd be controlled via redstone with the signal dictating how much power they have. Using a coupling hook, you'd be able to connect the end of it to any railcar within, say, 50m, and it would drag it to the position. This would have a pretty high capacity, but be limited by length. This may overlap with cable haulage.

**Comment by cam72cam** [comment]
Sorry, but I'm not interested in adding this complexity to IR
