### ISSUE TITLE
trains dont work in multiplayer

### ISSUE THREAD

**Issue by crrepitv** [TeamOpenIndustry/ImmersiveRailroading#1061]
UNU Streamliner B Unit and Trains like that dont work when you want to place it in multiplayer there come a chat message: Error rolling stock does not exist on the server. can not place. ensure you have installed the resource pack in the servers confic/immersiverailroading folder. but in the single player dont exist that too but there it works. its a unu civilian vehikels mod

**Comment by cam72cam** [comment]
Resource packs must be installed on the server in the config/immersiverailroading directory
