### ISSUE TITLE
trains dont work in the multiplayer

### ISSUE THREAD

**Issue by crrepitv** [TeamOpenIndustry/ImmersiveRailroading#1062]
UNU Streamliner B Unit and Trains like that dont work when you want to place it in multiplayer there come a chat message: Error rolling stock does not exist on the server. can not place. ensure you have installed the resource pack in the servers confic/immersiverailroading folder. but in the single player dont exist that too but there it works. which recource peaks they mean?

**Comment by cam72cam** [comment]
Either ask UNU for help since they do bad things or ask for help in discord.
