### ISSUE TITLE
Multiblock TE is null, casting basin.

### ISSUE THREAD

**Issue by novacheri1** [TeamOpenIndustry/ImmersiveRailroading#1065]
**Bug:**
Server console is being spammed with every tick with this message.
`
[16:55:07] [Server thread/WARN] [ca.mo.ModCore/]: Multiblock TE is null: (-79, 78, -134) (3, 7, 0) false class cam72cam.immersiverailroading.multiblock.CastingMultiblock$CastingInstance 
`
I've read some closed issues already, no solutions were given. We did break our basin with carry-on, which we've removed the mod for now. The basin was properly destroyed after, including all of our multiblocks, yet the message is still being put out.

**System Information**  
 <br>OS: Arch Linux x86_64
 <br>System Memory: 32GB
 <br>Allocated Memory: 16G
 <br>CPU: AMD Ryzen 5 3600 (12) @ 3.6GHz
 <br>GPU: NVIDIA GeForce GTX 1050 Ti
 <br>IR-Version: 1.9.0 - 1.16.5
 <br>Forge-Version: 36.2.2 - 1.16.5

**Modlist**
advancedperipherals-0.7r.jar
appliedenergistics2-8.4.0.jar
BetterAdvancements-1.16.3-0.1.0.102.jar
Botania-1.16.5-419.jar
cc-tweaked-1.16.5-1.98.1.jar
cfm-7.0.0pre22-1.16.3.jar
cgm-1.0.1-1.16.3 (1).jar
chiselsandbits-0.3.4-RELEASE.jar
chunkloaders-1.1.7-mc1.16.5.jar
Clumps-6.0.0.23.jar
CodeChickenLib-1.16.5-4.0.2.429-universal.jar
cofh_core-1.16.5-1.3.1.jar
comforts-forge-1.16.5-4.0.1.2.jar
createaddition-1.16.5-20210810a.jar
create-mc1.16.5_v0.3.2d.jar
curios-forge-1.16.5-4.0.5.2.jar
elevatorid-1.16.5-1.7.13.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
engineersdecor-1.16.4-1.1.14.jar
exnihilosequentia-1.16-20210628182320.jar
FastFurnace-1.16.4-4.4.0.jar
FastLeafDecay-v25.jar
FastWorkbench-1.16.4-4.5.1.jar
FluxNetworks-1.16.5-6.1.7.12.jar
flywheel-1.16-0.2.3.jar
gravestone-1.16.5-1.0.6.jar
ImmersiveEngineering-1.16.5-5.0.2-137.jar
ImmersivePetroleum-1.16.5-3.3.0-5.jar
immersiveposts-1.16.5-4.1.1.jar
ImmersiveRailroading-1.16.5-forge-1.9.0.jar
ironchest-1.16.5-11.2.13.jar
jei-1.16.5-7.7.0.106.jar
Mantle-1.16.5-1.6.109.jar
Mekanism-1.16.5-10.0.21.448.jar
morecfm-1.3.1-1.16.3.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
nophantomnocry-1.16.5-3.0.jar
obfuscate-0.6.2-1.16.3.jar
OreExcavation-1.8.157.jar
Patchouli-1.16.4-53.1.jar
Placebo-1.16.4-4.4.5.jar
randompatches-2.4.4-forge.jar
rsgauges-1.16.4-1.2.11.jar
sophisticatedbackpacks-1.16.4-2.5.0.271.jar
StorageDrawers-1.16.3-8.2.2.jar
supermartijn642configlib-1.0.9-mc1.16.jar
swingthroughgrass-1.16.4-1.5.3.jar
TConstruct-1.16.5-3.0.2.73.jar
theoneprobe-1.16-3.1.4.jar
thermal_expansion-1.16.5-1.3.0.jar
thermal_foundation-1.16.5-1.3.2.jar
thermal_innovation-1.16.5-1.3.0.jar
thermal_locomotion-1.16.5-1.3.0.jar
TrackAPI-1.16.4-forge-1.2.1.jar
UniversalModCore-1.16.5-forge-1.1.3.jar
Xaeros_Minimap_21.15.0.1_Forge_1.16.5.jar

**latest.log**
https://pastebin.com/E75XV7Rs

**Comment by novacheri** [comment]
We decided to remove Immersive Railroading, restart our server, then re-add it. This fixed the issue and caused the spam to stop, though I'm not sure if its worth closing the issue over that. We did have to deconstruct the thankfully limited equipment we had obviously, so I could imagine this isn't a solution for anyone with a large scale setup.
