### ISSUE TITLE
Crash when Joining a World 

### ISSUE THREAD

**Issue by MeeseGX** [TeamOpenIndustry/ImmersiveRailroading#1069]
Hello
I tryed to add this Mod to an Modpack.
And then the Modpack crashes every time i Join a World/Server.
[crash-2021-08-31_06.01.22-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7095643/crash-2021-08-31_06.01.22-client.txt)

**Comment by cam72cam** [comment]
What pack?  I've never seen that error before

**Comment by MeeseGX** [comment]
TNP Limitless 3
