### ISSUE TITLE
Crash when taking water from a tank car

### ISSUE THREAD

**Issue by This1sAUsername** [TeamOpenIndustry/ImmersiveRailroading#1070]
The tank car picked up water from somewhere, it wasn't suppose to be there so I tried removing it by putting a bucket into the ui slot for buckets and when i removed the full bucket the game crashed, report attached.
[crash-2021-09-03_20.14.49-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7108094/crash-2021-09-03_20.14.49-server.txt)

**Comment by cam72cam** [comment]
Please try upgrading to UMC 1.1.3, it appears you are on an old version
