### ISSUE TITLE
My resource pack does not work with version 1.9.1.

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [TeamOpenIndustry/ImmersiveRailroading#1073]
It worked in version 1.8.0, but it doesn't work in version 1.9.1. why?

Although it is a test version, I pasted the resource pack I am using.
[test.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7121892/test.zip)

**Comment by km00700** [comment]
install it via config/immersiverailroading and post the latest.log or crash report you get.

**Comment by KonohanaSakuya2680** [comment]
Thank you for your reply.

This is the latest.log when I put it in the config / immersiverailroading and resourcepack folders.

[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7124761/latest.log)

**Comment by KonohanaSakuya2680** [comment]
other one
[crash-2021-09-13_15.23.00-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7151879/crash-2021-09-13_15.23.00-client.txt)

**Comment by KonohanaSakuya2680** [comment]
other one
[crash-2021-09-13_15.26.38-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7151886/crash-2021-09-13_15.26.38-client.txt)


> config / immersiverailroadingを介してインストールし、取得したlatest.logまたはクラッシュレポートを投稿します。

**Comment by KonohanaSakuya2680** [comment]
> install it via config/immersiverailroading and post the latest.log or crash report you get.

other one
[crash-2021-09-13_15.26.38-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7151893/crash-2021-09-13_15.26.38-client.txt)

**Comment by cam72cam** [comment]
The json in your pack is incorrect.  If you are still having issues, please join the discord and ask for help there.
