### ISSUE TITLE
Can't get on the train

### ISSUE THREAD

**Issue by 1636578433** [TeamOpenIndustry/ImmersiveRailroading#1085]
**Describe the bug**  

Can't get on the train

**How to reproduce**  

https://cdn.discordapp.com/attachments/417309946288275467/890897458492739584/why.mp4
 
**Expected behavior**  
 A clear description of what you expected to happen.

**Screenshots**  

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory: 12gb [e.g. "8gb"]
 <br>Allocated Memory:11gb [The memory allocated to your Minecraft instance where you encountered the bug e.g. "4gb"]
 <br>CPU: i7-7700k[e.g. "Intel I7 7700k"]
 <br>GPU: n/a[e.g. "MSI 1080 8gb"]
 <br>IR-Version: 1.9.1 1.16.5[e.g. "1.6.1_1.12.2"]
 <br>Forge-Version: forge 1.16.5 36.2.5 [e.g. "1.12.2 - 14.23.5.2844"]

**Modlist**  
justenoughkeys-forge-0.2.2.jar, 
customizableelytra-1.16.4-1.5.7.jar, 
silent-lib-1.16.3-4.9.6.jar, 
BiomesOPlenty-1.16.5-13.1.0.482-universal.jar, 
silent-gear-1.16.5-2.6.30.jar, 
jei-1.16.5-7.7.1.121.jar, 
Iceberg-1.16.5-1.0.3.jar, 
flywheel-1.16-0.2.3.jar, 
curios-forge-1.16.5-4.0.5.2.jar, 
Patchouli-1.16.4-53.1.jar, 
etched-1.1.0-1.16.5-forge.jar, 
create-mc1.16.5_v0.3.2d.jar,
 Xaeros_Minimap_21.16.0_Forge_1.16.5.jar, 
Waystones_1.16.5-7.6.3.jar, 
camera-1.16.5-1.0.14.jar, 
XaerosWorldMap_1.17.0.1_Forge_1.16.5.jar, 
TravelersBackpack-1.16.5-5.4.3.jar, 
StorageDrawers-1.16.3-8.3.0.jar, 
cfm-7.0.0pre22-1.16.3.jar, 
SilentGems-1.16.3-3.7.16.jar, 
CraftTweaker-1.16.5-7.1.2.421.jar, 
mysticalworld-1.16.5-0.3.3.19.jar, 
Paraglider-1.16.5-1.3.2.1.jar, 
forge-1.16.5-36.2.5-universal.jar,
Aquaculture-1.16.5-2.1.21.jar,
valhelsia_core-16.0.10.jar, 
valhelsia_structures-1.16.5-0.1.5.jar, 
supplementaries-1.16.5-0.16.1.jar, 
geckolib-forge-1.16.5-3.0.46.jar,
 ars_nouveau-1.16.5-1.23.10.jar, 
betterendforge-1.16.5-1.6.2.jar, 
selene-1.16.5-1.7.jar, 
AdvancementPlaques-1.16.5-1.4.0.jar, 
DungeonsArise-1.16.5-2.1.47-release.jar, 
bukkit, 
voicechat-forge-1.16.5-1.7.11.jar, 
create-stuff-additions1.16.5_v1.0.8.jar, 
SlashBlade-1.16-0.0.12.jar, 
caelus-forge-1.16.5-2.1.3.1 (1).jar, 
dungeons_1.10_mc1.16.5.jar, 
VillagersAndMonstersLegacy3.1.jar, 
HealthOverlay-1.16.5-3.0.1 (1).jar,
 refinedstorage-1.9.15.jar, 
createplus-1.16.4_v0.3.2.1 (1).jar,
 ImmersiveEngineering-1.16.5-5.0.3-138.jar, 
Botania-1.16.5-419.jar, 
TrackAPI-1.16.4-forge-1.2.1.jar, 
AutoRegLib-1.6-49.jar, 
Quark-r2.4-316.jar,
 constructionwand-1.16.5-2.2.jar, 
architectury-1.23.33-forge.jar,
 ftb-library-forge-1605.3.3-build.71.jar, 
item-filters-forge-1605.2.5-build.9.jar,
 ftb-teams-forge-1605.2.2-build.32.jar, 
ftb-quests-forge-1605.3.4-build.60.jar, 
ImmersiveRailroading-1.16.5-forge-1.9.1.jar, 
UniversalModCore-1.16.5-forge-1.1.3.jar,
 ExtraBotany-r1.2-66.jar, 
CosmeticArmorReworked-1.16.5-v4.jar,
 Mekanism-1.16.5-10.0.21.448.jar, 
MekanismGenerators-1.16.5-10.0.21.448.jar, 
performant-1.16.2-5-3.72m (3).jar, 
ferritecore-2.0.7-forge (1).jar
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by Larky2k** [comment]
Remove quark or update to latest

**Comment by 1636578433** [comment]
which mod i need update to latest?quark or IR?

**Comment by Larky2k** [comment]
quark

**Comment by 1636578433** [comment]
but I am using the latest version already
Quark-r2.4-316.jar

**Comment by 1636578433** [comment]
Only delete quark can solve it?Is there any other solution?

**Comment by Larky2k** [comment]
quark causes issues with IR, its remove quark or remove IR

**Comment by 1636578433** [comment]
okay,i got it,thanks for ur help

**Comment by Raptor22a** [comment]
I've had a similar issue to this in 1.12.2 (IR 1.9.1, Quark r1.6-179) where I can get on a train after it's placed, but if I walk away and then come back, I can't get back on it or remove it - the only way to remove it is to use explosives (of course that means re-building the track afterwards). I'm really not a fan of having to chose either Quark or IR - do you know what specific feature in Quark is causing the issue? If it's a matter of disabling that feature, it'd be fairly easy due to how configurable Quark is, but I'd rather not just go cold turkey and get rid of it entirely.
