### ISSUE TITLE
White screen bug in 1.12.2

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [TeamOpenIndustry/ImmersiveRailroading#1089]
every time I go to a map, it happens to me, but when I move my camera, I notice that the chunks aren't loading correctly, besides i can't know what's going on around me, only at some angles i can see
![Screenshot_20210926-102601_Google](https://user-images.githubusercontent.com/85260889/134810069-284e5601-9f36-4989-8c6f-4d20d88d94cb.jpg)

**Comment by Larky2k** [comment]
Please follow bug reporting procedure.
