### ISSUE TITLE
Too much Track Clicking Sound 

### ISSUE THREAD

**Issue by PoseidonSHD** [TeamOpenIndustry/ImmersiveRailroading#1094]
Hey Guys

I have the following Problem. 
Everytime my train starts to roll a metallic clicking noice can be heard. It clicks everytime a new track section starts. With higher speed it drowns out every other sound and it sounds like cymbals going crazy. 

I already tried with other versions of the mod. Currently i play the 1.16.5 version.

Is it possible to delete this sound or to mute it ?
I have no idea how i should solve this problem.

**Comment by DamienHyde** [comment]
Or just have the clicking sound be time based instead of whenever it hits a new section of track.

**Comment by PoseidonSHD** [comment]
> Or just have the clicking sound be time based instead of whenever it hits a new section of track.

That would surely solve the problem but how do i change that?

**Comment by mzuletal** [comment]
You can get the sound from the mod jar and using an audio modifier tool, mute it or reduce the dB of it

**Comment by PoseidonSHD** [comment]
> You can get the sound from the mod jar and using an audio modifier tool, mute it or reduce the dB of it

Thanks for the replay mzuletal. Can you explain how i get the sound from the mod jar.? I'm new to modding and i have no clue how to do this .... particularly the step with the audio modifier.

**Comment by Racer395** [comment]
> > You can get the sound from the mod jar and using an audio modifier tool, mute it or reduce the dB of it
> 
> Thanks for the replay mzuletal. Can you explain how i get the sound from the mod jar.? I'm new to modding and i have no clue how to do this .... particularly the step with the audio modifier.

You can use an archive viewer like 7zip. Once you open the jar, follow the path immersive railroading->assets->sounds->default->clack.ogg

I dragged that audio file onto my desktop and opened the .ogg file with audacity (A free sound editor.) Once I changed the volume of the track on the left hand side, I exported it as an .ogg file with the same name. Then, with the archive viewer still open, I dragged the file into the spot and replaced the old one. 

Problem solved.

**Comment by wolfbaj** [comment]
is there a way to modify the sound if you are using the forge desktop launcher for modded? I cant find the file.

**Comment by cam72cam** [comment]
New audio config added so you can change individual sound volumes
