### ISSUE TITLE
Track Switch

### ISSUE THREAD

**Issue by A009i8** [TeamOpenIndustry/ImmersiveRailroading#1100]
Hello

I think in the 1.16.5 is a bug with the Track switches its only switch one side from the track switch. i did 2 Screens so you can see it :) hope its only a bug 

Mod Version:
ImmersiveRailroading-1.16.5-forge-1.9.1.jar

Forge Version:
1.16.5-36.2.2

System Information
OS: Windows
System Memory: "8gb"
Allocated Memory: "7g

![track 2](https://user-images.githubusercontent.com/69797309/136755694-6fb2c54f-c7f9-4024-8bfa-a4495650f696.png)
![track](https://user-images.githubusercontent.com/69797309/136755699-cbc629e9-e061-4d82-a849-ca23dda4a393.png)
b"

**Comment by A009i8** [comment]
> 
> 
> That's a pathing bug that has nothing to do with the visual that you've depicted.

It is still a bug so pls stop commantaiting  iwant to talk to the dev

**Comment by km00700** [comment]
It is a bug, however, the issue originally reported is not the actual bug being reported, so it wouldn't get tracked as the pathing bug. Also, I am one of the IR devs...
