### ISSUE TITLE
Events on computercraft of detector in Computer mode (1.16.5)

### ISSUE THREAD

**Issue by mzuletal** [TeamOpenIndustry/ImmersiveRailroading#1106]
**Describe the bug**  
So i think is already known, that when a train passes by a detector right now its triggered the peripheral or peripheral_detach event in computercraft, but this event can only be triggered when the detector is on "detecting stock" or "detecting speed" mode, so saying that when the detector its on computer mode the events do not show up but the rest of the functions like getting tag, setting tag, getting info or consist work for any mode there is.

**How to reproduce**  
 1. Connect a detector to a computer with wired modems and network cables.
 2. Run a program or a loop to print event names and its id.
 3. Set the detector to "Detecting stock" or "Detecting speed" mode and place/pick up a locomotive above the detector (here it triggers the peripheral or peripheral_detach event)
 4. Now set the mode of the detector to "Computer" then place/pick up a locomotive above the detector (here it doesn't trigger none event)
 5. (extra) run the loop or program and make a locomotive pass by the detector on each modes, you'll get the same results.
 
**Expected behavior**  
Should be expected for this events to work on "Computer" mode for detectors.

**Screenshots**  
I think is properly explained already. I'll add pictures if its needed

**System Information**  
IR-Version: "1.9.1_1.16.5"
Forge-Version: "1.16.5 - 36.2.4"

**Modlist**  
advanced peripherals.
cc-tweaked
ImmersiveEngineering
ImmersivePetroleum
ImmersivePosts
Immersive railroading
Immersive Signals
jei
TrackAPI
UniversalModCore
WithoutALib
 
**latest.log**
Does not show any information about this on logs.

**Comment by cam72cam** [comment]
This should be done with the recently added ir_train_overhead event polling which will be released in IR 1.10
