### ISSUE TITLE
Locos not working on 1.16.5 server

### ISSUE THREAD

**Issue by Pyato4ka** [TeamOpenIndustry/ImmersiveRailroading#1111]
**Describe the bug**  
It is not possible to drive on any loco when I'm on 1.16.5 server. When right clicking on loco, camera starts shaking, raising and lowering throttle, loco isn't moving.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

1. Run latest Magma 1.16.5 server
2. Place any loco on IR rails, for example, Hand Car
3. Press Num8 or Num2
 
**Expected behavior**  
I've expected that loco will drive.

**System Information**  
 OS: Windows 10
 <br>System Memory: 8gb
 <br>Allocated Memory: 2gb
 <br>CPU: Intel I3 4160
 <br>GPU: AMD Radeon HD 7700 Series
 <br>IR-Version: 1.16.5-forge-1.9.1
 <br>Forge-Version: 36.2.9

**Modlist**  
CBMultipart-1.16.5-3.0.2.120-universal
CodeChickenLib-1.16.5-4.0.3.434-universal
ImmersiveRailroading-1.16.5-forge-1.9.1
jei-1.16.5-7.7.1.130
ProjectRed-1.16.5-4.11.0-beta-0-core
ProjectRed-1.16.5-4.11.0-beta-0-exploration
ProjectRed-1.16.5-4.11.0-beta-0-illumination
ProjectRed-1.16.5-4.11.0-beta-0-integration
ProjectRed-1.16.5-4.11.0-beta-0-transmission
Scorge-3.1.3
TrackAPI-1.16.4-forge-1.2.1
UniversalModCore-1.16.5-forge-1.1.3
 
**latest.log**
[https://pastebin.com/w7P5jApe](https://pastebin.com/w7P5jApe)

**Comment by Larky2k** [comment]
Needs to be a forge only server, can't be a plugin server

**Comment by Pyato4ka** [comment]
Ok, thank you
