### ISSUE TITLE
Every time i join it says "This server has mods that require Forge to be installed on the client. Contact your server admin for more details."(im using apex hosting

### ISSUE THREAD

**Issue by PureThunder** [TeamOpenIndustry/ImmersiveRailroading#1112]
LOGS
10.11 17:04:42 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading stock models
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 1% : rolling_stock/tender/rodgers_460_tender.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 3% : rolling_stock/tender/skookum_tender.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 5% : rolling_stock/tender/br01_tender.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 7% : rolling_stock/tender/cooke_tender.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 9% : rolling_stock/tender/k36_tender.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 11% : rolling_stock/passenger/br_coach_mk1.json
10.11 17:04:43 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 36.2.9 Target: null
10.11 17:04:43 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [immersiveengineering] Starting version check at https://raw.githubusercontent.com/BluSunrize/ImmersiveEngineering/1.16.5/changelog.json
10.11 17:04:43 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [immersiveengineering] Found status: UP_TO_DATE Current: 1.16.5-5.0.5-140 Target: null
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 13% : rolling_stock/passenger/b70baggage.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 15% : rolling_stock/passenger/p70coach1.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 17% : rolling_stock/freight/boxcar_x26.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 19% : rolling_stock/freight/usra_boxcar_classrr40.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 21% : rolling_stock/freight/70t_hopper_slsf.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 23% : rolling_stock/freight/attx_flatcar_1.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 25% : rolling_stock/freight/dw_gondola.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 26% : rolling_stock/freight/prr_flatcar_1.json
10.11 17:04:43 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 28% : rolling_stock/freight/usra_hopper_55t.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 30% : rolling_stock/freight/n5c_cabin_car.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 32% : rolling_stock/freight/russell_snow_plow.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 34% : rolling_stock/freight/drgw_3000class_boxcar.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 36% : rolling_stock/freight/drgw_1000class_gondola.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 38% : rolling_stock/freight/drgw_5500class_stockcar.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 40% : rolling_stock/freight/drgw_rail_and_tie_outfit.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 42% : rolling_stock/freight/waycar.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 44% : rolling_stock/tank/tank_us2.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 46% : rolling_stock/tank/kamx_t.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 48% : rolling_stock/tank/slag_car_1.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 50% : rolling_stock/hand_car/hand_car_1.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 51% : rolling_stock/locomotives/ge_40_ton_boxcab.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 53% : rolling_stock/locomotives/ge_b40_8.json
10.11 17:04:44 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 55% : rolling_stock/locomotives/ge_b40_8w.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 57% : rolling_stock/locomotives/ge_c44_9cw.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 59% : rolling_stock/locomotives/emd_sd40-2.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 61% : rolling_stock/locomotives/emd_sw1500.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 63% : rolling_stock/locomotives/alco_rs1.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 65% : rolling_stock/tender/a1_peppercorn_tender.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 67% : rolling_stock/tender/big_boy_tender.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 69% : rolling_stock/tender/k4_tender.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 71% : rolling_stock/tender/e6_tender.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 73% : rolling_stock/tender/a5_tender.json
10.11 17:04:45 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 75% : rolling_stock/tender/class_38_tender.json
10.11 17:04:46 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 76% : rolling_stock/locomotives/a1_peppercorn.json
10.11 17:04:46 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 78% : rolling_stock/locomotives/big_boy.json
10.11 17:04:46 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 80% : rolling_stock/locomotives/k4_pacific.json
10.11 17:04:46 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 82% : rolling_stock/locomotives/e6_atlantic.json
10.11 17:04:46 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 84% : rolling_stock/locomotives/a5_switcher.json
10.11 17:04:46 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 86% : rolling_stock/locomotives/class_38.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 88% : rolling_stock/locomotives/rodgers_460.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 90% : rolling_stock/locomotives/skookum.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 92% : rolling_stock/locomotives/br01.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 94% : rolling_stock/locomotives/cooke_mogul.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 96% : rolling_stock/locomotives/k36.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/WARN [ca.mo.ModCore/]: Invalid model: Missing FRAME for rolling_stock/locomotives/firefly.json!  (this will fail in future versions of IR)
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 98% : rolling_stock/locomotives/firefly.json
10.11 17:04:47 [Server] ImmersiveRailroading-1/INFO [ca.mo.ModCore/]: Loading Models 100% : rolling_stock/locomotives/iron_duke.json
10.11 17:04:47 [Server] modloading-worker-0/INFO [ca.mo.ModCore/]: Loading tracks.
10.11 17:04:47 [Server] modloading-worker-0/INFO [ca.mo.ModCore/]: Loading Tracks 33% : default
10.11 17:04:47 [Server] modloading-worker-0/INFO [ca.mo.ModCore/]: Loading Tracks 66% : concrete
10.11 17:04:47 [Server] modloading-worker-0/INFO [ca.mo.ModCore/]: Loading Tracks 100% : railsonly
10.11 17:04:47 [Server] modloading-worker-1/WARN [ca.mo.ModCore/]: Unsafe tag access before load, try to avoid this if possible
10.11 17:04:47 [Server] modloading-worker-1/WARN [ca.mo.ModCore/]: Unsafe tag access before load, try to avoid this if possible
10.11 17:04:49 [Server] main/INFO [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
10.11 17:04:49 [Server] main/WARN Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
10.11 17:04:49 [Server] main/WARN Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
10.11 17:04:49 [Server] main/WARN Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
10.11 17:04:49 [Server] main/WARN Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
10.11 17:04:49 [Server] main/WARN Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
10.11 17:04:49 [Server] main/INFO Reloading ResourceManager: Default, TrackAPI-1.16.4-forge-1.2.1 (1).jar, forge-1.16.5-36.2.9-universal.jar, ImmersiveEngineering-1.16.5-5.0.5-140 (1).jar, ImmersiveRailroading-1.16.5-forge-1.9.1 (1).jar, UniversalModCore-1.16.5-forge-1.1.3 (1).jar
10.11 17:04:50 [Server] Worker-Main-2/INFO Skipping loading recipe immersiverailroading:item_rail-18207571851271488848 as it's serializer returned null
10.11 17:04:50 [Server] Worker-Main-2/INFO Skipping loading recipe immersiverailroading:item_manual-19645498871271488848 as it's serializer returned null
10.11 17:04:50 [Server] Worker-Main-2/INFO Skipping loading recipe immersiverailroading:item_switch_key-18947533411271488848 as it's serializer returned null
10.11 17:04:50 [Server] Worker-Main-2/INFO Skipping loading recipe immersiverailroading:item_large_wrench11815342711271488848 as it's serializer returned null
10.11 17:04:50 [Server] Worker-Main-2/INFO Skipping loading recipe immersiverailroading:item_hook2834828151271488848 as it's serializer returned null
10.11 17:04:50 [Server] Worker-Main-2/INFO Loaded 24 recipes
10.11 17:04:51 [Server] Worker-Main-2/INFO Loaded 1443 advancements
10.11 17:04:51 [Server] Worker-Main-2/INFO [immersiveengineering/]: Finished recipe profiler for Arc Recycling, took 25 milliseconds
10.11 17:04:51 [Server] Worker-Main-2/INFO [immersiveengineering/]: Recipes for potions: minecraft:long_slow_falling, minecraft:invisibility, minecraft:strong_regeneration, minecraft:harming, minecraft:awkward, minecraft:regeneration, minecraft:long_water_breathing, minecraft:long_turtle_master, minecraft:long_leaping, minecraft:slowness, minecraft:weakness, minecraft:strong_leaping, minecraft:long_slowness, minecraft:thick, minecraft:fire_resistance, minecraft:strength, minecraft:long_strength, minecraft:strong_strength, minecraft:turtle_master, minecraft:strong_swiftness, minecraft:long_weakness, minecraft:leaping, minecraft:poison, minecraft:strong_turtle_master, minecraft:strong_slowness, minecraft:strong_healing, minecraft:strong_poison, minecraft:healing, minecraft:strong_harming, minecraft:swiftness, minecraft:long_poison, minecraft:long_night_vision, minecraft:long_swiftness, minecraft:night_vision, minecraft:water_breathing, minecraft:long_fire_resistance, minecraft:long_regeneration, minecraft:long_invisibility, minecraft:water, minecraft:mundane, minecraft:slow_falling
10.11 17:04:52 [Server] Server thread/INFO Starting minecraft server version 1.16.5
10.11 17:04:52 [Server] Server thread/INFO Loading properties
10.11 17:04:52 [Server] Server thread/INFO Default game type: SURVIVAL
10.11 17:04:52 [Server] Server thread/INFO Generating keypair
10.11 17:04:52 [Server] Server thread/INFO Starting Minecraft server on 135.125.188.185:25642
10.11 17:04:52 [Server] Server thread/INFO Using epoll channel type
10.11 17:04:53 [Server] Server thread/INFO Preparing level "forge_1_16_5_1504325"
10.11 17:04:53 [Server] Server thread/INFO Preparing start region for dimension minecraft:overworld
10.11 17:04:54 [Server] Server thread/INFO Preparing spawn area: 0%
10.11 17:04:54 [Server] Server thread/INFO Preparing spawn area: 0%
10.11 17:04:54 [Server] Server thread/INFO Preparing spawn area: 0%
10.11 17:04:54 [Server] Server thread/INFO Preparing spawn area: 2%
10.11 17:04:55 [Server] Netty Epoll Server IO #1/INFO [ne.mi.fm.se.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting Player (server is still starting): Server is still starting! Please wait before reconnecting.
10.11 17:04:56 [Server] Worker-Main-3/INFO Preparing spawn area: 74%
10.11 17:04:56 [Server] Server thread/INFO Preparing spawn area: 74%
10.11 17:04:56 [Server] Server thread/INFO Preparing spawn area: 74%
10.11 17:04:56 [Server] Server thread/INFO Preparing spawn area: 74%
10.11 17:04:57 [Server] Worker-Main-3/INFO Preparing spawn area: 83%
10.11 17:04:57 [Server] Worker-Main-3/INFO Preparing spawn area: 83%
10.11 17:04:58 [Server] Worker-Main-3/INFO Preparing spawn area: 83%
10.11 17:04:58 [Server] Server thread/INFO Preparing spawn area: 84%
10.11 17:04:59 [Server] Worker-Main-3/INFO Preparing spawn area: 86%
10.11 17:04:59 [Server] Worker-Main-3/INFO Preparing spawn area: 89%
10.11 17:05:00 [Server] Worker-Main-3/INFO Preparing spawn area: 93%
10.11 17:05:00 [Server] Worker-Main-3/INFO Preparing spawn area: 96%
10.11 17:05:01 [Server] Server thread/INFO Time elapsed: 7893 ms
10.11 17:05:01 [Server] Startup Done (8.080s)! For help, type "help"
10.11 17:06:20 [Server] Netty Epoll Server IO #2/ERROR [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [immersiveengineering:main,universalmodcore:cam72cam.mod] rejected vanilla connections
10.11 17:06:20 [Server] Netty Epoll Server IO #2/INFO [ne.mi.fm.se.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
10.11 17:08:53 [Server] Netty Epoll Server IO #3/ERROR [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [immersiveengineering:main,universalmodcore:cam72cam.mod] rejected vanilla connections
10.11 17:08:53 [Server] Netty Epoll Server IO #3/INFO [ne.mi.fm.se.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
10.11 17:13:21 [Server] Netty Epoll Server IO #0/ERROR [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [immersiveengineering:main,universalmodcore:cam72cam.mod] rejected vanilla connections
10.11 17:13:21 [Server] Netty Epoll Server IO #0/INFO [ne.mi.fm.se.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.

**Comment by PureThunder** [comment]
I did install forge 1.16.5 and the files is 1.16.5

**Comment by mzuletal** [comment]
this is a client problem not server so for further support post the client log and seems like whoever is trying to join the server doesn't has the mods installed or either isnt running forge.

**Comment by PureThunder** [comment]
let me try

**Comment by PureThunder** [comment]
didnt work

it keep disconnectiong me]

**Comment by km00700** [comment]
We need the client log.

**Comment by PureThunder** [comment]
it didnt work

**Comment by km00700** [comment]
you need to send the client log. "latest.log"
