### ISSUE TITLE
Not able to modify the speed retarder

### ISSUE THREAD

**Issue by FearOath** [TeamOpenIndustry/ImmersiveRailroading#1113]
So I'm new to IR, and I just discovered the augments that let u automate the trains. I've managed to figure out the detector and locomotive controller, but when I follow the steps of the speed retarder nothing happens. Is this bug on my end or am I doing it wrong?

When I go to change the augments state, I'm not holding anything and right clicking on the speed retarder like the wiki says to. But when I do this nothing happens. I wasn't sure if this is a bug but I didn't know anywhere else to go to ask this question. Apologies

**Comment by mzuletal** [comment]
Speed retarders require a redstone signal to work, if i'm not wrong the stronger the redstone signal they receive better but you will also need a lot of them placed and powered to actually make a train stop. In other words, don't think what's happening to you it's considered as a bug
