### ISSUE TITLE
Sync Issue between server and client 1.16.5

### ISSUE THREAD

**Issue by vgaggia** [TeamOpenIndustry/ImmersiveRailroading#1114]
When using the Casting Basin on a multiplayer server, you can not change the cast type, it just always makes the A1 peppercorn driver wheel, no matter what, it doesn't change, even breaking and re-making the machine the issue persists.
ink.

**Comment by Larky2k** [comment]
need more info on server and client

**Comment by vgaggia** [comment]
What info do you need?

**Comment by Larky2k** [comment]
Forge version -
Java version - 
Type of server - Forge/Plugin server

**Comment by vgaggia** [comment]
Forge version - 36.2.9
Java version - 1.8.0_251-b08

It's running on a Forge server

A modlist is also attached.
[Modlist.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7528004/Modlist.txt)

**Comment by vgaggia** [comment]
I'm not sure what fixed it, but it seems to be just working after staying logged off for a while.
