### ISSUE TITLE
When laying railroad tracks with blueprints, an error was reported missing: 3, but what was missing was not written

### ISSUE THREAD

**Issue by JohnnyR-Bwh** [TeamOpenIndustry/ImmersiveRailroading#1118]
**Describe the bug**  
When laying railroad tracks with blueprints, an error was reported missing: 3, but what was missing was not written

**How to reproduce**  
Just use the railway blueprint to lay the railway
 
**Expected behavior**  
Missing: 3 (some item)

**Screenshots**  
![image](https://user-images.githubusercontent.com/94734977/142820974-88b2dd60-a04d-4304-b09c-3fb22c8cf863.png)

**System Information**  
 OS: [Windows 10]
 <br>System Memory: ["32gb"]
 <br>Allocated Memory: ["8gb"]
 <br>CPU: ["Intel I7 9700KF"]
 <br>GPU: ["3080Ti"]
 <br>IR-Version: ["1.12.2 - forge - 1.9.1"]
 <br>Forge-Version: ["1.12.2 - 14.23.5.2855"]

**Modlist**  
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:u1="tencent"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\admin\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\admin\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

mod英文名称 | JAR包名称 | 版本
-- | -- | --
Universal Mod Core | UniversalModCore-1.12.2-forge-1.1.3.jar | forge-1.1.3
Track API | TrackAPI-1.2.jar | 1.2
Immersive Engineering | ImmersiveEngineering-0.12-98.jar | 0.12-98
Immersive Railroading | ImmersiveRailroading-1.12.2-forge-1.9.1.jar | forge-1.9.1
Open Computers | OpenComputers-MC1.12.2-1.7.5.192.jar | 1.7.5.192

</body>

</html>

 
**latest.log**
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7578976/latest.log)

**Additional context**  
When laying railroad tracks with blueprints, an error was reported missing: 3, but what was missing was not written. Has anyone encountered this situation?
When I set the number of placements to 1, it is reported as missing 1, and when it is placed at 10, it is reported as missing 3, and when it is placed at 20, it is reported as missing 5.
Currently version 1.12.2, other mods use the highest version

**Comment by cam72cam** [comment]
Fixed in latest test builds
