### ISSUE TITLE
Check Speed with OC

### ISSUE THREAD

**Issue by KEEGUNATOR2** [TeamOpenIndustry/ImmersiveRailroading#1119]
Describe the suggestion
An API call (I think that’s what it’s called sorry new to OC) that would get the speed of the train it’s connected to and return the speed value

Applications of the suggestion
You could make a script that checks train speed and adjusts it to a preset value for a better auto control thing. You could have a script that measures the trains mass and speed to calculate where it’s gonna stop for better station stops

**Comment by mzuletal** [comment]
there's already an integration with OC and CC:tweaked that you can use to do the stuff you are mentioning (This is by using the detector and locomotive control augments). You can check the official discord of Immersiva Railroading for more info about how it works and a few showcase of how it is being used. :)

**Comment by KEEGUNATOR2** [comment]
Oh, wow should have done my research before opening a ticket.. thank you!
