### ISSUE TITLE
Enable more models in one custom track

### ISSUE THREAD

**Issue by touhourailway** [TeamOpenIndustry/ImmersiveRailroading#1128]
Maybe you will ask the reason. Hmmm ok, just image I 've made a old track with tall grass randomly and I don't want it seemed too regular.
Ok, I know this is decorate not useful function, even I will use this make more constructions including the bridge and tunnel what you always say they are not necessary but... yes, the mod really made so much than other mods, I've seen the mod from player stuck in platform to train door is openable, developers fixed many bugs and create many new fun, you really conscientious. This is my last hope, and especially many server just use your mod for create.

**Comment by cam72cam** [comment]
Closing in favor of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1197
