### ISSUE TITLE
Crash that I presume to be incompatibility with kemonocraft mod

### ISSUE THREAD

**Issue by rakostep** [TeamOpenIndustry/ImmersiveRailroading#1129]
Hi there, sorry to bother you with this.

I'd like to report a crash involving IR and Kemonocraft mod. Tho this wouldn't be much of an issue running on singleplayer(it crashes once but launching the world again forcefully would not have problems), but running this on servers won't let it launch. Heres the crash log btw(MC version 1.16.5 btw): 

[crash-2022-01-06_13.02.18-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7822204/crash-2022-01-06_13.02.18-server.txt)

I'm showing this here to inquire if there are some workaround this problem and stuff while I'm also trying to send this issue to the kemonocraft dev. Thanks for checking this issue up!

**Comment by km00700** [comment]
It seems Forge is returning something obfuscated from Kemonocraft that it thinks is a world. It might be a hardcoded reference to a world, but the latest version of the mod is closed source so I can't really tell what's going-on.

**Comment by rakostep** [comment]
I see, thanks for the input about this.
