### ISSUE TITLE
No fuel or diesel in 1.16.5?

### ISSUE THREAD

**Issue by slyy343** [TeamOpenIndustry/ImmersiveRailroading#1131]
I downloaded the 1.16.5 versions of IR, Track API, UMC, and Forge and loaded up the game to find that the fuel and diesel items are not present. This has never happened to me on previous versions and i'm not sure if its my pc or a problem with the mod on 1.16.5

If anyone else had had this problem or knows of a fix please let me know. I love this mod and it stinks when I cant use any diesel locomotives.

**Comment by WrongWeekend** [comment]
Diesel fuel items/fluids have never been included with IR. You will need to install a tech mod such as IE that adds diesel fuel or modify the IR config to allow diesel locomotives to use another available fluid as fuel.
