### ISSUE TITLE
Crash when place rail with blueprint

### ISSUE THREAD

**Issue by gaiteli** [TeamOpenIndustry/ImmersiveRailroading#1132]
When I laydown the rail in blueprint mode, It suddenly crashed. Near the rail there are some blocks made by the MOD Chisels & Bits which I think maybe the cause of the crash. AND in addition, I notice a very interesting phenomenon, that Your feet seem to be stuck with mucus making you move slowly when you walk on the place where the rail just existed.

[crash-2022-01-10_23.02.01-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7839777/crash-2022-01-10_23.02.01-client.txt)
[crash-2022-01-10_23.08.12-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7839781/crash-2022-01-10_23.08.12-client.txt)

**Comment by Squarebuilder** [comment]
Hi there,

I also have the problem that Minecraft crashes as soon as I add the Rail with Blueprint to my inventory. I only installed the three required mods, which is why I don't think it's up to Chisel and Bits.

**Comment by km00700** [comment]
There's a mod conflict between IR and Serene Seasons

**Comment by gaiteli** [comment]
> There's a mod conflict between IR and Serene Seasons

BUT most of the time, there's no crash. So it is must something or one typical action that triggers the crash.

**Comment by SpecificationsL** [comment]
ok when i place it down it lags and crash pls help me and i used a steam engine train and i start it up it crashes help me pls

**Comment by Larky2k** [comment]
Post crash report

**Comment by BugfinderGameCrasher** [comment]
Ok so I have found that the setting for using VBOs tends to crash games when loading tracks. If you turn it off the game is fine and dandy.
