### ISSUE TITLE
Im having issues with the items from the mod

### ISSUE THREAD

**Issue by YouMustBeAClown** [TeamOpenIndustry/ImmersiveRailroading#1133]
when i open JEI in my inventory i and type @Immersiverailroading i only see one train and a few items and i cant find anywhere of what to do 

![image](https://user-images.githubusercontent.com/97757823/149567385-830a8d4f-4990-4dfd-9808-d39a34922d1f.png)

**Comment by Matt2021lv** [comment]
i dont have **biodiesel** and thats making me mad like where did it go? i have 16.5 version. and its not showing anywhere!

**Comment by km00700** [comment]
IR never had biodiesel. That came with Immersive Engineering. As far as JEI, all the IR stock is actually the same item with different NBT data, so it's been compressed in JEI into one to avoid menu clutter. If you're in survival, consider checking out this guide: [https://github.com/TeamOpenIndustry/ImmersiveRailroading/wiki/Getting-Started](https://github.com/TeamOpenIndustry/ImmersiveRailroading/wiki/Getting-Started)
