### ISSUE TITLE
why is 1.10 not out?

### ISSUE THREAD

**Issue by utubysdog** [TeamOpenIndustry/ImmersiveRailroading#1137]
you said that 1.10 was going to be released on October, 17 2021

[](https://www.youtube.com/watch?v=iYCUyjspO7Y&ab_channel=cam72cam)

**Comment by km00700** [comment]
IR is a volunteer effort by cam and the dev team. Any stated release dates are not official hard deadlines. If life events happen, those will almost always take priority over IR development. Additionally, features may be finished by a certain time, but not refined by the beta testers yet. Please be patient.

TL;DR: IR is not a paid job, so timelines are flexible. Be patient.
