### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by XxneonisawesomexX** [TeamOpenIndustry/ImmersiveRailroading#1143]
Here's Thee 2 The Bugs In The Mod:
1: I Cant Delete The Trains (I Know How To But It Doesn't Work)
2: The Golden Spike/Custom Curve Can't Work, When I Try To Use The Golden Spike, It Does Nothing

**Comment by Larky2k** [comment]
Please post more info please, and follow the convention of posting bug reports. Will help us greatly.

**Comment by XxneonisawesomexX** [comment]
Well, If I'm Not Mistaken, When A Train Derails, I Tried To Delete It By Left Clicking It, But I Did Not Work! 
Example:
The First Time I Used The Mod, I Built A Little Railroad Next To A Dessert Village, I Tested It By Using The Hand Car, When I Go Up A Small Slope, It's Stops On The Middle Of The Slope (I Don't Need That One Fixed), And When I Ejected The Handcar, It Slides Down Off The Slope And The Handcar Going Fast At The Opposite Direction And The Hand Car Derails At The Beginning Of The Track, I Tried To Delete It By Using The Left Click Button, I Don't Know How Else To Do It!
Also,The Golden Spike, There Not Much To Explain, When I Tried Using It, I Expected It To Make A Custom Curve, BUT IT DID NOTHING.
So That All I Have To Explain, I Hope Fix These Issues!

**Comment by Larky2k** [comment]
Shift left click to remove stock, are you in blueprint mod

**Comment by XxneonisawesomexX** [comment]
Oh Thank You! Now I Can Delete Trains! Now, How To I Fix The Golden Spike/Custom Curve? And No, I Wasn't On Blueprint Mode When I Experienced That "Issue".

**Comment by Larky2k** [comment]
You got to have Blueprint checked to edit custom curves

**Comment by XxneonisawesomexX** [comment]
How Do I Do That?

**Comment by km00700** [comment]
check the box that says "Place Blueprint" If you can't see this box at the bottom of the rail configuration GUI, change your GUI size in the MC settings menu to something that's not Auto.

**Comment by XxneonisawesomexX** [comment]
What About The Golden Spike?

**Comment by km00700** [comment]
Once you have a blueprint placed, right-click using the golden spike on the tile with the transparent spike sticking out of it. Then right click at the desired endpoint using the spike. Shift+left click on the original tile will place the track.

**Comment by XxneonisawesomexX** [comment]
When I Try To Place The Golden Spike It Won't Appear

**Comment by km00700** [comment]
You don't place a golden spike. You place the track blueprint and use the golden spike to edit it before building the track.

**Comment by XxneonisawesomexX** [comment]
Oh Wait Never Mind I Watch A Tutorial Of How To Use The Golden Spike! Also, Thanks For Your Help!
