### ISSUE TITLE
sudden crash when train is running into a station, 1.16.5

### ISSUE THREAD

**Issue by ink717** [TeamOpenIndustry/ImmersiveRailroading#1146]
Resource pack(s) used:
Voxel trains v3
north American v0.2
Dark Raiders Freight
SS4
Amtrak+
[crash-2022-01-31_18.08.39-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/7974824/crash-2022-01-31_18.08.39-client.txt)

**Comment by km00700** [comment]
It appears your world has a GP38-2 placed but you do not have a resource pack with that loco in it installed.
