### ISSUE TITLE
1.16.5 creative mode 

### ISSUE THREAD

**Issue by 07jofurc** [TeamOpenIndustry/ImmersiveRailroading#1147]
game crashes when trying to access the inventory screen with the mod on it and more

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to  inventory
 2. click the right arrow going into the next section of items
  3. game crashes
  this also happens when typing in the name of the items
 
**Expected behavior**  
the next set of items to be available 

(i know the log shows more mods but it was doing it before they were added too
[crash-2022-02-04_16.23.55-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8006385/crash-2022-02-04_16.23.55-client.txt)
)

**Comment by Larky2k** [comment]
Need to be on java 8 not 16

**Comment by 07jofurc** [comment]
oh ty
