### ISSUE TITLE
Trains wont run in multiplayer

### ISSUE THREAD

**Issue by ToddyGoat** [TeamOpenIndustry/ImmersiveRailroading#1151]
**Describe the bug**  
A clear description of what the bug is. Trains will not work at all in multiplayer. But strictly multiplayer.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Load into Multiplayer in any gamemode
 2. Build any sized rail line, and attempt to use a train on it.
 
**Expected behavior**  
 A clear description of what you expected to happen.
 The train will not run, neither with, or without fuel requirements.
 
**System Information**  
 OS: Windows 10
 <br>System Memory: 32 GB
 <br>Allocated Memory: 8 GB
 <br>CPU: Ryzen 7 3700x
 <br>GPU: Gigabyte 3060
 <br>Game Version: 1.16.5
 <br>Forge-Version: 36.2.20

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.
 Appleskin
 Clumps
 Create
 Curios API (Forge)
 Enhanced Mob Spawners
 FallingTree
 Flywheel
 Immersive Engineering
 Immersive Railroading
 JourneyMap
 Just Enough Items
 Natures Compass
 Optiforge
 Ore Excavation
 Performant
 Puzzles Lib (Forge)
 Silent Gear
 Silent Lib
 Silent's Gems
 Sophisticated Backpacks
 Structures Compass
 Track API Universal Mod Core

**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.
https://mega.nz/folder/m81llKpB#lljZZXteFHYlYMDt0skhsA

**Additional context**  
Ive tried to drive the Ten-Wheeler, Big Boy, and A1 with this issue being apparent on all 3. They just stay still and wheelslip infinitely.

**Comment by km00700** [comment]
Wheel slipping with trains on servers is usually due to the server not having fuelRequired set to false in its copy of the IR config file.

**Comment by ToddyGoat** [comment]
I just edited the config and set it to false, still got the same bug, I might have phrased it wrong, but the trains just will not move period, but they do the animation like they are.
Aswell the audio for them is working.

**Comment by Larky2k** [comment]
Is the server a forge server or a hybrid server?

**Comment by ToddyGoat** [comment]
Its a forge server, im using Apex Hosting if specifics are needed

**Comment by ToddyGoat** [comment]
Im checking some of the datalogs now and its registering the trains as an "unknown entity", that probably has something to do with it.

**Comment by Larky2k** [comment]
That's not the cause. It's a mod conflict or using a plugin server.

**Comment by ToddyGoat** [comment]
Do you have any clues as to which mod it could be?

**Comment by Larky2k** [comment]
Does it do it single player?

**Comment by ToddyGoat** [comment]
It doesnt occur in single player at all, and im about to restart it again just to be sure.

**Comment by ToddyGoat** [comment]
Just did a server restart, its still doing the same thing.

**Comment by ToddyGoat** [comment]
Ok. Turns out im an idiot, Got home from work, and messed around the server config. It didnt take the file for the IR config because it had a (1) Next to the name due to me being an idiot and copying the file twice. The issue is resolved. Thank you for being patient with me lol.
