### ISSUE TITLE
Rendering items (Minecraft 1.16.5)

### ISSUE THREAD

**Issue by AlexMaudov** [TeamOpenIndustry/ImmersiveRailroading#1152]
For some unknown reason, the game is CONSTANTLY crashing.
And all this is due to the fact that for some reason he cannot render a Large Wrench.
Here is the crash log:
[crash-2022-02-13_15.51.02-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8055468/crash-2022-02-13_15.51.02-client.txt)

(PS: for those who write about 8 java - yes, I have 8 java installed, not 16...)

**Comment by arig4m3r** [comment]
I'm having the same issue

**Comment by km00700** [comment]
You're using Java 16, you need to use Java 8.

**Comment by arig4m3r** [comment]
> You're using Java 16, you need to use Java 8.

![image](https://user-images.githubusercontent.com/21111468/153770862-fbdbca95-b56a-4494-b8f3-6563fc03973a.png)

**Comment by km00700** [comment]
The log says MC is using java 16, so check your launcher configuration to make sure it's using the correct java version. Just because you have 8 as your system default doesn't mean MC is using it.
