### ISSUE TITLE
Error loading mod (1.16.5)

### ISSUE THREAD

**Issue by UWUmmm28471** [TeamOpenIndustry/ImmersiveRailroading#1157]
Anytime i try starting up the modpack it pops up with this

![Minecraft crash](https://user-images.githubusercontent.com/100202023/155118317-bf638f73-26d9-478e-af22-bae0218c3165.png)

What does this mean? And how can it be fixed

**Comment by km00700** [comment]
You either are missing or have an incorrect version of TrackAPI.
