### ISSUE TITLE
Track radius should be consistent at different angles 

### ISSUE THREAD

**Issue by AndMattBurt** [TeamOpenIndustry/ImmersiveRailroading#1159]
When placing blueprints, extending the angle (22.5 to 45) causes the radius to increace slightly meaning that 2 halves of a turn that are not the same angle dont line up when placed together
![image](https://user-images.githubusercontent.com/43927299/155482457-a2ed8f5a-d91a-4112-87f6-0ad4fdb20f29.png)
This is a 194 turn at 33.5 and 45deg

**Comment by AndMattBurt** [comment]
this stumped me for ages trying to match up the switch!

I dont know coding but it seems harder to do whatever this is vs having the true radius straight from the value in the blueprint?

**Comment by cam72cam** [comment]
This has to do with how minecraft blocks are spaced
