### ISSUE TITLE
Trains wont show

### ISSUE THREAD

**Issue by 793A** [TeamOpenIndustry/ImmersiveRailroading#1161]
Erroe with immersive railroading 1.12.2 , Trains won't render, help.

**Comment by 793A** [comment]
[debug.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8147498/debug.log)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8147499/latest.log)

**Comment by 793A** [comment]
no

**Comment by 793A** [comment]
i have video, but not screenshot

**Comment by km00700** [comment]
that works

**Comment by 793A** [comment]
ok

**Comment by km00700** [comment]
There's sometimes an issue with IR and RTM together, does it work without RTM?

**Comment by 793A** [comment]
tried to remove rtm. broke minecraft. :( . have to redownload minecraft.

**Comment by joewhojow** [comment]
I had the same issue except it was installing a mod before opening Minecraft. Basically, if you downloaded a mod before accessing the world all trains will disappear to fix just take out the mod and run the world. (Idk if this is your problem but it might work)

**Comment by RatorLP** [comment]
RTM is known to break a ton of things. That mod runs incredibly unstable, i wouldn't really use it outside of some just-for-fun-goofing-around-stuff. 
Basically, don't expect other things to behave as usual as long as RTM is installed.

**Comment by philix1** [comment]
also what is RTM

**Comment by 793A** [comment]
This will be closed. i have fixed it. just that some mods weren't compatible with immersive railroading
