### ISSUE TITLE
Train forces me to dismount after I right click it to get inside it

### ISSUE THREAD

**Issue by Revisty** [TeamOpenIndustry/ImmersiveRailroading#1162]
Every time I right click a train, it forces me to dismount the train after I get inside of it

**Comment by km00700** [comment]
send latest.log from the .minecraft/logs folder after a session where you attempt to board the train.

**Comment by Revisty** [comment]
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8191965/latest.log)

**Comment by km00700** [comment]
It looks like you're dismounting because the server isn't processing that you're boarding the train. Are you in single player or multiplayer?

**Comment by Revisty** [comment]
single
