### ISSUE TITLE
Weird Reflections on tracks and trains

### ISSUE THREAD

**Issue by Laducatigg** [TeamOpenIndustry/ImmersiveRailroading#1166]
**Describe the bug**  
When i use a shader that uses specular, the train and tracks show these patches of reflectiveness through out the trains / tracks.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 Shows up on any shader that enables Specular 
 
**Expected behavior**  
Using Dark Raider's Monorails, even using the base mod, it shows these weird reflections.

**Screenshots**  
[https://cdn.discordapp.com/attachments/237366235069808640/955152552859684894/2022-03-20_13.14.57.png](url)

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory: 32gb
 <br>Allocated Memory: 10gb
 <br>CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
 <br>GPU: NVIDIA GeForce RTX 2070 8GB
 <br>IR-Version: 1.16.5
 <br>Forge-Version:  36.2.30

**Modlist**  
chiselsandbits-0.3.4-RELEASE
effortlessbuilding-1.16.3-2.29
ImmersiveRailroading-1.16.5-forge-1.9.1
LEGENDARY RT SCI-FI RT6 MOD 1.16.5 FORGE
LightingWand-1.16.4-1.8.1
mapperbase-1.16.5-2.4.0.0
Modernxl+1.16.5
OptiFine_1.16.5_HD_U_G8
simplylight-1.16.5-1.4.0-build.24
TrackAPI-1.16.4-forge-1.2.1
Traffic_Plus_1.2.0_1.16.5
Ultimate Immersion Modern Archviz v3.6 (Forge 1.16.5)
UniversalModCore-1.16.5-forge-1.1.3
worldedit-mod-7.2.5-dist
 
**latest.log**
https://drive.google.com/file/d/1Lumyld3HJnw8krVHcyHhu7SE-oM241UJ/view?usp=sharing

**Additional context**

**Comment by cam72cam** [comment]
This will be fixed in the next test-build / released version.
