### ISSUE TITLE
crashing, when I open inventory page

### ISSUE THREAD

**Issue by cheshddf** [TeamOpenIndustry/ImmersiveRailroading#1172]
When I open inventory and and flipping to the second page (the page where the mod tabs) game crashes
[crash-2022-03-29_15.55.23-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8372850/crash-2022-03-29_15.55.23-client.txt)

**Comment by cam72cam** [comment]
Should be fixed in the latest test builds
