### ISSUE TITLE
1.16.5 crash while driving train

### ISSUE THREAD

**Issue by ink717** [TeamOpenIndustry/ImmersiveRailroading#1174]
Full crash log:
[crash-2022-04-01_00.28.12-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8394689/crash-2022-04-01_00.28.12-client.txt)
Sometimes it happens again, with almost identical crash reports.

**Comment by andrboot** [comment]
That crash indicates an issue with rendering a map, rather then IR

**Comment by Larky2k** [comment]
Can't use any other java than 8 with IR your on java 11, nee to downgrade
