### ISSUE TITLE
Dimmable Lights and CG-Specific Light-Level

### ISSUE THREAD

**Issue by SebastianD334** [TeamOpenIndustry/ImmersiveRailroading#1176]
Add the ability to dim lights with a widget and the ability to set interior light levels for CGs individually.

For example, think of a sleeper train, it might have compartments which have dark lighting in general, but you can also turn a dimmer-switch to dim the lights to be even darker.

**Comment by cam72cam** [comment]
Should be in master now and in test builds shortly
