### ISSUE TITLE
Missing Train Models

### ISSUE THREAD

**Issue by Godzilla8756** [TeamOpenIndustry/ImmersiveRailroading#1178]
Hi there, I just downloaded all the necessary mods and resource packs (in the case, voxel trains V4) for the immersive railroading mod, and I've found that some of the models are missing.

I was watching tutorials and reviews on the mod and I noticed that there are certain models I don't have in the current mod. I was wondering if this is from another mod or if this is from a second part of a mod that you have. If you have any idea as to what is going on here and how to fix it, I would greatly appreciate your help. Thank you!

These are the current models I have in the game, which all work fine and dandy!
<img width="482" alt="image" src="https://user-images.githubusercontent.com/102930070/161453229-9222690e-8278-48b1-a45a-7bf54128e0c5.png">

However, in this [video](https://www.youtube.com/watch?v=I8eos6UCf58), you can see he has way more models than my current screen has. Do you know what this is?
<img width="478" alt="image" src="https://user-images.githubusercontent.com/102930070/161453301-306c68bd-a2e2-4b86-9369-dbfb295b3c7e.png">

**Comment by WrongWeekend** [comment]
The only downloads required to run IR (other than IR itself and the correct modloader) are TrackAPI and Universal Mod Core. Resource packs are created and supported by independent authors in the community and are not required to run the mod. Make sure that you are downloading IR and any resource packs from CurseForge (if that is where the packs are originally uploaded to by their authors). You can also ask the video creator which resource packs were used in the video, as there are a large number available and using any combination (or none) of them is completely optional.
