### ISSUE TITLE
[1.12.2] java.nio.BufferUnderflowException when searching JEI for tank rendering GE B40-8 Fuel Tank

### ISSUE THREAD

**Issue by ProsperCraft** [TeamOpenIndustry/ImmersiveRailroading#1185]
**Describe the bug**  
Player reports client crashes every time he opens his inventory because he had searched for tank.
Player is on the official server.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Open TownCraft ONE for 1.12.2 and search for tank

**System Information**  
In the crash report.

**Modlist**  
In the crash report.

Crash report.
https://gist.github.com/Praxalyzed/e0e3719a53c2616a4708607833bbe0fd

**Comment by cam72cam** [comment]
Should be fixed in the latest test build
