### ISSUE TITLE
stop and go when train is moving

### ISSUE THREAD

**Issue by Comet051091** [TeamOpenIndustry/ImmersiveRailroading#1186]
is there a reason that trains stop and go when the throttle is open if so maybe should look into trying to solve this issue
![Screenshot (718)](https://user-images.githubusercontent.com/48610435/162640296-4b7c4008-6da2-4c1b-9a5e-fc866652283a.png)
this screenshot is a example i will be going under 5mph and the engine stops but still shows the speed and wheels moving and its on the latest test build

**Comment by Comet051091** [comment]
this video shows the issue better
https://www.youtube.com/watch?v=6UpDG7tjkZo

**Comment by Comet051091** [comment]
same vid just diff channel name
https://www.youtube.com/watch?v=t6JaHstntL8

**Comment by cam72cam** [comment]
Are you single or multiplayer?

What do you get when you run `/forge tps`?

Would you mind recording the same video with F3 turned on?

**Comment by Comet051091** [comment]
when i type /forge tps its at 20 and i can record again with F3 later

**Comment by Comet051091** [comment]
new vid as requested showing the F3 menu as well as the server tps
https://youtu.be/oDr3CljnXzE

**Comment by cam72cam** [comment]
Ah you are on a server.  If you hit tab you can see the ping delay.  It's likely the ping delay causing the jerkiness

**Comment by Comet051091** [comment]
is there a way to stop ping delay or is that a client only issue?

**Comment by cam72cam** [comment]
Let me know if this is better in the new test builds.  I reduced the amount of network data sent by IR each tick

**Comment by Comet051091** [comment]
all right i'll look next time the server runs on a test build but this is a issue that imo its not #1 on the list but eventually needs to be resolved
