### ISSUE TITLE
Turntable bridge model

### ISSUE THREAD

**Issue by Arbitz** [TeamOpenIndustry/ImmersiveRailroading#1195]
**Describe the suggestion**  
Currently, Turntables are quite lacking. I feel several changes could be made to improve them. The two big changes needed in my opinion are a bridge underneath the rails and animations.

The turntable bridges would work as follows. The model would be a named part on the track model, lets say RAILS_TURNTABLE. This part of the track model would be invisible, only being rendered on turntables. It'd be a nice change of pace from floating track. You could also have an additional part on the track model called RAILS_TURNTABLE_GUIDE, rendering a guiding rail and walkway on the sides of the track.

As for actual turning, I'm referring to Rails of War, as their turntable has proper animations. I don't feel it needs to be super detailed, but seeing rotation would be a nice change.

**Applications of the suggestion**  
These changes are aesthetic, designed to improve the outdated looking turntable model.

**Comment by notsoimmersiverailroader** [comment]
The bridge is available with certain track variants, though a turntable track variant should be added to stock IR.

**Comment by cam72cam** [comment]
Closing in favor of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/887
