### ISSUE TITLE
server crashing after building multiblock or track

### ISSUE THREAD

**Issue by lojziczech** [TeamOpenIndustry/ImmersiveRailroading#1196]
**Describe the bug**  
when placing tracks or clicking with large wrench to form a multiblock the localy hosted server crashes and savegame must be replaced for a backup that was taken before forming the multiblock or placing the track or it will not start

**How to reproduce**  
form a multiblock or place a track
 
**Expected behavior**  
it will form a multiblock and not crash the server

**System Information**  
 OS: Windows 10 Pro
 <br>System Memory: 32gb
 <br>Allocated Memory: 8gb server 8gb client
 <br>CPU: intel i7 9700k
 <br>GPU: MSI 1070 ti 8gb
 <br>IR-Version: 1.9.1_1.16.5
 <br>Forge-Version: 1.16.5 - 36.2.21
**Modlist**  
AppleSkin
Architectury API (Forge)
Chem Lib
Chunk Loaders
CoFH Core
Ender Storage 1.8.+
GeckoLib
JourneyMap
Moving Elevators
Mowzie's Mobs
Obfuscate
PneumaticCraft: Repressurized
ProjectE
Security Craft
Sophisticated Backpacks
The One Probe
Thermal Foundation
Thermal Locomotion
Tinkers Construct
A Lib
Alchemistry
Applied Energistics 2
Biomes O' Plenty
Blood Magic
CB Multipart
CodeChicken Lib 1.8.+
Configured
Cooking for Blockheads
Corail Tombstone
Create
Create Crafts & Additions
Flywheel
FTB Backups (Forge)
FTB Library (Forge)
Glasscutter
iChunUtil
Immersive Engineering
Immersive Industry
Immersive Petroleum
Immersive Railroading
Inventory Tweaks Renewed
Iron Chests
Just Enough Items (JEI)
Just Enough Resources (JER)
Mantle
Mekanism
Mekanism Additions
Mekanism Generators
Mekanism Tools
Morph
Mouse Tweaks
MrCrayfish's Furniture Mod
MrCrayfish's Vehicle Mod
Neat
Pam's HarvestCraft 2 - Crops
Pam's HarvestCraft 2 - Food Core
Pam's HarvestCraft 2 - Food Extended
Pam's HarvestCraft 2 - Trees
Patchouli
Project Red - Core
Project Red - Exploration
Project Red - Illumination
Project Red - Integration
Project Red - Transmission
Refined Storage
Refined Storage: Requestify
Scorge
Storage Drawers
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
Thermal Cultivation
Thermal Expansion
Thermal Innovation
Track API
Universal Mod Core

**latest.log**
https://pastebin.com/0SbkbiYa

**Additional context**  
allready tried diffrent versions of universal mod core and immersive railroading. downgrading immersive railroadnig resulted in client crashing immediately after serching for large wrench

**Comment by Purp1ePeak** [comment]
It's a Java issue. Use Java 64bit 8u311. I've had the same issue before. Change your Java!

**Comment by Larky2k** [comment]
Can't use any other version of Java part from java 8 your using java 15
