### ISSUE TITLE
Rotation Widget Addon for next update - Loco Speed Based Rotation

### ISSUE THREAD

**Issue by Nathan-TheSteelMann** [TeamOpenIndustry/ImmersiveRailroading#1198]
A widget similar to wheels! Have it still rotate on a definable axis but have its speed based on loco speed like wheels, would make stuff like fans and inverse wheels, and other small parts possible.

Something like having the normal defined rotation widget, but having to add a tag on the end like "_LOCOSPEED_TRUE" that makes it so the Widget rotates on it's axis similar to how Wheels under the loco rotate connected to the throttle.

**Comment by cam72cam** [comment]
Possible through Animatrix
