### ISSUE TITLE
Very often lag spikes on very large world [1.16.5, Forge, Optifine]

### ISSUE THREAD

**Issue by biauk** [TeamOpenIndustry/ImmersiveRailroading#1199]
When riding on a very large world, I experienced lag spikes for about every 5 minutes, when FPS dropped to 1-2 and ms ticks jumped over 100, sometimes reaching 500. Normally I got 40-50 FPS.

Windows 10, AMD Radeon, 8 GB RAM, 5 GB allocated to Minecraft.
Spark profiler: https://spark.lucko.me/54Wl0DfqNC
![2022-05-03_19 27 54](https://user-images.githubusercontent.com/58109852/166515852-090f24dc-b1a2-4e6f-9af8-4b3b231b74ca.png)
![lista 05 2022](https://user-images.githubusercontent.com/58109852/166515911-24889363-2637-44d8-a81e-aff769489fcb.PNG)

**Comment by cam72cam** [comment]
Closing as not an IR issue
