### ISSUE TITLE
I get an IRM (Manual) and not a blueprint book.

### ISSUE THREAD

**Issue by ErenInnit** [TeamOpenIndustry/ImmersiveRailroading#1203]
When I try to craft the blueprint book to start making the crafting basin/other machinery, instead of making me a blueprint book it turns into an Immersive Railroading Manual and it says "Type: PLATE_MACHINE" but there are no controls to change the type, I have checked it many times and it also crashes when I make the large wrench. (1.16.5)

Steps to reproduce the unwanted behavior:

 1. Get steel.
 2. Get a book.
 3. Try to craft the blueprint book.
 
**Expected behavior**  
I expected to craft a regular blueprint book but I soon realised that it didnt even exist. Not even in creative, not with /give commands.

**Screenshots**  
![Στιγμιότυπο οθόνης (342)](https://user-images.githubusercontent.com/105375246/167889797-ad840eed-04bc-41f5-b790-d3d1588ec970.png)

**System Information**  
 OS: Windows 11
 <br>System Memory: 32gb
 <br>Allocated Memory: 32gb
 <br>CPU: AMD Ryzen 5 5600g 3.9ghz
 <br>GPU: NVIDIA RTX 3080 Ti 12GB GDDR6X
 <br>IR-Version: 1.4.1.3-1.16.5
 <br>Forge-Version: 1.16.5-36.2.33

**Modlist**  
BetterCaves Forge
YUNG's API
Chisel
Citadel
Ice and Fire: Dragons (or Ice and Fire)
COFH Core
Immersive Engineering
Immersive Petroleum
Immersive Railroading
Cooking For Blockheads
CTM-MC
JEI
DynamicTrees
Optifine
OptiForge
TrackAPI
ThermalFoundation
ThermalCore
UniversalModCore
ValhesiaCore
ValhesiaStructures
Xaero's Minimap

**latest.log**
https://pastebin.com/mhuh9n7U

**Additional context**  
Please do not say "oh there's a different language here and there" because I am greek and I don't understand english that well so please be warned.

**Comment by Larky2k** [comment]
It's not called blueprint

**Comment by Larky2k** [comment]
Shift click in the air

**Comment by km00700** [comment]
If you're crashing with the large wrench, you're probably using Java 16 instead of Java 8.

**Comment by ErenInnit** [comment]
> If you're crashing with the large wrench, you're probably using Java 16 instead of Java 8.

No, I'm not. I made sure to check everything so it would be right and compatible with all my mods.

**Comment by ErenInnit** [comment]
> Shift click in the air

Doesn't work, as said in the text above, I have tried it many times, even removed every mod except IRL itself and the dependency.

**Comment by Larky2k** [comment]
Are your trying to make the track blueprint

**Comment by ErenInnit** [comment]
> Are your trying to make the track blueprint

No I'm not, I'm as said, trying to craft the blueprint book as shown in the description of the mod (IRM)

**Comment by Larky2k** [comment]
There is no such thing as blueprint book?? IR only has the Manuel and Track blueprint.

**Comment by km00700** [comment]
The wiki name needs to be updated, but the IR Manual is called the Blueprint Book in the wiki. Usage instructions should be exactly as they are in the IR wiki entry for "Blueprint Book"
