### ISSUE TITLE
game crash when anything collides with a train.

### ISSUE THREAD

**Issue by Aakkuli** [TeamOpenIndustry/ImmersiveRailroading#1205]
The game crashes when literally anything touches the trains. In my case only locomotives. I did not test the wagons. My friend has this same problem.

Collisions that trigger a crash (in my testing):
-A player touches a train
-An item touches a train
-A player enters a train

I play on forge 1.12.2 and I have tried these versions of Immersive Railroading:
-1.8.0-7e0f82
-1.9.0
-1.9.1
All of them have the same bug.

crash report (when touching a train on it's side):
https://pastebin.com/wSmBePkv

Any help is largely appreciated.
Thanks in advance!

**Comment by cam72cam** [comment]
Whatever you have in sponge forge is causing issues:
org.spongepowered.common.event.SpongeCommonEventFactory.callCollideEntityEvent

**Comment by Aakkuli** [comment]
Thank you for letting me know! I'm not that good at reading crash reports...

**Comment by Aakkuli** [comment]
I can't seem to fix this issue. I deleted SpongeForge but now when I launch Minecraft it just crashes right away.

![image](https://user-images.githubusercontent.com/70842568/168454030-3c0a758d-ee08-406a-ac06-ae1ac1770be7.png)

I have not configured SpongeForge in any way.

**Comment by Aakkuli** [comment]
I FIXED IT!!!!! WOO!!
I deleted Surge mod and spongeforge mod. The it just... worked!
