### ISSUE TITLE
Missing resource packs should not cause the game to crash

### ISSUE THREAD

**Issue by miiichael** [TeamOpenIndustry/ImmersiveRailroading#1208]
IR (1.16.5-5.0.7-143 in my case) should be kinder to users missing resource packs, rather than steering the client into a wall. Can a check happen during server connect handshake instead?

[crash-2022-05-16_19.38.26-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/8699707/crash-2022-05-16_19.38.26-client.txt)

**Comment by cam72cam** [comment]
Closing in favor of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1357
