### ISSUE TITLE
Perfomance bad inglish

### ISSUE THREAD

**Issue by IhaveweakPC** [TeamOpenIndustry/ImmersiveRailroading#1210]
Plsss make a option to remove the smoke because its so lag my minecraft run with 5 fps??? plss understand me people that dont have a good pc want to play this mod but they cant and its because of the models of the trains why a bigger thing just istead of a simple thing like rails of war this mod is so much good too but theres no way to use like to transport items and etc its need to change! Simple things are better pls just understand me i know you all worked so hard to make the models but pls make something that resolve this lag ;-) i love your mod pls understand:)

**Comment by cam72cam** [comment]
immersiverailroading_graphics.config particlesEnabled = false
