### ISSUE TITLE
Request for Rolling Stock

### ISSUE THREAD

**Issue by OVSBulleid** [TeamOpenIndustry/ImmersiveRailroading#122]
I think it would be magical if you could add this locomotive: the LNER Thompson A1/1 "Great Northern" pacific train because it looks really good. There isn't a colour photo of it but it was dark blue which looks really good. 

![19500000s g s long lner a1 great northern 60113 from gsl files 3](https://user-images.githubusercontent.com/33783130/32980518-a73c00fe-ccb7-11e7-93dc-2e92de9be29c.jpg)

**Comment by cam72cam** [comment]
That's pretty similar to the A1 Peppercorn I already have in game.  It should be easy to adapt the model

**Comment by OVSBulleid** [comment]
If it helps, here are two diagrams for it.
![great northern](https://user-images.githubusercontent.com/33783130/33408075-57dbd802-d5c4-11e7-97ad-7063151fdbb7.JPG)
![44](https://user-images.githubusercontent.com/33783130/33408198-183120f8-d5c5-11e7-9560-cefc7847e0a5.jpg)
