### ISSUE TITLE
EXPOSED

### ISSUE THREAD

**Issue by YouTubeGaming09** [TeamOpenIndustry/ImmersiveRailroading#1221]
![image](https://user-images.githubusercontent.com/106003744/169679570-7c63da0f-28c9-4c40-90bc-40ac8b1f6a1b.png)
![image](https://user-images.githubusercontent.com/106003744/169679576-c59c8a46-89b8-4d68-bfeb-8320c863ab39.png)
![image](https://user-images.githubusercontent.com/106003744/169679577-5bf81404-a5c4-49b1-ba1c-69a294049bc4.png)
![image](https://user-images.githubusercontent.com/106003744/169679572-b9f85ebc-f992-4f29-8930-11a5ff75286c.png)
![image](https://user-images.githubusercontent.com/106003744/169679571-96f37b30-68fd-4c79-b7f1-da3e4328fe3e.png)
![image](https://user-images.githubusercontent.com/106003744/169679573-10dbdb58-8d63-41e3-8cef-f9956f6f9a1b.png)
![image](https://user-images.githubusercontent.com/106003744/169679574-8fc5998b-28af-464f-a339-192cfe8dbeaf.png)
![image](https://user-images.githubusercontent.com/106003744/169679575-1ad1d219-e93d-4cc3-ac9d-27d129bc039a.png)
![image](https://user-images.githubusercontent.com/106003744/169679579-dfeca948-3a18-41f4-9daa-e31f3868069c.png)
![image](https://user-images.githubusercontent.com/106003744/169679581-9e7d524e-97f3-42cb-a350-c7c1fe7b2fe6.png)
![image](https://user-images.githubusercontent.com/106003744/169679580-eae1ab94-0c0b-42de-89ba-20b56a227a5c.png)
![image](https://user-images.githubusercontent.com/106003744/169679582-5a70c774-1293-49ae-926f-e19ead297ecd.png)
![image](https://user-images.githubusercontent.com/106003744/169679583-2efb4901-5df4-4e1f-9d3f-645ecbfc0ee9.png)
![image](https://user-images.githubusercontent.com/106003744/169679584-41677277-878e-4c0e-849c-c3af70af95b9.png)
![image](https://user-images.githubusercontent.com/106003744/169679578-29c43894-9fdc-47e7-8cb9-1f163cbe44cc.png)
![image](https://user-images.githubusercontent.com/106003744/169679585-97ad6765-afa5-4313-938e-e8b9e31109d4.png)
![image](https://user-images.githubusercontent.com/106003744/169679586-8a324913-0fc7-4fcc-8956-d54bece25c18.png)
![image](https://user-images.githubusercontent.com/106003744/169679587-6bb58d45-dfab-4500-abb3-5d90d40d6cfc.png)
![image](https://user-images.githubusercontent.com/106003744/169679588-a109d81f-bb0c-453e-83cc-3985beffd0b5.png)
![image](https://user-images.githubusercontent.com/106003744/169679589-d471cf9b-1764-4320-9fc4-7d85aa402135.png)
![image](https://user-images.githubusercontent.com/106003744/169679591-79509143-ef2b-4c05-92b7-9629e7031267.png)
![image](https://user-images.githubusercontent.com/106003744/169679592-b6d63766-7994-4041-9bac-9525691ccc1c.png)
![image](https://user-images.githubusercontent.com/106003744/169679590-b7cc6ce7-e051-4624-adf4-231b18c42ca7.png)
![image](https://user-images.githubusercontent.com/106003744/169679593-4cda3438-cbfa-4673-ad4e-019c155cb087.png)
![image](https://user-images.githubusercontent.com/106003744/169679594-b708e0d4-d9f9-4181-9e36-741af1ee4218.png)
![image](https://user-images.githubusercontent.com/106003744/169679595-8503177a-9f83-46f5-98e5-779e041e7621.png)
![image](https://user-images.githubusercontent.com/106003744/169679596-c1e12ed3-c319-47a4-babd-317b9f118d17.png)
![image](https://user-images.githubusercontent.com/106003744/169679598-b02f614d-682f-4d13-ad6b-a41b7d0a4856.png)
![image](https://user-images.githubusercontent.com/106003744/169679597-8d13d034-a8a8-4004-a0ae-d360da338697.png)
![image](https://user-images.githubusercontent.com/106003744/169679570-7c63da0f-28c9-4c40-90bc-40ac8b1f6a1b.png)

**Comment by km00700** [comment]
Glad you know how to inspect element.
