### ISSUE TITLE
Rail Squeal Sound On Sharp Curves

### ISSUE THREAD

**Issue by WebSoak** [TeamOpenIndustry/ImmersiveRailroading#1241]
-=[Describe the suggestion]=-

Users can add wheel screeching sound effects to their tracks or trains. The sound would play as trains take sharp turns. The sound intensity would increase with the degree of the turn. Depending on the intensity of the turn, nearby players could hear the screeching sound effect. The sound radius should be configurable. The degree that causes rail squealing should also be configurable. 
If devs do not wish to create a sound for the base mod, at least give us the option to use this with our own models : )

-=[Applications of the suggestion]=-
The screeching sound created when trains turn is very iconic. The feature would immensely increase immersion. The feature would allow for more realism and immersion in recreation builds as well. This is a key and well known train sound to anyone who lives in urban areas, where trains must navigate tighter turns.

**Comment by AirplaneBoi** [comment]
YESSSSS i need that cause I'm trying to recreate the Boston T system and I need the squeaking to convey that city vibe

**Comment by cam72cam** [comment]
Implemented
