### ISSUE TITLE
Rolling Stock crashes game upon using JEI item search bar

### ISSUE THREAD

**Issue by Quizer9O8** [TeamOpenIndustry/ImmersiveRailroading#1246]
Whenever I try to look up something in JEI it always ends up crashing due to something in Immersive Railroading.
The crash log shows something about a rolling rendering issue, but I'm not sure what it is exactly...

See crash log:
https://pastebin.com/WAQSP0kw

**Comment by shikyo13** [comment]
Also crash when searching JEI 

https://pastebin.com/wNK4YZ8Q

**Comment by cam72cam** [comment]
This is an issue with the cache/universalmodcore folder.  Deleting that should fix it, also underlying bug was fixed in the test builds
