### ISSUE TITLE
Stock glitching into Locomotive

### ISSUE THREAD

**Issue by Bomboy09** [TeamOpenIndustry/ImmersiveRailroading#1250]
**Describe the bug**  
When I am not in a train and I have a loop, if the train leaves render distance, then the cars teleport into the Locomotive or in a different order.

**How to reproduce**  
1. Set up Track (I had a loop)
2. Build your train (Mine was: K4+Tender w/ boxcar and caboose)
3. Start the train rolling and let it leave render distance (my Render Distance was 15 chunks)
 
**Expected behavior**  
The Train will freeze and not move until back in render distance, in a different order, commonly with cars inside one another.

**Screenshots**  
![2022-06-29_23 20 28](https://user-images.githubusercontent.com/103078406/176593230-666cfcc4-55cf-4815-86ed-ed9cfc48f61e.png)

**Modlist**  
Immersive Vehicles (w/ packs)
Immersive Railroading
Immersive Engineering
OpenComputers
Traffic Control
Furenikus Roads

**Comment by cam72cam** [comment]
Fixed with new physics system
