### ISSUE TITLE
Rolling Stock Does not exist on this Server

### ISSUE THREAD

**Issue by Tobiasdumy** [TeamOpenIndustry/ImmersiveRailroading#1254]
Im Trying to place down UNU trains but it says rolling stock does not exist can i have some help im using aternos

**Comment by km00700** [comment]
UNU trains don't work serverside without some extra steps because they don't load via the IR officially supported method. You need to make a copy of the UNU mod jar, change the extension to ".zip"  and install it server-side in the [server-directory]/config/immersiverailroading/ folder.
