### ISSUE TITLE
ComputerCraft/CCTweaked integration for 1.16.5?

### ISSUE THREAD

**Issue by bauerbach** [TeamOpenIndustry/ImmersiveRailroading#1258]
OpenComputers is not going to upgrade to 1.16.5, yet the card that is supposed to be used with OpenComputers is still in this mod. For 1.16, can you make it so that you can use ComputerCraft/CCTweaked to automate trains? I want to be able to automate trains in 1.16!

**Comment by cam72cam** [comment]
CC automation is already supported
