### ISSUE TITLE
The door switch is not smooth enough

### ISSUE THREAD

**Issue by fastjim** [TeamOpenIndustry/ImmersiveRailroading#1267]
Now the locomotive can open and close the door, which is undoubtedly a good thing. However, it is not smooth enough to open and close the door. There is a problem with the locomotive controller that controls the door switch. He only decides the size of the door according to the strength of Hongshi, and cannot open the door smoothly

**Comment by Larky2k** [comment]
Door opening is as smooth as the plate can open the door with left click and drag or if the modeller has done it as a Google then it's instant

**Comment by fastjim** [comment]
Now, I have finished the model making and can open the door by hand normally. However, if the locomotive controller is used to open the door, it will open instantaneously without any animation in the middle

**Comment by Larky2k** [comment]
That's how the Toggle function works

**Comment by fastjim** [comment]
So can we only maintain the status quo? I hope he can have a smooth door. Does it need to wait for the author to release the latest module?

**Comment by Larky2k** [comment]
there is no in-between with toggle

**Comment by fastjim** [comment]
OK, I hope the author can update in the next version. Thank you for your reply.

**Comment by fastjim** [comment]
为什么呢？
