### ISSUE TITLE
FileNotFound Item render error 1.12.2

### ISSUE THREAD

**Issue by Steven11q** [TeamOpenIndustry/ImmersiveRailroading#1269]
1.12.2 java 8 specified in the launcher
latest 1.12 version of IR

Whenever I open the creative inventory to the IR page, the game crashes with that log. I don't think its a mod conflict because of the content of the log but I could always be wrong. 

https://pastebin.com/Gu3dU03y

**Comment by Larky2k** [comment]
delete you cache folder (its in the instance of MC your using) and start MC

**Comment by Steven11q** [comment]
That worked! Thank you so much!
