### ISSUE TITLE
Stock Request: 1930 Vulcan 0-4-0 Saddle Tank 

### ISSUE THREAD

**Issue by Sir-Technical** [TeamOpenIndustry/ImmersiveRailroading#127]
I would absolutely LOVE to have this engine in game.  I would really like some smaller engines like this for more compact and mountainous railways(mine).  I would also be a good model for narrow gauge track, if/when that is implemented.  

![image](https://user-images.githubusercontent.com/33890687/33147072-1376095a-cf8c-11e7-8313-96fd01c16fc8.png)

**Comment by cam72cam** [comment]
Good suggestion, Narrow Gauge and Brunel Gauge will probably be in the next release!
