### ISSUE TITLE
*Translucency Support On Models

### ISSUE THREAD

**Issue by WebSoak** [TeamOpenIndustry/ImmersiveRailroading#1273]
**Describe the suggestion**  
Support for *translucent objects in IR

**Applications of the suggestion**  
Allows modelers to add physical windows to trains.

**Comment by SteampsonJake** [comment]
IR already supports that? You can have Alpha 0 for a transparent texture and 1 for opaque

Unless you meant trans_lucent_ in which case it will probably take up to a 100 years and a complete rewrite of IR's render engine

**Comment by WebSoak** [comment]
Translucency. Like what Little Tiles offers with its alpha scaling options

**Comment by cam72cam** [comment]
This might be incredibly difficult due to how MC's render system functions
