### ISSUE TITLE
Proper Ignitions for diesels (carried over from discord)

### ISSUE THREAD

**Issue by NightScale5755** [TeamOpenIndustry/ImmersiveRailroading#1275]
**Describe the suggestion**  
A clear description of what the suggestion is. This template is not for requesting additional models of locomotives, cars, or other rolling stock; those requests should be taken to the Immersive Railroading Discord channel under #suggestions. 
Link: https://discord.gg/CS2RTGq

you know what simple feature IR needs for diesels??? The ability for pack authors to provide a simple sound bite for ignition noises. As well as proper starters. Why? Because pressing the start key and the ignition process being instant and silent is immersion breaking. Among other reasons.

**Applications of the suggestion**  
A description of what the suggestion is needed for, or how it would improve the gameplay experience.

Immersion. Nuff said.

**Comment by cam72cam** [comment]
Implemented
