### ISSUE TITLE
OBJ track model not working

### ISSUE THREAD

**Issue by tANDyeet** [TeamOpenIndustry/ImmersiveRailroading#1276]
Hi,
I made a track model for bidirectional buffer stop with texture in blender. I exported it to obj and in track list it is not showing. 
[buffer.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/9586222/buffer.zip)

**Comment by fastjim** [comment]
I checked your model and found the reason. Because the naming of your model parts did not conform to the specification, IR could not identify them

**Comment by tANDyeet** [comment]
ok, thanks. Where can I find the specification?

**Comment by fastjim** [comment]
![image](https://user-images.githubusercontent.com/105442700/190995693-9cfd0b8a-4a43-4991-9eed-0d9f92ba0516.png)

**Comment by fastjim** [comment]
This is the name of the track parts I sorted out earlier. To be correctly identified, these three parts must be available

**Comment by fastjim** [comment]
Part names should be capitalized. You can also find detailed tutorials on the official Discord

**Comment by tANDyeet** [comment]
ok, thanks. i'll try that

**Comment by tANDyeet** [comment]
I did that, but it is still not working. 
[buffer.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/9598606/buffer.zip) - updated respack

**Comment by fastjim** [comment]
![image](https://user-images.githubusercontent.com/105442700/191044352-030ba1be-af20-43ac-882d-44afbba2e362.png)

I re rendered your part with the blander software, and now it can be correctly recognized by the game

**Comment by fastjim** [comment]
[buffer.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/9599938/buffer.zip)

**Comment by tANDyeet** [comment]
Thanks, it works. But how did you make it work? I renamed all objets to <name>.001, but it still doesn't work.

**Comment by tANDyeet** [comment]
@fastjim

**Comment by Larky2k** [comment]
its easier to explain on the discord https://discord.gg/ygkMtmXC

**Comment by fastjim** [comment]
I used the blander software to re export, which is the same as the problem I encountered for the first time. It seems that the model only supports the OBJ format of blander. I need to use the blander for secondary export after using 3Dmax. Fortunately, however, blander is completely free software, and you can get it on the official website

**Comment by km00700** [comment]
Also the software is called Blender, not blander.
