### ISSUE TITLE
Support For .GIF Files or Animated Textures On Models

### ISSUE THREAD

**Issue by WebSoak** [TeamOpenIndustry/ImmersiveRailroading#1278]
-=[Suggestion]=-
Support for GIF files on models; Or a way to animate textures on Immersive Railroading models.

-=[Applications]=-
Allows for animated display screens on trains, like the ones seen in real life. More accurate models. Adds more life to trains.

**Comment by cam72cam** [comment]
This is beyond what I am interested in implementing in IR
