### ISSUE TITLE
Trains not working on server

### ISSUE THREAD

**Issue by Carsblox** [TeamOpenIndustry/ImmersiveRailroading#1279]
When I place down a train the model is visible however when I get in the train, I can't use the train. I also get stuck inside the train. The only way to get out is by teleporting. When I try to remove the train, the model stays visible until I rejoin (this might be an issue with forge tho).

My server is 1.12.2.

**Comment by Larky2k** [comment]
need more info

**Comment by Carsblox** [comment]
I can't get info such as the logs at the moment. But the server is mohist 1.12.2 with 5gb of ram. I have immersive railroading as well as, immersive engineering, immersive veichles, UNU addon to immersive veichles, cubic chunks, and terra plus plus. If you need the logs i can give it but in a bit.

**Comment by Larky2k** [comment]
can't use plugin servers with IR must be Forge only

**Comment by Carsblox** [comment]
Oh. Well may I know what makes it not work with servers that run both mods and plugins?

**Comment by Carsblox** [comment]
Thanks for the explanation and help

**Comment by Carsblox** [comment]
One problem that I have with not being able to run plugins is that I use tcpsheild for ddos protection and it needs the plugin to work. Is there any alternative you that can work without a plugin?
