### ISSUE TITLE
Trains not working on server

### ISSUE THREAD

**Issue by AnAxolotlGod** [TeamOpenIndustry/ImmersiveRailroading#1280]
When i use trains on a server it does not work.
When i go on to my Aternos server and i place down a train and i set the fuel required to false the animation for the train moving is working but the train does not move.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to any aternos server with immersive railroading and dependencies
 2. place a train down and set fuel required to false
 3. try and drive forward.
 
Then that will happen
 The train will start moving the wheels but the train does not move.

**Screenshots**  

**System Information**  
 OS: Windows
 <br>System Memory: [e.g. "8gb"]
 <br>Allocated Memory: [The memory allocated to your Minecraft instance where you encountered the bug e.g. "4gb"]
 <br>CPU: Intel core i5
 <br>GPU: [e.g. "MSI 1080 8gb"]
 <br>IR-Version: 1.12.2
 <br>Forge-Version: 1.12.2-forge-14.23.5.2859

Immersive railroading 1.12.2 universalmodcore 1.12.2 trackapi 1.12.2 immersive engineering 1.12.2  

 

[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/9621064/latest.log)

**Comment by km00700** [comment]
Did you set FuelRequired to false on the server's copy of the IR config file?

**Comment by AnAxolotlGod** [comment]
thanks for the help :)
