### ISSUE TITLE
No trains/cars preview in inventory

### ISSUE THREAD

**Issue by danarocs** [TeamOpenIndustry/ImmersiveRailroading#1282]
Hello,
wanted to say that i don't have any previews in inventory when i trying to choose a train.

 
**Expected behavior**  
I want someone who had this problem before help me with solution.

**Screenshots**  
How it looks [*click*](https://i.imgur.com/oNPJaUV.png)
Mods folder [*click*](https://i.imgur.com/4iEFZic.png)

**System Information**  
 OS: Windows 11
 <br>System Memory: 16 gb
 <br>Allocated Memory: 6.8gb
 <br>CPU: Intel Core i7-8700K
 <br>GPU: Gigabyte Geforce GTX 1080 8g
 <br>IR-Version: 1.9.1_1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2859

**Modlist**  
[Here](https://i.imgur.com/4iEFZic.png)
 
**latest.log**
[latest.log](https://pastebin.com/FXcT0XEd)

**Comment by Skyler74** [comment]
Hey, I know this is a closed issue but can you enlighten me on how you fixed it? For me the models dont even show up at all, and most resource packs wont load the models either.
