### ISSUE TITLE
Better cabcar support

### ISSUE THREAD

**Issue by notsoimmersiverailroader** [TeamOpenIndustry/ImmersiveRailroading#1286]
**Describe the suggestion**  
A type of car that can access the locomotive's controls without actually being a locomotive so that villagers treat it like a regular passenger car
**Applications of the suggestion**  
Improves immersion, gives pack creators additional options when designing subway or push-pull trains, saves on fuel and steel for survival players,

**Comment by km00700** [comment]
This is a thing for the test build already
