### ISSUE TITLE
MTS/IV style registration

### ISSUE THREAD

**Issue by notsoimmersiverailroader** [TeamOpenIndustry/ImmersiveRailroading#1290]
**Describe the suggestion**  
MTS/IV vehicles can have license plates with custom registries. The registries can be either text or numbers. Using a system like this would work both for numbering compatible stock and naming compatible stock without having to create bulky resource packs just for numbered liveries.
**Applications of the suggestion**  
Players can name and number stock without making a resource pack, save precious megabytes for servers, keeping track of trains.

**Comment by cam72cam** [comment]
Not planned
