### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Petitek** [TeamOpenIndustry/ImmersiveRailroading#1299]
There are 2 types of animations door in the game (I'm not sure)
by clicking and holding the door nowhere else have I seen a clicking animation combined with an opening [animation]
https://user-images.githubusercontent.com/98583462/202854163-b61c509f-65e2-4bc0-aa1e-3f58e4e2e3d6.mp4 **click + holding** **down the mouse button and moving** https://user-images.githubusercontent.com/98583462/202854189-3cad6bb2-e4fb-493d-9047-708c72712242.mp4
= **click handle start aniamtion for something like this to happen** https://user-images.githubusercontent.com/98583462/202855157-f453ae49-49ba-4625-a70c-84e569d72ec7.mp4 **(sorry for my English)**

**Comment by Dreamyy313** [comment]
> There are 2 types of animations door in the game (I'm not sure) by clicking and holding the door nowhere else have I seen a clicking animation combined with an opening [animation] https://user-images.githubusercontent.com/98583462/202854163-b61c509f-65e2-4bc0-aa1e-3f58e4e2e3d6.mp4 **click + holding** **down the mouse button and moving** https://user-images.githubusercontent.com/98583462/202854189-3cad6bb2-e4fb-493d-9047-708c72712242.mp4 = **click handle start aniamtion for something like this to happen** https://user-images.githubusercontent.com/98583462/202855157-f453ae49-49ba-4625-a70c-84e569d72ec7.mp4 **(sorry for my English)**

**Comment by cam72cam** [comment]
This can be done with animatrix
