### ISSUE TITLE
Bug with rails

### ISSUE THREAD

**Issue by NONPLAYT** [TeamOpenIndustry/ImmersiveRailroading#1301]
**Describe the bug**  
So I have immersive railradoing installed on my minecraft server and after some restarts I have broken rails on WHOLE map

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. All is normal
 2. Run save-all command and restart server
 3. Get bug
 
**Expected behavior**  
After every restart I can use rails, but the last time - all rails are broken.

**Screenshots**  
here is, under rail we need gravel, and we don't see it. also why rails in one block?
![image](https://user-images.githubusercontent.com/76615486/205929137-5e38140a-3d95-4412-97e4-0cc457505b3b.png)

**System Information**  
 OS: Windows 10
 <br>System Memory: 16 gb
 <br>Allocated Memory: 8 gb
 <br>CPU: Xeon E5 2620 
 <br>GPU: 1050 ti
 <br>IR-Version: 1.9.1-7267b6a
 <br>Forge-Version: 1.12.2 - 14.23.5.2859

**Modlist**  
![image](https://user-images.githubusercontent.com/76615486/205929745-c97c5c1c-32b7-4d18-b4a9-5c5193d5e04c.png)

 
**latest.log**
http://api.bxteam.gq/latest.log (pastebin don't approve log, uploaded to my api)

**Additional context**  
No

**Comment by MichiruAvali** [comment]
I have the same issue on my 1.16.5 server

**Comment by Larky2k** [comment]
Think it's a bug with IR and Essentials
