### ISSUE TITLE
Admiral's List of Suggestions:

### ISSUE THREAD

**Issue by High-Admiral** [TeamOpenIndustry/ImmersiveRailroading#1306]
Compiling all my suggestions into one place:

STEAM LOCOMOTIVE CYLINDER SWAY:
https://www.youtube.com/watch?v=DqscywTjIS8
Starting at around 3:00 into this video linked here. Sometimes steamers generate enough power to override their suspension, especially when working pretty hard, and start to sway with the motion of the cylinders. Notice how 765 rocks with each blast from her stack, meaning the cylinders are affecting her on both the "in-stroke" and "out-stroke" (not really surprising due to the nature of double acting pistons but felt this was a bit necessary to add). I also want to point out the great stack talk in this vid too. Great example of a steamer working hard and sounding like it. Would it be possible to get something similar in IR with a modification of the current system?

ADDITIONAL TOGGLABLE SOUNDS FOR LOCOS:
As requested in the Dev Stream on 9/19/2021, an optional third sound slot for locomotives to use if they have more than just a single whistle/horn and a bell.

MORE PARTICLE EMITTERS FOR STEAM LOCOMOTIVES, PARTICULARY BLOWDOWNS AND ASSORTED APPLIANCES:
This was suggested on the discord in the Suggestions channel, but I'm also going to expand this to other things as well.
The main suggestion was for blowdowns for steamers. Blowdowns are a necessary function of steam boiler operation. As water is boiled, only the water molecules actually evaporate. The rest of the stuff suspended in the water then eventually collects at the lowest part of the boiler, nearly always the foundation of the firebox, which is called the mudring(it is also helpful to know that the firebox is surrounded on all sides and top by water between the actual heating surface and the exterior plates of the boiler). This suspended stuff collects in this mudring and blends together to make a sludge, which must be removed periodically for boiler health(and safety). As a mostly passive option, the railroad men created the blowdown. A valve(usually two,one on each side of the engine) is opened(whether by someone on the ground beside the engine or by the fireman, some engines are fitted with both methods) and the boiler, which is at pressure, blasts out water through this valve. The sudden new route for release of pressure creates a current which drags the sludge out of this valve and shoots it out of the boiler. This however does reduce the boiler pressure by a large amount(I don't know the true amount, but rough estimate, a loco at full operating pressure of 300 PSI could be as low as 200-250 psi depending on length of blowdown), meaning performance drops if the engine is in motion/underpower while the blowdown is underway.

So far, the most common way of blowing down that I've found is just straight up shooting it sideways from the mudring as shown in the youtube video linked here: https://youtu.be/sq6iG-Kd2FA

Another way is by piping the blowdown down closer to the tracks so any large chunks of mud don't utterly clonk someone across the face and injure them. Various applications of this exist as well.

As seen here on Pere Marquette 1225: https://youtu.be/vIsHW7oPTCA

PM 1225 has a sort of blowdown muffler, designed to lessen the force of the blowdown, while not actually hampering its effectiveness. SP 4449 and the rest of the Southern Pacific GS class also were equipped with Blowdown mufflers which is more of a shield on them and directly just blows the mud onto the ballast.

![image](https://user-images.githubusercontent.com/52846014/208269990-8e59d5ec-27df-4d08-936c-764068194f4b.png)

As seen on that picture(hopefully it shows) of SP 4450, the blowdown muffler is visible right behind the drivers and right before the lever linkage in the trailing truck brake system, that little rectangle with a pipe(or pipes) coming out the top and disappearing into the loco.

Now, the best way to implement this feature would probably to add another type of steam emitter that can be triggered, something like EMITTER_STEAM_BLOWDOWN_#
This would allow the modelers to individually configure their blowdown valves to best suit the engines, like my own TMW J class has SP style mufflers already modeled on so I could make them work as intended.

Now, as I said at the beginning, this was originally a suggestion for blowdown valves only, but I am expanding this idea. Having various emitters for steam locomotives would be useful. Currently, we are a bit limited in making the various appliances come alive by using the Safety Valve emitters to make things like the TurboGenerators spew out steam(speaking of the safety valves, I've found the current ones to be a bit... meh. Here's NKP 765, at speed, with safeties blowing https://youtu.be/_asx4MAdeXo ). Having emitters tailored to things like the turbogenerators(which would turn on around half pressure and stay on until the engine is shut down(no fire in the firebox)) and air pumps as well as other emitters giving out various levels of steam(steamers leak, its a fact of life. There will be steam wafting around the entire engine if the thing is operating). Having various emitters like EMITTER_STEAM_GENERATOR or EMITTER_STEAM_PUMP or EMITTER_STEAM_INJECTOR(both the pump and injector emitters would ideally emit steam on intervals(mabye coded in or specified in json) and not all the time) would help enhance the immersion of steam locomotives as living, breathing beings instead of cold machines like diesel-electric engines.

Examples of other possible emitter types, prototypes in operation listed below:
Turbogenerators: https://youtu.be/aNQwU3cSSQk

Air Pumps: https://youtu.be/tjtywWxg_l8

More can be provided upon request.

SPAN BOLSTERS:
Given the wide variety of rolling stock in the real world, I find that the current bogie/truck system might be a bit limiting on just what rolling stock can be modeled. I propose adding span bolsters in as an additional option for bogies/trucks. This would allow larger pieces of rolling stock such as large capacity freight cars, Schnabel Cars, and railroad guns to exist in the mod without relegating their trucks to a single solid mass which would appear quite off while negotiating curves. This feature also probably needs to be added for locomotives as well especially diesels/electrics where units such as the Baldwin Centipede and the PRR GG1 exist with articulating frames. I'm not sure if this will all fit under the new animations feature that's being worked on, but I hope that we can get more articulation/bogie options for engines and rolling stock soon.

OIL. FIRED STEAM:
Rehashing this here in 2022(almost 2023), but we need Oil fired steam locomotives. There is a growing number of them in the mod(particularly the ATSF pack, the Big Boy in the basemod, and then the Big Boy in Voxel Trains. Plus of course the stuff in Legend's American Steam), and given the growing number of them, I think its time this is explored. The issue primarily here would be two separate tanks in the tender(since oil fired steamers _have_ to be connected to an oil source to have a fire, they don't carry any fuel on the loco proper) and only having a water inventory on the loco. I also would like to suggest a new augment, or augment config so that the augments would only load certain types of liquid which means you don't have both oil and water tanks in an oil fired steamer tender filling with water and vice versa. Now, this also would have to be specified in the loco json, something like oil_fired: true/false. Controlling the oil fire would probably have to be a gui thing to set the oil flow(something like a slider in the inventory menu perhaps) or a widget in the cab. 

MORE VALVE GEARS:
More and more steamers are being modeled on both sides of the pond, and we need more than just Walschearts(standard, four and three cyl variants) and Stephensons, plus the Mallet, Cabforward, and Duplex codes. Popular gears like Bakers, Hackworth, Caprotti/Franklin Rotary Poppet, and others aren't really capable in the current system and thus has deprived the community of a more immersive experience and locos which use them. This limitation and angled cylinders are the primary setbacks for alot of steam locomotives, and I wish that we could get to fixing that.

Thank you to those that made it this far in my walls of text. I am free to discuss these at any time, just drop me a line or swing by the ATSF or Nordale discords. Thank you and have a great day!

- Admiral

**Comment by cam72cam** [comment]
I'm closing this as it's a huge wall of text.  Individual issues can actually be scheduled / completed.  Also make sure that there are not duplicate issues before posting.
