### ISSUE TITLE
Immersive Railroading crashes due to a file not found error

### ISSUE THREAD

**Issue by yuvalyly** [TeamOpenIndustry/ImmersiveRailroading#1311]
After making some changes to a mod pack I made a while ago the game is crashing when I look in the creative menu of Immersive Railroading due to a File not Found error. Yesterday it seems like keeping the mod Simple Voice Chat solved it for some reason but today it happened again. Now the game also get stuck (without the window freezing) when I try to create a new world but I'm not sure if it's related to this crash.

Log: 
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/10278353/latest.log)
Modpack (curseForge profile):  
[1.16.5 hard-1.0.4.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/10278365/1.16.5.hard-1.0.4.zip)

**Comment by yuvalyly** [comment]
I seem to solve it (at least for now) by deleting everything and remaking the pack, but the problem is still happening when I remove the Simple VC mod.

**Comment by cam72cam** [comment]
Was a problem with umc cache which has been fixed in the test builds
