### ISSUE TITLE
SUGGESTION: Stock Type Augment Filter

### ISSUE THREAD

**Issue by NightScale5755** [TeamOpenIndustry/ImmersiveRailroading#1319]
**Describe the suggestion**  
A clear description of what the suggestion is. This template is not for requesting additional models of locomotives, cars, or other rolling stock; those requests should be taken to the Immersive Railroading Discord channel under #suggestions. 
Link: https://discord.gg/CS2RTGq

Quite literally just a filter for augments based on what type of stock they are. (steam loco, diesel loco, both loco types, etc).

**Applications of the suggestion**  
A description of what the suggestion is needed for, or how it would improve the gameplay experience.
Well, it'd help with unloading/loading spots a bit, among other various augment-based uses. As augments currently aren't very versatile in the filter department.

**Comment by cam72cam** [comment]
At this point, I'm not planning on adding additional features to augments.  This can be accomplished with labels/naming stock
