### ISSUE TITLE
Bunker & Tank support for Tank Engines

### ISSUE THREAD

**Issue by Glawowow** [TeamOpenIndustry/ImmersiveRailroading#1322]
An extra coal storage space in locomotives marked with a Tank Engine section in the JSON. This extra space would behave like a tender, automatically refilling the firebox. There would be a similar setup for water as well, feeding water into the boiler like a tender would. This would allow for much more realistic-behaving tank engines, as currently they run out of coal and water much too quickly compared to how they would IRL.

**Comment by cam72cam** [comment]
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1200
