### ISSUE TITLE
Wiki pages not showing up. 

### ISSUE THREAD

**Issue by maral2014** [TeamOpenIndustry/ImmersiveRailroading#1325]
I tried to get to https://github.com/TeamOpenIndustry/ImmersiveRailroading/Getting-Started but it came up with an error "404".

**Comment by km00700** [comment]
Try [this](https://github.com/TeamOpenIndustry/ImmersiveRailroading/wiki/Getting-Started)

Github recently changed their wiki page structure.

**Comment by maral2014** [comment]
> 

seems to be working, thanks.

**Comment by cam72cam** [comment]
I edited the wiki sidebar which should fix it
