### ISSUE TITLE
Track on large turn tables doesn't visually go to the edges

### ISSUE THREAD

**Issue by Insprill** [TeamOpenIndustry/ImmersiveRailroading#1327]
**Describe the bug**  
The track on large turn tables doesn't go to the edges of the table. When rotating, it rotates around the center of the track so anything other than the default position of the track is not visually connected to anything. Trains can still use the turn table normally.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Place down a large turn table, say 48 blocks, with both fills enabled (to see the issue better).
 2. Observe.
 
**Expected behavior**  
The turn table stretches to the correct size

**Screenshots**  
![image](https://user-images.githubusercontent.com/52843537/211940086-a17d5d33-66ef-41c1-a032-7abc4215af38.png)
![image](https://user-images.githubusercontent.com/52843537/211942357-581c598f-2f29-45df-ac77-e3a9623de45c.png)

**System Information**  
 OS: Linux
 <br>System Memory: 64gb
 <br>Allocated Memory: 14gb
 <br>CPU: 7700k
 <br>GPU: 1070
 <br>IR-Version: 38fb0a34
 <br>Forge-Version: 1.12.2, 14.23.5.2847

**Modlist**  
What's included when running the `runClient` Gradle task.

**Comment by cam72cam** [comment]
This should have a limit of 30 meters (on standard, scaled for others)
