### ISSUE TITLE
Track with the direction option render over the GUI when set to lock right

### ISSUE THREAD

**Issue by Insprill** [TeamOpenIndustry/ImmersiveRailroading#1329]
**Describe the bug**  
In the track laying GUI, custom curves, turns, and switches render far to the left covering the UI when the direction is set to lock right.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Open the track laying GUI.
 2. Select a Custom Curve (most noticeable), switch, or turn.
 3. Set the direction to Lock Right.
 4. Observe.
 
**Expected behavior**  
The curve should stay in the middle of the UI.

**Screenshots**  
![image](https://user-images.githubusercontent.com/52843537/211963181-865ae5c2-37d1-4aac-8c89-e3782c48b19c.png)

**System Information**  
 OS: Linux
 <br>System Memory: 64gb
 <br>Allocated Memory: 14gb
 <br>CPU: 7700k
 <br>GPU: 1070
 <br>IR-Version: 38fb0a34
 <br>Forge-Version: 1.12.2, 14.23.5.2847

**Modlist**  
What's included when running the `runClient` Gradle task.

**Comment by cam72cam** [comment]
Good catch, I'll address this.
