### ISSUE TITLE
Bogies turn 90° to the track when turned on a turn table

### ISSUE THREAD

**Issue by Insprill** [TeamOpenIndustry/ImmersiveRailroading#1331]
**Describe the bug**  
When rolling stock is turned on a turntable, the bogies turn 90° to the track until moved.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Place down a turn table.
 2. Place a car on the turn table.
 3. Turn the turn table.
 4. Observe.
 
**Expected behavior**  
 The wheels should stay on the track, pointing in the correct direction.

**Screenshots**  

https://user-images.githubusercontent.com/52843537/212197495-5c3ef119-f3eb-47c8-b525-b122dd701942.mp4

**System Information**  
 OS: Linux
 <br>System Memory: 64gb
 <br>Allocated Memory: 14gb
 <br>CPU: 7700k
 <br>GPU: 1070
 <br>IR-Version: 3ed1f470
 <br>Forge-Version: 1.12.2, 14.23.5.2847

**Modlist**  
What's included when running the `runClient` Gradle task.

**Comment by cam72cam** [comment]
Fixed
