### ISSUE TITLE
train disappears at higher speed

### ISSUE THREAD

**Issue by angyalg89** [TeamOpenIndustry/ImmersiveRailroading#1339]
When I drive the train, it disappears after a while above 20kmh. If I leave the map and come back, I started inside the train

Video Included:
https://drive.google.com/file/d/11GU0-VNKdhMcqp-yD8RtXScmvZV39zeU/view?usp=share_link

**System Information**  
 OS: Manjaro Linux 5.15.89-1
 System Memory: 20GB
 Allocated Memory: 7GB]
 CPU: AMD Ryzen 5 3600
 GPU: NVIDIA Gefoimmerrce GTX 1060 3GB
 IR-Version: 1.9.1- 1.12.2
 Forge-Version: 14.23.5.2860-1.12.2

 
**latest.log**
(https://pastebin.com/8Mw9xmdg)

**Comment by cam72cam** [comment]
Can you post your full latest.log?
```
[B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_air
[B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_large
[B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_raycast
[B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_small
```
suggests there might be a mod conflict

**Comment by angyalg89** [comment]
> Can you post your full latest.log?
> 
> ```
> [B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_air
> [B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_large
> [B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_raycast
> [B#768]  [18:44:00] [Client thread/INFO]: Detected large movement or teleportation. Rebooted module _POM__scan_small
> ```
> 
> suggests there might be a mod conflict

offcourse, there is a latest log file
[2023-01-29-1.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/10530902/2023-01-29-1.log)

**Comment by cam72cam** [comment]
What modpack is this on?  tekkit 2?

**Comment by cam72cam** [comment]
I just had another user comment that it's an issue with one of the mods in tekkit2, not sure which one.

**Comment by angyalg89** [comment]
Yes, Tekkit 2, latest version

> What modpack is this on? tekkit 2?

**Comment by cam72cam** [comment]
I just had another user comment that it's an issue with one of the mods in tekkit2, not sure which one

**Comment by angyalg89** [comment]
Problem is solved, the mod is conflict with EntityCUlling-1.12.2-6.2.4 and EntitfyDesyncFix-1.12.12-1.0.2 mods
I closed the ticket, thanks for all help buddy :)

**Comment by cam72cam** [comment]
Thanks, I'll look into those mods and now I now how to help folks who have tekkit issues!
