### ISSUE TITLE
Idea for Braking, Wheel Locking/Wheel Slide (Wet Conditions)

### ISSUE THREAD

**Issue by Nathan-TheSteelMann** [TeamOpenIndustry/ImmersiveRailroading#1340]
**Describe the suggestion**  
With the update to braking with the updated braking coefficient system, maybe having it so hard applying breaks on full from high speed (especially in wet conditions like rain or snow) should lock the wheels up on the animation, and let the train slide. 

**Applications of the suggestion**  
During the slide the braking force would go down, slowing the train less. This also makes it so people have to pay attention and use the brakes wisely, as opposed to just jamming them full on and full off.

**Comment by cam72cam** [comment]
Implemented
