### ISSUE TITLE
Rendering of IR assets crash in JEI

### ISSUE THREAD

**Issue by TripOptic** [TeamOpenIndustry/ImmersiveRailroading#1346]
I admittedly have a kitchen sink pack but IR crashes when loading Ir items in JEI. 

https://paste.ee/p/zItNb

**Comment by cam72cam** [comment]
Easy fix:
remove the folder `D:\Games\Curse\Minecraft\Instances\wastland (1)\cache`

This is fixed already for the next release so you won't need to manually clear the cache when it hiccups.

**Comment by TripOptic** [comment]
Thank you Cam.
