### ISSUE TITLE
Weird scaling for widget translations

### ISSUE THREAD

**Issue by SteampsonJake** [TeamOpenIndustry/ImmersiveRailroading#1350]
I'm currently on the latest test build (1.9.1-32d9009) and have noticed a weird issue with the widgets - all translations seem to scale based on what gauge the model has been placed on, not at which scale the model is.

Here the locomotive is set to 1435mm gauge in the json and placed on 1435mm track; the whistle link moves down normally
https://user-images.githubusercontent.com/47562841/224506177-5ea46fb2-964e-4214-b342-aa089615696e.mp4

Here is the exact same locomotive, but set to 750mm in the json and placed on 750mm track. The model is exactly the same size, but the link suddenly goes down only ~52, or (750/1435)% of they way
https://user-images.githubusercontent.com/47562841/224506512-a1c58b17-4697-4965-8812-f62e5618cb02.mp4

**Comment by cam72cam** [comment]
By "set to" do you mean changing the model_gauge_m?

**Comment by SteampsonJake** [comment]
Yes
![image](https://user-images.githubusercontent.com/47562841/225052659-b0bbf117-e560-4e05-a3dc-0439540ad5b2.png)

**Comment by cam72cam** [comment]
Should be fixed in the next test-build
