### ISSUE TITLE
Oil-Fired Steam

### ISSUE THREAD

**Issue by High-Admiral** [TeamOpenIndustry/ImmersiveRailroading#1352]
I think it is time to address Oil fired steam locomotives. There is a growing number of them in the mod(particularly the ATSF pack, the Big Boy in the base mod, and then the Big Boy in Voxel Trains. Plus, of course, the stuff in Legend's American Steam), and given the growing number of them, I think its time this is explored. 

The issue primarily here would be two separate tanks in the tender(since oil fired steamers have to be connected to an oil source to have a fire, they don't carry any fuel on the loco proper) and only having a water inventory on the loco. Now, this also would have to be specified in the loco json, something like oil-fired: true/false. Controlling the oil fire would probably have to be a gui thing to set the oil flow(something like a slider in the inventory menu perhaps) or a widget in the cab.

I also would like to suggest a new augment, or augment config so that the augments would only load certain types of liquid which means you don't have both oil and water tanks in an oil fired steamer tender filling with water and vice versa. Now, this also would have to be specified in the loco json, something like oil_fired: true/false. Controlling the oil fire would probably have to be a gui thing to set the oil flow(something like a slider in the inventory menu perhaps) or a widget in the cab.

Regarding actual fuel, probably would have to be crude oil from Immersive Petroleum, and/or biodiesel from Immersive Engineering. Oil firing also allows a far faster response time fuel wise, making oil fired locos a bit more fuel efficient.

Thank you for coming to my TEDtalk

**Comment by WrongWeekend** [comment]
A ticket has already been created for this issue, so it would be best to add your ideas to that one:

https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/267
