### ISSUE TITLE
[Suggestions] Armored train system proposals

### ISSUE THREAD

**Issue by xinghuan2hao** [TeamOpenIndustry/ImmersiveRailroading#1355]
### Suggestions
The design of the armored train is actually very simple, that is, small and medium-caliber artillery turrets and machine guns are installed on the armored train car, which can be seen in the BP42 type of the German Empire and the MBV2 type of the Soviet Union, and the armored train of Battlefield 1 is also a good reference.
I think IRmod can be modeled with two universal armored trains, one angular and the other rounded. Equip weapons of the same country as needed
Take the German armored train, for example, their armored train is more like a box, two FLak38-20mm four-barreled / FLak36-88mm anti-aircraft gun carriages (the latter can be anti-tank, but to be honest, is such a compartment needed, after all, there are not many flying creatures capable of attacking, unless anti-aircraft guns attack ground targets, but this is not necessary)
Anti-tanks were usually equipped with an armored -IV turret (one for flatbed cars and two for general carriages) with 75-mm L / 43 or L / 48 cannons. (Of course, if you are interested, it is possible to install the turret of the Tiger tank or Panther tank on the armored train car, although not historical, but good)
Howitzer car, the Germans installed 75 mm / 105 mm howitzers.
Armored trains also have less obvious personnel carriers and flatbeds, which are used for the detonation of mines, which, of course, is not critical for IRmod. Historically, both artillery and anti-tank carriages were equipped with machine guns, depending on the difficulty of crafting, and if you want to be the same as in history, you can place two machine guns on either side of these two armored train carriages.
Speaking of which, it may be confusing, why do I keep talking about armored trains from WWII? Forgive me, my friend only collected models of WWII armored trains. Of course, the armored trains of the First World War were only not equipped with anti-tank and anti-aircraft gun vehicles, other carriages would still have them, equipped with guns with only 75 mm / 3 inch howitzers, and heavy machine guns would also have turrets, you can refer to "Battlefield 1"
That being said, you might be dazzled by so many weapon models, but there's an easy way to do it, you just need to make two armored train hull models and Soviet-German, Anglo-American, French weapon turrets (in fact, you can directly use the turret of a WWII tank) and design a UI for different carriages, players can DIY as much as they want. Of course, there are also simpler ones, and the weapon system requires only 75-mm and 3-inch howitzers with cylindrical or hemispherical turrets, as well as machine-gun turrets.
Train weapon systems cannot ignore railway guns, don't worry, I know that it is very unrealistic to make that 800mm big man (Dora cannon), but it should not be a problem to make a railgun no more than 20 inches, the French-made 520mm railgun uses standard train tracks, and the British also made an 18-inch railgun that travels on standard train tracks. But because I say a lot about armored trains, I do not demand much from railway guns, it is enough to have a 210 mm or 12-inch railgun
No matter what the thoughts are after watching, thank you for reading this opinion, saying so many ideas, a little confusing, please forgive me

**Comment by cam72cam** [comment]
I'm not planning on supporting guns on trains any time soon
