### ISSUE TITLE
bug with rail blueprint

### ISSUE THREAD

**Issue by Iliasoli** [TeamOpenIndustry/ImmersiveRailroading#1358]
I have a bug with the rail blueprint. when I right-click on the rail blueprint, it doesn't show me the full things like the place blueprint and grade crossing. and the direction for the custom curve doesn't work. Its always on left direction when I set the direction to the right lock.
**System Information**  
 OS: [Windows]
 <br>System Memory: ["8GB"]
 <br>Allocated Memory: [5500MG"]
 <br>CPU: [ "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)"]
 <br>GPU: ["Intel(R) UHD Graphics 620,NVIDIA GeForce MX110 "]
 <br>IR-Version: [1.9.0_1.12.2"]
 <br>Forge-Version: [1.12.2 - 14.23.5.2860"]

**Modlist**  
https://pastebin.com/J2kZg646
 
**latest.log**
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/11111648/latest.log)
**ScreenShot**
![2023-03-30_17 21 39](https://user-images.githubusercontent.com/105164394/228841722-639a734f-2ed2-468e-a253-8cd0e6830eaf.png)

**Comment by Larky2k** [comment]
Change gui scale from auto to large.

**Comment by Larky2k** [comment]
Settings, lock doesn't effect custom curve as you can go anywhere

**Comment by Iliasoli** [comment]
> Settings, lock doesn't effect custom curve as you can go anywhere

sorry😅, I made a mistake. i lock the turn direction to right but its always left, I said customer curve but it was turn

**Comment by Iliasoli** [comment]
> Does it show left when you place it. It could just be a visual bug
so thanks for speedy responding
