### ISSUE TITLE
[suggestion] extra way to sort & route trains

### ISSUE THREAD

**Issue by Evanvelzen** [TeamOpenIndustry/ImmersiveRailroading#1359]
I have been thinking of an extra way to sort & route trains. We currently (can be mistaking) only really can sort & route trains based on what locomotive they are. But what if we can make custom tags and give those tags to a locomotive. 

these tags can be used to sort and route trains by first creating the tag with a unqiue name and then simply adding it to the filter on the augments that already exsists in the mod. and it would then allow any train with the same tag to access the rail

also the tag could be displayed with a sign on the locomotive or on the carriage its pulling. alternatively it could display like how nametags are displayed.

Idk if its possible and what you guys think of it. But i think it could a be an interesting thing

**Comment by cam72cam** [comment]
This is in the test builds and will be in the next release
