### ISSUE TITLE
[Question] 1.18.2 Progress

### ISSUE THREAD

**Issue by Dibucci** [TeamOpenIndustry/ImmersiveRailroading#1360]
I have a technical buddy of mine that is making a Technological mod pack for 1.18.2. We have Create and ofc Create Trains, but he missis Immersive Railroading and how good everything looked and was. We know that it is in the progress of being worked on, due to others posts and question's in the issues section, but we want to know if it's posable to get a progress update, as in what still needs to be worked on, are there any complete features yet, and/or if you can't give specifics of current progress towards the upgrade, if you could give something as simple as an "Estimated" percentage of the progress or a posable guess of when it would be around "near" complete.

 I apologize if you hear stuff like this all the time, I don't mean to sound pushy or intrusive in any means. It's a mod that we, amongst many other's, enjoy, so it's just curiosity that is driving this question, that, and the fact that due to IRL stuff me and my friend find it hard to keep fully up to date on everything that has, or is, happening.

If you could give a rough estimate on the current, and posable future, status of things, I would be very happy to know.

Sincerely,
Me

**Comment by thebikwirm** [comment]
18.2 is not a priority if irc, its bringing new features and testing them up to 16.5 then 17.1 and upwards will be after that

**Comment by cam72cam** [comment]
It is in progress but I need to get the current code released on 1.7.10 through 1.16.5 first.
