### ISSUE TITLE
Unobtrusive Augments

### ISSUE THREAD

**Issue by CherubAgent1440** [TeamOpenIndustry/ImmersiveRailroading#1363]
Currently, track augments (e.g. detector etc.) take up a full block and are coloured in a really bright colour, which uses the textures of coloured blocks from vanilla minecraft. Whilst this makes them obvious, if you want to, for instance, make an automatic block signalling system, then you need to place detectors every 5 blocks or so, which ruins the appearance of the tracks. And whilst you can change those textures using a resource pack, it ruins the appearance of builds that use those blocks

I can think of three possible solutions to this:
1. Edit the size of track augments such that they only take up a small portion of the track (e.g. a 2 pixel by 2 pixel square in the middle of the rail bed). That way they are still visible, but are less obtrusive.
2. Make their texture a separate file from the vanilla texture, such that they can be retextured using a resource pack without ruining builds that use the blocks. That way the user can retexture the augments to match their choice of rail bed. Whilst this is probably the least work for you, it is the most work for the user.
3. Add a method of making track augments take the texture of the rail bed (or become invisible if there is no rail bed). Could be caused by using the paint brush on the augment. It should be a reversible process, as in if you use the paint brush on a camouflaged augment then it reverts to its normal texture. This last one would be my preference.

**Comment by cam72cam** [comment]
Track augments are a temporary work around and will be replaced with dedicated blocks in future updates.

**Comment by CherubAgent1440** [comment]
Maybe they are a temporary work around, but at least make them retexturable using a client-side resource pack. Temporary stopgaps and whatever have a tendency to last for a very long time, especially when they are a feature that for most people most of the time is not a big deal.

I would make this myself, except that I cannot seem to find anything that references any actual texture resource locations, and also I have no modding knowledge.

**Comment by bakinser** [comment]
IIRC, the rework of augments into something more fleshed out is one of the next priorities for feature updates, it would be pointless to put in that work when that system is on the cusp of being completely redone
