### ISSUE TITLE
Passenger pose improvements

### ISSUE THREAD

**Issue by CherubAgent1440** [TeamOpenIndustry/ImmersiveRailroading#1366]
Currently, a model made at 2 foot gauge (MC gauge) will default the player to be always sitting, meaning that almost all 2ft modellers need to set the `should_sit` flag to `false` in the json's `passenger` section. This wasn't a problem historically, since unless you used the trains on model gauge for a miniature railway, it didn't look out of place.

However, we now have working `SEAT` parts. And if the `should_sit` flag is set to false, then even when you are sitting on a `SEAT` then you are made to be standing.

---

I can think of four potential options to improve this:
1. The cutoff for automatically sitting is at gauges less than MC gauge, instead of less than or equal to. Since pretty much all railways smaller than 2 foot are miniature railways, for which you pretty much can't stand in anyway, then that should be all right. Only issue is existing MC gauge trains that want you to be always sitting but don't include the flag because it wasn't necessary.
2. If the model contains `SEAT` parts, then when `should_sit` is not specified, the default is standing regardless of the gauge. This is unlikely to be a problem because the use of `SEAT` parts is unlikely where you are seated by default, and in the unlikely situation where it is, `SEAT` parts are sufficiently new that the modeller will likely still be active.
3. If you are sitting in a seat you are always sitting even if `should_sit` is `false`. This might break things where a `SEAT` is used to represent a place to stand that is outside of the walkable area, e.g. a cupola on a caboose.
4. Another flag, something like `should_sit_in_seats`, which controls whether you should sit or stand in `SEAT` parts. If its default value is the same as the value of `should_sit`, then it won't break any current models. If its default value is `true` then it feels more intuitive, and as with point 2, any modellers who used `SEAT` parts are still active and can release a hotfix.

**Comment by cam72cam** [comment]
The original bug where the seat flag was ignored has been fixed.
