### ISSUE TITLE
my game crashing while I creating a train

### ISSUE THREAD

**Issue by SiwyC** [TeamOpenIndustry/ImmersiveRailroading#1367]
mods i have:
immersive rail loading 1.12.2 1.9.1
universal mod core 1.12.2 1.1.3
track API 1.2    1.12.2. 

Error: java.lang.AbstractMethodError: cam72cam.immersiverailroading.ImmersiveRailroading$$Lambda$199/124654028.postRender(Lcam72cam/mod/entity/Entity;F)V

**Comment by cam72cam** [comment]
Not enough information
