### ISSUE TITLE
Augments could be hideable

### ISSUE THREAD

**Issue by LukeTech2006** [TeamOpenIndustry/ImmersiveRailroading#1376]
**Describe the suggestion**  
I would suggest you make Augments be able to behave like Barrier Blocks. If you hold the item in your hand, It will be visible on the track. if not, it will be invisible. This could for example be achieved by shift-right-clicking the augment (e.g. a Detector) with a glass block or similar.

**Applications of the suggestion**
Hiding Contacts near Platforms
![grafik](https://user-images.githubusercontent.com/54572277/235303657-8d0e9404-f6cc-4f3f-b449-3049772d69ba.png)

**Comment by cam72cam** [comment]
Augments are slated to be replaced and I am not planning on making significant changes to them at this time
