### ISSUE TITLE
How to get headlights in the train? 

### ISSUE THREAD

**Issue by S4MillionYT** [TeamOpenIndustry/ImmersiveRailroading#1380]
I don't know how to get headlights on the locomotive 
I tried it to search on YouTube
They said just get test build of this mod Or just change the engine start/stop button from + to N that's all, but it didn't work at all
So if anyone knows how to get test build pls reply me 🙏🏻

**Comment by Larky2k** [comment]
Headlights are only available on certain stock and use with the test build of IR and UMC, which is available only on the IR discord and is currently 1.12.2 only

**Comment by S4MillionYT** [comment]
Oh thnks for help 
Can you give me the link of that discord server?

**Comment by km00700** [comment]
[Link is listed on here](https://github.com/TeamOpenIndustry/ImmersiveRailroading)
