### ISSUE TITLE
CG Suggestion #1

### ISSUE THREAD

**Issue by BrazilAlsoAutismoGG** [TeamOpenIndustry/ImmersiveRailroading#1386]
A good suggestion to new Immersive Railroading widgets , double CG , like you can have 2 CGs at a single toggle/button object. 2 or more , Example : a rolling stock piece has 4 sliding doors attached to CG #1 (Doors) but you want create a button to specificaly open *only one* , so you could using a CG #2 to this Door (If you want open only one instead of 4)

something like DOOR_#ID#_CG_1_CG_2

 this could be interesting for Doors and other movable widgets in general

**Comment by cam72cam** [comment]
Closing in favor of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1387
