### ISSUE TITLE
[Feature Request] "Global" modifier in custom GUIs

### ISSUE THREAD

**Issue by Jeronimo97** [TeamOpenIndustry/ImmersiveRailroading#1389]
**Describe the suggestion**  
Hey guys,
is it possible to add a boolean value "global" for the GuiBuilder, which ensures that the controlGroup controlled via the GUI can act global in the whole train. So similar or the same as the "GLOBAL" modifier in the models themselves in the Control class?

**Applications of the suggestion**  
I will need this feature to make control groups effect from the GUI across the entire train.

Kind regards
Jeronimo

**Comment by cam72cam** [comment]
Ah, this is a good idea!
