### ISSUE TITLE
The problem with the models

### ISSUE THREAD

**Issue by WyLand69** [TeamOpenIndustry/ImmersiveRailroading#1390]
Template goes here
During loading, it shows a lot of errors, and when I go into the world and try to open a page or drive in any part of the mod in search, minecraft crashes.
[crash-2023-07-27_18.06.51-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/12185739/crash-2023-07-27_18.06.51-client.txt)

**Comment by Larky2k** [comment]
Must be on java 8 your on java 17
