### ISSUE TITLE
Models not Loading

### ISSUE THREAD

**Issue by Skyler74** [TeamOpenIndustry/ImmersiveRailroading#1391]
So I installed Immersive Railroading on Minecraft 1.12.2 on Linux. On windows, the models of the train loaded but here, the models load in the bootstrap description but they don't show up in the inventory. Many resource packs (Except for UNU) have loaded with IR and I am using the latest version of everything (IR, IE (1.12.2), OpenComputers, etc.). If I have no resource packs loaded then it shows 3 menu's with the massive wrench and the menu's are empty. If I have a resource pack, than they will not show up. 

**How to reproduce**  
N/A
 
**Expected behavior**  
Upon installing, I expected there to be the default trains and carriages but they do not show up in the inventory (creative) but still "load" in the minecraft loading screen (stage 2)

**Screenshots**  

**System Information**  
 OS: Linux Mint
 Memory: 8GB
 Minecraft Memory: 4GB
 <br>CPU: [e.g. "Intel I7 7700k"]
 Intel UHD Graphics (I'm pretty sure it's an APU because there is no information)
 IR: 1.12.2 - 1.9.1
 Forge: 1.12.2 - Version 14.23.5.2859

**Modlist**  
BiblioCraft
OpenComputers
MrCrayfish's Furniture Mod
Xaero's Minimap
Immersive Engineering
Immersive Railroading
Universal Mod Core
Track API
 
**latest.log**
 Password: tVGMxT7hJk
https://pastebin.com/AYwqheUg

**Additional context**  
N/A

**Comment by Larky2k** [comment]
Clear the cache folder, sometimes it gets corrupted

**Comment by Skyler74** [comment]
I deleted the univeralmodcore folder under cache and then loaded the game. All it did was nearly overfill the minecraft memory and it still didn't work.
