### ISSUE TITLE
[Feature Request] Control Group Sound Definition

### ISSUE THREAD

**Issue by Jeronimo97** [TeamOpenIndustry/ImmersiveRailroading#1393]
**Describe the suggestion**  
It would be very nice if you could add a _control group sound definition_.
So that the sound is bound to a control group and not to a widget, because the implementation via the widget is rather bad than right. Like what is done with idle, running, horn etc. That should then also include the normal sound definition (start, main, looping, stop, distance, volume).
In the implementation this would then be so that I have a control group, which I can control via a TOGGLE or PRESS and as long as this is active, the sound is played.

**Applications of the suggestion**  
This would also allow custom sounds to be set to control groups when creating vehicles, to realize various things like fans or similar.

**Comment by Larky2k** [comment]
Kind of pointless as now with he new animation system you can put the sounds on the animation

**Comment by Jeronimo97** [comment]
But I dont want to use the animation system for that. Please standalone.

**Comment by cam72cam** [comment]
How would you actuate the control group?  Via the UI?  If so, I've already added that in the PR you saw this morning.

**Comment by Jeronimo97** [comment]
With buttons in the rolling stock

**Comment by Jeronimo97** [comment]
So I dont want the move, engange, disengage stuff but the normal sound defintion with start, main, stop, looping...

**Comment by cam72cam** [comment]
engage / move / disengage is all that will be supported for control group sounds.
