### ISSUE TITLE
Blueprint tool

### ISSUE THREAD

**Issue by stainedtp** [TeamOpenIndustry/ImmersiveRailroading#1402]
A tool which can convert track pieces into blueprint form without having to replace the track piece. Would make ballasting track so much more easier with brushes

**Comment by SteampsonJake** [comment]
What?

**Comment by stainedtp** [comment]
A tool, which reverts track back into a blueprint. Thats basically what I'm asking

**Comment by SteampsonJake** [comment]
I got that part, but how would it make ballasting (whatever that is) easier?

**Comment by stainedtp** [comment]
Use a W/E brush to brush underneath the track

**Comment by thebikwirm** [comment]
why would you not just leave it as a blueprint and do the brushing then place it?

**Comment by stainedtp** [comment]
because if I'm playing on nordale and everyones grumbling about the terrible TPS do i want to hold them back just so i can ballast

**Comment by stainedtp** [comment]
so i place it all and then wait until everyones gone to then ballast

**Comment by Larky2k** [comment]
Place blueprint, mark out route with wool, ballast, build the track.

**Comment by thebikwirm** [comment]
> because if I'm playing on nordale and everyones grumbling about the terrible TPS do i want to hold them back just so i can ballast

just work on sections at a time and tps should be fine

**Comment by stainedtp** [comment]
ok. case closed
