### ISSUE TITLE
Graphic glitch ? (trains disappears)

### ISSUE THREAD

**Issue by Castanea43** [TeamOpenIndustry/ImmersiveRailroading#1404]
**Describe the bug**  
Train disappear, "graphic glitch ?"

**How to reproduce**  
And with your train go on a switch rail and trains disappears
 
**Expected behavior**  
Exactly i don't know
I am using a MC server with a Ryzen 7 3700X and 32GB @3200Mhz DDR4 on Fedora Linux 38 (Server Edition)
And Server properties : 
```
#Minecraft server properties
#Mon Oct 16 14:28:55 CEST 2023
spawn-protection=16
max-tick-time=60000
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=false
level-type=OTG
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=false
level-name=Wildlands
view-distance=7
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=-9000299392127934756
use-native-transport=true
prevent-proxy-connections=false
enable-rcon=false
motd=A Minecraft Server
```

**Screenshots**  
See video
https://www.youtube.com/watch?v=6Bps0_AR5tA

**System Information**  
My system
 OS: Linux EndeavourOS (Arch)
 <br>System Memory: 48GB
 <br>Allocated Memory: 22GB
 <br>CPU: AMD Ryzen 7 5800X
 <br>GPU: AMD RADEON 7600
 <br>IR-Version: ImmersiveRailroading-1.12.2-forge-1.9.1 and the latest test-build on discord : ImmersiveRailroading-1.12.2-forge-1.9.1-e49acbb
 <br>Forge-Version: 1.12.2 - 14.23.5.2860

**Modlist**  
https://pastebin.com/2wLtWLij
 
**latest.log**
latest log : https://file.io/l93DWdSS03vO

**Additional context**

**Comment by Larky2k** [comment]
are you using shaders

**Comment by Castanea43** [comment]
No i don't use any shader

**Comment by Castanea43** [comment]
I found the problem with Universal Tweak with this line : 
# Fixes entity motion desyncs most notable with arrows and thrown items
B:"Entity Desync"=true

i need to make false, and no trains disappears
