### ISSUE TITLE
The test build crashes when using other mods!

### ISSUE THREAD

**Issue by ELDEX-HD** [TeamOpenIndustry/ImmersiveRailroading#1406]
I love the new test build because of all the new features.  But no matter what other mods I install.  It always crashes due to somehow "UniversalModCore".  By the way.  I always have the following Mlds with me that are always with me!: Immersive Engineering, Immersive Petrouleum, Immersive Vehicle + R.A.G.E.  Pack.  And of course Immersive Railroading.  Everything works when I take the full version.  Only the test builds crash with other mods.  But the full versions of IR don't crash at all with other mods.  Play only on 1.12.2 with "Forge-.2860".

**Comment by SteampsonJake** [comment]
Do you have the right version of Universal Mod Core installed? Each IR test build comes with its own UMC version

**Comment by cam72cam** [comment]
Please provide a crash report, otherwise I will have to close this issue @ELDEX-HD
