### ISSUE TITLE
Widgets/Controls/Doors on bogies/articulated frames

### ISSUE THREAD

**Issue by PeterKitsune** [TeamOpenIndustry/ImmersiveRailroading#1407]
**Describe the suggestion**  
As the title. Basically allow us to have THROTTLE_FRONT_1 or WIDGET_REAR_3 or DOOR_FRONT_2 or whatever.

**Applications of the suggestion**  
The obvious example is for certain types of railmotor (e.g. Pichi Richi) where the front bogie of the coach is basically a small 0-4-0 locomotive complete with controls etc. Would also allow, e.g., togglable pilot truck styles or whatever. It feels like an oversight considering that articulated component support was added for lights?

**Comment by Larky2k** [comment]
add _LOCOMOTIVE to end of FRONT
its already supported

**Comment by PeterKitsune** [comment]
> add _LOCOMOTIVE to end of FRONT its already supported

Having tried this (`THROTTLE_FRONT_LOCOMOTIVE`) it doesn't work.
