### ISSUE TITLE
Coupler Slack Readout

### ISSUE THREAD

**Issue by DankLondon** [TeamOpenIndustry/ImmersiveRailroading#1411]
**Describe the suggestion**  
The ability to have readouts for coupler slack on both front and rear. For custom animations and UI purposes
Link: https://discord.gg/CS2RTGq

**Applications of the suggestion**  
Couplers which use chains being able to play custom animations as slack is taken out/added to the consist, so the couplers visually look like they're pulling each other.

**Comment by cam72cam** [comment]
added in 547a54f7939dc554109e267b96d66bc4afe59bd5
