### ISSUE TITLE
Child Objects

### ISSUE THREAD

**Issue by DankLondon** [TeamOpenIndustry/ImmersiveRailroading#1415]
**Describe the suggestion**  
A system to allow for secondary OBJs to be added on top of existing stock. 
Link: https://discord.gg/CS2RTGq

**Applications of the suggestion**  
Having the ability to use one of an object (lamps for example) instanced over and over would be more efficient for both creating models and in terms of storage space. Or being able to use one wagon "base" but with different tops applied, each with their own types of interactions. 

For example a child object of a box added onto a base wagon, which can be set up in CAML/JSON to act like a boxcar, with opening doors. Or using the same base wagon having a tank object and simply referencing the original but with the visual of a tank on top.

**Comment by thebikwirm** [comment]
would be very cool
adds a whole new realm of customisation for pack makers

**Comment by SteampsonJake** [comment]
Sooo... You basically wanna do what 1.12 RoW does?

**Comment by cam72cam** [comment]
I'm not planning on doing that for performance reasons.  I have the entire model rendered in a single context and want to keep it that way.
