### ISSUE TITLE
1.20.1 version mod cannot Initialize

### ISSUE THREAD

**Issue by JiaqiYi** [TeamOpenIndustry/ImmersiveRailroading#1423]
1.20.1 version mod cannot Initialize！Please fix this bug.
![屏幕截图 2023-12-10 110433](https://github.com/TeamOpenIndustry/ImmersiveRailroading/assets/109802844/a371e65f-9284-4a8e-bce3-160e608185a9)
[crash log-2023-12-10_11.05.46.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/13626357/crash.log-2023-12-10_11.05.46.zip)

**Comment by cam72cam** [comment]
Not even remotely supported yet.  Please do not grab random versions from github actions.
