### ISSUE TITLE
Animated doors will randomly appear opened

### ISSUE THREAD

**Issue by WebSoak** [TeamOpenIndustry/ImmersiveRailroading#1426]
**Describe the bug**  
Doors on animation equipped stock may randomly appear opened, even if they have never been opened before.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Place down a full R160 consist (1 A-Car, 3 B-Car, 1 C-Car, repeat once to produce a 10 car consist)
 2. Leave the train idling
 3. Fly around and conduct various activities, allow 60-120 seconds to set.
 
**Expected behavior**  
 The doors appearing closed

**Screenshots**  

![2023-12-11_00 53 46](https://github.com/TeamOpenIndustry/ImmersiveRailroading/assets/79772407/d890bde3-39ca-486b-8f83-f0b7977b965b)

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory: [e.g. "64GB"]
 <br>Allocated Memory: [20GB"]
 <br>CPU: [e.g. "Ryzen 3900x"]
 <br>GPU: [e.g. "RTX 3070"]
 <br>IR-Version: [e.g. "1.9.1-511f40d"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2857"]

**Modlist**  

ALET
Chisel-MC
ColoredLights
CreativeCore
Creepypastacraft
CTM-MC
Cubic Chunks
Flan's Mod
Flat Colored Blocks
Flat Colored Hex Finder
GIRSignals
Glass Doors
Immersive Engineering
IR
John Mod
Kiros Blocks
LagGoggles
Little Frames
Little Tiles
Library mod
Macro Key Mod
Modern Lights
More blocks
moving elevators
NEI
optifine
rats
replay mod
scp lockdown
Sowith's ALlsnow mod
speedcart
tickcentral
trackapi
traffic control
UMC
Vanilla Builders Extension
Voice Chat Reloaded
world edit forge me
Xaeros Minimap
Xaeros World Map
 
**latest.log**
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/13631537/latest.log)

**Additional context**  

:J

**Comment by Jeronimo97** [comment]
In my case, I think, the CG are randomly activated when placing.
