### ISSUE TITLE
Edit Mode For Golden Spikes  / Way to edit existing track placement without breaking them

### ISSUE THREAD

**Issue by WebSoak** [TeamOpenIndustry/ImmersiveRailroading#1439]
**Describe the suggestion**  
Often times when a track is negotiating an angled / curved ROW or station it can be difficult to properly align the tracks with the ROW or platform. Which can lead to a tedious process aligning the platform edge with the trains. The suggestion is to add a way to use the golden spike to edit the placement of a track without breaking it to allow fine tuning of the track's position without placing a new one.

**Comment by SteampsonJake** [comment]
You mean adding and controlling more points along the curve rather than just the two end points and curvature as it's now?

**Comment by WebSoak** [comment]
Not necessarily points although that could be a separate useful suggestion. I mean a way to realign an existing custom curve so that you can line up the platform edge with trains on curves & angles without having to place and pray for half an hour (in order to prevent platform clipping or large voids between the doors & platform)

**Comment by cam72cam** [comment]
Unfortunately, this breaks a crazy number of assumptions in the core code and will lead to broken functionality.
