### ISSUE TITLE
Trains won't load.

### ISSUE THREAD

**Issue by Ender701** [TeamOpenIndustry/ImmersiveRailroading#1441]
**Describe the bug**  
Whenever I load up the game, everything else works fine, I have all the mods needed yet, when I place them trains down they only apper for a split second and disapper. If the track they are on is a smaller size than them, it spawns and load. but you can't drive the train. and if you walk too far back in the cab, it will kick you out of the game leaving no error message

I have no clue how this ever happened, I logged on one day and it doesn't work, I tried deleting and redownloading them, I think I'm at a point where I have no clue what to do.

**Expected behavior**  
I expected it to work.. looks like it didn't

**System Information**  
 OS: Windows
 <br>CPU:  Intel I7 7700k
 <br>GPU: MSI 1080 8gb
 <br>IR-Version: 1.16.4. 1.8.0
 <br>Forge-Version: 1.16.4- 35.1.37"]

**Modlist**  
Immersive Enginnering, Immersive Railroading, TrackAPI and Universal Mod Core
 
**latest.log**
 https://drive.google.com/file/d/1sFDd0jq0yujYprJGxGZtk6jT-PSwe0hh/view?usp=sharing

**Comment by cam72cam** [comment]
Please update to 1.16.5 and IR 1.10.0

**Comment by Ender701** [comment]
cheers mate
