### ISSUE TITLE
The mod doesn't work for me on the server. version 1.7.10

### ISSUE THREAD

**Issue by Maximkasup** [TeamOpenIndustry/ImmersiveRailroading#1463]
hi this is my video about my problem on version 1.7.10 on a server with Forge core https://youtu.be/crrU6G1tW0A

**Comment by Maximkasup** [comment]
In single player the mod works, I can interact with trains and configure the tracks.  but on the server I can’t interact with what I listed

**Comment by Larky2k** [comment]
Delete config file server and client
