### ISSUE TITLE
The letters break in the Immersive railroading mod for minecraft 1.16.5

### ISSUE THREAD

**Issue by MrKactys2003** [TeamOpenIndustry/ImmersiveRailroading#1471]
when I try to look at the name of an item, a random set of letters appears

**Comment by SteampsonJake** [comment]
Can you post a screenshot of what you mean?

**Comment by Larky2k** [comment]
This sounds like a translation issue

**Comment by MrKactys2003** [comment]
![Uploading 17119099106345817360719734399115.jpg…]()

**Comment by km00700** [comment]
Your screenshot didn't upload

**Comment by MrKactys** [comment]
https://drive.google.com/drive/folders/1J1zTtd50IflQVTaMfmZa5geJ3lIphbhq?usp=drive_link

**Comment by km00700** [comment]
no access. It's not shared so people can view

**Comment by MrKactys** [comment]
https://drive.google.com/drive/folders/1-HzpDdc8PXt7Bek9mv4gY0PhC6TXkOER?usp=drive_link

**Comment by SteampsonJake** [comment]
The folder is empty

**Comment by MrKactys** [comment]
https://drive.google.com/drive/folders/1F_kB6s5wVih5u_WfMeD1qoyejbKXPjFE?usp=drive_link

**Comment by Larky2k** [comment]
What is your native language

**Comment by MrKactys2003** [comment]
My native language is Russian

**Comment by Larky2k** [comment]
Ok, redownload Immersive railroading and see if that fixes it

**Comment by MrKactys2003** [comment]
Ok

**Comment by MrKactys2003** [comment]
It did not help

**Comment by Larky2k** [comment]
Does it go if you select another language

**Comment by MrKactys2003** [comment]
I'll check it and write the result, I hope it works

**Comment by MrKactys2003** [comment]
and the language needs to be changed in Minecraft or in the mod archive (I just can’t change the language in the mod archive)

**Comment by Larky2k** [comment]
It's in Minecraft, IR should have russian translation

**Comment by MrKactys2003** [comment]
it worked Thank you but what should I do if I want to play in my language and the same error appears

**Comment by MrKactys2003** [comment]
when I turn on the English language, everything seemed fine, but when I switched back to Russian, the same error occurred

**Comment by MrKactys2003** [comment]
what is IR and how to view it

**Comment by MrKactys** [comment]
https://drive.google.com/file/d/1C0uzGEt42eDPc80sr8ZZVHpfNWh5UyHy/view?usp=drive_link   
What to do?
