### ISSUE TITLE
Custom gamemode permissions

### ISSUE THREAD

**Issue by linuxfight** [TeamOpenIndustry/ImmersiveRailroading#1478]
**Describe the suggestion**  
Adding of some kind of permissions to the mod, like what group/gamemode can do certain actions:
- pick up trains
- control trains
- place trains
- etc...

**Applications of the suggestion** 
This will help restrict some of players (eg. players in gamemode 2 or in specific scoreboard group)
from interactions with trains. Can help the admins of roleplaying servers.

**Comment by cam72cam** [comment]
Take a look at immersiverailroading_permissions.txt.  That allows you to set what permissions require OP (or a forge permissions compatible mod group grant)

**Comment by linuxfight** [comment]
where can I find immersiverailroading_permissions.txt on my server?

**Comment by Larky2k** [comment]
Same place server and client

**Comment by linuxfight** [comment]
oh, i found it, thx you
