### ISSUE TITLE
Please add badly maintained trackage and vegetation growth.

### ISSUE THREAD

**Issue by UnstableOrbit** [TeamOpenIndustry/ImmersiveRailroading#148]
Let weeds and grasses be able to grow up through the rails, that way if a train hasn't gone through in a while the tracks will be overgrown(trains would destroy things growing through the rails like they do snow blocks). Additionally, some really poorly maintained trackage like [THESE TRACKS HERE](https://www.youtube.com/watch?v=Pfp7dabTX3I) be great once derailment is a thing. These bad tracks should have a good chance of derailing you if you take locomotives/cars on them that are too heavy or if you attempt to go too fast over them.

**Comment by MauveCloud** [comment]
I hope rails requiring maintenance will be a config option - keeping up with that might not be too hard in cooperative multiplayer, but in singleplayer it could easily get out of hand quickly.

**Comment by redstone2019** [comment]
@FriedrichLP are you working on this model?
