### ISSUE TITLE
What's the fact?

### ISSUE THREAD

**Issue by ErythroCraft** [TeamOpenIndustry/ImmersiveRailroading#1490]
Hello

I was wondering about your work. Your mod is an high frequently mod with many stuff.

What's the problem about you didn't create upgrades?

**Comment by km00700** [comment]
What does that mean?

**Comment by ErythroCraft** [comment]
All we waiting for version 1.20 until 1.20.6

So. Latest version of ImersiveRailroding is 1.16.5 and I was wondering about missing upgrades.

**Comment by Larky2k** [comment]
Rule 1 with any mod never ask for ETA or when it's going to be on X MC version. It be there when it's done

**Comment by km00700** [comment]
Updates take a lot of time because the mod and its core are very complex. None of the devs work on it full time because we have jobs, families, and other life commitments.

**Comment by SteampsonJake** [comment]
Not to mention that Mojang likes to throw wrenches into everything by rewriting big chunks of the base game with every update (see rendering changes past 1.16)

**Comment by ErythroCraft** [comment]
Thanks for your answers. @Larky2k @km00700 and @SteampsonJake
