### ISSUE TITLE
Make Compatible with Cubic Chunks?

### ISSUE THREAD

**Issue by jimmyking2004** [TeamOpenIndustry/ImmersiveRailroading#1495]
Is it possible to make Immersive Railroading Compatible with Cubic Chunks?

I tried it with
Immersive Railroading
TrackAPI
UniversalModCore

after I placed some tracks and saved then replayed the selected world it crashed the game

**Comment by Larky2k** [comment]
there is already

**Comment by jimmyking2004** [comment]
already?

**Comment by Larky2k** [comment]
been in for years

**Comment by jimmyking2004** [comment]
oh there is i thought I searched but I guess I messed it
