### ISSUE TITLE
Track blueprints asking for non IE Materials

### ISSUE THREAD

**Issue by Useydess** [TeamOpenIndustry/ImmersiveRailroading#1499]
So recently i was trying to get a resourcepack to work Serverside on my Minecraft server I have set up, I managed to get it working but now when i play on the server and try to place down tracks with the track blueprint it asks for Iron and Stone instead of Treated wood and Rail segments. I have Immersive Engineering installed and it worked fine before installing the resourcepack to the immersive railroading config folder so I'm not sure whats going on

![broken rail](https://github.com/user-attachments/assets/da6a7c75-9594-4c80-9886-acee3cd93f0d)

(im using Darkraiders Monorail resourcepack)

**Comment by km00700** [comment]
DarkRaider here, That's not an IR bug but is normal behavior. This specific track type is specified to use different materials in its recipe than the default tracks.

**Comment by Useydess** [comment]
oh alright, thank you for explaining this to me
