### ISSUE TITLE
Thomas4peyton's Rolling Stock To-Do List

### ISSUE THREAD

**Issue by Thomas4peyton** [TeamOpenIndustry/ImmersiveRailroading#227]
# _WELCOME TO THE LAND OF THE RIO GRANDE!_
## _FREIGHT CARS:_

- **D&RGW 3000 Class Boxcar** **✓**

- **D&RGW 1000 Class "High Side" Gondola** **✓**

- **D&RGW 5500 Series Single Deck Stockcar**  **✓**

- **D&RGW 700-800 Class Drop Bottom Gon**

- **D&RGW Short Reefer**  **✓**

- **D&RGW Long Reefer** -don't know if we will need it if we have the short version

- **D&RGW 6000/6200 Class Flatcar** **✓**

- **D&RGW 1000 Class Pipe Gondola** -once the code supports Interchangeable Parts

- **D&RGW 6700 Class Idler Flat** -for putting in-between pipe gondolas

- **UTLX Narrow Frame Tank Car** **✓**

- **UTLX/GRAMPS Oil Co. Frameless Tank Car** 

- **East Broad Top/Generic Hopper**

- **West Side Lumber Co. Log Skeleton Car**  **✓**

## _PASSENGER CARS & CABEESE:_

- **D&RGW RPO/Baggage** - **✓**

- **D&RGW Combine** 

- **D&RGW Passenger Car** **✓**

- **D&RGW Closed Vestibule Passenger Car** 

- **D&RGW Parlor Car** -Either The Durango or Chama

- **D&RGW Combine Caboose** - _sigh_ one day...

- **D&RGW 0500 Class Short Caboose** - **✓**

- **D&RGW 0500 Class Long Caboose** **✓**

- **Generic Bopper/Logging Caboose**

## _MoW & MISC_

- **D&RGW MoW Bunk Car (Boxcar Outfit)**

- **D&RGW MoW Office Car (Boxcar Outfit)**  **✓**

- **D&RGW MoW Bunk Car (Passenger Outfit)**

- **D&RGW MoW Wheel & Tie Car**  **✓**

- **D&RGW MoW Rail & Tie Car**  **✓**

- **D&RGW Flanger OD** **✓**

- **D&RGW Rotary Snowplow OY** -Winter 2018-2019

- **D&RGW MoW Tool Car (Boxcar Outfit)**

- **D&RGW Commisary Car (Boxcar Outfit)**

- **D&RGW Cook Car 053 (Passenger Outfit for Rotary OY)**

- **RGS Galloping Goose?** -once my skill in blender is good enough

- **Narrow Gauge Railbus** -Throwing around the idea, made from a passenger car

## _LOCOMOTIVES_

- **D&RGW C-25 # 375** **✓**

- **C&S B-3-C Mogul** **✓**

- **Eureka & Palisade 8/18C** **✓**

- **D&RGW C-16** **✓**

- **D&RGW K-28** **✓**

**Comment by CarterlikesIR** [comment]
only cars I will ever use

**Comment by Thomas4peyton** [comment]
thanks but you should use other people's stuff too, mine are not great in terms of textures or detail; I'm trying to make them with as much optimization and low triangle count as possible.
