### ISSUE TITLE
Tender - Loading Issue

### ISSUE THREAD

**Issue by andrboot** [TeamOpenIndustry/ImmersiveRailroading#249]
When a tender is loading either with water, or burnables it occasionally takes over your inventory that you are looking at, if you open a chest  / etc hopper at the wrong time.
You need to re-open the chest/hopper etc at the right time to get your inventory display back.

See screen shots for 'what' happens.
![2018-03-17_10 33 34](https://user-images.githubusercontent.com/2858196/37548874-36cd2292-29cf-11e8-886f-b9aad1554545.png)
![2018-03-17_10 33 31](https://user-images.githubusercontent.com/2858196/37548875-37065666-29cf-11e8-8060-9744177e06e0.png)
![2018-03-17_10 33 27](https://user-images.githubusercontent.com/2858196/37548876-37387f42-29cf-11e8-895a-dda24fca371f.png)

**Comment by cam72cam** [comment]
Having trouble reproducing this.  I wonder if it is a mod conflict?

**Comment by cam72cam** [comment]
@andrboot I think I have fixed this in the latest version.  EntityIDs were being confused server/client side

**Comment by cam72cam** [comment]
tigerbird1 reports this is still happening in 1.3.1

**Comment by andrboot** [comment]
Can confirm, happened last night briefly as well.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
