### ISSUE TITLE
Adam R. K.'s Rolling Stock To-Do List

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [TeamOpenIndustry/ImmersiveRailroading#257]
- I have no fucking idea.
- Uhm..... maybe first ill finish the cl08
- Torpedo liquid steel car
- Non torpedo liquid steel car
- Mine cart - a large one for standard gauge
- Hyper f***ing buffed super heavy huge passenger car with restaurant, cinema and shit knows what else

**Comment by qwryzu** [comment]
intermodal container car?

**Comment by Xelbayria** [comment]
hahaha LOL! 😂 
it's the comment that Adam posted on here. it's what is being said.
