### ISSUE TITLE
Nether-Ex "Pigtificates" don't work with boarding mechanic

### ISSUE THREAD

**Issue by SuspiciousMango** [TeamOpenIndustry/ImmersiveRailroading#264]
The nether-ex mod's "pigtificates" do not work with the villager train mechanic. I assume its because they don't extend the villager entity and the mod author implenents them in his own way. They also deal in Nether-Ex's "nether amethysts" instead of in emeralds. It would be cool if support got added for them, and they paid the player in nether amethyst instead of emeralds

**Comment by cam72cam** [comment]
Closing as won't fix
