### ISSUE TITLE
Can some new types of passenger trains be added?

### ISSUE THREAD

**Issue by DFO28** [TeamOpenIndustry/ImmersiveRailroading#296]
Hello! I'm currently using 1.0.1 mod version for 1.12.2 MC. Different types of freight cars/rolling stocks are fine, some of them are in content packs, but there is only baggage cart and only one passenger rolling stock type with seats. Why not to add such things  as far-distance passenger trains with bad (shelves) inside, subway train (especially) or city express (which even may have high speed) for model collection to be complete? Thanks for attention.

**Comment by dragonshardz** [comment]
All of the things you've requested are possible, however, adding more rolling stock is up to volunteers stock/loco modelers. If you want to try and talk one into making your specific requests, hop into this Discord channel: https://discord.gg/cQJYUWj

You can also look at the umbrella project for stock models here: https://github.com/cam72cam/ImmersiveRailroading/projects/3
