### ISSUE TITLE
slopes

### ISSUE THREAD

**Issue by OprichnikStyle** [TeamOpenIndustry/ImmersiveRailroading#313]
Hello cam:

My issue is to add the degree of slope in the HUD.
Then that degree could be used to limit certain types of trains 
this degree is calculated % =100 *h /d
Also it would be interesting if it's linked to the traction and HP of each locomotive
cants could also be taken in mind for this application although that would require a lot more of calculations
I hope my issue is good enough. 
Thanks

**Comment by OprichnikStyle** [comment]
Also, that it would ve possible to make inverse slopes so from where im standing would be able to place a slope going down

**Comment by BrisingrAerowing** [comment]
The inverse slope thing would be the best feature ever. It would make things SO much easier.
