### ISSUE TITLE
IR stock breaks Journey Map

### ISSUE THREAD

**Issue by qwryzu** [TeamOpenIndustry/ImmersiveRailroading#320]
I've had this issue for a while but I didn't narrow it down to IR stuff until just today, I figured it was something to do with Journey Map. It seems that when playing near IR stock, the full screen map turns blue and none of the buttons show up. Picture below describes the issue better than I can. The HUD minimap doesn't seem to be affected.

![2018-05-21_21 31 40](https://user-images.githubusercontent.com/27305244/40342265-8fd2905a-5d3e-11e8-9058-e2f8bf81493f.png)

While playing today the map was working fine, and then without me exiting the full screen, a train came past me and the screen turned blue. I waited until the train passed completely and after it was a few chunks away, the map was working totally fine again.

I play with a render distance of 32 chunks and if I go just a few chunks away from IR stock it seems to work just fine, so I don't think it's just any chunk with IR stock. Affected radius is only a few chunks, I can do more testing to get exact numbers if that helps. Tracks seem to have no effect.

**Comment by cam72cam** [comment]
Which journeymap version?

**Comment by qwryzu** [comment]
latest version, 5.5.2 for 1.12.2

**Comment by UntoldForce** [comment]
Strangely enough my overall map works fine, but the minimap stopped working entirely for me with Immersive Railroading installed.

**Comment by Larky2k** [comment]
Journey map works fine for me with IR

**Comment by CarterlikesIR** [comment]
^

**Comment by cam72cam** [comment]
@qwryzu can you PM me a copy of the pack and world to test with?

**Comment by PyroskE1987** [comment]
I have had this exact same issue as well, currently on a server I'm working on.

**Comment by EweLoHD** [comment]
I also have this Problem. But I think that is a Bug of JourneyMap, not of IR. Maybe it could have something to do with Optifine.

**Comment by cam72cam** [comment]
@qwryzu has this happened recently?

**Comment by 4gyanyuan** [comment]
Can you make an interface for the machine to output items？

**Comment by km00700** [comment]
That comment has nothing to do with this issue...

**Comment by zacharyhenry** [comment]
I'm having the same issue also

V 1.12.2-5.5.4 journeymap 
V 14.23.5.2838 forge
V1.6.1

Trains I used 
Ge B40-8
UNU IR-113-LPR
UNU NY-212-MPR
UNU SC-126-HCR
UNU DS-123-MCR

Basically the trains ......

I just have  the train  sitting  on the track and journeymap doesn't work in fullscreen
