### ISSUE TITLE
A few Suggestions for Features

### ISSUE THREAD

**Issue by Kriegfox** [TeamOpenIndustry/ImmersiveRailroading#327]
Couple of Ideas

Headlights: I'm sure its probably on your to-do list somewhere, but, I figured I'd throw it out there.

Ability to Manually Lite and Drop the fire. That way you can stack fuel in the engine without starting the fire, but also if you accidently start a fire with low or no water, dropping the fire would be a way to avoid a boiler explosion...unused WHOLE fuel would go back in the tender or ejected from the firebox, whatever was burning would be lost, but at least you'd have your engine.

Ability for Tenders to receive Solid fuel to the bunker from above as if it were a hopper, like coal chutes, or Immersive Engineering's conveyors placed above tracks. Same for Open Hoppers, also pouring molten metal into the Slag and a Hot metal car would be nice as well, kinda like you can do with the tinker's seared tanks.

The casting basin has one catch I'd like to point out, other than its a huge multi-block that those with less powerful computers can barely look at, but I love it anyway. If you cast a small item on repeat cast, you can't stop it unless you shut off the power, it pours the cast so fast as soon as you pick it out to access the GUI its already done casting the next one, and you can't access the GUI if there is a finished part because it assumes you just want to pick the part. There should be a way to access the GUI instead of picking the casting, OR Have Repeat casting setup to allow a number input on how many castings to pour. Also not being able to pick parts out of machines without using an empty hand...if that could be addressed somehow.

If you want to do oil burning steam engines, might I suggest adding a "grates" part to the list to determine what fuel the engine wants. Coal Grates, or Oil Jets, then create the respective tenders.

That being said about oil, I'd also suggest that the Bucket count for tank cars be increased, as Extra Utilities Drums, and Immersive Petroleum's Tanks can hold significantly more than a tank car, but in reality take up alot less space (in the game). It just seems like the capacity for a tank car is extremely low in comparison to other storage mediums within the game. Most single block tanks can hold 4 to 16 buckets on their own.

Now my big idea, this I'd expect to be a way down the road thing: CTC Blocks.

So, many mods use ingame computer systems and such, what if you create a Central Traffic Control system so if you are on a multiplayer server, or even single player, you can set a route or run multiple player driven trains. So there are a few major blocks in this idea, the first being a CTC Block.

A CTC block could be even a multi-block Interlocking Tower, just like the real thing, this block would be connected to the network of other associated blocks to coordinate traffic and routes.

Call Box Block: So a Call box would be placed at points of importance or train tiedown on the network. A player could right click the call box which would open a GUI you could then pick your route using "Station Signs" which would be another CTC system block called a "Station" block (doesn't have to be a building, just a point you can name and place somewhere under or next to the tracks). When you pick your destination, the CTC Towers would talk to eachother to set up your route (CTC towers can only control so much territory, so you can only plan a route as far as your CTC network goes) and involve the 2 other blocks.

Interlocking block: This would be your signalling system, this could be a multi-block placed trackside to wire up to multiblock signals, make it look like the signal box which holds all the relays. Signals would dictate train movements based on the network they are connected to and the route or routes planned by the CTC tower. The Interlocking Block would also be wired to one or more "Switch" blocks which would be your switch motors for CTC controlled switches, and would throw a switch based on the required route for the incoming train. Anything not wired to the CTC network would be dark territory and require Full player interaction with switches (Your handthrow switches). 

That is all for now, I haven't gotten a large enough network inplace yet to comment on locomotive abilities as far as power and tractive effort is concerned, But I will make a seperate post in a day or two about a few other odds and ends, like stationary steam piston engines for large generators for the equipment and boilers to go with them. I know this Mod requires Immersive Engineering, but IE skips right by steam-power generation entirely, and Immersive Tech skips Solid Fuel Boilers completely and you can only burn diesel...or use solar for the steam turbines.....the power sources just don't fit into the Steam Era correctly. 

I love this mod, I love the realism, the track system (though kinda finiky) is pretty nice. The rollingstock and locomotive models look amazing, I can't wait to see the new textures for the Machines. I would never want this to become an "automated" mod where operator-less trains could roam the landscape, thats what minecraft minecarts are for! I'm excited to see the turntable as been added to the blueprints, I can't wait until that is finished and add in those buildings (I'll need more bricks I guess!) From someone who lives in the Lehigh Valley amongst what used to be one of the larger Coal Mine areas filled to the gills with railroads, I am thoroughly enjoying myself, Keep up the good work! I'll be around, and I have some rollingstock in mind that isn't Pennsy ;P

**Comment by WrongWeekend** [comment]
> That being said about oil, I'd also suggest that the Bucket count for tank cars be increased, as Extra Utilities Drums, and Immersive Petroleum's Tanks can hold significantly more than a tank car, but in reality take up alot less space (in the game). It just seems like the capacity for a tank car is extremely low in comparison to other storage mediums within the game. Most single block tanks can hold 4 to 16 buckets on their own.

I think it's more an issue of other mods unrealistically exaggerating how much their containers are able to hold. Most IR stock is designed to be to-scale. This assumes that 1000 liters of real-life capacity translates to one bucket (assuming one bucket equals one cubic meter of fluid) capacity in-game.  The fluid mechanics in Minecraft are still very inconsistent and unrealistic, mostly because water and lava have little significance in vanilla Minecraft outside of environment generation. Unless some serious compression is involved, a single block tank should not be able to hold more than one bucket of fluid. Generally speaking a mod like IR that is restrained by realism is going to have less convenient content than a mod without such limitations- so trying to balance the two with each other is rather futile, like trying to balance train travel with teleporting and jetpacks.

But there's nothing stopping you from editing a resource pack to increase tank car capacity, or even adding your own car in a resource pack. 

> I know this Mod requires Immersive Engineering, but IE skips right by steam-power generation entirely, and Immersive Tech skips Solid Fuel Boilers completely and you can only burn diesel...or use solar for the steam turbines.....the power sources just don't fit into the Steam Era correctly.

I haven't tried it yet but the Better Boilers mod allows you to create steam in multiblock boilers for IT's turbine and for other steam powered machines. There are other tech mods (Thermal Expansion, Mekanism, and Magneticraft, for example) that also feature fuel-fired steam power.

**Comment by Kriegfox** [comment]
You make some good points. I have to admit, IE's generators burn through an enormous amount of diesel if you think about it in that kind of scale, and they do it quickly. Which was my initial reasoning for saying anything is in order to use the fuel, you need it in large quantities to run something for any extended period of time.

Didn't try better boilers, but the server I'm on is Running FTB Revelations with IR  added in. The problem we're noticing is the Multi-block structures tend cause a larger amount of lag (though it isn't as bad if you have a newer computer, or even noticeable in my opinion).

**Comment by robot256** [comment]
I know the capacities are realistic, and it is cool because makes longer trains necessary.  But stock Minecraft lets you compress dirt in chests by a factor of 1,728, which is why compressing fluid by a factor of 12 seems reasonable.  As noted, other mods are balanced assuming fluid compression, and most fluids are normally never placed as blocks so the volume unit is arbitrary.  This is how I would argue for a config setting to adjust tank car capacity globally if desired.

**Comment by km00700** [comment]
@robot256 What If I told you we have that feature already? It's in the config, and it determines how many MB of fluid are required to fill one liter of a tank car.

**Comment by robot256** [comment]
@km00700 I can't tell you how many times I read the config without realizing that "MilliBuckets per Liter" applied to tank cars.  Thanks, you guys rock!
