### ISSUE TITLE
Client "crash" after adding Immersive Railroading

### ISSUE THREAD

**Issue by ResqDiver1317** [TeamOpenIndustry/ImmersiveRailroading#330]
I'm building a 1.12.2 modpack for our community and one of our players resquested Immersive Railroading. I checked it out and it looks really nice so I added it to our pack. The server and client starts fine, but when I tried to connect to the server, I could log in but after a few seconds, I would get kicked out with a message about a java exception. I pulled Immersive Railroading and TrackAPI back out of our pack and server and am again able to connect just fine with no issues. I will attach the log files from my client. 
[2018-06-08-2.log](https://github.com/cam72cam/ImmersiveRailroading/files/2085848/2018-06-08-2.log)
[debug-1.log](https://github.com/cam72cam/ImmersiveRailroading/files/2085855/debug-1.log)

**Comment by cam72cam** [comment]
It looks like either a forge conflict or a mod conflict.  Can you post the logs from your server?

**Comment by ResqDiver1317** [comment]
Here is the server log as requested. Hopefully you will be able to find something useful in it. 
[2018-06-08-6.log](https://github.com/cam72cam/ImmersiveRailroading/files/2087406/2018-06-08-6.log)

**Comment by mcfilmmakers** [comment]
looks like a journey map problem?
