### ISSUE TITLE
A new mounting system that allows non-leadable mobs

### ISSUE THREAD

**Issue by SuspiciousMango** [TeamOpenIndustry/ImmersiveRailroading#344]
I would love to be able to ship creepers, zombies, or Jurassicraft T-Rexes by train, but these mobs are all non-leadable. Is it possible to get a mounting system that does not require the mob to be leaded?

**Comment by cam72cam** [comment]
Related to https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/344

**Comment by cam72cam** [comment]
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/254
