### ISSUE TITLE
Fix horsepower physics / pulling power.

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [TeamOpenIndustry/ImmersiveRailroading#347]
In short - 18 000 hp locomotive is not able to even start with 200x 80ton freight cars.
This issue does not only correspond to 18000 hp, it also happens with smaller locomotives, for example - a 3000hp diesel locomotive is not able to move 22 fully loaded tank cars (each tank car contains 163000 liters of water, and weighs (empty) 90 tons)

**Comment by cam72cam** [comment]
Will be addressed in the physics rewrite
