### ISSUE TITLE
Settings for loaders/unloaders

### ISSUE THREAD

**Issue by esotericist** [TeamOpenIndustry/ImmersiveRailroading#366]
Much like you can use a redstone torch to change the settings of a control augment, it would be nice if we could do similar with the fluid loaders and unloaders.

For fluid unloaders, it would be extremely helpful to be able to set them not to completely empty a tank; leaving one mB of fluid in the tank functions as a kind of filter.

For fluid loaders, there are cases where it might be desirable for them to only pump fluid into a non-empty tank (that is, one which already has some of the fluid they're pumping).

Similarly, there might also be some value in this for item loaders/unloaders, regarding individual item stacks. Being able to set a loader to only apply to partial stacks of the same item, and also set the unloader to leave one item out of a stack, to filter the contents of wagons.

**Comment by cam72cam** [comment]
Since augments can be controlled by redstone, I'm marking this effectively done, though not exactly in the spirit of the original ticket
