### ISSUE TITLE
Trains stalling downhill and then reversing back uphill

### ISSUE THREAD

**Issue by DorniNerd** [TeamOpenIndustry/ImmersiveRailroading#368]
Per the conversation on Discord the following bug is reported:

When travelling in a SW1500 and four hoppers (three empties, one loaded) as the train would go up an incline, the train would speed up. As the train would hit a down incline, the train would stall and then shove the entire consist back UP the hill it was coming down. See the attached video

 https://www.dropbox.com/s/btkzid5m09wiyqv/javaw.exe%2007.18.2018%20-%2009.48.06.02.mp4?dl=0

Now, after some testing and zeroing out the block weight setting in the configs... The issue completely resolved itself. 

Further testing is being done, this occurs both in 1.2.1 and the last 1.2.1 testing version.

**Comment by DorniNerd** [comment]
After more testing, it is very much so a problem. Just not as noticable when rail equipment is "0" kg on cargo... Loaded and unloaded.

**Comment by Alzurana** [comment]
I can confirm this bug. Tested on version 1.3.1 (Will test on 1.3.2 later)

I placed my track segments in one direction and have upwards and downwards slopes in it.
When driving a train (empty) from west to east, the slopes (almost always) behave normally, slowdown on an upwards slope (10 blocks per 1 slope block) speed gain going down.

It's much worse when driving the fully loaded from east to west. Every up slope speeds up the train insanely, every down slope slows it down, lets it roll backwards with no brakes applied. This makes it very hard to control very lengthy trains.

Is there a sign reversed somewhere in the code that causes this, maybe?

**Comment by seeker2921** [comment]
> I can confirm this bug. Tested on version 1.3.1 (Will test on 1.3.2 later)
> 
> I placed my track segments in one direction and have upwards and downwards slopes in it.
> When driving a train (empty) from west to east, the slopes (almost always) behave normally, slowdown on an upwards slope (10 blocks per 1 slope block) speed gain going down.
> 
> It's much worse when driving the fully loaded from east to west. Every up slope speeds up the train insanely, every down slope slows it down, lets it roll backwards with no brakes applied. This makes it very hard to control very lengthy trains.
> 
> Is there a sign reversed somewhere in the code that causes this, maybe?

See, I'm the opposite, Up slops (10 per 1 up) it goes slow, regardless of what locomotive I use, and going down gets upwards of 400 KPH+. I can't get up a 5 to 1 slope either, just stalls out than speeds down, brakes applied fully.

**Comment by neronakoma** [comment]
immersive railroading is based on a realistic scale of all equipment
including track, grade change, and speed. if you are attempting to go
uphill on a 5-1 slope, you are bound to lose control as the grade of that
slope is a 50% incline. or a 5-1 grade. average grade for track is around a
60-1 or 45-1. recommended slope is 50-1. this goes for curves as well as
switches and slopes.
this may also help fix the issue you are having of trains going backwards
on slopes as well

**Comment by cam72cam** [comment]
Fixed on the test builds
