### ISSUE TITLE
Iron/Wood Use

### ISSUE THREAD

**Issue by Kriegfox** [TeamOpenIndustry/ImmersiveRailroading#372]
As Discussed with cam;

Early engines use Iron instead of steel in real life, and alot more wood in rolling stock. Add ability for modelers to decide materials to be used per shape, through model coding or json coding.

**Comment by WrongWeekend** [comment]
I was thinking that iron boilers (being made of a lower quality material) should be more prone to boiler explosions than steel boilers, and any iron/wood parts should wear out more quickly when part maintenance is implemented.

**Comment by DargosQualtha** [comment]
Actually, Steel tends to be of a higher efficiency, but wear out faster than iron boilers. In fact, there are specific kinds of iron that are even more high-efficiency than steel, with the right production. See the graphite iron used on the Duke of Gloucester and the A1 Tornado.
