### ISSUE TITLE
Track Interferes with Mob Pathfinding

### ISSUE THREAD

**Issue by km00700** [TeamOpenIndustry/ImmersiveRailroading#377]
Mobs are unable to pathfind while standing on a track.

**Comment by hayesj1** [comment]
This doesn't seem to be true 100% of the time. A baby and a regular zombie just pathed to me across the track. I was within three blocks of the track (whereas usually I'm 4 or 5+ blocks away and they get stuck), so it might be a distance issue.

**Comment by FriedrichLP** [comment]
Minecraft is really really strange there. Every time you test it you will get different results

**Comment by km00700** [comment]
The problem is where they can't do it while standing _on_ track, not that they an't pathfind across it. Read each word in the issue.
