### ISSUE TITLE
More Stock ideas

### ISSUE THREAD

**Issue by Trinsdar** [TeamOpenIndustry/ImmersiveRailroading#387]
Would RF, EU, Mana, and possibly Thaumcraft Aspect cars be added? RF and EU would probably be the easiest to do.

**Comment by Larky2k** [comment]
up to modellers which is prob a nope

**Comment by Trinsdar** [comment]
or mabye if they don't want to do that an ability for rails to transfer electricity could be added. now that I think about that, that sounds better as it's closer to real life.

**Comment by WrongWeekend** [comment]
That's basically part of the eventual plan to add electrification. From what I understand the biggest problem with implementing that is not adding the overhead wire/third rail graphics, but getting the power to move through unloaded chunks.

In the meantime, it's probably better just to set up a parallel power line along the track.

**Comment by CalocoDoesGit** [comment]
The way Immersive engineering pipes handle it is:
if liquid input is loaded and if liquid output is loaded to your thing.
same for wires if i recall
