### ISSUE TITLE
cunk loader seems to doesn't work

### ISSUE THREAD

**Issue by gaojie429** [TeamOpenIndustry/ImmersiveRailroading#391]
I playing minecraft with immersive railroading mod v.1.3.2, and I found the issue that a train will stop when it goes out of my view distance.
So, the Automatic Train Control System (the system that you can control your loco without riding it) that I made died completely.
Is there any solution of this??

**Comment by cam72cam** [comment]
Can you provide more details?  Many servers are running in this mode without any problems.  Are there any errors in your logs? What forge version are you using?  What other mods?

**Comment by gaojie429** [comment]
Im so sorry, it was just a cofig problem.
Somehow it was turned off "always load stock" setting.
