### ISSUE TITLE
When placing cars, they may end up 'drifting' across multple tracks

### ISSUE THREAD

**Issue by SpudsMcCat** [TeamOpenIndustry/ImmersiveRailroading#409]
Seen this with locos, the plow, and tank car If 2 tracks are near each other, the car seems to prefer to be on both of them.

I stood between 2 tracks, facing one  at 90 degrees, with 2nd behind me and ended up with trank car at a 45 across them both.
![2018-07-19_00 23 06](https://user-images.githubusercontent.com/35882263/44240413-cb108000-a172-11e8-8e8a-57104b919e34.png)

**Comment by 420trains69tardis1337** [comment]
I see some potential for this... ;)

**Comment by redstone2019** [comment]
What other mods were you using with immersive railroading. Having your Minecraft, Forge, and mod versions would help too.

**Comment by km00700** [comment]
doesn't matter. This isn't a bug. It's a side-effect of the way the placement system locates track.

**Comment by redstone2019** [comment]
Oh ok thanks km00700

**Comment by cam72cam** [comment]
I'm not planning on fixing this
