### ISSUE TITLE
Rollingstock Skin Swap [Paintbrush GUI]

### ISSUE THREAD

**Issue by Kriegfox** [TeamOpenIndustry/ImmersiveRailroading#426]
The idea of creating a hud option on the rollingstock to swap between skins. This is not to be an in game painting tool, this is to swap between skins already stored at a minimum on client side, while in game without having to reload the game. 

Default skin will be in the base directory for that piece of rollingstock, optional skins will be in subfolders within that directory. The mod will understand what the extra folders are for and list those as options in the HUD.

**Comment by WrongWeekend** [comment]
I had an idea similar to this in #270. The way you describe the texture application is what I was thinking, except the base texture would always be something generic (like a freshly built, unpainted locomotive)

**Comment by cam72cam** [comment]
I am leaving this one open so we have a ticket for the GUI work
