### ISSUE TITLE
Support multiple model variants for the same entity

### ISSUE THREAD

**Issue by WrongWeekend** [TeamOpenIndustry/ImmersiveRailroading#430]
When building or placing a locomotive, players ought to have the option to choose between different model variants of that locomotive to include any variants added in the base mod or resource packs. This would allow different resource pack creators to create multiple versions of the same locomotive without one overwriting the other on a server.

If the resource pack creators assign different stats to the same rolling stock, perhaps a config option or CT script could allow players to choose which set of stats to use.

**Comment by EScapeTheShadows** [comment]
Alternatively you could do what I did for my live steam pack. The br in the pack uses the same model, but with different stats and configurations. The way I avoided overriding each other is by having the json file names be different.

**Comment by km00700** [comment]
Yeah, but that won't work. OBJ/MTL pairs bind textures to a model.

**Comment by Kriegfox** [comment]
what do you mean it binds it to a mesh?

**Comment by km00700** [comment]
Each OBJ file references an MTL file. That MTL file references a set group of textures.

**Comment by km00700** [comment]
Intercepting and replacing the texture in memory would change ALL trains of the same type into the same skin, regardless of their scheme.

**Comment by Kriegfox** [comment]
So, each piece of rollingstock isn't truly its own entity, but an copied instance, and in memory, the mod only loads one set of the rollingstock then just copies instances through the game in the world? Thats what I'm reading yes?

**Comment by km00700** [comment]
yeah.

**Comment by Kriegfox** [comment]
So then, CURRENTLY, the only way to support different schemes and model variations would be seperate jsons calling out the modified obj files with their own mtl files. I wonder if there would be a way you could modify that.

**Comment by km00700** [comment]
correct. I mentioned the modification.

**Comment by Kriegfox** [comment]
Oh right, sorry memory made me think someone else mentioned that xD

**Comment by km00700** [comment]
Advantage is that legend could do challenger in multiple schemes AND have the option to do smoke deflectors/ no smoke deflectors

**Comment by Kriegfox** [comment]
I had planned to do the same with the Camelback for "as delivered" and "As demoted" when they were demoted to branch service during the final years of their life, got a new tender, modified firemans porch....and would look a tad more rough

**Comment by km00700** [comment]
When one of us implements the mesh/skin swap, I'll collapse my F59PHI skins into one json. I think the original loader should only add the first one of each stock to the creative list as it is, because it iteraes through type, not by currentSkin.

**Comment by cam72cam** [comment]
Possible with widgets  or texture variants
