### ISSUE TITLE
Direct Inventory Output of Casting Basin, Track Roller, Etc.

### ISSUE THREAD

**Issue by dragonshardz** [TeamOpenIndustry/ImmersiveRailroading#472]
Adding specific points on the Casting Basin, Track Roller, etc. where items can be directly input or output to ducts, conveyors, hoppers, chests, and so on would be a marked improvement to the flexibility and mod compatibility of Immersive Railroading.

While it is possible to automate IR machines using the Mechanical User or similar items, the lack of I/O points locks players who do not or cannot have "fakeplayer" blocks into manually performing repetitive and tedious tasks for long periods of time.

Forcing players to endure tedium is not fun, and failing to account for direct inventory I/O does not allow for creative and flexible solutions to the problem of manually casting many parts being a tedious and repetitive task.

To ward off some naysayers ahead of time: Balance-by-tedium is not fun. Conscious decisions to lock a portion of your end-users into manually performing tasks they may not enjoy is hostile design.

**Comment by neronakoma** [comment]
i like the factor of casting each part. feels more of an accomplishment
when you make every part yourself instead of going to a chest and pulling
it out. its a pride thing

**Comment by Ommina** [comment]
Happily, it would still be possible to retrieve the item manually, should the player desire to do so.

For my part, I've printed out the "Balance-by-tedium" quote above and attached it to the wall.

**Comment by dragonshardz** [comment]
Omnima is correct. I neither want not desire for the Casting Basin to have One True Way of use - it should support *both* fakeplayer automation and inventory automation, as well as manual retrieval.

**Comment by km00700** [comment]
I smell a config option...

**Comment by dragonshardz** [comment]
> 
> 
> I smell a config option...

I don't think it would be necessary to have a config option to enable/disable inventory automation on the Casting Basin. Just have it *available* so that if someone wants to make use of it, they can.

**Comment by lordfriend** [comment]
Well. I also found this issue. So I use a robot make this for me. It requires casting basin and rail roller next to each other with 5 block distance (or you can adjust code). If you don't require auto charge your robot, you can remove the charge function.
https://github.com/lordfriend/opencomputers-snippets/blob/master/robot_rail_casting.lua

**Comment by dragonshardz** [comment]
That's certainly an interesting solution, but it also illustrates my point - More methods by which one can retrieve castings increases the ability of players to be creative and solve the problem in new ways.

**Comment by lordfriend** [comment]
By the way, If any change added to casting basin. I hope it can emit redstone signal strength base on the internal liquid steel volume or add an Adapter support to get the volume of liquid steel. so I can make it possible to auto resupply steel for casting basin.
