### ISSUE TITLE
Allow Automation of Simple Track placement

### ISSUE THREAD

**Issue by hayesj1** [TeamOpenIndustry/ImmersiveRailroading#478]
I poked around in the code for creating straight track and found that a slight tweak could enable fakeplayers like Opencomputers Robots to place straight track in any direction(right now it is limited placing track towards the South; which is a little odd, as the current default is EnumFacing.North).

Relevant lines are 80 in BuilderStraight.java, and 68 in ItemTrackBlueprint.java, and a bunch of calculations, in the second constructor in RailInfo.java.

**Comment by cam72cam** [comment]
It's all based on the fakeplayer rotationYaw.  The EnumFacing.NORTH is just a artifact of some old code which I removed in my new track branch

**Comment by hayesj1** [comment]
Is that branch functional at this time? I know there are backward-compatibility issues, but I'd like to at least see if the rewrite works with robots.

**Comment by cam72cam** [comment]
Feel free to test it, I'd just make a copy of your world ahead of time.  I am hoping to post a test release this weekend if I can get back compat working mostly correctly.

**Comment by hayesj1** [comment]
I almost got my fork running, but I can't for the life of me find a de-obfuscated IE for 1.12. Any idea where I can find one?

**Comment by cam72cam** [comment]
You'll have to clone the IE repo and build the deobf jar there, then copy it into the IR folder

**Comment by hayesj1** [comment]
yikes alrighty. I was hoping to avoid that...

**Comment by cam72cam** [comment]
Also, if you mess with the track placement logic, I'd recommend doing it on the track_rewrite branch

I'll probably be merging that into master this weekend
