### ISSUE TITLE
[1.5.0_1.12-402] Crashing when using an auto placer with track

### ISSUE THREAD

**Issue by GameBurrow** [TeamOpenIndustry/ImmersiveRailroading#524]
Immersive Railroading is causing our server to crash if client's get near a certain chunk. As nobody from us can actually get near it, this is the only description I have of the setup:

> "That large square of cobblestone is where I have been testing the immersive raliroading mod. I had an idea of using a mechanical user to place track so I could use a model hand car, but instead of finding the right settings to lay track, I found the settings that WILL crash the server. Right now I think if I log in the server Will Crash again. Sorry for the migraines this will cause."

Logfiles:
[2019-01-10-7.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/2746038/2019-01-10-7.log.gz)
[crash-2019-01-10_16.34.30-server.txt](https://github.com/cam72cam/ImmersiveRailroading/files/2746039/crash-2019-01-10_16.34.30-server.txt)
[crash-2019-01-10_16.36.48-server.txt](https://github.com/cam72cam/ImmersiveRailroading/files/2746040/crash-2019-01-10_16.36.48-server.txt)

**Comment by cam72cam** [comment]
Closing due to A) changes in modcore B) I don't want to support this
