### ISSUE TITLE
Investigate rendering with VBOs

### ISSUE THREAD

**Issue by cam72cam** [TeamOpenIndustry/ImmersiveRailroading#53]
May be able to get a big performance boost with that

**Comment by DonBruce64** [comment]
I was under the impression that Display Lists were the fastest way to render things as they were stored on the GPU.  Will converse with other modders to make sure I'm not a moron.

**Comment by cam72cam** [comment]
VBA's in a display list are quite fast.  That is what I am using for v0.1.4

**Comment by cam72cam** [comment]
This was done a while ago
