### ISSUE TITLE
Add textbox on the train

### ISSUE THREAD

**Issue by Excited-Naive** [TeamOpenIndustry/ImmersiveRailroading#576]
Use NAME TAG to change the word on the train to name them (like IV mod)

**Comment by Excited-Naive** [comment]
Sorry gor submiting a lot of suggestions at the same time.

**Comment by Excited-Naive** [comment]
for*

**Comment by km00700** [comment]
similar to #30

**Comment by cam72cam** [comment]
Closing as dupe of #30
