### ISSUE TITLE
[suggestion] Vanilla tracks and curved rails

### ISSUE THREAD

**Issue by VioletWyvern** [TeamOpenIndustry/ImmersiveRailroading#581]
Although this mod is supported to put trains on vanilla tracks, But it will encounter some problems:
**Train will stuck on turning**...     

The trains in this mod can only running at straight vanilla tracks, if going on vanilla curved tracks the train will stuck...   So some players just replaced some 3D curved rails from this mod on the turning points, Trying to solve this problem, But they encounter a new problem: **Train still stuck on turning**....

Because the 3D rails in this mod was a little higher then vanilla tracks,  If a train going on straight vanilla tracks and switched on 3D curved rails, Train will stuck on this small altitude difference...

So how to solve this?   My suggestions was these:
1. Making vanilla-alike 2D rails by using this mod's rail mechanism...   Put them just like 3D rails but in vanilla-alike 2D...
2. Just remove the ability to put trains on vanilla tracks...  If you don't want to solve it, just remove it!

**Comment by Excited-Naive** [comment]
u can do it urself btw

**Comment by cam72cam** [comment]
This is actually a TrackAPI bug that I have been putting off for quite a while

**Comment by cam72cam** [comment]
Fixed, will be released along with the next IR release
