### ISSUE TITLE
Water tanks get passed to the output slot when not emptied first

### ISSUE THREAD

**Issue by Paul17041993** [TeamOpenIndustry/ImmersiveRailroading#585]
The tank gets passed when the internal water tank becomes full, as opposed to when the input tank is emptied, requiring the user to cycle the tank back over to make full use of it.

**Comment by cam72cam** [comment]
This is by design, it depends on how the added tank functions

**Comment by Paul17041993** [comment]
Have you looked at how other mods handle it? they hold the tank until it's emptied.
