### ISSUE TITLE
About Custom Rail

### ISSUE THREAD

**Issue by Excited-Naive** [TeamOpenIndustry/ImmersiveRailroading#589]
in the future versions hope rail height can be changed in json instead of detecting the model directly or detect the height of part RAIL_LEFT or RAIL_RIGHT instead of whole model

**Comment by DrprofLuigi** [comment]
I agree. Then we can have overhead wires.

![2019-04-08_21 21 50](https://user-images.githubusercontent.com/36775575/57200738-30481380-6f44-11e9-8bee-edcbd057758b.png)
