### ISSUE TITLE
Server spams WARN Multiblock TE is null

### ISSUE THREAD

**Issue by Faelris** [TeamOpenIndustry/ImmersiveRailroading#591]
Hi! My server with ImmersiveRailroading is spamming this in console every tick:

[21:41:40] [Server thread/WARN] [immersiverailroading]: Multiblock TE is null: BlockPos{x=-223, y=144, z=-15} BlockPos{x=3, y=7, z=0} false class cam72cam.immersiverailroading.multiblock.CastingMultiblock$CastingInstance

I tried to look for Tile Entities at those BlockPos, but MCEdit and NBTExplorer said there's none (I know, it's null)

**Comment by km00700** [comment]
Is that a location where you built a casting basin at any time?

**Comment by Faelris** [comment]
the thing is that my casting basin is in a different position, and there's no block/tile at this coords

**Comment by km00700** [comment]
what are the actual coords of your Casting Basin TEs (according to MCEdit)?

**Comment by Faelris** [comment]
it's x=-194, y=80, z=-43, etc

**Comment by cam72cam** [comment]
Closing due to modcore changes / inactivity
