### ISSUE TITLE
Default Track Costs - Balance?

### ISSUE THREAD

**Issue by Kriegfox** [TeamOpenIndustry/ImmersiveRailroading#592]
Current default track cost multipliers are 0.25, with custom track recipes should we put defaults to 1.0? That way, a Tie is 1 tie, not 1 tie is 4 ties? This kind of goes inline with the adjustment I just made to the rail rolling machine.

**Comment by cam72cam** [comment]
I am keeping it cheap for now.  There config option is there for exactly this purpose
