### ISSUE TITLE
[Suggestion] Custom Track Gauge Locking

### ISSUE THREAD

**Issue by DrprofLuigi** [TeamOpenIndustry/ImmersiveRailroading#593]
I made a track meant for MC Gauge. The idea being that the original track doesn't quite work right for MC gauge (you can see in the picture it is a bit short). This causes problems for things like slopes.

So when I made my MC Gauge track, I scaled it up by 1.435/0.632 (Standard/MC). This kind of works, because when this custom track is selected to be MC Gauge, it properly fills the block length (like how standard track does at the standard gauge). However, as you can see on the far left, the ties overlap in a weird way.

My suggestion is to allow gauge-locking for custom track. This would also make it easier to find the track you want (i.e. my custom MC track can only be selected when you choose Minecraft gauge). 
Plus if the track at MC gauge were treated normally, instead of a scaled-down version of a scaled-up track, it would fix the tie visuals.

I think the visual issues occur because it is assumed the track is 1m in length, so when it's scaled up it overlaps really bad because it's actually longer than 1m.

Pictured:

Far Left: Length of my custom MC Gauge track at MC gauge
Top Left: Single piece of my custom MC Gauge track at standard gauge
Bottom Left: Single piece of my custom MC Gauge track at MC gauge

Far Right: Length of IR default track at MC gauge
Top Right: Single piece of IR default track at standard gauge
Bottom Right: Single piece of IR default track at MC gauge

![2019-05-05_14 40 46](https://user-images.githubusercontent.com/36775575/57200762-67b6c000-6f44-11e9-8b9c-5dd94497a8f2.png)

**Comment by Larky2k** [comment]
already been discussed when Cam first made the code as im after it
