### ISSUE TITLE
[mc-1.10.2 ir-1.6.1] conflict with optifine breaks resource packs

### ISSUE THREAD

**Issue by xemnes** [TeamOpenIndustry/ImmersiveRailroading#597]
it seems that theres a conflict with optifine on 1.10.2 if newer versions of immersive railroading is installed completely breaking all resource packs, stopping them from loading.
an error is spit out when the texture atlas is being created causing it to abort and unload the resource pack being loaded.
heres the error in question: https://pastebin.com/VUGevWp4

and heres the full latest log that contains the error: https://pastebin.com/V6fV71xY

its weird as it appears to be some kind of ctm conflict maybe? it claims it cant find literally every texture in the resource pack under ctm though they are definitely there and can be loaded fine without ir installed or if older versions of ir, like 0.5.5 is instaled.

heres a latest log for 1.6.1 when optifine is not installed: https://pastebin.com/7AW5cZib

ive noticed at the point it created a texture atlas in this version, that it goes through fine and lists a load of "rolling_stock" jsons which doesnt happen when optifine is installed and instead throws that error and unloads the resource pack.

**Comment by cam72cam** [comment]
This happens when MC runs out of memory when loading packs.  This should be fixed in the latest code
