### ISSUE TITLE
Rolling stock inventories destroy items

### ISSUE THREAD

**Issue by PDelta41** [TeamOpenIndustry/ImmersiveRailroading#599]
When adding items to an existing stack in rolling stock inventories, there is an good chance that said items will be deleted instead.

**Comment by redstone2019** [comment]
If you put another item in the first clear slot then you will get the "deleted" item back.

**Comment by redstone2019** [comment]
I'm sorry that's for locomotive inventories

**Comment by redstone2019** [comment]
@PDelta41 How good a chance? Is it specific to certain items? This doesn't happen to me on IR 1.6.1 
(MC 1.12.2)

**Comment by km00700** [comment]
Any items, it's more prevalent on servers (Where packet desync is more of an issue)

**Comment by redstone2019** [comment]
Ok I can't help that

**Comment by cam72cam** [comment]
Fixed by https://github.com/TeamOpenIndustry/UniversalModCore/commit/1cd5466fa8631644a779e8c537ab684548dbe9e5
