### ISSUE TITLE
Bumping into rolling stock in shunting mode causes cars to run away

### ISSUE THREAD

**Issue by Railroadactive** [TeamOpenIndustry/ImmersiveRailroading#602]
One annoying bug I sometimes encounter when switching is that having a coupler on the engine set to shunting mode causes the cars that I want to couple on to to run away all the way to the end of line. This occurs even in low speeds and it sends the cars so fast that they can run up many long hills that would normally cause them to slow down and roll back. It is especially annoying when the switch at the end of the yard is set to the longest route and the cars are tank cars full of biodiesel...

**Comment by moscontheroad** [comment]
Hello, i have the same problem, which log or info do you need to address this issue?
