### ISSUE TITLE
Crash when rendering Conductor's Whistle in JEI

### ISSUE THREAD

**Issue by hayesj1** [TeamOpenIndustry/ImmersiveRailroading#608]
Forge Versions: 2838, 2836, 2831
Minecraft Version: 1.12.2
IR Version: 1.6.1_1.12-1138
I get this crash log when the page containing the conductor's whistle is loading in JEI:

https://pastebin.com/ACMDsVuC

This was a client-side only crash, but I was playing on a dedicated server at the time. Latest.log appears to have nothing of value, and is almost 9k lines, but I can pastebin that too if necessary.

**Comment by hayesj1** [comment]
I also get this crash when placing a loco on the dedicated server

**Comment by hayesj1** [comment]
Upon reentering the world, if login facing the loco I get a frame or two then crash. The loco I used was the Baldwin Consolidation from Legend’s American Steam pack. Turning off the Use VBO’s setting made no difference. Some brief Initial research suggests there might be a missing “if (GLUtil.isVBOEnabled()) {}” check somewhere.

**Comment by hayesj1** [comment]
I also have a hunch it might be a forge issue, but I’ll have to further test that when I have time

**Comment by hayesj1** [comment]
Nope, looks like a dedicated server issue. Singleplayer seems fine oddly, even with Use VBOs turned on

**Comment by hayesj1** [comment]
Scratch the above comment about VBO's making no difference, I am able to log in to the server crash free with them disabled. However, enabling VBO's causes a crash immediately, before even leaving the video options menu.

**Comment by cam72cam** [comment]
We probably need `@Optional.Interface(iface = "mezz.jei.api.ingredients.ISlowRenderItem", modid = "jei")` on a few of our items including this one.

**Comment by cam72cam** [comment]
Fixed
