### ISSUE TITLE
crash while breacking track (world ticking) server-side

### ISSUE THREAD

**Issue by bobodoustaud** [TeamOpenIndustry/ImmersiveRailroading#614]
crash report : 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  OTGCorePlugin (OTG-Core.jar)
  SpongeCoremod (spongeforge-1.12.2-2825-7.1.6.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/17/19 6:03 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at cam72cam.immersiverailroading.tile.TileRailBase.func_189515_b(TileRailBase.java:286)
	at cam72cam.immersiverailroading.tile.SyncdTileEntity.func_189518_D_(SyncdTileEntity.java:51)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.immersiverailroading.tile.TileRailBase.func_189515_b(TileRailBase.java:286)
	at cam72cam.immersiverailroading.tile.SyncdTileEntity.func_189518_D_(SyncdTileEntity.java:51)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: DIM-100
	All players: 1 total; [EntityPlayerMP['bobodoustaud'/375, l='DIM-100', x=-775.18, y=178.00, z=867.42]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 3868542081208469510
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: OTG
	Level spawn location: World: (0,81,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6728872 game time, 6728872 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjo000(MinecraftServer.java:3980)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-9-amd64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 917468992 bytes (874 MB) / 2053636096 bytes (1958 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms128M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                  | Source                                            | Signature                                |
	|:------ |:----------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                     | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | otgcore                 | 1.12.2 - v7              | minecraft.jar                                     | None                                     |
	| LCHIJA | spongeapi               | 7.1.0-fb496dbf0          | spongeforge-1.12.2-2825-7.1.6.jar                 | None                                     |
	| LCHIJA | sponge                  | 1.12.2-7.1.6             | spongeforge-1.12.2-2825-7.1.6.jar                 | None                                     |
	| LCHIJA | spongeforge             | 1.12.2-2825-7.1.6        | spongeforge-1.12.2-2825-7.1.6.jar                 | None                                     |
	| LCHIJA | openmodscore            | 0.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJA | opencomputers|core      | 1.7.4.153                | minecraft.jar                                     | None                                     |
	| LCHIJA | dsurroundcore           | 3.5.4.3                  | minecraft.jar                                     | None                                     |
	| LCHIJA | uncraftingtable         | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar               | None                                     |
	| LCHIJA | jei                     | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCHIJA | mantle                  | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCHIJA | tconstruct              | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                  | None                                     |
	| LCHIJA | redstoneflux            | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LCHIJA | cofhworld               | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalfoundation       | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | immersiveengineering    | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | alternatingflux         | 0.12.2-2                 | alternatingflux-0.12.2-2.jar                      | None                                     |
	| LCHIJA | antiqueatlas            | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                     | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | appliedenergistics2     | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | openterraingenerator    | v6                       | OpenTerrainGenerator-1.12.2+-+v6.jar              | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LCHIJA | biomebundle             | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                      | None                                     |
	| LCHIJA | botania                 | r1.10-361                | Botania+r1.10-361.jar                             | None                                     |
	| LCHIJA | chiselsandbits          | 14.33                    | chiselsandbits-14.33.jar                          | None                                     |
	| LCHIJA | chunkpregenerator       | 2.1                      | Chunk+Pregenerator+V1.12-2.1.jar                  | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | crafttweaker            | 4.1.18                   | CraftTweaker2-1.12-4.1.18.jar                     | None                                     |
	| LCHIJA | crafttweakerjei         | 2.0.3                    | CraftTweaker2-1.12-4.1.18.jar                     | None                                     |
	| LCHIJA | customnpcs              | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                    | None                                     |
	| LCHIJA | enderstorage            | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | valkyrielib             | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                   | None                                     |
	| LCHIJA | environmentaltech       | 1.12.2-2.0.20.1          | environmentaltech-1.12.2-2.0.20.1.jar             | None                                     |
	| LCHIJA | extrautils2             | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCHIJA | griefprevention         | 1.12.2-4.3.0.689         | griefprevention-1.12.2-4.3.0.689.jar              | None                                     |
	| LCHIJA | hammercore              | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | ichunutil               | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hats                    | 7.0.0                    | Hats-1.12.2-7.0.2.jar                             | None                                     |
	| LCHIJA | waila                   | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | igwmod                  | 1.4.4-15                 | IGW-Mod-1.12.2-1.4.4-15-universal.jar             | None                                     |
	| LCHIJA | immersivepetroleum      | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| LCHIJA | trackapi                | 1.1                      | TrackAPI-1.1_1.12.jar                             | None                                     |
	| LCHIJA | immersiverailroading    | 1.6.1                    | ImmersiveRailroading-1.6.1_1.12-1138.jar          | None                                     |
	| LCHIJA | immersivetech           | 1.3.10                   | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                       | None                                     |
	| LCHIJA | dosmike_lockette        | 1.1                      | Lockette.jar                                      | None                                     |
	| LCHIJA | luckperms               | 4.4.26                   | LuckPerms-Sponge-4.4.26.jar                       | None                                     |
	| LCHIJA | mobends                 | 0.24                     | mobends-0.24_for_MC-1.12.jar                      | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
	| LCHIJA | opencomputers           | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar              | None                                     |
	| LCHIJA | ocdevices               | snapshot_20190121        | ocdevices-snapshot_20190121.jar                   | None                                     |
	| LCHIJA | openmods                | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks              | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openprinter             | 0.1.0.2                  | OpenPrinter-1.12.2-0.1.0.2.jar                    | None                                     |
	| LCHIJA | projectred-core         | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
	| LCHIJA | projectred-integration  | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCHIJA | projectred-transmission | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCHIJA | randomthings            | 4.2.7.1                  | RandomThings-MC1.12.2-4.2.7.1.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | tails                   | 1.12-1.10.0              | Tails-1.12-1.10.0.jar                             | None                                     |
	| LCHIJA | thermalexpansion        | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics         | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tinkertoolleveling      | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCHIJA | universalmodifiers      | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                   | None                                     |
	| LCHIJA | visuals                 | 6r                       | Visuals-1.12.2-6r.jar                             | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | worldedit               | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | orelib                  | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround               | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
  lumien.randomthings.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
SpongeCoremod (spongeforge-1.12.2-2825-7.1.6.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1094 names; 1198 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Visuals (visuals) @6r

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['bobodoustaud'/375, l='DIM-100', x=-775.18, y=178.00, z=867.42]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

please fix, i can't anymore delete this track ! D:

**Comment by Larky2k** [comment]
what was you doing at the time

**Comment by bobodoustaud** [comment]
breacking the track with hands

**Comment by bobodoustaud** [comment]
ah... to remove bugged tracks, i placed chunk loaders, tnt near the tracks and redstone. then make a long redstone wire and unload the chunks qith the tracks and activate the chunk-loaded tnt widh the redstone.
