### ISSUE TITLE
[Suggestion] Improving the paintbrush. 

### ISSUE THREAD

**Issue by Tazzer1993** [TeamOpenIndustry/ImmersiveRailroading#617]
Would it be possible to add some finer control to the paintbrush to allow the selection of multiple re-textures at once.

For example I'm doing some modeling of a log car with multiple log re-textures and company logos.
Would it be possible to add a way to have these different textures in there own folders so that the users can choose which ones they want instead of me having to make all the possible combinations.

Like:
I want wood A with logo D.
Selecting from a list of all the re-textures available on the rolling stock. 

Thinking about the number of combinations I would need and the number of duplicate textures having them one time could save on the overall file size.

**Comment by km00700** [comment]
It's not currently possible due to the way liveries are added. There are plans to add a GUI to the paintbrush. It's possible that we could add separate sets using the advanced GUI.

**Comment by Tazzer1993** [comment]
Nice to know that there are plans to improve the paintbrush.
