### ISSUE TITLE
NPE on creating track from blueprint

### ISSUE THREAD

**Issue by km00700** [TeamOpenIndustry/ImmersiveRailroading#618]
Seen across multiple users. Occurs on the first frame after the blueprint has broken, but before the track tiles are placed.
[crash-2019-07-04_13.21.54-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3360407/crash-2019-07-04_13.21.54-client.txt)

**Comment by Flow86** [comment]
here is another one at a different location while laying tracks
[crash-2019-07-26_11.03.52-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3435049/crash-2019-07-26_11.03.52-client.txt)

**Comment by Morketh** [comment]
Minecraft Server Specs:
Xenserver running on Dell T610
Model: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz x2
Total memory: 32 Gb ECC RAM DDR3

Minecraft VM:
4 Sockets with 1 Core per socket (configurable in Xen)
Ubuntu 16.04.6 LTS
VM RAM 10 GB

[crash-2019-08-11_14.16.48-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3490418/crash-2019-08-11_14.16.48-client.txt)
[crash-2019-08-11_14.26.07-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3490419/crash-2019-08-11_14.26.07-client.txt)
[crash-2019-08-11_13.49.44-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3490420/crash-2019-08-11_13.49.44-client.txt)
[latest.log](https://github.com/cam72cam/ImmersiveRailroading/files/3490426/latest.log)
