### ISSUE TITLE
crash when opening inventory tab

### ISSUE THREAD

**Issue by Animus-Surge** [TeamOpenIndustry/ImmersiveRailroading#620]
Every time when I try to open the main tab, not the ones with the rolling stock (locomotives, cargo, passenger), the game crashes with a `NullPointerException` whilst rendering an item. I am using the curse client to play my custom modpack (the mods are listed in the crash report, linked below), and all I do is open my inventory and navigate to the tab with the rails, augments, and golden spike.

This had started after using three resource packs that add rolling stock into your mod.\
* TFL Pack by thomaslovessalmon
* Amtrak+
* DarkRaider's monorails

The list above is the packs that I used, in case it has anything to do with them.

I have provided the crash report (and if I need the log too I will gladly attach that too) in the [pastebin](https://pastebin.com/6D1040i6) I have linked.

Thank you.

**Comment by Larky2k** [comment]
Update your java post latest.log, remove all RP and see it it's does it if it stops add them one at a time to fine the culprit

**Comment by Animus-Surge** [comment]
Okay, so I did that. Everything went smoothly and it showed the inventory tab without any resource packs. I loaded TFL first, and it crashed.

[Here](https://gist.github.com/Animus-Surge/453e1a973806aa2505b1ded1ad60d7e9) is the log for that one.

Now I loaded Amtrak+ and it broke again with the same exact problem. ([log](https://gist.github.com/Animus-Surge/e6cb2b820cf8ef0fe48bce863f46cf59))

I took a small look at the specific location of the stacktrace and it led me to your `cam72cam.immersiverailroading.render.VBA.drawVBA(VBA.java:153)` thing here. 

Maybe the issue is using the 2d item models?

**Comment by km00700** [comment]
Do you have a discrete graphics card, or just the Intel HD? Also, can you allocate more than 3GB RAM? The VBAs grab from VRAM, but when using Intel Integrated, your system RAM is used a VRAM and things can get overwritten. This causes all types of graphical NullPointerExceptions.

**Comment by Animus-Surge** [comment]
"Do you have a discrete graphics card, or just the Intel HD?"
I only have the intel. The game runs fine without the resource packs, and is showing the inventory just fine (also without the resource packs).

"Also, can you allocate more than 3GB RAM?"
I could, but I don't really want to because, like I said, the game is running fine. I play games that take the entire 12gb memory bank I have and it still works. But, I could definitely do it if needed. However, my client says to not allocate _too_ much ram, because that could cause performance issues (like giving a lag spike every two seconds, which I fixed by using the 3gb allocation that I currently use :P).

**Comment by Larky2k** [comment]
So what is the total RAM your system has. Forge requires 4gb minimum with IR we recommend 8gb ish due to the fact IR loads models to RAM so it requires more. Now loading RP requires decent amount of RAM as they are loaded into the GPU which in your case is using your System RAM. Which isn't very good for being used as VRAM. Try using your RAM to about 6gb ish and see if you load.

**Comment by Animus-Surge** [comment]
12gb.

**Comment by Larky2k** [comment]
ok just read your log your maxing out your GPU VRAM. try giving your Intel some more RAM to see how it goes and also update your Java your going to run into issues with IE and IR with your version of Java

**Comment by Animus-Surge** [comment]
"ok just read your log your maxing out your GPU VRAM. try giving your Intel some more RAM to see how it goes"

I'll try that. But just to be clear with my issue, the base mod (without the __resource packs__) is loading fine (including the inventory tab), but I do want to use some addons for it (b/c im building a city around this mod and my modpack) just so I can make it look a little nicer. It's when I load in a resource pack that adds on to the mod that the game crashes when I go into the inventory tab that contains the augments, rails, etc.

"also update your Java your going to run into issues with IE and IR with your version of Java"

Not to try to sound rude or anything, but as far as I know, the java version isn't the issue with 1.12.2 forge (partly because I have worked with the latest version (of java) and 1.12.2 and it wouldn't work). I did install the latest java version just to be safe, however. I also have gotten the 1.13 forge update, which, according to forge forum mods, is compatible with java 10, but 1.12 is only compatible with up to java 8 (as far as I know (it could have changed)).

**Comment by Larky2k** [comment]
well java version 51 IE will randomly crash with there manuel open and the only way to fix that is use latest java. the more RP you load for IR requires more VRAM as you are loading more models to it. if yo don't have the RAm MC will crash

**Comment by Animus-Surge** [comment]
I know. The pack loads (and it loads with my current allocation) just fine and renders the rolling stock (and the rolling stock category tabs, just not the main IR tab) in and out of the inventory.

**Comment by hayesj1** [comment]
What larky is trying to say is use the latest version of Java 8, not the latest and greatest of all Java, because as you correctly pointed out, 1.12.2 Forge will NOT work with Java 9+.

Unfortunately if I remember correctly, Oracle has stopped hosting Java 8 Releases. Thankfully the OpenJDK still hosts Java 8 builds, but I’m not sure if there’s a way to get Java from them without using a Terminal/Command Prompt.

**Comment by Larky2k** [comment]
you want this
https://www.java.com/en/download/

**Comment by Animus-Surge** [comment]
Oh... I totally knew that... Java's update detector thing got me the version that you said (8_211), so that shouldn't be a problem anymore
