### ISSUE TITLE
Game Crashes when attempting to load resource pack with flat Icons enabled

### ISSUE THREAD

**Issue by High-Admiral** [TeamOpenIndustry/ImmersiveRailroading#621]
Attempting to load Legend's American Steam Pack which just updated. Keeps crashing before the home screen. Traced it back to the GS-4 tender. DarkRaider said something about IR having an issue when generating the flat icon. 
[crash-2019-07-12_22.22.09-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3388410/crash-2019-07-12_22.22.09-client.txt)
This is my testing client, only have American Steam, Custom Steam, and American Diesel packs on it and the problem only cropped up after I updated American Steam.

**Comment by DoomGuy1** [comment]
Im having the same issue with the gs-4 tender i removed it from legends pack and it worked perfectly after that heres my crash
[crash-2019-07-12_22.15.07-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3388419/crash-2019-07-12_22.15.07-client.txt)
