### ISSUE TITLE
Hunger Loss using Handcart

### ISSUE THREAD

**Issue by titanium-cid** [TeamOpenIndustry/ImmersiveRailroading#624]
When using the handcart on version 1.6.1_1.12-1138 I noticed that there is significant hunger loss even though I had full saturation. 

This was visible due to Appleskins showing the Saturation Level.

Running on Forge V14.23.5.2837

If you need any further information let me know.

**Comment by Larky2k** [comment]
feature

**Comment by hayesj1** [comment]
I didn’t know the handcar ignored saturation entirely. Good to know.

**Comment by cam72cam** [comment]
hmm, it should probably use saturation
