### ISSUE TITLE
[Suggestion} Buffers and Train Block Breaking

### ISSUE THREAD

**Issue by titanium-cid** [TeamOpenIndustry/ImmersiveRailroading#625]
I believe this has been suggested before, but I would like to second the need for some buffer block that the trains don't break easily.

Current, even a hand cart will go right through any block in the game including bedrock which seems a little ludicrous.

**Comment by Carvercarver1** [comment]
Updiating on the suggestion. Apparently this user made an addon which adds buffers. So... now we actually have a buffer. https://www.curseforge.com/minecraft/mc-mods/signal-stuff

Enjoy!

**Comment by km00700** [comment]
Note, this buffer is not functional. It's purely visual.
