### ISSUE TITLE
Strange bug with enchantments.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamOpenIndustry/ImmersiveRailroading#626]
![](https://user-images.githubusercontent.com/18079316/59392486-6fbb1880-8daa-11e9-80ee-746698e9edec.png)

I posted an issue like this to the Immersive Engineering github and turns out this issue is to do with immersive railroading.

Essentially the enchanted overlay is literally just a giant square which looks really wrong.

https://github.com/BluSunrize/ImmersiveEngineering/issues/3492 Immersive Engineering github post I made.

**Comment by cam72cam** [comment]
This should be fixed with changes made in modcore.  If IR version 1.7.0 does not fix this issue (when released in a few weeks) please re-open the issue.
