### ISSUE TITLE
Locomotives will not accept fuel

### ISSUE THREAD

**Issue by 412pgh** [TeamOpenIndustry/ImmersiveRailroading#628]
On my 1.12.2 immersive railroading world, the C44-9W, SD70ACe, SD70MAC, B40-8 and B40-8W will not accept any fuels. Basically, if you put a fuel bucket into the fuel bucket slot, it won't fill the engine up and give me an empty bucket back. This issue frustrates me beyond belief, I've tried every single fuel, re-downloaded the mod several times, and it STILL wont work

**Comment by km00700** [comment]
please send latest.log as I requested earlier.

**Comment by moscontheroad** [comment]
Hello, i have the same problem, which log or info do you need to address this issue?

**Comment by HellMoon845** [comment]
Why did you reference to a closed request?
Now both requests are closed and no solution is found.

**Comment by HellMoon845** [comment]
oh sry I see, it's open

**Comment by HellMoon845** [comment]
I have the same problem now on a minecraft 1.12.2.  When I tried it yesterday, everything was fine. But when I started the game again today, the locomotive didn't acept water and coal, also the hotkeys for break and throttle were not working any more. Could it be that it is a problem that occurs while saving the game before shutdown?

**Comment by HellMoon845** [comment]
So, for my version of this problem, a solution is found: 

It was a conflict between Immersive Railroading and Industrial Craft 2.
Instead of Industrial Craft 2, you can use Buildcraft and/or a combination of Immersive Engineering and Immersive Petroleum.

**Comment by 412pgh** [comment]
Do you can use buildcraft fuels in the engines?

**Comment by HellMoon845** [comment]
I have both, buildcraft and immersive petroleum installed, so I'll try what
works better

412pgh <notifications@github.com> schrieb am Do., 21. Nov. 2019, 20:40:

**Comment by 412pgh** [comment]
Good, let me know! Because my ES44AC/DC, C44-9W, SD70MAC, SD70ACe, and
P42DC and F59PHI all won’t accept fuel when in standard gauge mode

**Comment by HellMoon845** [comment]
Yes, it's working

412pgh <notifications@github.com> schrieb am Do., 21. Nov. 2019, 20:40:
