### ISSUE TITLE
Request: Schwerer Gustav

### ISSUE THREAD

**Issue by HighSeasCaeser** [TeamOpenIndustry/ImmersiveRailroading#63]
![dora-unique-superheavy-train-artillery-gun-the-army-germany-gauge-mm-bob-tank-train-gun-men-dora-unique-super-heavy-rail-artillery-cannon-army-germany-caliber-807-mm-tank-train-gun-soldiers](https://user-images.githubusercontent.com/31832081/30254433-655277e8-965e-11e7-8f5f-3b451bbe881e.jpg)

**Comment by CarterlikesIR** [comment]
lol
