### ISSUE TITLE
[Suggestion] specified item/fluid loading...

### ISSUE THREAD

**Issue by Ash-0666** [TeamOpenIndustry/ImmersiveRailroading#631]
This may be tedious, but what if the item/fluid (un)loaders could be set to load/unload specific items? This would allow for a different form of automated loading/unloading. I haven't tested to see if you can accidentally mix fluids in unloading, but you could theoretically do any and all loading without worry of misloading (items loading into unintended coaches).

Lets say you need to fill a steam engine with more water, but you also have one tank car you want to fill with...let's say ethanol, and another you want to fill with milk, or some other fluid. With the regulating scripting, you wouldn't have to worry about filling your tankcar needlessly with water, or ending up having the two tank cars fill up with just one of the two fluids.

You could control loading in a much quicker and easier maner, albeit with prior prep work.

**Comment by hayesj1** [comment]
currently, you can filter the augments by stock. This means you'd need a unique wagon for each unique field/item you wished to load.

**Comment by Ash-0666** [comment]
Thank you, that's helpful to know. I'll remember that for my layout.

Also, I'd like to expound my thinking by the concept of specified coaches, designated to be loaded with certain contents, and possibly the option to load multiple select items into said carriages. Please humor me. This can already be done with the stock- filter the augments use, so this idea is mostly streamlinig the existing proccess.

To explain my logic, picture a box car that can be loaded with wool. We'll go with white, grey, and black for this example. Now this box car will only recieve these three colors of wool, instead of another color (like blue) or any other item, acting as an item router of sorts. Now on the flip side, you want to unload the white wool at a station, without unloading the grey or black wool. Idealy, you could unload the said cargo withoud regard for which coaches it's in.

That's just my train of thought.
