### ISSUE TITLE
Feedback on griefers for Immersive Railroading mod.

### ISSUE THREAD

**Issue by aurimilky** [TeamOpenIndustry/ImmersiveRailroading#632]
Feedback

First off I love this mod :D

Problems that I have found with this mod. I play on a server with other players that build rail tracks to towns all on the overworld. Due to this the tracks are always getting griefed by griefers or by players that do not know better. items normaly used are: the pickaxe, empty hand or any other items in the game. Also the griefers love to steal anything that is placed on the tracks.

Solution to the problems, make the rail track and anything that can be placed on them only break by using Immersive Railroading wrench.

Many thanks and best of luck.
aurimilky

**Comment by Pannoniae** [comment]
But then they can get a wrench from the mod.... Sadly, griefing won't be fixed by that. I think you should talk to the admin to get them to not do it. :(

**Comment by moscontheroad** [comment]
Maybe permissions, only owners of the track are allowed to break it?

**Comment by senatormailman** [comment]
@moscontheroad wouldn't that be solved with a block log/ownership plugin? Also, first time commenting on this project. Love the work you guys do!
