### ISSUE TITLE
British rolling stock/ british passenger cars and chain 

### ISSUE THREAD

**Issue by therealbdld** [TeamOpenIndustry/ImmersiveRailroading#633]
british flatbed car able to have a locomotive or blocks placed on it. Also more british coaches and a chain or cable of some sort that can be coupled on the rolling stock or locomotives and be able to be pulled. thank you I really love this mod

**Comment by tom-23** [comment]
I made the font end of a 1992 LU Stock dl here: https://www.curseforge.com/minecraft/texture-packs/prototype-tfl-pack-for-immersive-railroading
