### ISSUE TITLE
NullPointerException Error: Tesselating block in world

### ISSUE THREAD

**Issue by aagha** [TeamOpenIndustry/ImmersiveRailroading#637]
My son's Mincraft edition is throwing the following error when he goes into his significantly well built out world:

The game crashed whilst tesselating block in world
Error: java.lang.NullPointerException: Tesselating block in world

I looked at the other errors (like #606) and it seems that @cam72cam might need to see the error log to figure out the issue. The log is attached.  I'm hoping you might be able to help.

[crash-2019-08-07_19.02.04-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3479524/crash-2019-08-07_19.02.04-client.txt)

**Comment by km00700** [comment]
See this
https://github.com/cam72cam/ImmersiveRailroading/issues/606

**Comment by cam72cam** [comment]
Yes, try that jar in the patched version.  I need to release an official update soon with that fix in it

**Comment by aagha** [comment]
Thanks, I thought about that but had assumed the version I had was already patched.

Question: Should I drop the #606 patched jar into that folder, or remove ImmersiveRailroading-1.5.0_1.12-402 and replace it?

**Comment by km00700** [comment]
did you use the second jar?

**Comment by aagha** [comment]
I did. 

I used:

ImmersiveRailroading-1.6.1_snowfix**2**

What I'm asking is:

Should I _remove_ ImmersiveRailroading-1.5.0_1.12-402 and replace it with ImmersiveRailroading-1.6.1_snowfix2 or should I keep ImmersiveRailroading-1.5.0_1.12-402 in the dir and just add ImmersiveRailroading-1.6.1_snowfix2 ?

**Comment by cam72cam** [comment]
replace the jar

**Comment by aagha** [comment]
OK, thanks. Replaced it. 

Same Tesselating block error.

**Comment by cam72cam** [comment]
Hmm, that's a different crash.  Let me look into it and try to put together a patch for you soon.

**Comment by aagha** [comment]
Thanks @cam72cam

**Comment by wxdao** [comment]
@aagha Were you playing it on mac? After I had upgraded the os to macos 10.14.6 I encountered the similar error I never seen before. Here's my log:

```
23:26:12.973
java.lang.NullPointerException: Tesselating block in world
23:26:12.973
at cam72cam.immersiverailroading.tile.TileRailBase.getRenderGauge(TileRailBase.java:104)
23:26:12.973
at cam72cam.immersiverailroading.blocks.BlockRailBase.getExtendedState(BlockRailBase.java:130)
23:26:12.973
at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
23:26:12.973
at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
23:26:12.973
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
23:26:12.973
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
23:26:12.973
at java.lang.Thread.run(Thread.java:745)
```

[crash-2019-08-11_23.26.11-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3490144/crash-2019-08-11_23.26.11-client.txt)

**Comment by cam72cam** [comment]
Macos upgrade does not have an impact.  It's just a bug in my code that I need to patch

**Comment by aagha** [comment]
> @aagha Were you playing it on mac? After upgrading the os to macos 10.14.6 I encountered the similar error I had never seen before. Here's my log:
> 
> ```
> 23:26:12.973
> java.lang.NullPointerException: Tesselating block in world
> 23:26:12.973
> at cam72cam.immersiverailroading.tile.TileRailBase.getRenderGauge(TileRailBase.java:104)
> 23:26:12.973
> at cam72cam.immersiverailroading.blocks.BlockRailBase.getExtendedState(BlockRailBase.java:130)
> 23:26:12.973
> at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
> 23:26:12.973
> at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
> 23:26:12.973
> at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
> 23:26:12.973
> at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
> 23:26:12.973
> at java.lang.Thread.run(Thread.java:745)
> ```
> 
> [crash-2019-08-11_23.26.11-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3490144/crash-2019-08-11_23.26.11-client.txt)

@wxdao For the record, using a PC.

**Comment by cam72cam** [comment]
This should be fixed in modcore
