### ISSUE TITLE
Crash in combination with CraftTweaker

### ISSUE THREAD

**Issue by ParadiseTeamAF** [TeamOpenIndustry/ImmersiveRailroading#640]
If you use the /ct hand command the get the recipe name it works fine. If you click the name to copy it like every other recipe. Minecraft or at least the server/internal server crashes.

**Comment by cam72cam** [comment]
Which version of IR/Minecraft/CraftTweaker?

**Comment by ParadiseTeamAF** [comment]
IR Version: ImmersiveRailroading-1.6.1_1.12-1138.jar
Minecraft : 1.12.2
Crafttweaker: CraftTweaker2-1.12-4.1.19.jar
