### ISSUE TITLE
Locomotives steam and diesel not burning any fuel coal or water

### ISSUE THREAD

**Issue by TrainLord** [TeamOpenIndustry/ImmersiveRailroading#646]
The Locomotives will spawn in and the bell works but when I go to feul
![2019-09-04_08 38 39](https://user-images.githubusercontent.com/50807961/64280767-6bb91580-cf17-11e9-8a69-9f49da91c5ca.png)
 it up it will take the items it just won't use them

**Comment by moscontheroad** [comment]
Hello, i have the same problem, which log or info do you need to address this issue?

**Comment by cam72cam** [comment]
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/628

**Comment by HellMoon845** [comment]
Sry but why did you close this topic?? There was no solution for both of them. I have this problem now, tooand I'd be glad to hear how tofix it.
