### ISSUE TITLE
NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by GEbb4** [TeamOpenIndustry/ImmersiveRailroading#648]
Repeated crashes on boot, when a player logs in, or when a player logs out on a 1.12.2 server. One player was stood with a few machines loaded, but it looks like ticking the casting basin was the problem.

Temporary fix is for us all to avoid reloading any of the machines, but a patch soon would be appreciated :-)

Crash report attached, I'm not sure what other data you'll need but I'll try and respond to comments as best I can.

[crash-2019-09-14_16.06.52-server.txt](https://github.com/cam72cam/ImmersiveRailroading/files/3612838/crash-2019-09-14_16.06.52-server.txt)

**Comment by cam72cam** [comment]
Hmm, odd.

Did this happen when the machine was placed down or after it had already been running for a while?

Are you able to world edit the world and remove the erroring blocks/tiles?

**Comment by GEbb4** [comment]
The casting basin had been placed and used, then moved and placed and used again, then one time someone logged in and it crashed.
I'm not sure we could worldedit because it won't load - but we'll try single player starting and see how it goes

**Comment by GEbb4** [comment]
Update: trying to remove the erroneous tile, but I'm not even to get close enough to setblock.

**Comment by GEbb4** [comment]
Another update: MCEditing out the two chunks containing the casting basin have restored the world to fully working. Still happy to provide any further debugging needed if you want further details.

**Comment by cam72cam** [comment]
As this has been completely rewritten in the past 6 months I am going to close it as it most likely no longer applies
