### ISSUE TITLE
how do i move stuff

### ISSUE THREAD

**Issue by ShadowsRevenge2** [TeamOpenIndustry/ImmersiveRailroading#653]
ive been trying for hour to figure out how this mod works. i got the basic track laying down but the trains cant be controlled. i tried using the manual and the machine wont finish even with a hammer. what do i do to make this work because i really want to start using this mod

**Comment by km00700** [comment]
You need to use the Wrench to finish machines, not a hammer. Diesels need to be turned on before use. (numpad ADD by default)

**Comment by ShadowsRevenge2** [comment]
awesome. i will give it a try. cheers

**Comment by km00700** [comment]
(On that note, the diesels need to heat up after being turned on as well, so give it some time for that)

**Comment by ShadowsRevenge2** [comment]
ok cool. do steam engines work the same or is there something different?

**Comment by cam72cam** [comment]
steam engines need burnable fuel in the lower slots and water in the upper slot.  Make sure you add a few buckets of water first.

You will see the burning animation and the pressure starting to rise on the gui on the side of your screen.

Once you have enough steam pressure, you can move the locomotive using the keybinds

**Comment by ShadowsRevenge2** [comment]
ok cool. thank you
