### ISSUE TITLE
[Suggestion] Hide items without Recipe from JEI

### ISSUE THREAD

**Issue by ben-mkiv** [TeamOpenIndustry/ImmersiveRailroading#660]
**Describe the suggestion**  
Actually there are several items displayed in JEI which don't have a vanilla recipe. I would appreciate if those get hidden.

Also rendering of all the models might create FPS drop on slow machines

Here's an small example how to hide Items from JEI
https://github.com/PC-Logix/OpenSecurity/blob/c837bc053b62a382bb3d36ec867d56b2a0825a66/src/main/java/pcl/opensecurity/client/jei/JEI_Plugin.java#L52-L54

But for some big mod like IR i would suggest some actual Handler where Content creators of addon packs can opt in their items from being hidden.

This could possibly also be bound to a config option so that players can chose if they want the items to be displayed or not

**Comment by NightScale5755** [comment]
there's a mod that does that for you:
https://www.curseforge.com/minecraft/mc-mods/jei-hider

**Comment by ben-mkiv** [comment]
Thanks, JEI also offers some way to hide ingredients on its own, but not everyone is aware of that, and not all IR Items can be selected for some reason.

**Comment by cam72cam** [comment]
At some point we will be attempting to add JEI integration so the parts will have an actual recipe.
