### ISSUE TITLE
How do I power this Locomotive?

### ISSUE THREAD

**Issue by LuciferHKY** [TeamOpenIndustry/ImmersiveRailroading#661]
Hi,

I have no clue on how to power the GE B40-8w. It said it was electric however I don't know where to input the power or how to power it in general.

**Comment by hayesj1** [comment]
Electric power isn’t implemented yet. Any “eletrics” currently available are actually diesels (or maybe steam locos, but I haven't seen any) under the hood. So you’d add some form of diesel fuel, which is configured in the config. IE biodiesel, IP petroleum products(gasoline, diesel, etc), the fuels from Pnuematicraft Repressurized, the fuels from TE, and more I’m sure are all added by default if those mods are present in your modlist

**Comment by km00700** [comment]
General Electric is the name of the company that manufactures the B40-8W. The B40 is a diesel locomotive.
