### ISSUE TITLE
Better Glass

### ISSUE THREAD

**Issue by Grandpagrump** [TeamOpenIndustry/ImmersiveRailroading#662]
**Describe the suggestion**  
I would like to see less blocks (or none) on glass. From locos to the phone booth to vehicles, everything looks like the glass has been riddled with machine gun bullets.

**Comment by cam72cam** [comment]
Sorry, we are not planning on re-doing the glass any time soon.  We will be posting a tutorial on modifying game assets before the year is out if you wish to dig into it at that level.
