### ISSUE TITLE
Sounds not loading

### ISSUE THREAD

**Issue by SteampsonJake** [TeamOpenIndustry/ImmersiveRailroading#672]
Whistles, chuffs and few other sounds from resource packs don't load in game.

My [latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3827656/latest.log) if needed
And the pack [CSD pack.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3827658/CSD.pack.zip)

**Comment by cam72cam** [comment]
* Chuffs worked in your pack
* Whistles were being overridden by quilling
* You don't override the default sounds in resourcepacks.  Instead add your own sound files with their own names and "wheels": "yoursound", "clack": "yourothersound", in the sounds section of all your stock.
