### ISSUE TITLE
crashed when starting the game

### ISSUE THREAD

**Issue by zues3000** [TeamOpenIndustry/ImmersiveRailroading#675]
Template goes here
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BringMeTheRings plugin (Bring-Me-The-Rings-Mod-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
  CraftDevLoadingPlugin (CraftDev-Core-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 11/10/19 8:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UniversalModCore (universalmodcore)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:340)
	at cam72cam.mod.render.obj.OBJTextureSheet.<init>(OBJTextureSheet.java:124)
	at cam72cam.mod.render.obj.OBJTextureSheet.<init>(OBJTextureSheet.java:33)
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:31)
	at cam72cam.immersiverailroading.render.entity.StockModel.<init>(StockModel.java:36)
	at cam72cam.immersiverailroading.render.StockRenderCache.getRender(StockRenderCache.java:31)
	at cam72cam.immersiverailroading.render.item.StockItemModel.getSpriteModel(StockItemModel.java:62)
	at cam72cam.mod.render.ItemRender.lambda$register$5(ItemRender.java:65)
	at cam72cam.mod.render.ItemRender$$Lambda$243/852214886.run(Unknown Source)
	at cam72cam.mod.event.ClientEvents$$Lambda$1134/1525853899.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cam72cam.mod.event.Event.execute(Event.java:14)
	at cam72cam.mod.event.ClientEvents.fireReload(ClientEvents.java:36)
	at cam72cam.mod.ModCore$Internal.clientEvent(ModCore.java:176)
	at cam72cam.mod.ModCore$ClientProxy.lambda$event$0(ModCore.java:118)
	at cam72cam.mod.ModCore$ClientProxy$$Lambda$232/787952084.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at cam72cam.mod.ModCore$ClientProxy.event(ModCore.java:118)
	at cam72cam.mod.ModCore.init(ModCore.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333134744 bytes (317 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 Optifine OptiFine_1.12.2_HD_U_E3 114 mods loaded, 114 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version              | Source                                              | Signature                                |
	|:----- |:--------------------------------- |:-------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                         | 1.12.2               | minecraft.jar                                       | None                                     |
	| LCHI  | mcp                               | 9.42                 | minecraft.jar                                       | None                                     |
	| LCHI  | FML                               | 8.0.99.99            | forge-1.12.2-14.23.5.2807.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                             | 14.23.5.2807         | forge-1.12.2-14.23.5.2807.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | architecturecraft                 | @VERSION@            | ArchitectureCraft-ElytraDev-Mod-1.12.2.jar          | None                                     |
	| LCHI  | codechickenlib                    | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | avaritia                          | 3.3.0                | Avaritia-1.12.2.jar                                 | None                                     |
	| LCHI  | baubles                           | 1.5.2                | Baubles-Mod-1.12.2.jar                              | None                                     |
	| LCHI  | better_diving                     | 1.0.4                | Better-Diving-Mod-1.12.2.jar                        | None                                     |
	| LCHI  | miscrails                         | 1.0.0                | Better-Railroads-Mod-1.12.2.jar                     | None                                     |
	| LCHI  | betterbuilderswands               | 0.11.1               | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar     | None                                     |
	| LCHI  | bonsaitrees                       | 1.1.2                | bonsaitrees-1.1.2-b144.jar                          | None                                     |
	| LCHI  | bmtr                              | 0.4                  | Bring-Me-The-Rings-Mod-1.12.2.jar                   | None                                     |
	| LCHI  | jmcm                              | 9.2                  | Capes-Mod-1.12.2.jar                                | None                                     |
	| LCHI  | chameleon                         | 1.12-4.1.3           | Chameleon-Library-1.12.jar                          | None                                     |
	| LCHI  | chestcow                          | 1.0                  | Chest-Cow-Mod-1.12.2.jar                            | None                                     |
	| LCHI  | chesttransporter                  | 2.8.8                | Chest-Transporter-Mod-1.12.2.jar                    | None                                     |
	| LCHI  | chickens                          | 6.1.0                | chickens-6.1.0.jar                                  | None                                     |
	| LCHI  | chiselsandbits                    | 14.22                | Chisels-and-Bits-Mod-1.12.2.jar                     | None                                     |
	| LCHI  | redstoneflux                      | 2.1.0                | RedstoneFlux-1.12-2.1.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHI  | cofhcore                          | 4.6.3                | CoFHCore-1.12.2-4.6.3.27-universal.jar              | None                                     |
	| LCHI  | cofhworld                         | 1.3.1                | CoFHWorld-1.12.2-1.3.1.7-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHI  | colorfulpotions                   | 1.12.2-1.1           | Colorful-Potions-Mod-1.12.2.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | colytra                           | 1.2.0                | colytra-1.12.2-1.2.0.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | controlledburn                    | 1.12.2.005           | Controlled-Burn-Mod-1.12.2.jar                      | None                                     |
	| LCHI  | craftdevcore                      | 2.2.8                | CraftDev-Core-1.12.2.jar                            | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| LCHI  | cucumber                          | 1.0.4                | Cucumber-Mod-1.12.2.jar                             | None                                     |
	| LCHI  | modcurrency                       | 1.12-1.3.9           | Currency-1.12.0-1.3.9.jar                           | None                                     |
	| LCHI  | cxlibrary                         | 1.6.1                | CXLibrary-1.12.1.jar                                | None                                     |
	| LCHI  | dynamictrees                      | 1.12.2-0.9.5         | DynamicTrees-1.12.2-0.9.5.jar                       | None                                     |
	| LCHI  | endercore                         | 1.12.2-0.5.43        | EnderCore-1.12.2-0.5.43.jar                         | None                                     |
	| LCHI  | jei                               | 4.12.0.216           | jei_1.12.2-4.12.0.216.jar                           | None                                     |
	| LCHI  | enderio                           | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiointegrationtic             | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiobase                       | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderioconduits                   | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderioconduitsappliedenergistics | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderioconduitsopencomputers      | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | refinedstorage                    | 1.6.3                | Refined-Storage-Mod-1.12.2.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHI  | enderioconduitsrefinedstorage     | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiointegrationforestry        | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiointegrationticlate         | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiomachines                   | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiopowertools                 | 5.0.39               | EnderIO-1.12.2-5.0.39 (1).jar                       | None                                     |
	| LCHI  | enderiozoo                        | 5.0.39               | EnderIO-zoo-1.12.2-5.0.39.jar                       | None                                     |
	| LCHI  | extrautils2                       | 1.0                  | Extra-Utilities-Mod-1.12.2.jar                      | None                                     |
	| LCHI  | fnaf                              | 1.12.2-V12           | Five-Nights-at-Freddys-Universe-Mod-1.12.2.jar      | None                                     |
	| LCHI  | mcmultipart                       | 2.5.3                | MCMultiPart-2.5.3.jar                               | None                                     |
	| LCHI  | sonarcore                         | 5.0.19               | sonarcore-1.12.2-5.0.19-20 (2).jar                  | None                                     |
	| LCHI  | fluxnetworks                      | 3.0.19               | fluxnetworks-1.12.2-3.0.19-21 (1).jar               | None                                     |
	| LCHI  | furnaceoverhaul                   | 1.0.3                | Furnace-Overhaul-Mod-1.12.2.jar                     | None                                     |
	| LCHI  | headcrumbs                        | 2.0.4                | Headcrumbs-1.12.2-2.0.5.17.jar                      | None                                     |
	| LCHI  | hopperducts                       | 1.5                  | Hopper-Ducts-Mod-1.12.jar                           | None                                     |
	| LCHI  | immersiveengineering              | 0.12-88              | ImmersiveEngineering-0.12-88.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHI  | immersivepetroleum                | 1.1.3                | Immersive-Petroleum-Mod-1.12.2.jar                  | None                                     |
	| LCHI  | immersivetech                     | 1.3.5                | Immersive-Tech-Mod-1.12.2.jar                       | None                                     |
	| LCHI  | trackapi                          | 1.1                  | Track-API-1.12.2.jar                                | None                                     |
	| LCHI  | immersiverailroading              | 1.7.0                | ImmersiveRailroading-1.7.0_1.12.2 (1).jar           | None                                     |
	_**_| LCHE  | universalmodcore                  | 1.0.0                | ImmersiveRailroading-1.7.0_1.12.2 (1).jar           | None                                     |_**_
	| LCH   | ironchest                         | 1.12.2-7.0.46.831    | Iron-Chests-Mod-1.12.2.jar                          | None                                     |
	| LCH   | ironjetpacks                      | 1.0.5                | Iron-Jetpacks-Mod-1.12.2.jar                        | None                                     |
	| LCH   | jrftl                             | 1.1                  | Just-Another-Rotten-Flesh-to-Leather-Mod-1.12.2.jar | None                                     |
	| LCH   | justenoughbuttons                 | 1.12-1.2.1           | Just-Enough-Buttons-Mod-1.12.1.jar                  | None                                     |
	| LCH   | keepinginventory                  | 2.4                  | KeepingInventory-1.12.2-2.4.jar                     | None                                     |
	| LCH   | longfallboots                     | 1.2.1a               | longfallboots-1.2.1b.jar                            | None                                     |
	| LCH   | lootbags                          | 2.5.8.5              | LootBags-1.12.2-2.5.8.5.jar                         | None                                     |
	| LCH   | loyaltymedals                     | 1.2                  | Loyalty-Medals-Mod-1.12.2.jar                       | None                                     |
	| LCH   | malisiscore                       | 1.12.2-6.4.0         | MalisisCore-1.12.2.jar                              | None                                     |
	| LCH   | malisisdoors                      | 1.12.2-7.3.0         | MalisisDoors-Mod-1.12.2.jar                         | None                                     |
	| LCH   | mantle                            | 1.12-1.3.2.24        | Mantle-Mod-1.12.2.jar                               | None                                     |
	| LCH   | mob_grinding_utils                | 0.3.13               | MobGrindingUtils-0.3.13.jar                         | None                                     |
	| LCH   | morefurnaces                      | 1.10.5               | MoreFurnaces-1.12.2-1.10.6.jar                      | None                                     |
	| LCH   | mysticalagriculture               | 1.6.7                | Mystical-Agriculture-Mod-1.12.1.jar                 | None                                     |
	| LCH   | mysticalagradditions              | 1.2.7                | Mystical-Agradditions-Mod-1.12.2.jar                | None                                     |
	| LCH   | mystagradcompat                   | 1.2                  | MystAgrad-Cloche-Compat-Mod-1.12.2.jar              | None                                     |
	| LCH   | openablewindows                   | 0.0.1                | Openable-Windows-Mod-1.12.2.jar                     | None                                     |
	| LCH   | elevatorid                        | 1.3.5                | OpenBlocks-Elevator-Mod-1.12.2.jar                  | None                                     |
	| LCH   | oreberries                        | 0.5.0                | oreberries-1.12.x-0.5.0.jar                         | None                                     |
	| LCH   | placebo                           | 1.4.1                | Placebo-1.12.2.jar                                  | None                                     |
	| LCH   | projecte                          | 1.12-PE1.1.0         | ProjectE-Mod-1.12.1.jar                             | None                                     |
	| LCH   | ptrmodellib                       | 1.0.3                | PTRLib-1.0.3.jar                                    | None                                     |
	| LCH   | rangedpumps                       | 0.5                  | Ranged-Pumps-Mod-1.12.jar                           | None                                     |
	| LCH   | reborncore                        | 3.12.1.385           | RebornCore-1.12.2-3.12.1.385-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | rebornstorage                     | 1.0.0                | RebornStorage-1.12.2-3.3.2.79.jar                   | None                                     |
	| LCH   | redstonepaste                     | 1.7.5                | Redstone-Paste-Mod-1.12.1.jar                       | None                                     |
	| LCH   | respawnablepets                   | 1.0.3                | Respawnable-Pets-Mod-1.12.2.jar                     | None                                     |
	| LCH   | roguelike                         | 1.7.2                | Roguelike-Dungeons-Mod-1.12.2.jar                   | None                                     |
	| LCH   | roost                             | 1.2.0                | Roost-Mod-1.12.2.jar                                | None                                     |
	| LCH   | silentlib                         | 3.0.9                | SilentLib-1.12.2-3.0.9-159.jar                      | None                                     |
	| LCH   | simplemagnet                      | 1.12.0-1.2.6         | Simple-Magnet-Mod-1.12.2.jar                        | None                                     |
	| LCH   | solarflux                         | 4.21r                | SolarFluxReborn_1.12.2-4.21r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | spookycraft                       | 1.0.1                | SpookyCraft-Mod-1.12.2.jar                          | None                                     |
	| LCH   | storagedrawers                    | 1.12-5.2.5           | StorageDrawers-1.12.2-5.3.5.jar                     | None                                     |
	| LCH   | lostcities                        | 1.0.1                | The-Lost-Cities-Mod-1.12.1.jar                      | None                                     |
	| LCH   | thutcore                          | 5.19.9               | thutcore-1.12.2-5.19.9.jar                          | None                                     |
	| LCH   | thutcore_compat                   | 1.0                  | thutcore-1.12.2-5.19.9.jar                          | None                                     |
	| LCH   | thuttech                          | 6.1.5                | thuttech-1.12.2-6.1.5.jar                           | None                                     |
	| LCH   | tinymobfarm                       | 1.0.5                | TinyMobFarm-1.12.2-1.0.5.jar                        | None                                     |
	| LCH   | torchbandolier                    | 0.1.1                | Torch-Bandolier-Mod-1.12.2.jar                      | None                                     |
	| LCH   | torchmaster                       | 1.7.1.74             | torchmaster_1.12.2-1.7.1.74.jar                     | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCH   | bspkrscore                        | at_0.9               | TreeCapitator-Mod-1.12.jar                          | None                                     |
	| LCH   | treecapitator                     | at_0.9               | TreeCapitator-Mod-1.12.jar                          | None                                     |
	| LCH   | treechopper                       | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                        | None                                     |
	| LCH   | universalremote                   | 1.12-0.9.10          | UniversalRemote-1.12-0.9.10.jar                     | None                                     |
	| LCH   | vanilladeathchest                 | 1.12.2-1.5.0.0       | Vanilla-Death-Chest-Mod-1.12.2.jar                  | None                                     |
	| LCH   | veinminer                         | 0.38.2               | VeinMiner-1.12-0.38.2.647+b31535a.jar               | None                                     |
	| LCH   | veinminermodsupport               | 0.38.2               | VeinMiner-1.12-0.38.2.647+b31535a.jar               | None                                     |
	| LCH   | wanionlib                         | 1.12.2-2.2           | WanionLib-1.12.2-2.2.jar                            | None                                     |
	| LCH   | waterstrainer                     | 3.2.0                | WaterStrainer-1.12-3.2.0.jar                        | None                                     |
	| LCH   | waystones                         | 4.0.67               | Waystones_1.12.2-4.0.67.jar                         | None                                     |
	| LCH   | weirdinggadget                    | 1.0                  | Weirding-Gadget-Mod-1.12.2.jar                      | None                                     |
	| LCH   | wolfarmor                         | 1.12.2-2.1.0-RELEASE | Wolf-Armor-Storage-Mod-1.12.2.jar                   | None                                     |
	| LCH   | xaerominimap                      | 1.15.8               | Xaeros-Minimap-Mod-1.12.jar                         | None                                     |
	| LCH   | pipemaster                        | 1.0.2                | PipeMaster-1.0.2-b8.jar                             | None                                     |

	Loaded coremods (and transformers): 
BringMeTheRings plugin (Bring-Me-The-Rings-Mod-1.12.2.jar)
  zabi.minecraft.bmtr.core.BaublesTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  net.fybertech.nwr.NWRTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  c4.colytra.asm.ElytraTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
CraftDevLoadingPlugin (CraftDev-Core-1.12.2.jar)
  core.upcraftlp.craftdev.asm.CraftDevClassTransformer
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.12.1.385
		Runtime Debofucsation 1
		RenderEngine: 1
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by andrboot** [comment]
This is a memory issue, increase your allocation to Minecraft, 2GB isn't enough, you need at  least 4-6GB.
' Caused by: java.lang.OutOfMemoryError: Java heap space'

**Comment by zues3000** [comment]
how would i fix it so i can play on 4-6GB?

**Comment by andrboot** [comment]
Change your launcher options, instead of 2GB go to 4GB or 6GB.
