### ISSUE TITLE
crash when loading world

### ISSUE THREAD

**Issue by moscontheroad** [TeamOpenIndustry/ImmersiveRailroading#676]
Hi, my game crashes when loading my world with the newest version.
I have 12GB assigned to Minecraft, deleted IR and Track API, flew over all areas where I had IR stuff, updated the mod and still crashes.

What else can I do to play with the latest version?

[crash-2019-11-10_21.52.05-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3829642/crash-2019-11-10_21.52.05-server.txt)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3829644/latest.log)

**Comment by andrboot** [comment]
Remove the traffic-control mod / railstuff mod/s, they aren't updated to latest IR currently.

**Comment by moscontheroad** [comment]
Thanks for the quick reply, the game now crashes after the world loading screen and actually loading the world, I'll try to figure out if it is still IR causing the crash or any other mod.
