### ISSUE TITLE
Can't mount to any type of train

### ISSUE THREAD

**Issue by whatsapp2** [TeamOpenIndustry/ImmersiveRailroading#677]
**Version:**
     ImmersiveRailroading-1.7.0_1.7.10

**Bug Description:**
     When I right click a vehicle (cars, trains) to mount it, the GUI doesn't appear and you can move    
     freely around your world as if have never clicked the vehicle. When "dismounting", you are 
     teleported to the location where you right clicked the vehicle. 

**System Information:**  
 OS: macOS Catalina version 10.15.1
 <br>System Memory: 16 GB
 <br>Allocated Memory: 8192MB
 <br>CPU: 3.6 GHz Intel Core i7 
 <br>GPU: Radeon Pro 560 4 GB
 <br>IR-Version: 1.7.0_1.7.10
 <br>Forge-Version: 1.7.10 - 10.13.4.1614

**Modlist:**  
https://pastebin.com/WDLnRXR5
 
**latest.log**
https://pastebin.com/8JmuKqJc

**Comment by cam72cam** [comment]
@whatsapp2 is there a link to your pack or is it custom?  I'd like to try your pack with a IR version with debug turned on

**Comment by whatsapp2** [comment]
It's a custom mudpack, but I can provide you a Dropbox link with the mods I use
https://www.dropbox.com/sh/ji4yt5l24mvfl1c/AAA0OyoWK8tqgcYQhLw3_Wcra?dl=0

**Comment by cam72cam** [comment]
I can confirm this is an issue.  Would you mind taking the time to go down to only IR and adding in a few mods at a time to see which one is causing the conflict?

**Comment by whatsapp2** [comment]
I was testing a few mods until I discovered it was the mod called "BetterSprinting++MC-1.7.10++v1.1.3.jar" causing the bug; which is kind of weird, considering this mod is to speed the creative flight up to 8 times more

**Comment by km00700** [comment]
Makes a lot of sense, actually. Both mods affect player movement. It's likely that IR is moving the player but the last player location cached by betterSprinting isn't updated when the train move the player, so it snaps them back.
