### ISSUE TITLE
Client crashes when rendering mod assets.

### ISSUE THREAD

**Issue by 1Pawelgo** [TeamOpenIndustry/ImmersiveRailroading#679]
I'm running a private sponge forge server and I've just updated your mod and Track API to the newest version. However, whenever a pleyer gets close to our railway system it's game crashes.
The crash doesn't happen everytime and players can interact with some blocks/items. I think it's caused by rendering two overlapping railroad switches, but I'm not sure.
It's a client-side crash and I can't see anything in server console, exept that Track API is named universalmodcore now.
I was able to fix the crash by reverting to version 1.5.0_1.12-402 of ImmersiveRailroading and 1.1_1.12 of Track API. After reverting I ran into another crash, but I managed to fix it by removing all entities with mcedit.

Here's clien's crash report uploaded by VanillaFix:

 https://paste.dimdev.org/xuyosiqiqu.mccrash

Here's client's log:

 https://paste.dimdev.org/genihuyeru.md

Here's server's log (edited for convenience):

 https://paste.dimdev.org/avifowuquv.sql

**Comment by cam72cam** [comment]
Reverting to older versions is not supported with IR, I made some non-back-compatible changes.

It's an interesting crash.  It looks like the server is sending the update packet without some information.  I am taking a deeper look into it now

**Comment by cam72cam** [comment]
Give https://drive.google.com/open?id=1pw2Bfo7SafCR3QLf-5lYfZtehFTx8vJL a try client side.  It adds a bunch of logging to that error case.

I did not test with spongeforge so there will probably be a few other fun things we'll have to iterate on.

**Comment by 1Pawelgo** [comment]
I'm testing the file that you have provided.

**Comment by 1Pawelgo** [comment]
Here's the log:

https://paste.dimdev.org/covamiyaqi.md

**Comment by cam72cam** [comment]
Ok, the crash should be fixed with: https://drive.google.com/open?id=1fBEW5O0RYSHuHoDefhnjTl6ISz0r7BOJ

Give that a try

**Comment by 1Pawelgo** [comment]
I confirm, crash no longer occurs with this file. Thank you for resolving the issue.

**Comment by cam72cam** [comment]
excellent.  The latest stable version should include that fix (1.7.1) if you want to upgrade.
