### ISSUE TITLE
Black rolling stock when turning around in railyard.

### ISSUE THREAD

**Issue by CyaNox** [TeamOpenIndustry/ImmersiveRailroading#680]
The new texture unloading causes a lot of my rolling stock to go black each time I turn around which in turn makes my frames go poopy when it is loading the textures ...

Could we have an option to keep the textures in memory?

**Comment by cam72cam** [comment]
Yes, I can add a config option to change how long stuff is kept in memory.  I'll add that to the list for 1.7.1

**Comment by CyaNox** [comment]
Thank you works great ... even when set to something like 86400 (a day).

**Comment by cam72cam** [comment]
The lower you put it the less GPU memory you will use on average.  86400 is NOT recommended

**Comment by CyaNox** [comment]
I wish this was true. The design behind the unloading of GPU resources is a nice idea but on my system (somewhat slow disk IO and average memory speed) the constant loading and unloading cause a large number of pauses of more than 250ms making playing nearly impossible. Setting it to the inadvisable number of 86400 does strain VRAM but at least it is much much smoother. I'd rather have a smooth 15FPS over a very stuttery slideshow.

Now I do realize that this is my test world where I have all the rolling stock placed down usually you only have a few different types of rolling stock around. However this is not that uncommon on the server I play on. Many people have a large number of rolling stock out in the open for display and use.

I essentially test with a worst case scenario situation.
