### ISSUE TITLE
Track exchanger ability to alter railbed.

### ISSUE THREAD

**Issue by NoxyNixie** [TeamOpenIndustry/ImmersiveRailroading#682]
As much of a cool tool the exchanger is it lack the ability to alter the rail-bed. Since there are many more choices in rail-bed over actual tracks I think it would be very useful if the track exchanger could change the rail-beds too.

**Comment by FriedrichLP** [comment]
That’s a great idea and I totally forgot about that possibility. I’ll implement this as soon as possible

**Comment by cam72cam** [comment]
work has been done

**Comment by NoxyNixie** [comment]
Awesome!
