### ISSUE TITLE
Inventory issues with Crayfish Gun Mod

### ISSUE THREAD

**Issue by cam72cam** [TeamOpenIndustry/ImmersiveRailroading#683]
Jensran Just did a test with IR. The "MrCrayfish Gun mod" Does not work with IR. It causes issues with loading coal/water/fuel in general into the GUI of the trains.
Jensran: 1.12.2 for MC version, and Gun Mod 0.15.2.

**Comment by pigs-fly** [comment]
I had this issue too, however after updating a few days ago I issue seems to have resolved. Can anyone else confirm this?

Currently running.
    ImmersiveRailroading-1.7.3_1.12.2.jar
    guns-0.15.3-1.12.2.jar

I seem to remember something in the last guns update was about GUI interactions, maybe that was the thorn?
