### ISSUE TITLE
Locomotive disappeared without a trace

### ISSUE THREAD

**Issue by NoxyNixie** [TeamOpenIndustry/ImmersiveRailroading#685]
**Describe the bug**  
My A1 Peppercorn locomotive disappeared without a trace while it was going around the top track of my oval. This was not long after I loaded the world and all I was doing was look at my performance numbers which were not as they used to be.

**How to reproduce**  
I loaded my world and this happened. No clue on what steps as I personally only looked around and admired the bad frames.
 
**Expected behavior**  
A1 Peppercorn locomotive to not disappear.

**Screenshots**  
![image](https://user-images.githubusercontent.com/211381/68677673-c648a080-055c-11ea-858d-4987883a0fef.png)
The A1 tender is still rolling on its momentum.

**System Information**  
OS: Windows
System Memory: 8GB
Allocated Memory: 4616 MB
CPU: AMD Phenom II X4 955 Black 3.2Ghz
GPU: AMD Radeon HD 6670 1GB
IR-Version: 1.7.1_1.12.2
Forge-Version:  14.23.5.2847

**Modlist**  
https://paste.dimdev.org/oqugigogun.txt
 
**latest.log**
https://paste.dimdev.org/fakehifuwe.log

**Additional context**  
The save file I loaded: http://cyanox.nl/a-ir_1.7.1_bug.zip .
This is a save from before I updated to 1.7.1. If loaded this should be roughly the same. This is a test world and may need the entire pack with configs to be loaded so here: http://cyanox.nl/a-ir_1.7.1_bug_pack.zip .

There are a few things I noticed in the log when loading the world (line `4351` and beyond):

**1:**
```
[14:46:03] [Server thread/WARN] [FML]: The mod immersiverailroading has registered persistent chunkloading data but doesn't seem to want to be called back with it - it will be removed from the world save
```
This worries me as incorrect chunkloading and unloading has been a major issue in the past for me when maintaining servers.

**2:**
```
[14:50:55] [Server thread/WARN] [universalmodcore]: Coupled entity was not loaded after 20 ticks, decoupling
[14:50:55] [Server thread/INFO] [universalmodcore]: f6c598c4-a187-4640-92ea-fc703a239a00 decouple Front
```
I think this is where the locomotive was discovered "gone" but no errors or indications as to why it was gone just before it.

**Comment by neronakoma** [comment]
coupled entities is simply saying that after so many ticks, the object would not regester that it was connected to a train. however if the mod refused to load an item, i can see why you have the item disappearing. i will pass this on to the others and see if they can come up with a fix

**Comment by andrboot** [comment]
@NoxyNixie upgrade IR please, new version forces chunkloading on non-moving stock which may help your issue.
