### ISSUE TITLE
Train Inventory Icons Invisible

### ISSUE THREAD

**Issue by FangeHaux** [TeamOpenIndustry/ImmersiveRailroading#687]

**Comment by cam72cam** [comment]
Please provide more information.

**Comment by FangeHaux** [comment]
The icons in creative mode inventory displayes the locomotives, stock and
passenger car icons as solid grey or white. The tools icons eg track
blueprint displays correctly. The icons are supposed to be displayed as the
model of the train. It's impossible to see what train ur picking and it
looks invisible in your inventory hotbar. It only displays the name when u
hover the mouse over it.

**Comment by cam72cam** [comment]
Please post what MC version, what IR version, and what other mods you have installed.

Thanks
