### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by Nachtflame** [TeamOpenIndustry/ImmersiveRailroading#688]
Recipes for Blueprint Book, Track Blueprint, Large Wrench, & Coupling Hook are not present in Forge 1.14.4 version.  
Do no appear in JEI at all; attempted to craft as per wiki with both Iron & Steel ingots, no results.

ImmersiveRailroading-1.7.1_1.14.4 [forge]

[Adding custom recipes via data-pack works fine]
[[Confirmed that no tools have native recipes in 1.14.4 version]]

**Comment by Nachtflame** [comment]
I've made a simple data-pack of recipes for Large Wrench, Coupling Hook, Blueprint Book, Track Blueprint, and Conductors Whistle. Main recipe set from {"tag": "forge:ingots/steel"}, and the _alt set from {"item": "minecraft:iron_block"}, set as per the pictures on the Wiki.  Judging from internal structure of your mod.jar, you should be able to drop the *data* folder contained within this .zip into your .jar/{root}, adjacent to the pack.mcmeta, and it would register the recipes.
:)
[IR_Recipe_DP.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3848949/IR_Recipe_DP.zip)

**Comment by cam72cam** [comment]
yeah, my goal is to add them dynamically in code.  We'll see how well that works.

**Comment by Nachtflame** [comment]
Just realize my own derpage there.  Of course the DP I built would only work for 1.14+.  🙄 🤣

**Comment by GameBurrow** [comment]
Why is this closed, this bug still exists :(
