### ISSUE TITLE
Crashing - Due to Track updates(?)

### ISSUE THREAD

**Issue by Nachtflame** [TeamOpenIndustry/ImmersiveRailroading#689]
Having an issue that I can't seem to pin down, other than related to tracks  Basically causing server to Watchdog when specific area (presumably with tracks/machines) becomes loaded.
1.14.4 Dedicated Server 
forge-28.1.87
IR 1.7.1
TrackAPI 1.2

https://pastebin.com/ct2LnMAz

**Comment by LokeYourLord** [comment]
I think I have a similar issue with #694 , maybe our issues are related.

**Comment by cam72cam** [comment]
This is it's own issue

**Comment by cam72cam** [comment]
This is a forge issue.  I test on 28.1.38 or you could try upgrading to the latest
