### ISSUE TITLE
SteamHammer place/form not recognizing Pistons

### ISSUE THREAD

**Issue by Nachtflame** [TeamOpenIndustry/ImmersiveRailroading#690]
**Describe the bug**  
When attempting to place SteamHammer with Manual, Pistions are not recognized

**How to reproduce**  
Collect 14x Block of Iron + Piston + Manual
Attempt to use manual to place Steam Hammer structure
Get told 'Missing 1x Piston!'

Even with Piston manually placed, Wrench fails to form Steam Hammer

MC 1.14.4
forge-28.1.87
IR 1.7.1
TrackAPI 1.2

**Additional context**  
Placement/Formation worked in 1.7.0, but had issue there with improper breaking code.

**Comment by andrboot** [comment]
What version of Minecraft?

**Comment by Nachtflame** [comment]
updated to include that (I'd thought It obvious with the Forge version.)

**Comment by cam72cam** [comment]
Pushing a fix for the upcoming version

**Comment by Nachtflame** [comment]
Actually, tried again after updating to IR 1.7.2. Still not working for us.

**Comment by BobbyMcJoe** [comment]
Yes, this is kind of a necro-post, but I'm running that version and am wondering what mods you have in that?
