### ISSUE TITLE
Hovering over an augment crashes the internal server

### ISSUE THREAD

**Issue by Yousei9** [TeamOpenIndustry/ImmersiveRailroading#691]
Version: IR 1.7.1
Custom Modpack (with working IR 1.6.1): https://drive.google.com/open?id=1BPxiiGix1rZoxCrHa8zgzmtVT1ltjKu4

I'm reliably crashing the internal server whenever I hold shift and hover over an augment.
I swapped shift and ctrl so it might be ctrl - mouse over for you.

[2019-11-18-3.log.gz](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3859038/2019-11-18-3.log.gz)

**Comment by neronakoma** [comment]
I would suggest switching to IR1.7.1 now that it is out. Also CTL is used as a secondary function for many mods. You may be having a conflict with mod config and controls due to your crouch button being changed

**Comment by Yousei9** [comment]
This bug is what's keeping me from upgrading to 1.7.1.

With 1.6.1 there are no problems. Nothing else changed.

**Comment by cam72cam** [comment]
@Yousei9 There's no error in that logs.  Can you try to find the right log file?

**Comment by Yousei9** [comment]
Are those the reports you want?
[crash-report.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3875571/crash-report.zip)
[logs.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3875573/logs.zip)

**Comment by cam72cam** [comment]
Ok, this is fixed in the latest build which will be released tonight
