### ISSUE TITLE
Train moves forward but player doesn't (But Teleports upon Unmounting)

### ISSUE THREAD

**Issue by LokeYourLord** [TeamOpenIndustry/ImmersiveRailroading#692]
**Describe the bug**  
So the issue is funny: If I want to drive with the Train forwards (or backwards, doesn't matter which direction), then the Train itself moves forward, however the player stays at the same spot he mounted himself at. However, if the Train moves forward and gets stopped (breaks, slowing down, etc) or continues driving, if the player unmounts at the location the Train is currently at, the player will be immediately teleported where the Train is currently at. So the issue is, that technically the player moves along with the Train, but isn't able to see the ride and be moved by it before the player unmounts from the Train.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

1: Enter Train
2: Move Train in any direction
3: The Train will drive without you
4: Unmount from Train when it is at a new position, you will be teleported to where the Train is now
5: Profit?
 
**Expected behavior**  
Well, obviously I am supposed to move along with the Train :P

**Screenshots**  
1: Me in the Train, perfectly mounted and everything looking fine.
![2019-11-19_15 19 00](https://user-images.githubusercontent.com/5807595/69121645-35d00a00-0ae0-11ea-8076-d52fea83b889.png)
2: The Train has moved on without me, however I can still control it as I am technically still inside it, just not moving along with the Train itself.
![2019-11-19_15 19 57](https://user-images.githubusercontent.com/5807595/69121696-4d0ef780-0ae0-11ea-951b-70caf34ac751.png)
3: I have now stopped the Train about 30-40 blocks ahead of the starting point and unmounted myself from the Train, I got teleported next to it where I should have unmounted if I would have moved along with the Train aswell.
![2019-11-19_15 20 10](https://user-images.githubusercontent.com/5807595/69121776-74fe5b00-0ae0-11ea-91a1-fc43a3a2f320.png)

**System Information**  
 OS: Windows 10 Pro - 1903
 <br>System Memory: 16GB
 <br>Allocated Memory: 8GB
 <br>CPU: Intel i5 8300H @3.8GHz
 <br>GPU: NVIDIA GTX 1050Ti
 <br>IR-Version: 1.7.1 - 1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2847

**Modlist**  
https://pastebin.com/wCkPJqpy
 
**latest.log**
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3862268/latest.log)

**Additional context**  
Nothing additional that I can come up with, I just remember not having had this bug with many more mods (about half a year ago) and with an older version of IR. I have cut down from about 200 mods down to 155, updated all these mods and added the newest version of IR, since then this bug has occurred.

**Comment by km00700** [comment]
You're using sponge, right? That breaks IR in really bad ways.

**Comment by km00700** [comment]
One of which is leaving the player behind when driving trains.

**Comment by LokeYourLord** [comment]
Well yeah but it did work fine like I said quite a while ago, but yes I am using Sponge because I have to (server reasons and a mod that needs Mixin so it also has to be installed on the client). Is there any fix for this?

**Comment by km00700** [comment]
No. Sponge modifies some base code directly so IR is incompatible.

**Comment by LokeYourLord** [comment]
Well I have not updated my Sponge version on the client that I used about half a year ago, I have only updated IR so that means IR broke on the way and not Sponge. I mean, should I seriously disable my entire server setup? I mean is there no config option or the likes in Sponge or IR that can be enabled/disabled that fixes this? Again, this was not an issue before I updated IR so yeah.

**Comment by km00700** [comment]
No, IR switched how we hook into base MC (2/3 of all the code is redone)

**Comment by km00700** [comment]
And the best method performance wise in the new version uses some stuff sponge had modified.

**Comment by LokeYourLord** [comment]
Do you think a new version of Sponge may work? As I am using an outdated version, maybe that is the issue?

**Comment by km00700** [comment]
Probably not

**Comment by LokeYourLord** [comment]
Well that's just great, the usual "my project is perfect, it's the other mod developers doing wrong". This is why mods will never be 100% compatible with each other, great...

**Comment by km00700** [comment]
It's not the usual my project is perfect. It's a compromise we made so that a majority of players would benefit.

**Comment by LokeYourLord** [comment]
But then what is about all the servers? Sponge is now the major platform for servers and managing them :/

**Comment by LokeYourLord** [comment]
> 
> 
> But then what about all the servers? Sponge is now the major platform for servers and managing them :/

I mean, would it be possible for Sponge to fix the issue then, and if so, what would they need to do?

**Comment by LokeYourLord** [comment]
Well nevermind, Sponge DID fix this issue in their latest recommended version, so the issue is now actually solved.

**Comment by km00700** [comment]
good to know.

**Comment by LokeYourLord** [comment]
Latest recommended version of SpongeForge, version "1.12.2-2838-7.1.7". Could be a version before it as well, but that is the version I currently use which works fine with IR, I only had crashes due to the mod "Random Patches", so that mod does not work with SpongeForge.

**Comment by LokeYourLord** [comment]
Oh and btw, before I open another issue tracker, I wanted to show you this crash that I just received (I guess it's a fairly normal crash, I had it a while ago aswell): https://pastebin.com/S6TbyEEb
