### ISSUE TITLE
Add in Multi Point Switches

### ISSUE THREAD

**Issue by PyroskeGaming** [TeamOpenIndustry/ImmersiveRailroading#693]
**Describe the suggestion**  
Currently you can use the golden spike to right click and set 1 side of the point to a location, if you could shift click which would change the length to a custom curve / spot as well.

**Applications of the suggestion**  
Would allow for more variety when doing switches and allow for greater track design and to make tracks simpler and compact.
![2019-11-17_19 25 25](https://user-images.githubusercontent.com/57936269/69124340-c239f700-0af7-11ea-875a-40e46eac37b1.png)

**Comment by cam72cam** [comment]
Closing as won't fix.  You can do similar stuff (esp in the new test build) but it's way too much work to do right.
