### ISSUE TITLE
Crash: Exception ticking world

### ISSUE THREAD

**Issue by LokeYourLord** [TeamOpenIndustry/ImmersiveRailroading#694]
So I am getting this crash on the server (and client) whenever I try to do something with Rails. For the most part it's all fine, but sometimes breaking Rails, placing them or even just driving a Train across them causes the server (or game if playing SSP) to crash.

Here is the crashlog:
https://pastebin.com/xybhhMEW

IR version: 1.12.2-1.7.1
Minecraft version: 1.12.2

Thanks for the help :)

**Comment by neronakoma** [comment]
forwarded

**Comment by cam72cam** [comment]
@LokeYourLord give https://drive.google.com/open?id=19Xv2H1Rahq8a9sEaalHjqsDiETRMP5hx a try.  I believe that fixes your issue

**Comment by LokeYourLord** [comment]
> 
> 
> @LokeYourLord give https://drive.google.com/open?id=19Xv2H1Rahq8a9sEaalHjqsDiETRMP5hx a try. I believe that fixes your issue

Yes sir, will do :)

**Comment by LokeYourLord** [comment]
@cam72cam Alright, so after a while without crashes I thought the issue had been solved, but just as I was about to destroy a track I had wrongfully placed (sideways into a straight track), the game crashed, with this log: https://pastebin.com/URsg8Beq

I thought you also might want the debug.log , so here it is:
[debug.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3875194/debug.log)

Best of luck :)!

**Comment by cam72cam** [comment]
I've fixed this in the latest build and will be pushing it tonight

**Comment by LokeYourLord** [comment]
Indeed, you did fix the issue. I loaded into a world that crashed everytime upon loading due to this issue, but this time it loaded fine and I could properly delete the Track.

Thanks a lot :D!

**Comment by bobodoustaud** [comment]
happened to me too, thanks for fixing it !
