### ISSUE TITLE
ir_augments missing in OpenComputers 

### ISSUE THREAD

**Issue by Yousei9** [TeamOpenIndustry/ImmersiveRailroading#700]
With IR 1.7.2 OpenComputers 1.7.5.192 or 1.7.4.153 no longer provide ir_augment_detector and ir_augment_control.
I didn't test if it's generally a bug of 1.7.x or specifically 1.7.2

**Expected behavior**  
Existing component.ir_augment_detector and component.ir_augment_control

**Comment by andrboot** [comment]
They Exist and function, i can confirm on my pack.
OC Events don't appear to work.
What version of forge / minecraft?

**Comment by Yousei9** [comment]
They don't exist for me
![2020-01-05_09 23 16](https://user-images.githubusercontent.com/8436934/71777211-16f8da80-2f9d-11ea-8fd8-906b60b48a03.png)

Can't comment on events if i cant even access the augments.

Forge 14.23.5.2847

**Comment by andrboot** [comment]
I take it you have the adapters wired into the computer via cables?
Are you on discord?

**Comment by Yousei9** [comment]
Yes, Optera#1522

**Comment by cam72cam** [comment]
@Yousei9 has this issue been fixed?

**Comment by Yousei9** [comment]
No.

**Comment by c0nnex** [comment]
Make sure you connect the adapter to the computer.
The augments are there, however the event "ir_train_overhead" does exists and is never raised. Looks like you have to endless oull the redstone signal.

**Comment by Yousei9** [comment]
> 
> 
> Make sure you connect the adapter to the computer.
> The augments are there, however the event "ir_train_overhead" does exists and is never raised. Looks like you have to endless oull the redstone signal.

Adapters should be connected.
I tried cables from OC and EnderIO, both worked before IR 1.7.
I rebuilt augment, adapter, cables in different order multiple times.

**Comment by andrboot** [comment]
I have encountered similar, tested in SP with both listen, and pull event isn't raised, augments are there though.

**Comment by c0nnex** [comment]
> I have encountered similar, tested in SP with both listen, and pull event isn't raised, augments are there though.

My bad, Typo. The event "```ir_train_overhead```" does **NOT** exist. 
I changed my script to use "```redstone_changed```" event and checking for the origin. Works like a charm

**Comment by c0nnex** [comment]
> > Make sure you connect the adapter to the computer.
> > The augments are there, however the event "ir_train_overhead" does exists and is never raised. Looks like you have to endless oull the redstone signal.
> 
> Adapters should be connected.
> I tried cables from OC and EnderIO, both worked before IR 1.7.
> I rebuilt augment, adapter, cables in different order multiple times.

Must be some other mod interfering.
Using same versions on my modded FTb relevation server works fine, apart from the missing events.

**Comment by andrboot** [comment]
@c0nnex if you try the latest git build, OC events are fixed :)  (you will need to restart OC computer after updating)
