### ISSUE TITLE
Cannot place a switch

### ISSUE THREAD

**Issue by HydrogenC** [TeamOpenIndustry/ImmersiveRailroading#702]
**Describe the bug**  
If I place a switch with the blueprint (in creative mode), the switch will break by itself immediately, I cannot even place a switch. Also, I have did this with the rail bed and rail bed fill set to brick block. I haven't test if it behaves correctly if I don't set the rail bed and rail bed fill. 

**How to reproduce**  
Steps to reproduce the unwanted behavior:
 1. Fetch a blueprint
 2. Set it to rail type switch and the rail bed to brick (or concrete)
 3. Place it in creative mode
 
**Expected behavior**  
 The rail should be placed down, but it breaks as soon as I place it. 

**Screenshots**  
None

**System Information**  
 OS: Windows
 <br>System Memory: 8gb
 <br>Allocated Memory: 4200mb
 <br>CPU: I7-8550U
 <br>GPU: MX150
 <br>IR-Version: 1.7.2_1.12.2
 <br>Forge-Version: 14.23.5.2847
 
**latest.log**
Nothing related to this bug in it. 

**Additional context**  
None

**Comment by whatsapp2** [comment]
This is a bug, but I know how to fix it.
Just simply expand 3 block the borders of the switch, make sure the switch is on a plain surface. Just look at this image, hope I can help you solving the bug :D 

![Fix Bug IR](https://user-images.githubusercontent.com/25994176/69506436-47f0e480-0ef4-11ea-8ec4-a80565ca0669.jpeg)

**Comment by ChlorineX** [comment]
> This is a bug, but I know how to fix it.
> Just simply expand 3 block the borders of the switch, make sure the switch is on a plain surface. Just look at this image, hope I can help you solving the bug :D
> 
> ![Fix Bug IR](https://user-images.githubusercontent.com/25994176/69506436-47f0e480-0ef4-11ea-8ec4-a80565ca0669.jpeg)

Thanks a lot! It works. But this bug will still make it inconvenient to build a railway in creative mode, wish it to be fixed soon.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
