### ISSUE TITLE
[Suggestion] Special blocks to ease making platforms

### ISSUE THREAD

**Issue by biauk** [TeamOpenIndustry/ImmersiveRailroading#703]
Making platforms is not problematic unless stock is more than 3 blocks wide. Special blocks would be solution for that. To allow different hights (0,5; 1; 1,5), there should be something like a vertical slab and half-slab. Also some a bit wider block would be helpful.

**Comment by cam72cam** [comment]
Cosmetic stuff like that is not planned for IR.  There are some addon mods that might be interested in adding that though

**Comment by biauk** [comment]
Can I have some links to mods adding cosmetic stuff?
