### ISSUE TITLE
Multi-block is not registered correctly for other mods

### ISSUE THREAD

**Issue by TheWerdOfRa** [TeamOpenIndustry/ImmersiveRailroading#705]
Thank you for your hard work on this fairly ambitious project.

I have a mod-pack with Carry On in it:
https://www.curseforge.com/minecraft/mc-mods/carry-on

Carry On uses the Shift+Click to pick up objects (chests, animals, etc), it does not pickup any blocks that the Immersive Railroading uses for it's multi-block structures though. However, when the multi-block structure is formed the Carry On can take the blocks from the multi-block. I've only had it happen when trying to use the casting machine, didn't try on the other machines because it causes a lot of grief I'd like to avoid. 

Once the block is "being carried" your character's inventory becomes corrupted. The machine is still "formed" and appears to be usable, but the player character is not able to interact with the world. The only way to resolve the issue is to die, load a backup, or wipe the player file from the server. If you break the multi-block with a pick axe you will notice the missing block from the structure (the one that was shift-clicked with Carry On and not the one you just mined). 

After I killed my character a phantom block that WAILA couldn't ID was left behind:
![2019-11-24_19 35 14](https://user-images.githubusercontent.com/17488364/69501815-6d83eb00-0f00-11ea-8127-c26d136b09c1.png)

Mining it out causes something of a TNT explosion, but amongst the remains was the missing block that was taken from the multi-block structure.

I tested this functionality out with other multi-block structures from other mods, such as Immersive Engineering and when their multi-block is formed this behaviour is not seen. This is the reason I brought this bug to your attention and not Carry On's. Please let me know if you need more information.

**Comment by TheWerdOfRa** [comment]
This also seems to occur with the track as well. I shift clicked with an open hand to get an item inserter back and it, instead, took the multi-block "block". Track was still formed correctly and appeared to not cause issues to the trains on it.

**Comment by cam72cam** [comment]
Ok this is 100% NOT supported

**Comment by TheWerdOfRa** [comment]
Thank you for your response.

I reported a bug and not a feature request, I'm not sure what you are advising is "NOT supported" because I did not request anything. To be clear, your multi-blocks SHOULD NOT interact with Carry-On and the fact that they do is why I created this ticket. It seems that there is something wrong with how the multi-block is registered/presented to Minecraft that could be causing this issue. Other mods with multi-block structures do not display this behaviour (allowing their component blocks to be interacted with as discrete blocks instead of one large structure).

I ask you to please have another look into this and feel free to ask me clarifying questions since it appears I didn't do a good job explaining the issue.

**Comment by cam72cam** [comment]
This is an issue with https://github.com/Tschipp/CarryOn

Create an issue over there saying that they should not interact with IR's stuff.

There's nothing I can do to block it on my side

**Comment by Tschipp** [comment]
I am going to blacklist it on CarryOn's side. There's no way for me to detect multiblocks, as there is no standardized way of doing them.

**Comment by cam72cam** [comment]
Thanks @Tschipp
