### ISSUE TITLE
Icons are bugging away

### ISSUE THREAD

**Issue by HavelKind** [TeamOpenIndustry/ImmersiveRailroading#707]
When I install addonpacks with more locos, the icons from all Locos are away.
And I have this problem since the older version of IR.

PC:
Ryzen 7 2700
16GB RAM
RX Vega 56
![Screenshot](https://user-images.githubusercontent.com/58188797/69571010-5953f280-0fc1-11ea-9356-9d41888f530d.png)

**Comment by neronakoma** [comment]
are you running it with 3D icons aactive?

**Comment by HavelKind** [comment]
Yes

**Comment by neronakoma** [comment]
if you go into your settings config for IR, you have the option to shut off 3D icons. if you turn it off it will show the icons without bugging out

**Comment by andrboot** [comment]
What version of IR? latest version has no icon option, renders it all differently.
