### ISSUE TITLE
Random crash when flying around in a world

### ISSUE THREAD

**Issue by Kehaan** [TeamOpenIndustry/ImmersiveRailroading#708]
Hey

I am not sure what causes this issue or how to recreate it. But i thought i would report it :)

[crash-2019-12-01_12.16.44-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3908126/crash-2019-12-01_12.16.44-client.txt)

It seems like it is from Immersive Railroading as it writes "cam72cam.mod.render".

- Kehaan

**Comment by cam72cam** [comment]
Dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/698
