### ISSUE TITLE
Linear Slopes for Custom Curves

### ISSUE THREAD

**Issue by bigyihsuan** [TeamOpenIndustry/ImmersiveRailroading#709]
**Describe the suggestion**  
As it currently is implemented, custom curves are defined as a cubic curve, using two intermediate points for both pitch and yaw.

This suggestion is about having those intermediate points being only used for yaw, with the pitch being defined linearly (as in the slope between the two endpoints). This would be a separate option from the current custom curve.

**Applications of the suggestion**  
Making an option for a custom curve with linear slope would allow for a more smooth slope between the endpoints. Currently, the cubic method leads to the endpoints being less steep than the middle, leading to a somewhat nonuniform appearance in, say, a parallel downward slope that has one track shift over 1 block. The options for this is either have the shift before or after the slope (may not be possible within a given space), or have the shift within the curve (leads to a custom curve interrupting the otherwise linear slope).

Another use would be a smooth helix, either going upwards or downwards. Using custom curves as it is currently leads to the track pitching up and down as you reach their endpoints. A smooth curve would make it seem like a single piece of track.

Building curved gradients on the side of mountains for example would not lead to locomotives being stuck/slowed down by the slope of the center of the custom curve being greater than the endpoints.

**Comment by Larky2k** [comment]
You do that already with Custom Curve

**Comment by km00700** [comment]
No you can't. The vertical component is still cubic.

**Comment by km00700** [comment]
He's proposing a slope which is linear in slope (ie dy/dt = constant) over the length of the segment, as opposed to a bezier curve in 3 dimensions.

**Comment by Larky2k** [comment]
So a normal slope then but you can choose length via golden spike

**Comment by km00700** [comment]
No, a full custom curve, except where slope is constant.

**Comment by Larky2k** [comment]
Ah so just a check to stop the slope from curving at the beginning and end so it's constant? Wasn't someone working on that anyway?

**Comment by bigyihsuan** [comment]
I've looked through the commits, forks, and branches, and can't seem to find anything regarding linear slopes for custom curves.
