### ISSUE TITLE
Concurrent Modification Crash

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [TeamOpenIndustry/ImmersiveRailroading#710]
Hello, After upgrading to the latest version (	ImmersiveRailroading-1.7.2), I keep getting a crash with this report: 
https://paste.dimdev.org/yofusatatu.mccrash

The suspected mods being UniversalCore and Immesrsive Railroading.  The crash seems to happen randomly, as sometimes it crashed right into loading into the world and other times after some time at play.

It should be worth noting that I havent even begun getting into Immersive Railroading, the most I have done is craft the book.

If its any help, I am playing on a very modified Enigmatica 2 Normal, version 1.69b

**Comment by andrboot** [comment]
Are you using an onboard GPU?

**Comment by ErnestoPeroPezzi** [comment]
No, I am not using a laptop, and my graphics card is an Nvidia GTX 1070

**Comment by cam72cam** [comment]
Some other mod is modifying `Minecraft.getMinecraft().world.loadedTileEntityList` in a different thread.  IR is accessing it on the main thread as should be the case.
