### ISSUE TITLE
Fluid unloaders not working

### ISSUE THREAD

**Issue by Railroadactive** [TeamOpenIndustry/ImmersiveRailroading#711]
After updating Immersive railroading to 1.7.2 in 1.12, my fluid unloaders have stopped working with the Kamx tankcars. I toggle them between unloading all stock and setting them back to the tank cars again but nothing worked

**Comment by andrboot** [comment]
What Pipe/Connectors are using?

**Comment by Railroadactive** [comment]
The Immersive engineering ones. Everything was working fine before updating Immersive Railroading

**Comment by whatsapp2** [comment]
Same issue with IR 1.7.2 for Minecraft 1.7.10. I tried using different pipes from different mods but any of them worked with the fluid unloader

**Comment by Carvercarver1** [comment]
Adding on that, apparently fluids are flowing somewhere. Either internal storage of the fluid unloaders , thus former just can't unload the fluid but gathers it in itself, or something else.

**Comment by andrboot** [comment]
You may need to pump it from/to?
I have confirmed working fine with Fluid-Ducts + servo's.

**Comment by Carvercarver1** [comment]
More like it does not really work as it should with IE pipes. Or anything.
It flows into the train, but does not unload the same way it did before. Unless you changed the direction and it should be put under the tracks (which I did, actually) or at the side.
