### ISSUE TITLE
Immersive Railroading 1.12.2 latest version error

### ISSUE THREAD

**Issue by Proffset728** [TeamOpenIndustry/ImmersiveRailroading#713]
Hello everytime i start the minecraft immerisve railroading throws this error provided in the picture if you need any more details let me know Best regards MGO
![error trainmod ](https://user-images.githubusercontent.com/26243999/71303467-807fc300-23b9-11ea-9071-04be51a67244.jpg)

**Comment by Larky2k** [comment]
Nothing to worry about that's normal

**Comment by Proffset728** [comment]
okey thanks :)
