### ISSUE TITLE
WorldEdit + ImmersiveRailroading

### ISSUE THREAD

**Issue by tomas-git-404** [TeamOpenIndustry/ImmersiveRailroading#714]
Hi,
Error ->
https://pastebin.com/bJ7hQ7v6

**Comment by km00700** [comment]
That's a side-effect of IR tracks requiring the block update when they're modified (which WE doesn't do) Best bet is to not WE too close to IR track. If the chunk is broken, you can remove the affected track using MCEdit

**Comment by tomas-git-404** [comment]
Well, thank you. @km00700
