### ISSUE TITLE
Camera isn't syncing with the trains and cannot enter the cars themselves. Any help would be appreciated

### ISSUE THREAD

**Issue by Tuck22222222222** [TeamOpenIndustry/ImmersiveRailroading#715]
Title says it all basically. when the trains move we don't move with them. And when we try and enter the cars we just climb up the side of them. Is there something we are missing?

**Comment by km00700** [comment]
Use sponge version 1.12.2-2838-7.1.7 if you're on 1.12.2.

**Comment by km00700** [comment]
also, you enter cars by right-clicking, not by walking in to them.
