### ISSUE TITLE
Server / Client Crash - Augment Loader Related

### ISSUE THREAD

**Issue by andrboot** [TeamOpenIndustry/ImmersiveRailroading#716]
See logged attached.
https://pastebin.com/2XECXdu3
Possible fix (quote by Cam)
https://github.com/TeamOpenIndustry/ImmersiveRailroading/blob/master/src/main/java/cam72cam/immersiverailroading/tile/TileMultiblock.java#L279
if (this.getMultiblock() != null && this.getMultiblock().getInvSize(offset) == 0) {

**Comment by andrboot** [comment]
Confirmed, same issue after trying that line change.

**Comment by cam72cam** [comment]
Missed the && vs ||

**Comment by andrboot** [comment]
https://flatworld.crafting.builders/crash-2020-01-13_18.34.50-server.txt
