### ISSUE TITLE
some locomotives can not be removed

### ISSUE THREAD

**Issue by Plutonium-236** [TeamOpenIndustry/ImmersiveRailroading#720]
**Describe the bug**  
A clear description of what the bug is.
some locomotives such as the handcar can not be destroyed/ removed from the tracks
**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. launch the game with immersive railroading 1.12 or 1.14
 2. spawn a handcar on the rails
 3. then try to punch it (also shift-clicking does nothing, shift-right clicking makes this appear in the log; [m[32m[17:59:17] [Client thread/INFO] [STDOUT/]: [cam72cam.mod.gui.GuiRegistry:lambda$registerEntityContainer$11:125]: PROBS SHOULD SEND PKT)
 
**Expected behavior**  
the cart will not dissapear

**Screenshots**  

**System Information**  
 OS: Windows
 <br>System Memory: [e.g. "8gb"]?
 <br>Allocated Memory: [The memory allocated to your Minecraft instance where you encountered the bug e.g. "4gb"]?
 Processor 
AMD Ryzen 7 1700 Eight-Core Processor 
 
Video Card 
Radeon(TM) RX 550 
 
RAM 
16 GB 
 
Operating System 
Windows 10 

 <br>IR-Version: just look in the mods.zip that i  put down below
 <br>Forge-Version: 1.14.4-forge-28.1.111

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.

[the mods i had in a zip (on dropbox because github cant handle it)](https://www.dropbox.com/s/ti939wphxm5ynan/mods.zip?dl=0)

**latest.log**

 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4024440/latest.log)

**Additional context**  
also sometimes i will destroy the cart but it seems to stay there,

**Comment by cam72cam** [comment]
So this only happens on forge 1.14?  Or does it happen on 1.12 like in your description?
