### ISSUE TITLE
[1.12.2] Server crash - immersiverailroading.track.TrackBase.placeTrack

### ISSUE THREAD

**Issue by ProsperCraft** [TeamOpenIndustry/ImmersiveRailroading#721]
Console stack trace- https://gist.github.com/ProsperCraft/402763cbf1ed537cd7e4531541ed3a54

Crash report- https://gist.github.com/ProsperCraft/7b7c424b138eb44b7e462d2e1e601e10

Full server log- 
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4033762/latest.log)

ImmersiveRailroading-1.7.2_1.12.2
Mohist-cdc8c79-server

**Comment by cam72cam** [comment]
I have no idea how this is possible, should be a fun one.

How often does this happen?

**Comment by cam72cam** [comment]
Ok, this is due to how farseek is wrapping the world.

I can program around it, but the fact that they wrap the block break event with their own world which does not support creating tile entities is the problem.

**Comment by ProsperCraft** [comment]
Does the strikethrough mean I shouldn't poke farseek about this?

**Comment by cam72cam** [comment]
Yeah, it means I was wrong.  I found a much worse bug deep in IR that commit fixes.
