### ISSUE TITLE
[1.12.2] Players are teleported from all over the world to trains on being placed.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamOpenIndustry/ImmersiveRailroading#722]
**Describe the bug**  
When stock is placed down - one specifically Big Boy 4014, players from all over the map, who have never been anywhere near that train are being teleported, if they don't have the resouce packs enabled they get kicked.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Place stock
 2. Players from all over the map even 8k away get teleported to the train.
 
**Expected behavior**  
 Place stock, nothing happens.

**System Information**  
 OS: Linux Centos 7 server.
 <br>IR-Version: ImmersiveRailroading-1.7.2_1.12.2
 <br>Forge-Version: 1.12.2  - Mohist-cdc8c79-server - Forge 2846

**Modlist**  
https://www.curseforge.com/minecraft/modpacks/towncraft
 
**latest.log**
too large to paste-
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4037186/latest.log)
[FP-Latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4037187/FP-Latest.log)

**Additional context**  
I found this that may be related - https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/453

**Comment by Linux-MissingNo** [comment]
I play on the same server as ProsperCraft's when we discover this issue. It seems to happen regardless of the train used. Rodger Ten-Wheeler, Bigger Boy, EMD SDmac90 from _Heavy Industrial_, Br01, and GE P42DC from _American Diesel_. When I placed GE P42DC, two AFK players teleported to my train. One was nearby while the another was thousand of blocks away.

**Comment by cam72cam** [comment]
This has to be a conflict with another mod in that list.  Could you try pairing the list down by setting up a temp server and adding mods a few at a time until it happens again?

**Comment by Avalkiz** [comment]
Hi I have the same problem. Mods I have installed in my pack:
CustomMainMenu
Immersive Engineering
Immersive Petroleum
Immersive Railroading
Immersive Tech
Forestry
Binnie’s Mods
Project RED
Zetta Industries
Extreme Reactors
Inventory Tweaks
Tinker’s Construct
Iron Chests
Wawla
Just Enough Items
Thermal Expansion
Thermal Dynamics
Storage Drawers
YABBA
Treecapitator
Nether Ores
Chickenchunks
Applied Energistics 2
Decocraft
Ender Storage
Journeymap

**Comment by ProsperCraft** [comment]
@Avalkiz This helps  a ton, here is the list of mods we have the same-
CustomMainMenu
Immersive Engineering
Immersive Petroleum
Immersive Railroading
Immersive Tech
Forestry
Binnie’s Mods

Zetta Industries
Inventory Tweaks
Just Enough Items
Thermal Expansion
Thermal Dynamics
Storage Drawers

Applied Energistics 2
Decocraft

Journeymap

**Comment by carfaces42** [comment]
I've been having a similar issue in my pack, I also share these with the rest of you:

baubles
Biomes 'o plenty
cooking for blockheads
corail tombstone
Immersive Engineering
Immersive Tech
Immersive Petroleum
Immersive Railroading
Industrial foregoing
Inventory tweaks
Just Enough Items
Morpheus
No Recipe book
Shadowfacts Forgelin
Tesla Core lib
track API
VanillaFix


    ones we defo all have:
    Immersive Engineering
    Immersive Petroleum
    Immersive Railroading
    Immersive Tech
    Inventory Tweaks
    Just Enough Items

**Comment by Avalkiz** [comment]
And also - I think it's not only when a train is being placed but also later, totally randomly even when the train is moving.

**Comment by ProsperCraft** [comment]
Please post your forge versions.

**Comment by ProsperCraft** [comment]
Mohist-2b0299e-server  - running 2846 - https://github.com/Mohist-Community/Mohist

**Comment by Avalkiz** [comment]
Magma-d83ece1

**Comment by ProsperCraft** [comment]
Would someone please take a second and see if it happens with only Immersive Railroading?

**Comment by cam72cam** [comment]
@ProsperCraft give https://github.com/TeamOpenIndustry/ImmersiveRailroading/suites/419935181/artifacts/1337127 a try on the server and turn on the UniversalModCore DebugLog option

**Comment by ProsperCraft** [comment]
Is this compatible with current release or did it version increment?

**Comment by cam72cam** [comment]
Should be directly compatible

**Comment by ProsperCraft** [comment]
Uploading now,does this have the client crash fix too we should test on our clients? or just the debug?

**Comment by cam72cam** [comment]
It has both if you want to drop it client side.

**Comment by andrboot** [comment]
Here is a copy of my latest log, with special debugging indicating the issue.
https://pastebin.com/7b9M4bV4

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
