### ISSUE TITLE
[1.12.2] - Erroring multiblock causes crash whenever a player gets near

### ISSUE THREAD

**Issue by Avalkiz** [TeamOpenIndustry/ImmersiveRailroading#725]
Hey. Server console suddenly started spewing out a lot of these:

[20:50:17] [Server thread/WARN] [universalmodcore]: Multiblock TE is null: BlockPos{x=352, y=69, z=-385} BlockPos{x=3, y=7, z=0} false class cam72cam.immersiverailroading.multiblock.CastingMultiblock$CastingInstance

When teleported there, there was this casting thing that had a texture but no complete hitbox. After destroying parts of it and a piece of pipe somewhere in the area the server crashed and now even after restart keeps crashing everytime anyone gets near.

Crash report:
https://pastebin.com/XPrW4B2v

**Comment by Avalkiz** [comment]
After attempting to remove that multiblock's entries from map with NBTexplorer to make the server playable again, immediately after server startup still one or two of these show up:
>[16:16:20 WARN]: Multiblock TE is null: BlockPos{x=352, y=69, z=-385} BlockPos{x=3, y=7, z=0} false class cam72cam.immersiverailroading.multiblock.CastingMultiblock$CastingInstance
(still on the same coords that I removed stuff from, but maybe I'm just dumb and did not succeed)
And immediately after that the server crashes.
Slightly different crash report
https://pastebin.com/j8ad29eq

**Comment by andrboot** [comment]
Ah, looks very similar to  #716 
Note, testing of that fix applied for #716  didn't resolve it possibly something else being oddball, or it is in a bad state.

**Comment by andrboot** [comment]
Just to give you more information @Avalkiz 
Building of current source will fix your issue, or at least identify  where you problem is occurring.

**Comment by cam72cam** [comment]
This will be fixed in the next release.  For now you can use the build from  https://github.com/TeamOpenIndustry/ImmersiveRailroading/suites/414190996/artifacts/1273019
