### ISSUE TITLE
[Feature Suggestion] Keybind assignment for using alternate sound for whistles/horns on locomotives.

### ISSUE THREAD

**Issue by Frosty-Nimiko** [TeamOpenIndustry/ImmersiveRailroading#726]
This feature would be the ability to use a separate key bind in conjunction with the normal "Horn" key bind to allow for use of a horn or a secondary whistle on a steam locomotive or a second horn on a diesel locomotive. 

It would improve the "immersion" of a few locomotives such as the NYCS' Niagara or a Southern Pacific's GS Class locomotive.

Use case scenario: Ridding along in the Niagara and then blowing the whistle, a player can't hear said whistle, use the horn instead and they hear it. But they die anyways because they were actually AFK.

**Comment by cam72cam** [comment]
Closing in favor of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1209
