### ISSUE TITLE
N-switch

### ISSUE THREAD

**Issue by Dushess** [TeamOpenIndustry/ImmersiveRailroading#727]
**Describe the suggestion**  
Double lines with single switch for both. It means fixed model and space between lines, probably better allow the nail to be placed INSIDE of 1st module endpoint. That way 2nd switch will be connected perfectly. (Curves in use, yeah)

**Applications of the suggestion**  
There is unable to make 2 switches and align it correctly. Also because nearby placed railways leaves no place for 2 endpoints facing each other.

**Comment by cam72cam** [comment]
Use the golden spike instead.  It's only a few clicks and you can find examples on the IR 1.5 release video

**Comment by Dushess** [comment]
Ok, will check.
