### ISSUE TITLE
Connection terminates every time a train item is being picked up

### ISSUE THREAD

**Issue by dennis-qt** [TeamOpenIndustry/ImmersiveRailroading#728]
Whenever someone picks up a train(not tested other items) on my server, the connection gets instantly terminated by the server and shows an error in the server log. After that, the player is unable to join again until the item despawns, is removed or moved away from the player so it's not getting picked up on join.

It's a 1.7.10 - 10.13.4.1614 forge server running IR 1.7.2_1.7.10 with 4GB of RAM allocated. The server is hosted on a headless Ubuntu machine with a Ryzen 5 3600 CPU and 16GB of RAM installed. No major software running in parallel.

In singleplayer picking up items works.

[error log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4093760/errorlog.txt)
[whole server log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4093759/fml-server-3.log)

**Comment by cam72cam** [comment]
This will be fixed in the next release
