### ISSUE TITLE
crash when saving world i guess

### ISSUE THREAD

**Issue by bobodoustaud** [TeamOpenIndustry/ImmersiveRailroading#732]
log : https://pastebin.com/skFm8fHa

after switching from V1.7.1 to V1.7.2, every times that the server was saving a chunk that was containing a bugged half-broken rail (the rail texture was disappearing but the rail blocs were still there as ghost blocks (walking on them was making the camera shaking)) the server was crashing.

**Comment by bobodoustaud** [comment]
crash report : https://pastebin.com/pExRSRJt

**Comment by bobodoustaud** [comment]
the first time the server have crashed, i have got a different crash report : https://pastebin.com/ubM1kY3g

**Comment by cam72cam** [comment]
Try setting remove erroring tile entities

**Comment by bobodoustaud** [comment]
still crashes


Le sam. 25 janv. 2020 à 15:19, Christian Mesh <notifications@github.com> a
écrit :

**Comment by cam72cam** [comment]
Can you remove that block using something like worldedit and try again?

**Comment by bobodoustaud** [comment]
with mcedit i could but i need to download the world file so it will take a while

**Comment by bobodoustaud** [comment]
fixed
