### ISSUE TITLE
Random crash when more players ride a train

### ISSUE THREAD

**Issue by Avalkiz** [TeamOpenIndustry/ImmersiveRailroading#733]
This magnificent 2000+ lines crash happened already quite a few times on both Magma and Mohist server engines I tried this on.

https://pastebin.com/cDEHAcTg

It's quite hard to reproduce, seems like it happens when more players are in the same train and possibly "walking" inside / changing cars / hopping on-off the train while it moves.

**Comment by cam72cam** [comment]
Will be fixed in the next release (later today)

**Comment by Avalkiz** [comment]
Holy chickens, that was fast. Thanks!
