### ISSUE TITLE
Casting basin does not drop item for fake user (mechanical user or robot)

### ISSUE THREAD

**Issue by ClaytonAstrom** [TeamOpenIndustry/ImmersiveRailroading#738]
ImmersiveRailroading-1.7.2_1.12.2
OpenComputers-MC1.12.2-1.7.5.192
extrautils2-1.12-1.9.9

Steps to reproduce:

1.  Set the casting basin to create Rail Casting (single or repeat)
2.  Place a mechanical user (Activate Block with Item, Right Click, Upper Left Slot Only) or a opencomputers robot (activate with `robot.use(sides.front)` if facing the basin)

Expected:
The rail casting is taken out when activated and exists...somewhere

Actual:
The rail casting is removed and does not exist.

**Comment by ThizThizzyDizzy** [comment]
Just a note:
Drones from PneumaticCraft: Repressurized cannot extract items either in the same manner (pneumaticcraft-repressurized-1.12.2-0.11.10-385)

This worked in ImmersiveRailroading-1.6.1_1.12-1138, where the item was dropped on the ground where it was clicked (with pneumaticcraft-repressurized-1.12.2-0.11.3-366)
