### ISSUE TITLE
Auxillary Tender functionallity. 

### ISSUE THREAD

**Issue by Sunozikio** [TeamOpenIndustry/ImmersiveRailroading#739]
The Aux tenders in the mod currently do not supply an engine's tender as it would in real life.

Any water in the aux tender will fill up the engine's tender when in use. Instead of just sitting there and having the player be forced to move it to the engine's tender, it could pull it directly.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
