### ISSUE TITLE
Client Render Crash Possible Bug?

### ISSUE THREAD

**Issue by reggie9235** [TeamOpenIndustry/ImmersiveRailroading#741]
Current Mod versions in use of IR:
ImmersiveRailroading-1.7.2_1.12.2
TrackAPI-1.2

Hello, think I've found a possible issue here.. I've loaded up a handful of mods and seem to have a rendering bug with immersive railroading or the track api while holding track in my hand while looking at the ground for the blueprint highlight to show you where the track will be placed etc..  Only way I've found to resolve this is to delete the my player data file to reload into the world to remove the items from my inventory. I've posted the most recent crash log for you all to look at hope to find an answer to this issue. Many thanks!

[crash-2020-02-17_06.57.33-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4213652/crash-2020-02-17_06.57.33-client.txt)

Edit: Server crashed on restart after loading the world log below.

[crash-2020-02-17_12.40.09-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4213799/crash-2020-02-17_12.40.09-server.txt)

**Comment by cam72cam** [comment]
These will be fixed by the next release
