### ISSUE TITLE
Passenger train disconnects before switch track

### ISSUE THREAD

**Issue by CheekierSky** [TeamOpenIndustry/ImmersiveRailroading#745]
The passenger train always seems to disconnect with the engine when trying to use the switch. It doesn't seem to matter which curve, speed or train. I have tried using the coupling hook and that doesn't seem to fix the problem. 

I'm new to Immersive Railroading so maybe there is something I'm doing incorrectly. 

![immersive railroading issue](https://user-images.githubusercontent.com/60241340/75272223-7b7d2c80-57cb-11ea-8c19-7e1992779532.gif)

The mods I have installed are:
MrTJP Core
Forge Multipart
CodeChickenLab
Project Red Integration, Fabrication, Compat, and Base
Automated Redstone
CD4017BE Lib
Industrial Wires
Track API
Open Computers
IGW Mod
Immersive Engineering and Railroading
Traffic Control
Thuttcore
Thuttech
Mystical lib
BiblioCraft
Blockcraftery
Skye's Bakery
Little Tiles
Creative Core
Forgelin
SimplyLight
World Edit
Corail Pillar
MrCrayfish's Device Mod
Placeable Items
Xaeros Minimap
NiftBlocks
Carpenters Blocks
Optifine
Traffico+
Chisels and Bits
MrCrayfish's Vehicle Mod
Obfuscate
MrCrayfish's Furniture Mod

**Comment by Railroadactive** [comment]
just out of curiousity, how sharp is that curve?

**Comment by CheekierSky** [comment]
The curve is 67.5 but I've tried it with every preset curve as well as a custom curve. 
    On Tuesday, February 25, 2020, 09:09:57 PM EST, Railroadactive <notifications@github.com> wrote:  
 
 
just out of curiousity, how sharp is that curve?

**Comment by andrboot** [comment]
What version of Minecraft, IR and forge please.
Also if you use 'smaller' stock does it do the same? that is a very sharp curve.

**Comment by CheekierSky** [comment]
I just tested smaller stock and the same thing happens. As for the curve, it is very sharp but that doesn't seem to change the outcome. I've tried all of the preset curves (as well as numerous custom curves) and it still happens exactly the same way. 
Minecraft -1.12.2Forge -1.12.2-14.23.5.2847Immersive Railroading-  1.7.2_1.12.2     On Tuesday, February 25, 2020, 10:53:29 PM EST, Andrew B <notifications@github.com> wrote:  
 
 
What version of Minecraft, IR and forge please.
Also if you use 'smaller' stock does it do the same? that is a very sharp curve.

**Comment by CheekierSky** [comment]
Update: I tried it on curves (so no switch) on every preset curve and it does it then too. So...that would leave me to believe that it's a curve issue, not a switch issue?

**Comment by CheekierSky** [comment]
Update 2: After further testing, it seems to work on perfect circles and if I start the train on a curve and go straight. If I start on a straight track or go to a straight track and curve again it breaks every time, every preset curve, and on multiple different-sized tracks. I hope these updates are helpful.

**Comment by km00700** [comment]
That's normal.

**Comment by km00700** [comment]
The cars are still coupled. The reason they appear to disconnect is because IR, to save on performance, calculates center-to-center distance, since the chord of a curve is shorter than the arc length, the cars will spread apart on fairly tight curves.

**Comment by CheekierSky** [comment]
Okay typically I think that would apply, but the passenger car stops moving and the engine continues. The coupling hook also says that they are not coupled. It only seems to happen on straight to curved track at any angle. I hope that makes sense. 
    On Wednesday, February 26, 2020, 11:24:55 AM EST, Kai Mills [km00700] [DarkRaider] <notifications@github.com> wrote:  
 
 
The cars are still coupled. The reason they appear to disconnect is because IR, to save on performance, calculates center-to-center distance, since the chord of a curve is shorter than the arc length, the cars will spread apart on fairly tight curves.

**Comment by km00700** [comment]
Well, then that seems like an issue in the physics accumulator. If you wouldn't be opposed, would you be able to remove the other mods one-by-one and see if it starts working after removing a certain one?

**Comment by CheekierSky** [comment]
Okay, I'll try that. It will take a little while though. I'll report back when I'm done. Thanks!
    On Wednesday, February 26, 2020, 11:40:22 AM EST, Kai Mills [km00700] [DarkRaider] <notifications@github.com> wrote:  
 
 
Well, then that seems like an issue in the physics accumulator. If you wouldn't be opposed, would you be able to remove the other mods one-by-one and see if it starts working after removing a certain one?

**Comment by CheekierSky** [comment]
Update 3: I finally got it to work after some testing. If you start on a curve and go straight the length of the curve doesn't matter, but if you go from a straight to a curved track I noticed that the length of the track has to be 30 or higher or the train will disconnect no matter the degree of the curve.  Because I'm new to immersive railroading, I'm not sure if that's typical or not. If this is typical then I'll close the repository. Thanks again for all of your help!

**Comment by robot256** [comment]
I'll mention this since it wasn't earlier: When you select "Turn" or "Switch", the meaning of the typed number box changes from length to *radius*.  When we say a turn is "sharp", that means the *radius* is too small.  IR is known to misbehave with turns of too small a radius for a particular rolling stock.

Radius and sharpness are not affected by the "preset slider", which sets the *angular change* of the turn.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
