### ISSUE TITLE
Overlapping Custom Curve tracks causes NullPointerException

### ISSUE THREAD

**Issue by AnonymousDapper** [TeamOpenIndustry/ImmersiveRailroading#746]
**Describe the bug**  
Placing two or more sections of custom curve track such that they overlap will cause a NullPointerException to be thrown.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Get Custom curve track (rail bed and fill doesn't seem to make a difference)
 2. Place track section 1 and build blueprint
 3. Place track section 2 so it overlaps at least once with track section 1 and build blueprint

If it doesn't place at all, try placing the ends of section 2 in reverse order.
 
**Expected behavior**  
Tracks are placed and appear correctly.

**Actual behavior**
NPE is logged (VanillaFix), rail bed is missing in sections, rail blueprint block is not selectable in sections.

**Screenshots**  

**System Information**  
 OS: Windows 10
 <br>System Memory: 16GB
 <br>Allocated Memory: 4GB
 <br>CPU: AMD Ryzen 7 2700X
 <br>GPU: PNY GTX 1070 XLR8
 <br>IR-Version: 1.7.2_1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2847

**Modlist**  
- FoamFix
- Immersive Engineering
- Immersive Railroading
- InGame Info XML
- JEI
- Optifine
- Phosphor
- Unidict
- VanillaFix
- VoxelMap
- Waila
- WorldEdit
 
**latest.log**
https://paste.a-sketchy.site/ereweqajol.txt

**Screenshot**
![image](https://totally-not.a-sketchy.site/3Ksur4G.png)

**Comment by cam72cam** [comment]
This will be fixed by the next version
