### ISSUE TITLE
[1.12.2]Server crash report

### ISSUE THREAD

**Issue by EnterFor** [TeamOpenIndustry/ImmersiveRailroading#747]
Forge:2847
Mod:1.7.2-1.12.2
Accidentally placing two tracks in a row in one place can cause a crash

[crash-2020-03-07_17.12.05-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4301621/crash-2020-03-07_17.12.05-server.txt)

**Comment by cam72cam** [comment]
This will be fixed in the next version

**Comment by EnterFor** [comment]
> This will be fixed in the next version

My God!!!
You seem to have disappeared for a long time
I thought you weren't going to maintain the project
