### ISSUE TITLE
Can't move inside trains after dimension change [Forge]

### ISSUE THREAD

**Issue by jhayes2-chwy** [TeamOpenIndustry/ImmersiveRailroading#748]
**Describe the bug**  
After changing dimensions, players can't no longer move inside-of or with trains. As a result, the train moves away from the player who is stuck in place. This occurs in Singleplayer, and Multiplayer(tested on a personal dedicated server and others')

**How to reproduce**  
Steps to reproduce the unwanted behavior:

1. Enter world
2. Create 10m section of straight track, and put a handcar on it
3. hop on and move around a little bit, all is well
4. get off and build + enter a nether portal
5. wait a bit, then hop back out
6. get on handcar again
7. see that it doesn't move at all or moves without you
8. get off, instantly teleporting to where the train should have visually been
9. quit game
 
**Expected behavior**  
The player should be able to move with the train, as well as around its interior.

**Screenshots**  

**System Information**
PC Specs:
 OS: Windows 10
 System Memory: 16G
 Allocated Memory: 4G-8G
 CPU: Intel 8600K
 GPU: GTX 1070ti
 Java-Version: Java 8, u241, 64 bit

Dedicated Server Specs:
OS: Ubuntu server 18.04
 System Memory: 24G
 Allocated Memory: 8G
 CPU: AMD-FX 8320
 Java-Version: Java 8, u241, 64 bit

Minecraft Specs:
 IR-Version: 1.7.2_1.12.2
 Forge-Version: 1.12.2 - 14.23.5.2847

**Modlist**  
This bug is encountered with just Forge, Track API, and IR.
 
**latest.log**
Log files are contained in this zip archive: 
[IR_Testing.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4302248/IR_Testing.zip)

**Additional context**  
Re-logging is a workaround that fixes the issue until the next dimension change.

This issue was opened on behalf of @dicksoak#4448 from the IR discord channel

**Comment by ArmaWizard** [comment]
I can confirm this happens when switching to any dimension. Relogging on the spot will fix this.
Running MCEternal modpack + IR dependencies and IR itself.
