### ISSUE TITLE
server crash 1.12.2

### ISSUE THREAD

**Issue by DigitalNikki** [TeamOpenIndustry/ImmersiveRailroading#749]
Template goes here
I'm blind and don't see a template.

Update to Immersive Railroading 1.7.2 and the server crashes. Using TrackAPI 1.1 or 1.2 doesn't make a difference.

Reverting to the previously used ImmersiveRailroading-1.6.1_1.12-1138 corrects the issue.
[crash-2020-03-18_15.01.41-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4351378/crash-2020-03-18_15.01.41-server.txt)

**Comment by andrboot** [comment]
Reset your configs, you have a malf config.

**Comment by DigitalNikki** [comment]
It's the radio range setting in the config. I'm not sure why it was set that high, but I think that if there is a maximum range anything over that should be lowered to that instead of causing a crash.
