### ISSUE TITLE
Not always placed switch

### ISSUE THREAD

**Issue by Grigoriewich** [TeamOpenIndustry/ImmersiveRailroading#750]
**Describe the bug**  

Any rails are placed on a flat surface. The switch does not fit on an uneven surface.

I do not speak English. Sorry for that.

rus: Любой вид рельсов устанавливается на ровную поверхность. Но на не ровную не хочет устанавливаться стрелка.

**Video**  
https://youtu.be/T25l-e1D0ts

**System Information**  
 OS: [Linux Mint]
 <br>System Memory: ["8gb"]
 <br>Allocated Memory: [ "6gb"]
 <br>CPU: ["Intel I3 7100"]
 <br>IR-Version: [e.g. "1.7.2_1.12.2"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2847"]

**Comment by Grigoriewich** [comment]
Switch itself is destroyed when loading the world

https://youtu.be/dgsNi9qbwgM

**Comment by MAX2136** [comment]
Same issue here, and it is VERY annoying.

**Comment by andrboot** [comment]
Please upgrade your IR, 1.7.3 is currently  the stable.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
