### ISSUE TITLE
Broken villager payout

### ISSUE THREAD

**Issue by SteampsonJake** [TeamOpenIndustry/ImmersiveRailroading#751]
Villagers don't pay after getting off the train.

I have the multiplier set to 0.05 and have these items in the ore dict. (in case that is somehow messing it up)
![image](https://user-images.githubusercontent.com/47562841/77432484-6998a480-6dde-11ea-8f86-899603a5e957.png)

New (much smaller) [latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4375700/latest.log)

**Comment by shotbyapony** [comment]
IR, TrackAPI, Forge, Minecraft... etc versions???

**Comment by Doublehelix13** [comment]
I have the same issue.  I am on Minecraft 1.12.2, IR version 1.7.3, TrackAPI version 1.2, and Forge version 14.23.5.2847.  I did not touch the list of villager payout items in the config and changed the number of items per meter to 0.002 after noticing the bug to make absolutely sure I moved them far enough to pay me.  Hopefully the extra information helps.
