### ISSUE TITLE
[Feature Suggestion] Extra Track angles

### ISSUE THREAD

**Issue by Thomas4peyton** [TeamOpenIndustry/ImmersiveRailroading#752]
I propose the addition of extra angle of track for added realism and flexibility, all in 11.25° increments to add upon the current 22.5°, 45°, 67.5°, and 90° options. 

The new available angles for placement, as well as curves would be: 0° > 11.25° > 22.5° > 33.75° > 45° > 56.25° > 67.5° > 78.25° > 90°

Such a change will improve track flexibility and the creation of scale recreations of real life scenes: ones that are currently impossible with the limited track angles available.

**Comment by latibro** [comment]
I think you can do that from the config:
        # Angle Placement Segmentation
        I:AnglePlacementSegmentation=4

Quick look at the code looks like the config option is the reason it is 22.5°, 45°, 67.5°, and 90°
But haven't tried it out.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
