### ISSUE TITLE
Distilled Water is infinite source in locos 

### ISSUE THREAD

**Issue by 62512** [TeamOpenIndustry/ImmersiveRailroading#754]
**Describe the bug**  
Distilled water is an infinite source in steam engines 
**How to reproduce**  
 1. Set up a steam loco
 2. Throw in some Distilled water
 3. Boom infinte Distilled water
 
**Expected behavior**  
Immersive Engineering's Distilled water is an infinite source in locos 
Happens on Server and Singleplayer 

**System Information**  
 OS: Windows 10
 <br>System Memory: 8gb
 <br>Allocated Memory: 4gb
 <br>CPU: Intel- (well im not sure)
 <br>GPU: MSI 1080 8gb
 <br>IR-Version: 1.7.3_1.12.2
 <br>Forge-Version: "1.12.2 - 14.23.5.2844"

**Modlist**  
IE 1.12.2 (latest version)
IR 1.7.3_1.12.2
Track api 1.12.2 (lastest version)
 
**latest.log**
 Is a constant issue

**Additional context**  
Doesn't do the same to regular water, but only to IE's Distilled water

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
