### ISSUE TITLE
Train/Stock chunkloading not loading on server start

### ISSUE THREAD

**Issue by andrboot** [TeamOpenIndustry/ImmersiveRailroading#757]
Chunkloading
When a server is restarted,  trains that were chunkloaded before shutdown aren't re-chunkloaded.

Enable forced chunkloading, visit some stock, then restart the server

Trains should automatically rechunk on server start.

Has happened on all previous IR version, and latest current.
Minecraft 1.12.2 , doesn't matter which forge version.

On server startup, the following message is displayed on latest log.
`Server thread/WARN] [FML]: The mod universalmodcore has registered persistent chunkloading data but doesn't seem to want to be called back with it - it will be removed from the world save`

**Comment by cam72cam** [comment]
fixed in 1.12.2
