### ISSUE TITLE
Casting basin crash (1.7.10)

### ISSUE THREAD

**Issue by hubb2001** [TeamOpenIndustry/ImmersiveRailroading#758]
**Describe the bug**  
Game crashed when trying to change gauge on the casting basin
**How to reproduce**  
Steps to reproduce the unwanted behavior:
Create casting basin, open and try to click the gauge to change it

**System Information**  
 <br>IR-Version: 1.7.3_1.7.10

**Modlist**  
Was using FTB infinity evolved : https://ftbwiki.org/Feed_The_Beast_Infinity_Evolved
Plus Opencomputers, Minus funky locamotion.

 
**Log**
[2020-03-30-2.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4406142/2020-03-30-2.log)

**Additional context**  
The bug only happened once, after forming it and crashing I logged back in to the server and the model was overlapping with the block version of it, I broke the model and reformed the casting bin and it worked fine.

**Comment by shotbyapony** [comment]
Tried several times. Cannot reproduce.
