### ISSUE TITLE
Boiler plating item pickup crash/timeout. (1.7.10)

### ISSUE THREAD

**Issue by hubb2001** [TeamOpenIndustry/ImmersiveRailroading#759]
**Describe the bug**  
Server timeout when picking up boiler plating
**How to reproduce**  
On a server, create a plate machine and try to craft a narrow gauge boiler plate for the DSP&P, once crafted attempt to grab and pick up and it times out and sometimes fully crashes

 
**Expected behavior**  
It gives me a boiler plate and **doesn't** time me out.

**Screenshots**  
https://imgur.com/a/q4lSWSO

**System Information**  
 <br>IR-Version:1.7.3_1.7.10

**Modlist**  
Was using FTB infinity evolved : https://ftbwiki.org/Feed_The_Beast_Infinity_Evolved
Plus Opencomputers, Minus funky locamotion.

**latest.log**
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4406456/latest.log)

**Additional context**  
Doesn't crash in single player, whenever I log on to the server and try to pick up the item it times me out leaving the item on the ground, causing me to be unable to log in until the item times out. 
It does not negatively effect the server in any way, and others are able to continue playing without issue.

**Comment by shotbyapony** [comment]
The latest.log you attached - you logged in and immediately picked up the item and crashed?

**Comment by shotbyapony** [comment]
I've got no clue what's going on. I removed all mods except IR and its dependencies and it works fine.

**Comment by hubb2001** [comment]
[crash-2020-04-18_20.42.27-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4498163/crash-2020-04-18_20.42.27-client.txt)

We finally got a crash log that wasn't completely useless, seems to be a rendering error of some kind. Haven't been able to narrow down what does it though since it only happens on a server.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
