### ISSUE TITLE
Game crashes when I go into the rail menu in the creative tabs 1.14.4

### ISSUE THREAD

**Issue by phueyflame** [TeamOpenIndustry/ImmersiveRailroading#760]
Problem is as stated in the title.

crash log here:

https://pastebin.com/PS8dkkNT

minecraft 1.14.4
forge 28.2.3
immersiverailroads 1.7.3
Track api 1.2

**Comment by shotbyapony** [comment]
That's not the crash log. Make the game crash again and attach your latest.log, please.

**Comment by cam72cam** [comment]
That's a GPU problem.  Update your nvidia driver.
