### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by MatrixSystemPVP** [TeamOpenIndustry/ImmersiveRailroading#761]
When i try to start a modded server with the mod and some other mods then it crashes.

[crash-2020-04-03_17.12.35-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428229/crash-2020-04-03_17.12.35-server.txt)
[fml-server-latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428241/fml-server-latest.log)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428242/latest.log)

**Comment by shotbyapony** [comment]
For starters, JEI is not a server side mod. Please remove it from your server mods folder and try again. Let me know what this gets you.

**Comment by MatrixSystemPVP** [comment]
Nothing changed after i removed JEI.

[crash-2020-04-03_18.25.40-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428605/crash-2020-04-03_18.25.40-server.txt)
[fml-junk-earlystartup.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428608/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428609/fml-server-latest.log)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428610/latest.log)

**Comment by shotbyapony** [comment]
where can i get this modpack?

**Comment by MatrixSystemPVP** [comment]
I created the modpack myself, but i can send the export of the modpack.
[LevelUp-1.0.0.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4428778/LevelUp-1.0.0.zip)

**Comment by MatrixSystemPVP** [comment]
Without the ImmersiveRailroading Mod the server starts just fine.

**Comment by cam72cam** [comment]
The Client crashed inside of:
mods.octarinecore.client.render.RenderCtx.render

Try removing that mod and opening an issue on their github
