### ISSUE TITLE
Using Automation to Extract Crafted Items From Casting Basin Voids Items

### ISSUE THREAD

**Issue by jhayes2-chwy** [TeamOpenIndustry/ImmersiveRailroading#763]
**Describe the bug**  
Using the Mechanical User from EU2 to extract items from the Casting Basin voids items. 

**How to reproduce**  
Steps to reproduce the unwanted behavior:

1. Setup and Power a Casting Basin
2. Automate extraction from the Casting Basin with EU2 Mechanical User (and optionally a vacuum hopper to collect the casts)
3. Throw some steel into the basin
4. Cast something
5. Mechanic User extracts from the basin, but item is deleted
 
**Expected behavior**  
It used to spit the item out like a dispenser.

**System Information**  
I've run into this bug on my old computer and my new beefier computer, but I've included the hardware specs for both:
OS: Windows 10 / Windows 10
System Memory: 16G / 32G
Allocated Memory: 10G / 12G
CPU: I don't remember / Intel Core i7 9th Gen
GPU: Nvidia Quadro M2000M / Nvida Geforce 1660Ti
IR-Version: 1.7.2_1.12.2 & 1.7.3_1.12.2
Forge-Version: 1.12.2 - 14.23.5.2847

**Modlist**  
The mod list is extensive, but I've provided the minecraft profile folder with the world where I had this working until 1.7.2 IR. The Waypoint is Railworks (x,y,z coords: 35,67,-254), and everything should be there. Power, Casting Basin, Automation, everything.
 
**latest.log**
I personally ran into this issue months ago (using IR 1.7.2_1.12.2), so I don't have the latest.log anymore. leonhelmle#0124 on the Discord has recently had the same issue with IR 1.7.3_1.12.2.

**Additional context**  
Zipfile of the instance is [here](https://drive.google.com/file/d/1DOrkpLb3rnBJxXS0mazGJLaxDvK38Qbm/view?usp=sharing)

This seems to be the Same Issue from #738, but I hope the extra context here will help debugging (also that issue doesn't follow the issue template...).

**Comment by Pavelsvt** [comment]
I have exactly the same issue.

**Comment by cam72cam** [comment]
This can now be automated with a hopper
