### ISSUE TITLE
Auto-generate track gauge options based on existing rolling stock .json

### ISSUE THREAD

**Issue by WrongWeekend** [TeamOpenIndustry/ImmersiveRailroading#764]
In addition to manually inserting track gauge options, resource packs should generate additional track gauges if the .json for a locomotive or car is configured for a gauge that does not currently exist. For example, if a locomotive's .json file specifies 1,067 mm ("Cape") gauge, the resource pack would automatically add 1,067 mm gauge to the gauge options when using the track blueprint.

This would ensure that the correct track gauge for any locomotive or car is always present (provided that the information in the .json is specified correctly).

**Comment by cam72cam** [comment]
I'm still not 100% sold on this as sometimes it's nice if people specify two different gauges that are really close together.
