### ISSUE TITLE
[1.14.4] Tesselating block model

### ISSUE THREAD

**Issue by Jason-m858** [TeamOpenIndustry/ImmersiveRailroading#766]
Hey my Game is crashing with the Above Error when i Try to Place a Track Template.
I dont really know what to do i hope you can help me.
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4431696/latest.log)

**Comment by jhayes2-chwy** [comment]
The 1.14.4 IR builds are still semi-unstable, and I believe Sponge is still unsupported. Try without Sponge; if you still get the crash it's probably a bug with the 1.14.4 versions of IR.

**Comment by cam72cam** [comment]
It looks like another mod causing:
```
Failed to read message: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(42) exceeds writerIndex(3): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 2, widx: 3, cap: 256)
```
