### ISSUE TITLE
Game keeps crashing in a world

### ISSUE THREAD

**Issue by 1gn4ac10** [TeamOpenIndustry/ImmersiveRailroading#767]
**Crash Report:https://paste.ubuntu.com./p/4z8GXgZcC5/**

Well, I have a world where I have a lot of mods (+80) and they didn't make any problems, that was a few months ago, I stopped playing minecraft and came back, but out of nowhere the game crashes every time I enter the world if I have Immersive Railroading (If I enter without the mod there is no problem) . I would say this is a bit urgent as it is a world where I am quite advanced

**Comment by jhayes2-chwy** [comment]
Nothing looks obviously out of place that I know of... you say the world was from a few months ago; do you still crash with the 1.7.2 version of IR? It might be a bug with the recent 1.7.3 version.

**Comment by 1gn4ac10** [comment]
I tested with 1.7.2,1.7.3 and 1.6.1 and still crashing,but im gonna test again

**Comment by 1gn4ac10** [comment]
Tested again,still crashing

**Comment by 1gn4ac10** [comment]
Now tested with all version and still crashing

**Comment by jhayes2-chwy** [comment]
Well, it’s either a mod conflict or a bug, or both. I didn’t see any fish mods in the original crash report with version 1.7.3. I’m guessing Cam will want the full `latest.log` from that version, so you should get a pastebin link for that in the mean time.

**Comment by 1gn4ac10** [comment]
So, here i what says the _latest.log_:https://paste.ubuntu.com/p/VRM8PfB45y/

(PD:Just in case, maybe I don't understand something since I don't speak English)

**Comment by cam72cam** [comment]
If you downgrade to 1.6.1 it will break your world.  If you have done this, you will need to go back to a backup or start a new world

**Comment by 1gn4ac10** [comment]
Thank you, I found a backup of the world and it worked again. But now I have another problem which, although not as serious, is a bit annoying: The thumbnails are bugged
![bug](https://user-images.githubusercontent.com/63067279/78502230-04be4200-772e-11ea-9224-3194943f65a0.JPG)

**Comment by Larky2k** [comment]
Iv got that bug and have no idea what's caused it, thought it was Optifine but I have another instance that's the same but doesn't do that.

**Comment by SteampsonJake** [comment]
Most of the time it's caused by Optifine fast render.
Turning it off and restarting the game usually fixes it.

**Comment by Larky2k** [comment]
Doesn't work, took Optifine still does it

**Comment by 1gn4ac10** [comment]
And is starting to crash again with the same error,gonna try a older backup and see if works

**Comment by 1gn4ac10** [comment]
Ok,all is fixed for now,so im gonna close this.Thanks for the help!

**(PD:I have other problem that is not that bad but its annoying,im gonna post that later)**
