### ISSUE TITLE
Rolling stock does not exist on server #2

### ISSUE THREAD

**Issue by EnderTeleportation** [TeamOpenIndustry/ImmersiveRailroading#772]
In https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/401, you've been talking about a recurce pack, could I know what you are talking about, because I am experiencing this issue too.

**Comment by 1gn4ac10** [comment]
I dont know if this is the problem but a comments says

_"Server resource packs go in config/immersive railroading"_

Just in case put the **latest.log** so the people can help you more

**Comment by EnderTeleportation** [comment]
But I don't know what resource packs you are talking about?

**Comment by km00700** [comment]
Which stock are you trying to place?

**Comment by EnderTeleportation** [comment]
any, it doesn't work

**Comment by km00700** [comment]
We need some specific names and/or a log file.

**Comment by EnderTeleportation** [comment]
UNU Aerotrain
[2020-04-12-3.log.gz](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4466275/2020-04-12-3.log.gz)

**Comment by EnderTeleportation** [comment]
...Hello... ...I still need help...

**Comment by km00700** [comment]
UNU doesn't work like other packs on servers. You need to copy the UNU mod jar file then change the ".jar" to ".zip" Then you put that in the server's config/immersiverailroading folder.

**Comment by EnderTeleportation** [comment]
1. This worked without doing this on another server,
2. It doesn't let me place trains EVEN if they are out of the original pack

**Comment by km00700** [comment]
I'm guessing you're using an Aternos server?

**Comment by EnderTeleportation** [comment]
I am! But it works on another aternos server! Just on this one it doesn't

**Comment by km00700** [comment]
In the log you sent, IR isn't installed on that server.
