### ISSUE TITLE
Not able to place tracks in any way other than "fixed" position

### ISSUE THREAD

**Issue by ravensbeard103** [TeamOpenIndustry/ImmersiveRailroading#773]
**Describe the bug**  
Trying to place rail down in any way other than "fixed" position does not let me place down tracks.

**How to reproduce**  
Try to place down track in any way other than "fixed" position
 
**Expected behavior**  
Well clearly I expected for it to place.

**System Information**  
 OS: Windows 10
 <br>System Memory: 16 GB
 <br>Allocated Memory: 2 GB
 <br>CPU: Intel i7-8750H
 <br>GPU: MSI Geforce RTX 2060 16 GB
 <br>IR-Version: 1.7.3 1.14.4
 <br>Forge-Version: 1.14.4

**Modlist**  
 Immersive railroading, Track API, MrCrayfish furniture mod, Minecolonies, structurize (Note that when other mods other than Immersive railroading and Track API are removed, there are no changes to behavior of tracks.
 
**latest.log**
6:59:05 PM CONSOLE: thread/WARN] [ca.mo.ModCore/]: Loaded false {controlMode:0,parent:{X:2,Y:0,Z:2},railHeight:0.0f,snowLayers:0,couplerMode:0,version:3,flexible:1b,x:215,y:62,z:-1231,id:"immersiverailroading:block_rail_gag",redstoneMode:0,height:0.0f}

**Comment by DarkAlex666** [comment]
Tracks self-destruct after installation. It is impossible to establish them, there are no obstacles since the road is located high above the ground. But the tracks are still destroyed right after installation. Direct tracks and a turn are installed without problems, but the train arrow is destroyed.

**Comment by DarkAlex666** [comment]
ravensbeard103 Hi, if you need help with the modification of Immersive Railroading, I will tell you. I also came across this after the last update. You go to the minecraft / minecraft / config folder and look for the immersiverailroading.cfg file there, then change the line there (If more than X% of the tracks are above non solid block, break the track
         D: trackFloatingPercent = 0.05) by default there is such a figure 0.05 you need to replace with any larger figure. In my case, set 5.5. And everything works - the rails put nothing breaks.
