### ISSUE TITLE
Not able to place tracks

### ISSUE THREAD

**Issue by DarkAlex666** [TeamOpenIndustry/ImmersiveRailroading#780]
**Describe the bug**  
Tracks self-destruct after installation. It is impossible to establish them, there are no obstacles since the road is located high above the ground. But the tracks are still destroyed right after installation. Direct tracks and a turn are installed without problems, but the train arrow is destroyed.

**How to reproduce**  
I tried to set the track to the arrow in any way, and in creative and in survival, I set a fixed position and not fixed. The result is still tracks are broken.
 
**Expected behavior**  
 So that all varieties of train tracks are installed without problems.

**System Information**  
 OS: Windows 10
 System Memory: "16gb"
 Allocated Memory: "13gb"
 CPU: "Intel I7 7700k"
 GPU: "MSI 1080 8gb"
 IR-Version: "1.7.3_1.12.2"
 Forge-Version: "1.12.2 - 14.23.5.2844"

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
