### ISSUE TITLE
NPE from TrackBuilderIterator

### ISSUE THREAD

**Issue by ekat2468** [TeamOpenIndustry/ImmersiveRailroading#781]
Sample Pastebin: https://pastebin.com/hMjRZVwz

Upon the error triggering, upon loading a world the screen flickers for a few seconds and then goes straight black. Even more oddly is that the issue appears to resolve itself if on reloads the save enough times or waits around 30-60 minutes and reloads the save. 

I wish I could provide steps to reproduce but I'm not 100% certain what is causing the issue. My best guess is that it is caused by connecting a 1 block length straight track to a slope track. Maybe start there? If you really are unable to replicate it I can provide a copy of the world where this is occurring and the mod list.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
