### ISSUE TITLE
Loaders (Specifically Unloaders) need an overhaul.

### ISSUE THREAD

**Issue by TheAceOneXL** [TeamOpenIndustry/ImmersiveRailroading#782]
Fluid/Item unloaders need an overhaul, a few things. 

One, they should have their internal buffer removed, or at the very least needs some type of GUI to tell what's currently in them. 

Two, unloaders shouldn't automatically pull from inventories above them, for those who'd say, *they have a filter* I am aware. the problem is there are 10s of different stock that have inventories, and making an individual unloader for each one is crazy. another point that might get brought up, *just tell the pipes when to pull items* this doesn't fix the fact that unloaders will pull from the first thing they see since they are always active. thus, another problem with them pulling automatically, again they should only pull when a Redstone signal is given. (preferably with an option to allow/ disallow a signal from an adjacent detector augment). 

Three, with fluid unloaders, you can have multiple right next to each other and it speeds up the process of fluid removal, but with item unloaders, it will only allow one to pull items a time. meaning you can clear tankers with 100s of buckets of fuel in seconds, but hoppers take a decade to unload. it would be nice if this were changed to allow faster unload times.

I looked around the discord/online and there were only mentions of the loaders, no one talks about the unloaders much and even less so answers to the questions about them, I came upon these suggestions in my testing of a functional large scale train depot on @TheDragonGamer#6476's server along with single player testing. Thanks for coming to my TED talk. 
~Fu

**Comment by cam72cam** [comment]
Closing as won'tfix since augments will be replaced with dedicated blocks / multiblocks eventually.
