### ISSUE TITLE
Rolling stock still visible after being destoyed

### ISSUE THREAD

**Issue by jeffswt** [TeamOpenIndustry/ImmersiveRailroading#783]
**Describe the bug**  
As title
(Visible artifact)

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Create any (default) rolling stock, longer the better
 2. Sneak and hit it
 3. From certain angles, the particular rolling stock could still be seen (this might take some time to reproduce?)
 4. It disappears permanently after reloading the save.
 
**Expected behavior**  
 A clear description of what you expected to happen.

**Screenshots**  

**System Information**
OS: Windows
System Memory: 8192MB
Allocated Memory: 4096MB
CPU / GPU: irrelative
IR-Version: 1.7.2
Forge-Version: 1.14.4-28.2.0

**Modlist**  
Just TrackAPI and IR, w/o Optifine
 
**latest.log**
<null>

**Comment by andrboot** [comment]
Update IR to 1.7.3 please, and 4GB of memory may be pushing the limit.
