### ISSUE TITLE
Using Locomotives Permission for Forge Essentials

### ISSUE THREAD

**Issue by FGBxRamel** [TeamOpenIndustry/ImmersiveRailroading#789]
It would be pretty cool to have a permission for Forge Essentials like the "fe.protection.use.immersiverailroading.item_rolling_stock.*" so that Players which don't have the Permission can't use Locomotives and/or Wagons.

We want to make a Roleplay Server (GIRC) and we don't want normal Members ("Citizens") to use Locomotives.

**Comment by latibro** [comment]
Could you be more specific about what permission you think could be useful here?
Like "control locomotive", "board stock", "place stock" etc. ?
