### ISSUE TITLE
Add Modern Railway

### ISSUE THREAD

**Issue by touhourailway** [TeamOpenIndustry/ImmersiveRailroading#791]
The topic I use morden but not electrification is because the different country have different railroad even other rail transit .So only the electrification is one-sidedness. 
But the same similarities from there are three main points:
1.Pure bridge without minecraft block.
2.piers and telegraph Pole with the same interval.
3.power cable or noise barrier,attachments of the rail.
4.automatic cabin door.
The second and third are all the attachments of the rail, but I don't know if the modifition can selection the rail each model. If it can't, then point 2 can be made a menu to set the pier and the pole theres interval, the point 3 can just make the model into rail then add the attribute to the rail [just like the goldenrail,then use the power equipment give power, although it's unreal]
The model of these can be made by player, I've made a lot of models of Shanghai Metro, but because of the bug I haven't made a compeletely map.
I'm bad in English, so here is the original text
标题起现代化铁路而不是电气化铁路是因为个人觉得不同的地区的铁路样式不同，甚至于有其他的非铁路轨道交通工具，光是制作电气化是片面的。但是这些轨道交通都有着一些共同点，下面是个人归纳的三个点，可能会有缺漏甚至于理解错误。
1.纯粹的不包含方块的高架型式。
2.等间距的桥梁、接触线支架。
3.一些例如噪音屏障和动力电缆的附件。
4.自动控制的车门。
其中第二第三点可以看作是轨道的附件，分开写的原因是不确定游戏内功能是否达到可以稳定的单独选中某一段铁轨模型，如果不能，那么第二点可以以在布置铁轨前设置需要的部件以及间隔距离来实现，而第三点可以按照修改铁路模型达到[如果生存需要的话可以增加铁轨属性就和游戏内的红石铁轨一样，甚至于说可以利用现有的能源设施供电，虽然数人从发电到运行操作一条电气化铁轨有点不现实]
另外，基于强大的自定义追加功能，上述模型完全可以由玩家提供，我这里就做了一些ST的电气化桥梁、桥柱[但是由于弯道bug和方向22.5度的限制还没有到达最佳效果]

**Comment by DDX5-DX12-Media** [comment]
@touhourailway, Not Trying To Come Across As Rude Here. You May Want To Use Their Discord Under #suggestions As I Have Seen Another Issue With A Different Suggestion And They Were Pointed In The Direction Of Discord Aswell

**Comment by km00700** [comment]
For mod feature suggestions, we actually recommend they be here on the github, as they're less likely to get buried.
