### ISSUE TITLE
Electric Trains

### ISSUE THREAD

**Issue by EpicPuppy613** [TeamOpenIndustry/ImmersiveRailroading#795]
Add electric train support. Trains are powered by electricity by either internal batteries and rail charging stations or via electrified track. Powered like IR machines, a rail charger will electrify a electrified part of track or charge a train's battery. Electrified track would be a option when placing track, and takes either LV or MV cable. Depending on the type of cable, the rail charger will electrify a different amount of track. Powerlines could be suspended from the ceiling of tunnels, or posts overground.

Electrified track can also be done with a electrified third rail, such as in subways or metro systems irl.

**Comment by km00700** [comment]
Already on the to-do list.

**Comment by EpicPuppy613** [comment]
> Already on the to-do list.

**Comment by Trollebas** [comment]
Make as RealTrainMod, only good.
