### ISSUE TITLE
Immersive railroading block bug

### ISSUE THREAD

**Issue by Baconverse** [TeamOpenIndustry/ImmersiveRailroading#797]
The bug is that trains will not destroy any blocks even though the setting is enabled

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 
![2020-05-14_17 55 25](https://user-images.githubusercontent.com/65372478/81991562-8cda1600-960f-11ea-80d6-63f6d95421b2.png)
1. Go to ...
 2. Do ...
 3. ...
 
I expected for the blocks to break but they didnt

**Screenshots**  

**System Information**  
windows 10]
 <br>System Memory: [e.g. "12gb"]
 <br>Allocated Memory: [The memory allocated to your Minecraft instance where you encountered the bug e.g. "4gb"]
 <br>CPU: [e.g. "Intel I5 8300h"]
 <br>GPU: [e.g. "GeForce gtx 1050"]
 <br>IR-Version: [e.g. "1.6.1_1.12.2"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2844"]

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by Larky2k** [comment]
Update IR, your using an old version. Comen back if problem is still there.

**Comment by saneandsad** [comment]
Same bug as above. Using IR v 1.7.3
Windows 10.
