### ISSUE TITLE
Make it easier to see obstructing blocks, even through other blocks

### ISSUE THREAD

**Issue by RRyyas** [TeamOpenIndustry/ImmersiveRailroading#799]
**Describe the suggestion**  
When i'm making custom curves that follow the terrain, it's really difficult to see the obstructing blocks because the obstructing block needs to be exposed to the air vertically in order to highlight it as red. This makes alot of failed build attempts, and you have to dig quite wide trenches until there's no obstructing blocks and the rails will be placed down, and then it has to be filled again afterwards.

**Applications of the suggestion**  
Highlight obstructing blocks through the terrain, kind of like x-ray, and also maybe add an option for the opacity of the highlighted blocks to be easier seen.

**Comment by cam72cam** [comment]
Fixed many of these rendering issues in the latest test build, will be included in the next release.
