### ISSUE TITLE
[1.14.4] Windmill/Water Wheel Don't Render.

### ISSUE THREAD

**Issue by Minfrog314** [TeamOpenIndustry/ImmersiveRailroading#800]
**Describe the bug**  
When using IR with IE, neither the windmill or water wheel render into the game. As soon as I remove IR they render in just fine.
![2020-05-21_12 49 28](https://user-images.githubusercontent.com/43827119/82608953-cfa06e80-9b78-11ea-8a9a-84eb73d4a3b7.png)

**How to reproduce**  
Load Minecraft with Immersive Railroading and Immersive Engineering, then place a windmill or water wheel and they will not render into the world.

**Expected behavior**  
 When you place down a windmill you should be able to see it.
![2020-05-21_13 01 09](https://user-images.githubusercontent.com/43827119/82608985-e21aa800-9b78-11ea-9f67-b5ba70351fbb.png)

**System Information**  
 OS: Ubuntu 20.04 LTS (Also tested in Windows 10)
 <br>System Memory: 8gb
 <br>Allocated Memory: I think 2gb
 <br>CPU: Intel i5 3570
 <br>GPU: Integrated Intel Graphics
 <br>IR-Version:  1.7.3_1.14.4
 <br>Forge-Version: 1.14.4 - 28.2.16 (Also tested in 28.2.3)

**Modlist**  
 Immersive Engineering
Immersive Posts
Immersive Railroading
TrackAPI
 
**latest.log**
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4664975/latest.log)

**Comment by Larky2k** [comment]
Its a bug with 1.14.4 IE i have it with and without IR

**Comment by Minfrog314** [comment]
Interesting, I only get it with IR.
