### ISSUE TITLE
Null pointer exception on start up. Likely mod conflict.

### ISSUE THREAD

**Issue by AkkarinDarkmoor** [TeamOpenIndustry/ImmersiveRailroading#801]
Seems to be a bit of a mod conflict between the 1.14.4 version and cooking for blockheads. 
Get a null pointer exception on startup. 

log and crash attached. 
[crash-2020-05-24_00.23.25-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4671946/crash-2020-05-24_00.23.25-client.txt)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4671947/latest.log)

**Comment by cam72cam** [comment]
Related to #822
