### ISSUE TITLE
AMD Video Memory not properly detected

### ISSUE THREAD

**Issue by septer99** [TeamOpenIndustry/ImmersiveRailroading#803]
**Describe the bug**  
The current paremeters used to detected video memory on amd cards is old and therefor will not work on newer amd cards. The current version of lwjgl for minecraft 1.12.2 doesn't support the right flag for these newer cards.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Boot Forge with Immersive Railroading while having a newer AMD card.
 2. Look in the console and see only 1024MB of video memory detected
 3. Notice that IR can't see how much of your video memory is free
 
**Expected behavior**  
Immersive Railroading should be able to see all the video memory that is present and is able to see how much of this is available.

**Screenshots**  
Old parameter:
![image](https://user-images.githubusercontent.com/4425364/83397771-764d0080-a3fe-11ea-8146-3e58355146a9.png)

Edited Fallback values to get it to 8192MB (still doesn't fully work):
![image](https://user-images.githubusercontent.com/4425364/83397778-7947f100-a3fe-11ea-8f05-8e0cd0bb0133.png)

My AMD card as an example (is a 4 year old card):
![image](https://user-images.githubusercontent.com/4425364/83397784-7baa4b00-a3fe-11ea-9ba5-743f386432c5.png)

**System Information**  
 OS: Windows 10
 <br>System Memory: 16GB
 <br>Allocated Memory: 4GB 
 <br>CPU: Intel I7 9700k
 <br>GPU: Sapphire RX 480 8GB
 <br>IR-Version: 1.7.3 for MC 1.12
 <br>Forge-Version: 1.12.2 - 14.23.5.2854

**Modlist**  
- Forge
- Immersive Railroading
- Immersive Engineering
- Biomes O plenty
 
**latest.log**
Log of MultiMC booting the game:
https://pastebin.com/FTkaSfR9

**Additional context**  
Maybe there is like an other API or library that is able to get the vram available. The current LWJGL version doesn't support it.

**Comment by cam72cam** [comment]
There's not much I can do at this point.  It's just used as a log message / F3 overlay so it's not causing an issue.
