### ISSUE TITLE
[1.12.2] Yet another java.lang.NullPointerException

### ISSUE THREAD

**Issue by Loupyboy** [TeamOpenIndustry/ImmersiveRailroading#804]
Using a heavily modded custom pack, I've built a large railroad. The client crash seems to be happening whenever I hold an unlocked track, with OptiFine.
It also crashes OpenGL or whatever's used for the render (meaning I can't exit the game without alt-F4 when it happens).

Here's the crashlog: [crash-2020-06-04_01.40.39-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4726724/crash-2020-06-04_01.40.39-client.txt)
Here's the whole log (it's heavy): [latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4726739/latest.log)
If you need the debug.log, feel free to ask.

I'll try to remove tracks from my inventory to see whether I can fix it or not, but for now it softlocks the save.

EDIT: this line (12297) might help you a bit more than just the "null pointer exception" error I guess
![image](https://user-images.githubusercontent.com/54676216/83700476-3c9b1600-a607-11ea-865c-4166960ff3f5.png)

EDIT 2: I've tried removing every IR items from the inventory, without success. Tried disabling OtpiFine too, so the issue might not have anything to do with either...

**Comment by andrboot** [comment]
From what we can see, your using an onboard GPU (Intel), with only 8GB of system memory.
You are going to have issues, and Intel GPU's using a large pack, with this mod currently.
These are known and expected due to the Intel GPU.
If you have 16GB of system memory you may have less of an issue, but your Intel GPU shares that memory.

**Comment by Loupyboy** [comment]
That's weird... My Java Virtual Machine should be running on my GTX.

**Comment by Loupyboy** [comment]
Okay, I've fixed it by removing the turntable track, so this might be the problem there. Anyway, thanks for the fast reply!

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
