### ISSUE TITLE
Horn not working

### ISSUE THREAD

**Issue by Punisher4U** [TeamOpenIndustry/ImmersiveRailroading#806]
The horn does work when I press the enter key. I tried several trains and it didn't work.

Using forge 1.12.2 with Immersive Railroading 1.7.3_1.12.2

**Comment by km00700** [comment]
Not a bug. You need to rebind the horn to the Enter key in the MC controls menu. By default it's bound to Return because the head dev uses linux.

**Comment by Punisher4U** [comment]
That did the trick. Thanks

**Comment by DOMINOAVASYT** [comment]
> Not a bug. You need to rebind the horn to the Enter key in the MC controls menu. By default it's bound to Return because the head dev uses linux.

Still not working

**Comment by km00700** [comment]
If you're using a diesel locomotive, it needs to be turned on before the horn will work.
