### ISSUE TITLE
Server Error Messages

### ISSUE THREAD

**Issue by paulrach** [TeamOpenIndustry/ImmersiveRailroading#807]
We are using ImmersiveRailroading-1.7.3_1.12.2 on a server. The server generates these reports. Typically when a train goes over an augment.

[Server thread/warn] [minecraft/tileEntity]: Skipping BlockEntity with id
[Server thread/warn] [universalmodcore]: BAD TE DATA [controlMode: 0,parent:(x:0,Y:0,Z:-2), railHeight:0.0f,flexible:1b,snowLayers:0,coupleMode:0,version:3,redstoneMode:0,height:0.0f)

What are the causes or cures?

**Comment by septer99** [comment]
This can also be caused by the trafficcontrol mod, this is something I've had experience with.

**Comment by andrboot** [comment]
This is known, the BAD TE DATA is pending an update release and has been patched.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
