### ISSUE TITLE
Vertical smoothing issue ?

### ISSUE THREAD

**Issue by Rysiek18** [TeamOpenIndustry/ImmersiveRailroading#810]
Tracks don't optically connect like they used to before March 2020 update

![2020-06-11_15 07 05](https://user-images.githubusercontent.com/59761804/84388914-a2823180-abf5-11ea-8538-b08ad7340c9d.png)
(They don't connect on any type of vertical smoothing)

![2020-06-11_15 07 21](https://user-images.githubusercontent.com/59761804/84388916-a44bf500-abf5-11ea-9ac6-07e5afe51ae8.png)

**Comment by cam72cam** [comment]
You need to overlap the first and last pieces of track
