### ISSUE TITLE
[1.12.2] Thermalexpansion creosote oil incompatible

### ISSUE THREAD

**Issue by MegaMech** [TeamOpenIndustry/ImmersiveRailroading#814]
Hello,

I am trying to make treated wood which requires creosote. I believe thermal expansion overrides railcrafts creosote oil. I can't make treated wood with thermal expansion creosote buckets. I have railcraft installed.

Also, is there a way to fix JEI integration? Many crafting recipes are missing, but this isn't a big deal.

**Comment by km00700** [comment]
That's not an issue for us. You'll want to post the creosote override thing on the Immersive Engineering GitHub.

**Comment by MegaMech** [comment]
I do not have immersive engineering installed.

**Comment by MegaMech** [comment]
So apparently heavy engineering block is from IE. How do I figure out the recipe if only IR is installed?

**Comment by km00700** [comment]
https://github.com/TeamOpenIndustry/ImmersiveRailroading/wiki/Track-Roller Look at the example here for the substitutions. IR uses vanilla blocks is IE is not installed.

**Comment by MegaMech** [comment]
If the wiki doesn't mention, which I think it probably does. Please mention that multi-block structures are intendid to look much better with immersive engineering. I think it's just bad research on my part. I was like "Naah, don't need that" and when I went to build a multi-block structure I was like "Nope, I definitely desire it to have that"
