### ISSUE TITLE
Visual glitch when rolling stock crosses some track segment boundaries

### ISSUE THREAD

**Issue by robot256** [TeamOpenIndustry/ImmersiveRailroading#817]
**Describe the bug**  
When driving a train down a track, rolling stock sometimes appears to do a quick 360-degree spin as is moves from one track segment to another.  Some segment junctions cause this effect reliably, some occasionally, and some never.  It happens at many speeds and with different trains in the same persistent spots.  Any player riding the train sees their view briefly obscured as they quickly spin around.

**How to reproduce**  
I am using Narrow gauge track and a good mixture of regular track and custom curves, placed with all possible Position modes.  I have a suspicion it could be related to custom curves and/or smooth position mode, since those are the ones I use the least and most joints are okay. 
 
**Expected behavior**  
 If track looks contiguous, train should drive graphically like it was one track.

**Screenshots**  
 I will add more info and do some experiments if this bug is not already known to the community.

**System Information**  
 OS: Windows 10
 <br>System Memory: 16GB
 <br>Allocated Memory: 4.3GB
 <br>CPU: Intel I5-3570K
 <br>GPU: EVGa GTX 650 2GB
 <br>IR-Version: 1.7.3_1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2854

**Modlist**  
IR, Immersive Engineering, D&RG pack, Immersive Petroleum, Buildcraft, and some smaller ones.
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by Catz1301** [comment]
I know it's happened to me plenty of times before, and there was no custom curve. I also used the fixed mode and it still occured.

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.
