### ISSUE TITLE
Locomotive Model Disappears when viewed at a certain angle.

### ISSUE THREAD

**Issue by bCubez** [TeamOpenIndustry/ImmersiveRailroading#819]
When in the cabin or standing outside certain locomotives, the model will sometimes disappear when you look around, particularly toward the front or back.
I have observed it with a handful of locomotives, but not all..

Here are the ones that have this problem:
SD90MAC
Peppercorn
GE C44-9CW
SD40-2
FP7 B-Unit
DR E94
BXF 796
BR 112
BR 114
CD 750
ES44AC Gevo
ES44DC Gevo
GE EMD SD44C-9
GE EMD SD44C-9 HN
Bigger Boy
DDFA40
EMD E8
E8 B-Unit
Hitachi Subway

Reproduce:
Place any of the locomotives, enter the cab, and look around.

![traINSTUPID2](https://user-images.githubusercontent.com/67515652/85928315-b7a3c500-b871-11ea-8f75-4076dcc4f3a3.gif)

System Information
OS: Windows 10 64-bit
System Memory: 16 GB DDR4
Allocated Memory: 8GB
CPU: Intel Skylake i7-6700
GPU: MSI GTX 1050ti 4GB
IR-Version: 1.7.3_1.12.2
Forge-Version: forge-14.23.5.2854

Modlist

![image](https://user-images.githubusercontent.com/67515652/85928266-50861080-b871-11ea-9286-965d4eec5240.png)

 Latest Log

[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/4841000/latest.log)

Not sure if this is a mod issue, an issue with Optifine/Vanilla Fix, or hardware. Either way, if someone can help me out, I would love it! Thanks.

**Comment by bCubez** [comment]
I forgot to add what resource packs I'm using! Here they are:
![image](https://user-images.githubusercontent.com/67515652/85928477-e4a4a780-b872-11ea-90a5-04ca052a4c08.png)

**Comment by km00700** [comment]
this is a known bug with rendering in IR 1.7.3

**Comment by bCubez** [comment]
> this is a known bug with rendering in IR 1.7.3

Is there any way that I can fix it?

**Comment by km00700** [comment]
No. It should be patched in the next release.

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.
