### ISSUE TITLE
SERVER FUEL ERROR

### ISSUE THREAD

**Issue by ShaderName** [TeamOpenIndustry/ImmersiveRailroading#820]
When i tryed to fill my steam locomotive with water the level of water only grow until one exact point (server)

How to reproduce
Steps to reproduce the unwanted behavior: 

 1. Put any steam Locomotive in a server
 2. Try to fill it with water
 3. Water dont overpass a fake limit
 
Expected behavior  
If the steam locomotive have a limit like 270000mb of water this bug will make this 27000, 
examples: 
Peppercon 270000mb limit /error limit 27000mb
Big Boy 950000mb limit /error limit 95000mb
class 38 370000mb limit/error limit 37000mb
br 340000mb limit/error limit 34000mb

Screenshots
[image](https://user-images.githubusercontent.com/67617032/86079452-23df1e00-ba56-11ea-9417-6d8d8b96c376.png)
![image](https://user-images.githubusercontent.com/67617032/86079511-483afa80-ba56-11ea-9d47-1084c59ddede.png)
![image](https://user-images.githubusercontent.com/67617032/86079576-67d22300-ba56-11ea-9b12-c32620221e0f.png)

System Information  
 OS: [Windows 10]
 <br>System Memory: [e.g. "16gb"]
 <br>Allocated Memory: ["8gb"]
 <br>CPU: [e.g. "Intel I5 6500"]
 <br>GPU: [e.g. "AMD radeon 370 series sapphire nitro oc edition"]
 <br>IR-Version: [e.g. "1.7.3_1.12.2"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2847"]

Modlist  

![image](https://user-images.githubusercontent.com/67617032/86079811-fa72c200-ba56-11ea-8b63-ccec05a32939.png)
![image](https://user-images.githubusercontent.com/67617032/86079831-0b233800-ba57-11ea-9efc-36b840f3fea7.png)

 
**latest.log**
no latest log?
**Additional context**  
It is something about server side mod, i cant use the train with that low amount of water...

**Comment by robot256** [comment]
Did you change the immersiverailroading.cfg config file on either the client or the server?  Are they the same?

**Comment by km00700** [comment]
It looks the the server might have a different Mb multiplier in the config than your client.

**Comment by km00700** [comment]
server config will always overrule client config.

**Comment by ShaderName** [comment]
> server config will always overrule client config.

can i show you the config file of the mod in server and my minecraft?

**Comment by km00700** [comment]
sure, attach it here

**Comment by ShaderName** [comment]
# Configuration File
general {
    balance {
        # Cost to place down rail bed
        D:BedCostMultiplier=0.25
        
        # Prevent stock from being built outside the recommended and model gauges
        B:DesignGaugeLock=false
        
        # All gauges require fuel
        B:FuelRequired=true
        
        # MilliBuckets per Liter
        I:MB_PER_LITER=1
        
        # Models require fuel
        B:ModelFuelRequired=true
        
        # IEnergy cost (RF) per radio transmission per metre
        I:RadioCostPerMetre=0
        
        # Only select Locomotives with suitable equipment can be radio-controlled
        B:RadioEquipmentRequired=true
        
        # Range of radio-control, positive integer
        I:RadioRange=500
        
        # Cost to place down a rail
        D:RailCostMultiplier=0.25
        
        # Cost to place down a tie
        D:TieCostMultiplier=0.25
        
        # How heavy is a single block in Kg
        I:blockWeight=10
        
        # Brake Multiplier: Higher numbers increase slowdown, lower numbers decrease slowdown
        D:brakeMultiplier=1.0
        
        # Allow diesel locomotive engine overheating
        B:canDieselEnginesOverheat=true
        
        ##################################################################################
        # dieselFuels                                                                    #
        # ------------------------------------------------------------------------------ #
        # Fuels for diesel Locomotives                                                   #
        # Note: Naphtha of Thermal Foundation is internally registered as 'refined oil'. #
        ##################################################################################
        dieselFuels {
            I:diesel=200
            I:fuel_mixed_heavy=130
            I:lpg=150
            I:biofuel=170
            I:fuel=180
            I:oil_dense=110
            I:gasoline=100
            I:fuel_light=150
            I:oil_distilled=50
            I:ethanol=170
            I:kerosene=180
            I:refined_fuel=150
            I:refined_oil=100
            I:oil=100
            I:oil_heavy=70
            I:fuel_dense=110
            I:fuel_mixed_light=100
            I:biodiesel=170
            I:olive_oil=40
        }
        
        # How fast the diesel locomotive should heat up. 1 is real internal (slow), 72 is scaled to minecraft time
        I:dieselLocoHeatTimeScale=72
        
        # Diesel Fuel Efficiency
        I:locoDieselFuelEfficiency=100
        
        # How fast the steam locomotive should heat up.  1 is real internal (slow), 72 is scaled to minecraft time
        I:locoHeatTimeScale=72
        
        # Steam Fuel Efficiency
        I:locoSteamFuelEfficiency=100
        
        # How much water the locomotive should use
        F:locoWaterUsage=10.0
        
        # Machine power factor (0 means no power required)
        F:machinePowerFactor=1.0
        
        # Slope Multiplier: Higher numbers increase slowdown, lower numbers decrease slowdown
        D:slopeMultiplier=1.0
        
        # If more than X% of the tracks are above non solid block, break the track
        D:trackFloatingPercent=0.05
        
        # Traction Multiplier: Higher numbers decreases wheel slip, lower numders increase wheel slip
        D:tractionMultiplier=1.0
        
        # Distance the villagers will hear the conductor's whistle
        D:villagerConductorDistance=50.0
        
        # Villager payout items (ore dict)
        villagerPayoutItems <
            gemEmerald
        >
        
        # How much you getContents payed per meter the villager traveled (default 1 emerald per km)
        D:villagerPayoutPerMeter=0.001
        
        # Water Substitutes
        waterTypes <
            water
            dist_water
            hot_spring_water
            purified_water
        >
        
    }
    
    damage {
        # Trains should break block
        B:TrainsBreakBlocks=true
        
        # Clear blocsk in creative mode when placing tracks
        B:creativePlacementClearsBlocks=true
        
        # Drop snowballs when the train can't push a block out of the way
        B:dropSnowBalls=false
        
        # Break block around the border of the tracks in creative
        B:enableSideBlockClearing=true
        
        # km/h to damage 1 heart on collision
        D:entitySpeedDamage=10.0
        
        # Enable environmental damage of Boiler Explosions
        B:explosionEnvDamageEnabled=true
        
        # Enable Boiler Explosions
        B:explosionsEnabled=true
        
        # Requires solid block to be placed under the rails
        B:requireSolidBlocks=true
        
        # Trains getContents destroyed by Mob explosions
        B:trainMobExplosionDamage=true
        
    }
    
    debug {
        # Range between couplers to try coupling
        D:couplerRange=0.3
        
        # DEBUG: Buckets infinite fill/empty tanks
        B:debugInfiniteLiquids=false
        
        # Print extra chunk loading info
        B:debugLog=false
        
        # Deep Snow on tracks
        B:deepSnow=false
        
        # Keep rolling stock loaded even when it is not moving
        B:keepStockLoaded=true
        
        # DEV ONLY: How much to artifically lag the server (per internal)
        I:lagServer=0
        
        # Time between open computers poll ticks for augments
        I:ocPollDelayTicks=1
        
        # Old Narrow track placement (single width instead of 3)
        B:oldNarrowWidth=false
        
        # Speed up IR stock server onTick stepping to compensate for tps lag
        B:serverTickCompensation=false
        
        # How fast deep snow should melt, 0 = disabled, 20 = fast, 400 = slow
        I:snowMeltRate=0
        
    }
    
    performance {
        # Use multiple threads when loading stock. This is used on Minecraft's initial load or when manually reloading stocks.
        B:multithreadedStockLoading=true
        
    }
    
}
 some of that is different, or wrong?

**Comment by ShaderName** [comment]
(My minecraft IR config file)

# Configuration File
general {
    balance {
        # Cost to place down rail bed
        D:BedCostMultiplier=0.25
        
        # Prevent stock from being built outside the recommended and model gauges
        B:DesignGaugeLock=false
        
        # All gauges require fuel
        B:FuelRequired=true
        
        # MilliBuckets per Liter
        I:MB_PER_LITER=10
        
        # Models require fuel
        B:ModelFuelRequired=true
        
        # IEnergy cost (RF) per radio transmission per metre
        I:RadioCostPerMetre=0
        
        # Only select Locomotives with suitable equipment can be radio-controlled
        B:RadioEquipmentRequired=true
        
        # Range of radio-control, positive integer
        I:RadioRange=500
        
        # Cost to place down a rail
        D:RailCostMultiplier=0.25
        
        # Cost to place down a tie
        D:TieCostMultiplier=0.25
        
        # How heavy is a single block in Kg
        I:blockWeight=10
        
        # Brake Multiplier: Higher numbers increase slowdown, lower numbers decrease slowdown
        D:brakeMultiplier=1.0
        
        # Allow diesel locomotive engine overheating
        B:canDieselEnginesOverheat=true
        
        ##################################################################################
        # dieselFuels                                                                    #
        # ------------------------------------------------------------------------------ #
        # Fuels for diesel Locomotives                                                   #
        # Note: Naphtha of Thermal Foundation is internally registered as 'refined oil'. #
        ##################################################################################
        dieselFuels {
            I:diesel=200
            I:fuel_mixed_heavy=130
            I:lpg=150
            I:biofuel=170
            I:fuel=180
            I:oil_dense=110
            I:gasoline=100
            I:fuel_light=150
            I:oil_distilled=50
            I:ethanol=170
            I:kerosene=180
            I:refined_fuel=150
            I:refined_oil=100
            I:oil=100
            I:oil_heavy=70
            I:fuel_dense=110
            I:fuel_mixed_light=100
            I:biodiesel=170
            I:olive_oil=40
        }
        
        # How fast the diesel locomotive should heat up. 1 is real internal (slow), 72 is scaled to minecraft time
        I:dieselLocoHeatTimeScale=72
        
        # Diesel Fuel Efficiency
        I:locoDieselFuelEfficiency=100
        
        # How fast the steam locomotive should heat up.  1 is real internal (slow), 72 is scaled to minecraft time
        I:locoHeatTimeScale=72
        
        # Steam Fuel Efficiency
        I:locoSteamFuelEfficiency=100
        
        # How much water the locomotive should use
        F:locoWaterUsage=10.0
        
        # Machine power factor (0 means no power required)
        F:machinePowerFactor=1.0

**Comment by km00700** [comment]
Your client has a value of:
`    # MilliBuckets per Liter
    I:MB_PER_LITER=10`
Your server has the default value of:
`    # MilliBuckets per Liter
    I:MB_PER_LITER=1`
So your client thinks it can load 10x more fuel than the server allows.

**Comment by ShaderName** [comment]
ok, i will try fix that

**Comment by ShaderName** [comment]
one question more, which one is the default set? (which one is the correct set?)

**Comment by km00700** [comment]
Answered above.

**Comment by ShaderName** [comment]
ok, thank you. That didm't work
![image](https://user-images.githubusercontent.com/67617032/86083402-c51ea200-ba5f-11ea-8805-ab42f3d6e370.png)

**Comment by km00700** [comment]
you've restarted your game, right?

**Comment by ShaderName** [comment]
no, i did not, i will try

**Comment by ShaderName** [comment]
Look this, is the real limit?  16000mB (Skookum)
![image](https://user-images.githubusercontent.com/67617032/86084026-65c19180-ba61-11ea-9a6e-4b3f6df2ca18.png)

**Comment by km00700** [comment]
yes

**Comment by ShaderName** [comment]
Thank you for your help, GREAT SUPPORT!
