### ISSUE TITLE
Weird issues with a Server error message that seems to be recorded every second the server is active. Anyone know how to fix this please?

### ISSUE THREAD

**Issue by Visceralfulton** [TeamOpenIndustry/ImmersiveRailroading#821]
[universalmodcore]: Multiblock TE is null: BlockPos{x=-233, y=69, z=398} BlockPos{x=1, y=0, z=0} false class cam72cam.immersiverailroading.multiblock.RailRollerMultiblock$RailRollerInstance

It would be greatly appreciated if someone could help me out please.

**Comment by km00700** [comment]
It means that there's a railRoller MultiBlock whose TileEntity has been deleted. The fix for that is to open that map in MCEdit and delete the multiblock structure that contains those BlockPos coordinates and the entities in that selection area.

**Comment by Visceralfulton** [comment]
I cant seem to  figure out how to get the version of MC that I am using with my Modpack which is Sevtech.Everytime I attempt to try and find the MC version for MCEdit to work I cant seem to find it at all in any folders or instances

**Comment by neronakoma** [comment]
MCedit unfortunately does not have a 1.12 supported version to it, however if you know where the area is that is affected you can reset the area chunk using world edits /regen command.

**Comment by septer99** [comment]
This can also be caused by the trafficcontrol mod, this is something I've had experience with.
