### ISSUE TITLE
IR with LiteLoader and Immersive Vehicles causes audio issues for IV

### ISSUE THREAD

**Issue by PeculiarSana** [TeamOpenIndustry/ImmersiveRailroading#823]
**Describe the bug**  
Having Immersive Railroading, Immersive Vehicles and LiteLoader installed together causes all audio played by Immersive Vehicles to cease functioning. Presumably an issue with LiteLoader, but posting the issue anyway just in case.

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory: 16gb
 <br>Allocated Memory:6gb
 <br>CPU: Intel i7-6700k
 <br>GPU: Nvidia GeForce GTX 1070
 <br>IR-Version: 1.7.3_1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2838

**Modlist**  

- Immersive+Vehicles-1.12.2-18.2.0
- ImmersiveRailroading-1.7.3_1.12.2
- Liquid's-Vehicles-Pack-v2.2
- liteloader-1.12.2-SNAPSHOT-release
- MTS_Official_Pack_V16
- TrackAPI-1.2

 
**latest.log**
https://pastebin.com/sBF1Dipd

**Comment by CSX8600** [comment]
Per the Immersive Vehicles Discord, this is an issue with Immersive Railroading.  The only way to get the audio to work correctly right now is to start Minecraft and let it load in the foreground.  If you don't hear button clicks on the main menu, you'll have to restart and try again.  It's super annoying.

**Comment by km00700** [comment]
Currently neither mod has anything obvious and glaring that should cause this. It's likely an issue that lies deeper down that's created after liteloader code injection.

**Comment by CSX8600** [comment]
I should note that I have this issue and do NOT use liteloader

**Comment by km00700** [comment]
System specs?

**Comment by cam72cam** [comment]
@PeculiarSana have you tried changing the IR sound config 'overrideSoundChannels' to false?

**Comment by cam72cam** [comment]
Probably fixed in the test-builds, will be in the next release.
