### ISSUE TITLE
new caching system idea?

### ISSUE THREAD

**Issue by NightScale5755** [TeamOpenIndustry/ImmersiveRailroading#826]
**Describe the suggestion**  
A clear description of what the suggestion is. This template is not for requesting additional models of locomotives, cars, or other rolling stock; those requests should be taken to the Immersive Railroading Discord channel under #suggestions. 
Link: https://discord.gg/CS2RTGq

hi. I do have a suggestion for a better game booting system with IR.
What if the current IR caching system, instead of the current way it works currently. Creates a cache/list of the IR textures/tex-names/models/model-names? And reads said cache/list on game boot. If the texture lists don't match, it redoes the caching system. And if they do match, it just loads the textures/models in a faster manner?

**Applications of the suggestion**  
A description of what the suggestion is needed for, or how it would improve the gameplay experience.

My suggestion would, in theory, help with the long load times. Possibly improve performance as well

**Comment by cam72cam** [comment]
IR already does this behind the scenes
