### ISSUE TITLE
Not using all VRAM

### ISSUE THREAD

**Issue by DiFFoZ** [TeamOpenIndustry/ImmersiveRailroading#827]
**Describe the bug**  
Not using all VRAM ( only 1GB ). Starting spamming `[universalmodcore]: GPU Memory: 100% 1024/1024MB`.

**System Information**  
 OS: Windows
 <br>System Memory: 8 GB
 <br>Allocated Memory: 4 GB
 <br>CPU: Ryzen 1600
 <br>GPU: MSI Radeon 580 RX 8 GB VRAM
 <br>IR-Version: 1.7.2_1.12.2
 <br>Forge-Version: 1.12.2-forge-14.23.5.2854

**Modlist**  
https://pastebin.com/fFX3EFMU
 
**latest.log**
https://gist.github.com/DiFFoZ/8c879dd4a4573e646f070c523dda5bd9

**Comment by km00700** [comment]
do you have a screenshot of your F3 screen?

**Comment by DiFFoZ** [comment]
here
![2020-07-24_04 08 57](https://user-images.githubusercontent.com/48765566/88339021-7f55b080-cd63-11ea-85a3-e7707163923a.png)

**Comment by Larky2k** [comment]
DiFFoZ
try the work around from this issue raised and see if that fixes it
https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/803

**Comment by DiFFoZ** [comment]
Is fixed, thanks
