### ISSUE TITLE
[Feature Suggestion] Track lengh config option

### ISSUE THREAD

**Issue by olegikoligik** [TeamOpenIndustry/ImmersiveRailroading#829]
At the moment, the maximum length of a track segment is 1m. After 1m it is repeated.

Suggestion is to add an option for the config file to change the segment length.

For what?
This will allow you to create more interesting options for tracks and not only (for example, slightly hanging wires, a fence - mesh).

P.S. There would also be a cool segment randomness function. For example this will allow you to create damaged / varied track segments. However, I understand that all this may not be easy to do.

**Comment by cam72cam** [comment]
Closing as won't fix.  It's way too much work given the way the track system currently works.
