### ISSUE TITLE
Changing coal stacks in GUI messes up count.

### ISSUE THREAD

**Issue by DonBruce64** [TeamOpenIndustry/ImmersiveRailroading#83]
Right-clicking on a coal stack in the locomotive GUI, and then left-clicking on the same slot results in the coal stack being destroyed.  After this right-clicking on another slot in the bunker causes the first slot to gain coal and the second slot to lose it.  This appears to be client-side only, as the correct amount is displayed after closing and re-opening the GUI.

Additionally, attempting to add coal to a stack results in a wrong count on the GUI, but like the above is fixed by re-opening the GUI.

**Comment by redstone2019** [comment]
I have a similar thing:
https://drive.google.com/file/d/1rJWr77PcJxikaeHBdIVFgjP3retw3lZF/view?usp=sharing

**Comment by cam72cam** [comment]
Fixed finally!
