### ISSUE TITLE
Unable to control locomotives with laptop numbers

### ISSUE THREAD

**Issue by Unusual-Danger** [TeamOpenIndustry/ImmersiveRailroading#832]
**Describe the bug**  
A clear description of what the bug is.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to locomotive
 2. Try controlling
 3. Nothing happens
 
**Expected behavior**  
 A clear description of what you expected to happen.
The locomotive will move

**Screenshots**  

**System Information**  
 OS: [e.g. Windows 10]
 <br>System Memory: [e.g. "8gb"]
 <br>Allocated Memory: [The memory allocated to your Minecraft instance where you encountered the bug e.g. "N/A"]
 <br>CPU: [e.g. "Intel i7 8550u "]
 <br>GPU: [e.g. "N/A"]
 <br>IR-Version: [e.g. "1.6.1_1.12.2"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2820"]

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.
 Railcraft
Weather2
Buildcraft
Twilight Forest
The Aether
Iron Chest
Dense Ore

**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.
N/A
**Additional context**  
Provide any additional information that might help us fix the bug.
I play on a laptop since I don't have money for a pc

**Comment by km00700** [comment]
Make sure numlock is on.

**Comment by km00700** [comment]
If it's not, then your number keys map to functions that are not numbers.

**Comment by Unusual-Danger** [comment]
How do I turn number lock on?

**Comment by km00700** [comment]
Press the NumLock key on your keyboard to toggle it.

**Comment by Unusual-Danger** [comment]
about that
my laptop keyboard doesn't have a number lock and I cant find one in settings

**Comment by km00700** [comment]
do you have a numpad at all?

**Comment by Unusual-Danger** [comment]
All I have is a row of numbers on the top of my keyboard

**Comment by km00700** [comment]
then you won't have a NumLock. You need to rebind the IR controls to other keys in the MC controls menu.

**Comment by Unusual-Danger** [comment]
What keys would you recommend

**Comment by km00700** [comment]
any that aren't being used by other mods.

**Comment by Unusual-Danger** [comment]
got it and I will now end this
