### ISSUE TITLE
speed glitch

### ISSUE THREAD

**Issue by Baconverse** [TeamOpenIndustry/ImmersiveRailroading#833]
**Describe the bug**  
Every 1 out of 12 times, my trains speed up instantly to anywhere from 300 to 500 km per hour.

**How to reproduce**  
it happens by itself randomly.
 
**Expected behavior**  
 I expected every thing to run at there written top speed 

**Screenshots**  

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory: [e.g. "8gb"]
 <br>Allocated Memory: [The memory allocated to your Minecraft instance where you encountered the bug e.g. "4gb"]
 <br>CPU: [e.g. "Intel I7 7700k"]
 <br>GPU: [e.g. "MSI 1080 8gb"]
 <br>IR-Version: [e.g. "1.6.1_1.12.2"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2844"]

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by andrboot** [comment]
You are on a very old version of IR, stable IR is now 1.7.3, please update.
