### ISSUE TITLE
Ability to replace the classic rails via resourcepacks

### ISSUE THREAD

**Issue by CaptainSkipper** [TeamOpenIndustry/ImmersiveRailroading#839]
Rail models included in resourcepacks should be able to override the mod-intern rail models, as long as they match certain criteria (i.e. the naming scheme "default, "concrete", "railsonly").

This feature will allow for users to play on already published maps without having to replace the old rails with the new ones. (This issue is specifically for the voxel pack)

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.

**Comment by facetorched** [comment]
It would be great if there was a blacklist.json for tracks as well :)
