### ISSUE TITLE
Trains blinking when riding it.

### ISSUE THREAD

**Issue by Gartosz** [TeamOpenIndustry/ImmersiveRailroading#840]
Hello, I would like to know if there is a planned date of release of the new version with the rendering improvements? In version 1.6.1 using trains was quite nice and every release after it has that annoying bug. I've heard that it should be repaired in the next version, but last update was 5 months ago.

**Comment by lordfriend** [comment]
Have the same issue with 1.7.3 in Minecraft 1.12.2. 
I have the same modpack with friends, but he doesn't have the issue.

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.
