### ISSUE TITLE
I'm guessing you're using an Aternos server?

### ISSUE THREAD

**Issue by TimerLuke** [TeamOpenIndustry/ImmersiveRailroading#843]
I am also using aternos but it wotn work no matter what i did it still will say "rolling stock does not exist" i need help please.

**Comment by Larky2k** [comment]
What pack you trying to use?

**Comment by SteampsonJake** [comment]
IR doesn't work with Aternos servers

**Comment by TimerLuke** [comment]
> What pack you trying to use?

I was trying to use the CD pack its a czechoslovakian train pack and im guessing its impossible to use them.
