### ISSUE TITLE
IR resource packs not working with Minecraft server on 1.12.2

### ISSUE THREAD

**Issue by WholeaseFight124** [TeamOpenIndustry/ImmersiveRailroading#844]
**Describe the bug**  
So,I was testing out the Immersive Railroading mod 1.12.2 on my minecraft server with many other mods.I wanted to add some more resource packs for IR so I could have more trains for it.When I try placing ANY resource pack trains(btw. resource packs are MatoiVanillaPack(IR) and UNU CivilPack(.jar file) ),it displays ВО-2 error(watch the screenshot)

 

**Screenshots**  
![image](https://user-images.githubusercontent.com/71653925/93782513-55b9e800-fc33-11ea-8a90-bad1a252c159.png)

error BO-2: error of access to rolling stock

Same thing with MatoiVanillaPack
![image](https://user-images.githubusercontent.com/71653925/93782723-944fa280-fc33-11ea-9790-5c4ae7a1da26.png)

**Modlist**  

![image](https://user-images.githubusercontent.com/71653925/93782762-9fa2ce00-fc33-11ea-9a6f-c85733973c3d.png)

**Comment by ThePiGuy24** [comment]
Did you put the packs in `config/immersiverailroading` on the server?

**Comment by WholeaseFight124** [comment]
I put them in config folder and now it works!Thank you
