### ISSUE TITLE
Resource Packs for server?

### ISSUE THREAD

**Issue by Jackboy317** [TeamOpenIndustry/ImmersiveRailroading#846]
So I followed the correct steps for installing resourcepacks onto a server, putting the zips into the config/immersiverailroading folder,
Yet when I Try to start the server, it doesn't load the packs and crashes the server while starting. attached is the log.
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5361398/latest.log)

Any ideas on how to fix this?

**Comment by km00700** [comment]
The server isn't crashing. It's shutting down due to another instance running on that port.

**Comment by Jackboy317** [comment]
> The server isn't crashing. It's shutting down due to another instance running on that port.

Oh I see, thanks for helping!
