### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by alnega31** [TeamOpenIndustry/ImmersiveRailroading#849]
Ok so me anda muy Friends want to do a server with this awesome mod and more others. I know that the mod is quite heavy (99 mb) and we were wondering if someone has tried it with maybe 40 more mods for example in a server. I just want some information because we are looking for a train mod for 1.12.2 and the others are or not made for 1.12 or too shity but this one is very nice but quite heavy.  Is this mod going to lay the server much? Thanks everyone

**Comment by cam72cam** [comment]
It should be ok.  Also the 1.8 update (coming in the next month or so) should make it even lighter
