### ISSUE TITLE
Broken slope

### ISSUE THREAD

**Issue by kippari2** [TeamOpenIndustry/ImmersiveRailroading#851]
When i was changing the slopes lenght it got distorted.
The bug ofcourse affects the model of the slope.
  
Steps to reproduce the unwanted behavior:

 1. Change the track type to slope
 2. Set lenght to 1
 3. Place it
  
The Track will get all cut up in parts that float in the air.

Screenshot of the event
![2020-10-26_16 14 07](https://user-images.githubusercontent.com/73481094/97183343-57347e00-17a6-11eb-9cf7-bf0efeab094c.png)
  
I believe it to be caused by the way you build/render the tracks since there is no error code nor crash.

Modlist 
https://www.curseforge.com/minecraft/mc-mods/immersive-railroading/files/2913738
https://www.curseforge.com/minecraft/mc-mods/track-api/files/2825261

Logs 
Unfortunately the file is too large to paste anywhere so here is a link to download:
https://drive.google.com/file/d/16Nz-vDg3B8AprYoFJtb5eg97J-AdhuZD/view?usp=sharing

Possible solution
Change the way to build/render the model of the slope.

I am aware that it should work on all versions. Atleast in 1.12.2 and 1.14.4

Thanks again!

**Comment by cam72cam** [comment]
CLosing as won't fix.
