### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by cam72cam** [TeamOpenIndustry/ImmersiveRailroading#852]
**Describe the bug**  
Crankshaft and fan diesel parts do not have translations

**How to reproduce**  
JEI search immersive on 1.8rc3
 
**Expected behavior**  
A translation is used

**System Information**  
 OS: Linux FTW
<br> IR-Version: 1.12.2
<br> Forge-Version: latest stable

**Comment by Jimmy805** [comment]
Just out of curiosity, when are you likely to release the new version? (Don't worry. I'm not urging you.)

**Comment by cam72cam** [comment]
By the end of the year

**Comment by Jimmy805** [comment]
December?
