### ISSUE TITLE
Crash after breaking some Blocks with rails .

### ISSUE THREAD

**Issue by SoulOfFox** [TeamOpenIndustry/ImmersiveRailroading#855]
[crash-2020-11-05_12.48.04-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5494190/crash-2020-11-05_12.48.04-client.txt)

Here's the crash report . I really hope that's fixable , because the world is really important to me where it happend .

I'm sorry for my English , I'm not a native english speaker.

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.
