### ISSUE TITLE
Track Augment for Fast Loading of Locomotives and Stock

### ISSUE THREAD

**Issue by Some1C** [TeamOpenIndustry/ImmersiveRailroading#864]
**Description of Suggestion**
basically, something like a Loading Platform or a Coal Bunker/ Water tower, which has it's own inventory and has the ability to discern when a car is present withins it's range, and be able to load the car automatically from it's internal inventory, should be able to hold liquids, and Items, (maybe be able to fast load livestock within it's range if possible) and maybe act like a ME system where objects can be imported and exported to it automatically. Should also be able to detect if a car cannot take what it has. If automatic loading isn't possible, maybe an a menu where the player can drag or move stuff from a Me system like inventory.

**Applications of the suggestion**  
Would massively increase the speed of getting locomotives and stock loaded up and make the overall player experience quicker and nicer, along with just adding nice realism bonuses

**Comment by cam72cam** [comment]
I'm not planning on doing much more with the augments, next step is multiblocks for loading/unloading
