### ISSUE TITLE
Turning on a multi-unit train from one loco

### ISSUE THREAD

**Issue by SteampsonJake** [TeamOpenIndustry/ImmersiveRailroading#865]
The ability to turn all diesel locomotives in a consist at once from one loco. Would make multi-headed and push-pull consists easier to manage.

**Comment by WrongWeekend** [comment]
Generally speaking, this is not something MU-capable diesel locomotives are able to do. Earlier generations of diesel locomotives in particular require each locomotive in a consist to be started manually from within the engine compartment.

**Comment by robot256** [comment]
Yeah, I think it's enough that the throttles and brakes be synchronized, and properly reversed for locomotives connected in opposite directions (which I think will be new in the next version).

**Comment by km00700** [comment]
They already reverse based on loco direction.
