### ISSUE TITLE
Possible Compatibility error with bspkrsCore

### ISSUE THREAD

**Issue by Some1C** [TeamOpenIndustry/ImmersiveRailroading#866]
Crash caused on startup and no Crash report is generated, Unknown as to the exact issue. Repeatable and removing BspkrsCore fixes the issue.

**Comment by facetorched** [comment]
The error shows up in the log https://pastebin.com/0i9iR0Wd

modlist:
FML@7.10.99.99
trackapi@1.2,ImmersiveEngineering@0.7.7
Forge@10.13.4.1614
bspkrsCore@6.16,mcp@9.05
immersiverailroading@1.8.rc1
universalmodcore@0.1.0

**Comment by cam72cam** [comment]
Closing as won't fix.  UMC is incompatible with BspkrsCore.  They rewrote a ton of internal minecraft functionality that we depend on.
