### ISSUE TITLE
Odd thing about dying near an unmanned locomotive

### ISSUE THREAD

**Issue by RealisticMC73309** [TeamOpenIndustry/ImmersiveRailroading#868]
**Describe the bug**  
I went to test 2 mods, immersive railroading and whisperwoods and I let an unmanned locomotive run to see if any bugs will araise from leaving a loco do its own thing while looking for bugs in a whisperwood's mob's behaviour. The whisperwoods mob killed me, I respawned and the train was stopped. It's wheels were still rotating, its sound was going but it didn't move. And I couldn't board the loco (well I could but it put me awhile down the track spinning in place until I dismounted)
Second time I let the loco run on its own and did /kill and then respawned and again the loco stopped, and continued making noise

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. choose a locomotive (idk if it makes a difference but I was using a diesel)
 2. fuel it up and throttle up and let it move on its own(without you in the cab)
 3. do ./kill to kill yourself and then respawn and check back at the loco
 
**Expected behavior**  
 what should happen is that the loco should continue moving even after a player death

**Screenshots**  
 already put some in discord

**System Information**  
 OS: winters 10
 <br>System Memory: [e.g. 16gb
 <br>Allocated Memory: 9gb
 <br>CPU: [e.g. "Intel I7 7700k"]
 <br>GPU: [e.g. "MSI 1080 8gb"]
 <br>IR-Version: [e.g. "1.6.1_1.12.2"]
 <br>Forge-Version: 1.15.2 31.2.45

**Modlist**  
 immersive railroading
betteranimalsplus
betteranimals
iceandfire
wyrmroost
whisperwoods
optifine
terrafoirged
just enough items
 
already gave a log as you know

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by cam72cam** [comment]
Fixed
