### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by Macintosh-Fan** [TeamOpenIndustry/ImmersiveRailroading#869]
**Describe the bug**  
A clear description of what the bug is.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to ...
 2. Do ...
 3. ...
 
**Expected behavior**  
 A clear description of what you expected to happen.

**Screenshots**  

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory: [e.g. "8gb"]
 <br>Allocated Memory: [The memory allocated to your Minecraft instance where you encountered the bug e.g. "4gb"]
 <br>CPU: [e.g. "Intel I7 7700k"]
 <br>GPU: [e.g. "MSI 1080 8gb"]
 <br>IR-Version: [e.g. "1.6.1_1.12.2"]
 <br>Forge-Version: [e.g. "1.12.2 - 14.23.5.2844"]

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by Macintosh-Fan** [comment]
@cam72cam Sorry but I accidentally pressed enter. Just edited my comment.

**Comment by cam72cam** [comment]
Good news it's already fixed in the test builds and should be in the next release (coming soon)

**Comment by Macintosh-Fan** [comment]
> Good news it's already fixed in the test builds and should be in the next release (coming soon)

@cam72cam Is there a way for me to be notified about the next release?

**Comment by km00700** [comment]
We notify members on the Immersive Railroading discord when a new update is out.
https://discord.gg/jTFennYGMM
