### ISSUE TITLE
Big Boy 4000 class train heats up too quickly and blows up my whole station.

### ISSUE THREAD

**Issue by Macintosh-Fan** [TeamOpenIndustry/ImmersiveRailroading#870]
MC 1.12.2

I was just using this train and it heated to 100°C+ and the pressure increased too quickly and sometimes resets, but then one other time, it blew up my whole train station!
![image](https://user-images.githubusercontent.com/50642934/100699269-5b2c6080-334f-11eb-966f-36a95b177ecb.png)

I'm not sure if the train is supposed to do this but it seems a bit unusual when compared to real-life trains.

**Comment by robot256** [comment]
Was the engine full of water before you put fuel in?  Have you changed any config options (like mb_per_liter)?

**Comment by Macintosh-Fan** [comment]
> Was the engine full of water before you put fuel in? Have you changed any config options (like mb_per_liter)?

It did the weird reset thing in either case: with water first then coal/coal first then water. However, it did explode with fuel before water.

**Comment by robot256** [comment]
Exploding after inserting coal first then water is correct.  Randomly resetting while heating up is probably not.  Maybe try disabling engine explosions and do some more tests to figure out what is going on with that.  Post the rest of the stuff needed for a bug report (mainly a log file showing your mod list and the time period where one of these resets happens).
