### ISSUE TITLE
1.12.2 Crash after placing of locomotive

### ISSUE THREAD

**Issue by Pavelsvt** [TeamOpenIndustry/ImmersiveRailroading#871]
I use the currently latest release of IR and US steam loco pack. When I place a PS4 or G-3 class engine, it places, but about a second later the game crashes. And when I reload the world, it crashes again. The crash screen refers to their obj.png files.
Is there any way to fix this? I really like the pack and there are many really useful engines. Even PS4 and G-3 are obviously quality models, there is just that nasty bug that crashes the game.
RAM should not be the issue. I have 16GB in total and 12GB allowed for MC.

**Comment by km00700** [comment]
Delete the cache folder from your instance directory, then relaunch.

**Comment by Pavelsvt** [comment]
Thanks, problem solved.
By the way, is there any chance to fix the issue with icons/thumbnails?
![thumbnails](https://user-images.githubusercontent.com/73953849/101484692-4dcc3300-395a-11eb-880f-66199bbecf77.png)

**Comment by km00700** [comment]
Do you have Optifine installed? If so, disable fast render, delete cache, and relaunch.

**Comment by Pavelsvt** [comment]
Thank you, this problem is now also solved.
