### ISSUE TITLE
Can you update this mod to version 1.16.4 (using fabric API)

### ISSUE THREAD

**Issue by EDGW** [TeamOpenIndustry/ImmersiveRailroading#873]
This article is a machine-translated foreign language into English. Please understand the improper use of words.

I am a server administrator using the fabric server. Now we want to add train-related content to the server. I think your mod is very good and suitable for us. I hope you can upgrade this mod to 1.16.4 for Minecraft  Version, thanks a lot.

Original:
Title:
你能把这个mod更新到1.16.4(使用fabric API)版本吗.
Text:
本文是外文由机器翻译成英文，用词不当之处请谅解。
我是一个使用fabric服务端的服务器管理员，现在我们想在服务器里加入与火车有关内容，觉得您的这个mod十分优秀且适合我们，希望您能将这个mod升级到适用于我的世界1.16.4 的版本，万分感谢

**Comment by VirtualGaming1** [comment]
#856

**Comment by cam72cam** [comment]
I am planning on releasing the next version soon with forge support for 1.16.4.  A fabric equivalent is planned before the end of the year.
