### ISSUE TITLE
Errored Datapack - Invalid tag references

### ISSUE THREAD

**Issue by Nachtflame** [TeamOpenIndustry/ImmersiveRailroading#876]
ImmersiveRailroading-1.16.4-forge-1.8.0-7e0f82
TrackAPI-1.16.4-forge-1.2
UniversalModCore-1.16.4-forge-1.0.0-fixed
1.16.4-forge-35.1.13

Loaded with ONLY the above to double-check. logs below

[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5685207/latest.log)
[debug.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5685208/debug.log)

**Comment by cam72cam** [comment]
Wrong reported the same thing, the initial UMC issues I had today caused some resources not to be generated correctly.  Will have a new jar soon with a fix
