### ISSUE TITLE
Trains wont move when in server, rolling stock does not exist 

### ISSUE THREAD

**Issue by ShavdMercury** [TeamOpenIndustry/ImmersiveRailroading#877]
Hi guys, i created a server that has immersive railroading in it. I have the IR .jar installed both client and server side, along with the track api. When in singleplayer, everything works fine. The trains move, i can place all the cars, etc... When on my server, i can place certain engines, but i cant get them to move, and i cant place cars. I have the ir .jar in config/immersiverailroading as a zip file on the server side, and in the mods folder as a .jar on the client side. Is there anything im missing? thank you!

**Comment by cam72cam** [comment]
Can you provide a log file (client and server side)

**Comment by ShavdMercury** [comment]
Forgive me for my lack of knowledge, but where would i find a log file?

**Comment by ShavdMercury** [comment]
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5685262/latest.log)

Here we go!

**Comment by cam72cam** [comment]
hmm, that looks like the client log, nothing strange in there.

Did you say that you have "the ir .jar in config/immersiverailroading as a zip file on the server side"?  That won't work.  It needs to be added to the mods folder as any normal mod as a jar.

**Comment by ShavdMercury** [comment]
I do have it in the config/immersiverailroading as a .zip. I had originally had it in the mods folder as a .jar on the server side and it still had the same issue

**Comment by Carzie123** [comment]
Hi, I'm having the same issue, and I have a list of mods for you to see what might be conflicting. If you need any more information please let me know.

Here are the mod file names without the .jar part (not including immersive railroading and immersive engineering):
animania-1.12.2-base-2.0.3.28
animania-1.12.2-extra-1.0.2.28
animania-1.12.2-farm-1.0.2.28
Baubles-1.12-1.5.2
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
DoggyTalents-1.12.2-1.15.1.6
ElectroblobsWizardry-4.3.4-MC1.12.2
iChun-Util-Mod-1.12.2
jei_1.12.2-4.16.1.301
LLibrary-1.12.2
LucraftCore-1.12.2-2.4.16
Morph-1.12.2-7.2.1
PymTech-1.12.2-1.0.2
TFSpellPack-1.1.0-MC1.12.2
twilightforest-1.12.2-3.11.1021-universal
wings-1.1.6-1.12.2
xray-1.12.2-1.6.0
