### ISSUE TITLE
1.12.2 forge server crash 

### ISSUE THREAD

**Issue by TJDS92212** [TeamOpenIndustry/ImmersiveRailroading#878]
[crash-2020-12-13_19.18.04-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5685277/crash-2020-12-13_19.18.04-server.txt)

Everything appeared to be working until I flew towards an area with a a large amount of rolling stock when the server abruptly crashed. Attempts to restart and join the server result in the same crash to repeat.

The world that was loaded was started in IR version 1.5.0 and has now been updated to IR version 1.8.0.

The forge server is locally hosted on my PC.

**Comment by cam72cam** [comment]
I did not test the 1.5.0 to 1.8 upgrade path, that's an old version.

A) Do you have a world backup?
B) I'll take a deeper look tonight and may send you a custom jar in the mean time

**Comment by TJDS92212** [comment]
I've been using the 1.5.0 version of IR as newer versions have not always worked well on my server. I do have a back-up of the world file so there should be no problems there. Any time that you can spare for this problem would be greatly appreciated. In the meantime I have an idea or two to try and get around the issue myself.

**Comment by TJDS92212** [comment]
After backdating the IR version back to 1.5.0, removing all of the steam locomotives, saving the world and then using IR version 1.8.0 again, I have managed to get around the issue that was causing the crash.

**Comment by cam72cam** [comment]
interesting, if the world is a reasonable size, would you mind uploading it somewhere so I can trace down the bug?

**Comment by cam72cam** [comment]
I'm glad you found a good work around in the mean time :)

**Comment by TJDS92212** [comment]
[Great Central Railway (1.5.0 with steam locos).zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5692384/Great.Central.Railway.1.5.0.with.steam.locos.zip)

This should be the offending world save. I believe you'll need the following extra 1.12.2 mods/IR resource packs:

Mods:
Immersive Engineering 
Immersive Petroleum
LittleTiles
ProjectRed 
Railcraft

Resource packs: 
BAM
BoCo's British Pack
Dragon's BR/GWR/LMS/LNER/SR steam
Dragon's Modern British
Heavy Industrial
Old Timey Engines

**Comment by TJDS92212** [comment]
To aid you in your investigation, the forge server crashed when I loaded in the area around x=1928.50, y=22.35, z=-2264.64 which is where almost all of the steam locomotives on the map are located.
