### ISSUE TITLE
Railbed glitch?

### ISSUE THREAD

**Issue by francoisM77** [TeamOpenIndustry/ImmersiveRailroading#880]
Whenever I put anything other than air as a railbed on any track type, all the railbed pieces appear at a crazy angle and I'm not sure why it is being caused. It has been present from the installation of the mod which I only installed about an hour ago. 
![2020-12-14_13 18 13](https://user-images.githubusercontent.com/70468959/102028432-26b8aa00-3e0f-11eb-98df-25c9ca83e7d4.png)

**Comment by cam72cam** [comment]
Certain shaders don't play nicely with IR on 1.14+.  Give a different shader a try.  I still need to look deeper into this issue.

**Comment by francoisM77** [comment]
> Certain shaders don't play nicely with IR on 1.14+. Give a different shader a try. I still need to look deeper into this issue.

Ah yes, I did find that turning shaders off solved the issue. This mod must be insane complicated so its understandable to have this issue, thanks for your help.

**Comment by cam72cam** [comment]
Fixed in the next version
