### ISSUE TITLE
Using manual to build machines does not use materials in inventory

### ISSUE THREAD

**Issue by Railroadactive** [TeamOpenIndustry/ImmersiveRailroading#883]
When using the manual to build machines in version 1.8.0.1, the materials are not removed from the player inventory in survival. It will not build the structure if the necessary blocks are not in player inventory but if they are it doesn't remove the needed blocks so none are used. To repeat, go into survival mode and get the blocks needed to build machine, use the IR manual to build them and place down machine and check inventory. None of the blocks should disappear

**Comment by cam72cam** [comment]
I'm actively working on this :)
