### ISSUE TITLE
[1.12.2] Game Crash when Looking at Rail Block, Likely Related to WAILA

### ISSUE THREAD

**Issue by jdawg3636** [TeamOpenIndustry/ImmersiveRailroading#885]
**Describe the bug**  
Game crashes when looking at rail block. Obviously a conflict with another mod, guessing this was a result of the transition to Universal Mod Core but haven't tested on older versions.

**How to reproduce**  
Take a rail from the creative tab, place it, and look at it. (See the additional context section at the bottom for more info)

**System Information**  
 OS: Windows 8.1
 <br>System Memory: 16GB
 <br>Allocated Memory: 10GB
 <br>CPU: AMD A8-6500
 <br>GPU: Integrated
 <br>IR-Version: ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82.jar
 <br>Forge-Version: forge-1.12.2-14.23.5.2847.jar 

**Modlist**  
https://pastebin.com/1xc5kWi3
 
**latest.log**
https://pastebin.com/m5BG1abm

**Additional context**  
This crash was produced while connected to a dedicated server, tried to reproduce in singleplayer and crashed just by opening the creative tab (no taking it out or placing required). VanillaFix is installed and suggested that CodeChickenCore could be related to the crash, though given the error message in the original crash report I'm more inclined to blame WAILA.

**Comment by km00700** [comment]
The transition to modcore was actually in IR 1.7.0. 1.8.0 just moved UMC to a separate jar file. 

Is that the latest version of Quark? IR 1.8.0 + certain versions of quark + some other yet to be isolated mod/mods cause a crash.

**Comment by jdawg3636** [comment]
Just tested on an older version [https://www.curseforge.com/minecraft/mc-mods/immersive-railroading/files/2913751](https://www.curseforge.com/minecraft/mc-mods/immersive-railroading/files/2913751) with all of the other mods the same and it works just fine.

The pack is derived from [this](https://www.curseforge.com/minecraft/modpacks/mc-eternal-lite) by the way if you're trying to reproduce the environment, only a few minor changes:
 Updated CreativeCore and LittleTiles. Added AmbientSounds 3, jdawg3636's Bleach Mod, MalisisCore, MalisisDoors, Modular Powersuits, Pam's Harvestcraft, Streams, and Farseek.

**Comment by cam72cam** [comment]
It's looking like a mod conflict. I'll spin this up locally today

**Comment by chakinnuggets** [comment]
I'm also having a similar issue with universal mod core, using mc eternal instead of mc eternal lite as my base modpack, although I somehow managed to get any mention of waila to disappear from the crash log, leaving just universal mod core

Crash Report:
[crash-2021-01-06_23.37.33-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5775824/crash-2021-01-06_23.37.33-client.txt)

Modlist:
https://pastebin.com/x2njhWMY

I can also reproduce this issue by trying to assemble an IR machine using the large wrench
