### ISSUE TITLE
Trains wont move when in server, rolling stock does not exist

### ISSUE THREAD

**Issue by ShavdMercury** [TeamOpenIndustry/ImmersiveRailroading#890]
Im still having the issue of "rolling stock does not exist in this server" and trains not moving only when in a server. I custom made my server, i dont use any services to run a server. If i play singleplayer not on my server, this mod works just fine. Its only when i get onto the server world that i have this issue.

**Comment by cam72cam** [comment]
It sounds like you have issues configuring the server correctly.  Please ask in Discord for help.
