### ISSUE TITLE
Player may get moved by moving train which is far away

### ISSUE THREAD

**Issue by Vodulm** [TeamOpenIndustry/ImmersiveRailroading#892]
Player may get moved by moving train which is far away

https://vimeo.com/495559551

**System Information**  
Windows 10 
 <br>System Memory: 8gb
 <br>Allocated Memory: 2gb
other specs on video

**Modlist**  
![Capture](https://user-images.githubusercontent.com/73194834/103308077-3f81ac00-4a1a-11eb-85a7-2ae48ddabc30.PNG)
 
**latest.log**
[2020-12-13-3.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5751846/2020-12-13-3.log)

**Comment by cam72cam** [comment]
This should be fixed in the latest version (1.8)
