### ISSUE TITLE
This is really odd behavior

### ISSUE THREAD

**Issue by shelbykauth** [TeamOpenIndustry/ImmersiveRailroading#895]
**Describe the bug**  
Train starts going backwards

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Make a somewhat small, but reasonable, track.  I'm using Model Gauge with 2-block turns
 2. Hook up a couple locomotives
 3. Set 2 locomotives to brakes=0, throttle=0
 4. Set 1 locomotive to throttle=positive
 5. Train switches rapidly between positive and negative speed
 
**Expected behavior**  
 Train moves forward at a consistent speed

**Screenshots**  

https://user-images.githubusercontent.com/10117276/103389878-7968b600-4adf-11eb-978c-88d15861e56a.mp4

**System Information**  
 OS: Windows
System Memory: 16GB
Allocated Memory: roughly 4GB
CPU: i7-4470 @ 3.40GHz
GPU: none
IR-Version: 1.16.4-forge-1.8.0.1
Forge-Version: 1.16.4 - 35.1.9

**Modlist**  

<details>
<summary>
I don't know how to get the actual modlist, but this is the result of `ls` in my mods folder.  (Note: a couple of these are new as of last game restart, such as Pam's Harvest Craft.
</summary>

 AppleSkin-mc1.16.2-forge-1.0.14.jar
 AutoRegLib-1.6-47.jar
 BetterAdvancements-1.16.4-0.1.0.103.jar
 Bookshelf-1.16.4-9.3.18.jar
 CodeChickenLib-1.16.4-3.5.0.398-universal.jar
 Controlling-7.0.0.11.jar
 CookingForBlockheads_1.16.3-9.2.2.jar
 Cyclic-1.16.4-0.10.1.jar
 DefaultOptions_1.16.3-12.2.0.jar
 DustrialDecor-1.1.4.jar.disabled
 EnchantmentDescriptions-1.16.4-6.0.2.jar
 EnderStorage-1.16.4-2.7.0.159-universal.jar
 FastLeafDecay-v25.jar
 Hwyla-fabric-1.16.2-1.9.23-79.jar.disabled
 ImmersiveEngineering-1.16.4-4.1.2-129.jar
 ImmersivePetroleum-1.16.4-3.1.0-2.jar
 ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar
 JustEnoughResources-1.16.4-0.12.0.103.jar
 Morpheus-1.16.4-4.2.68.jar
 MouseTweaks-2.13-mc1.16.2.jar
 NaturesCompass-1.16.4-1.8.6.jar
 NetherPortalFix_1.16.3-7.2.1.jar
 Placebo-1.16.3-4.3.3.jar
 Quark-r2.4-280.jar
 StorageDrawers-1.16.3-8.2.1.jar
 Toast-Control-1.16.3-4.3.0.jar
 TrackAPI-1.16.4-forge-1.2.1.jar
 UniversalModCore-1.16.4-forge-1.0.1.jar
 WAWLA-1.16.4-7.0.2.jar.disabled
 WailaHarvestability-mc1.16.2-forge-1.1.13.jar.disabled
'[1.16.4]LagMeter-1.3.3.jar'
 appliedenergistics2-8.1.0.jar.disabled
 architectury-1.1.55-forge.jar
 astralsorcery-1.16.4-1.13.7.jar.disabled
 cc-tweaked-1.16.4-1.95.0.jar
 chiselsandbits-0.2.8-RELEASE.jar
 curios-forge-1.16.4-4.0.3.0.jar
 decorative_blocks-1.16.4-1.6.2.jar.disabled
 engineersdecor-1.16.4-1.1.6-b1.jar
 engineerstools-1.16.4-1.1.3-b1.jar
 ftb-backups-2.1.1.6.jar
 ftb-chunks-1604.2.2.54.jar.disabled
 ftb-gui-library-1604.1.1.26.jar
 ftb-quests-1604.1.1.18.jar.disabled
 ftb-ranks-1604.1.1.9.jar
 ftb-teams-1604.1.0.13.jar
 ftb-ultimine-1603.1.1.13.jar
 ftbessentials-1603.1.0.11.jar
 immersiveposts-1.16.3-3.0.0.jar
 ironchest-1.16.4-11.2.10.jar
 item-filters-1604.2.2.19.jar
 jei-1.16.4-7.6.0.62.jar
 kubejs-1604.3.2.121-forge.jar.disabled
 kubejs-immersive-engineering-1604.1.0.9.jar.disabled
 observerlib-1.16.4-1.4.4.jar
 pamhc2crops-1.16.3-1.0.1.jar
 pamhc2foodcore-1.16.3-1.0.0.jar
 pamhc2foodextended-1.16.3-1.0.0.jar
 pamhc2trees-1.16.3-1.0.0.jar
 platforms-1.16-1.7.8.jar
 rhino-1.7.13.9.jar.disabled
 shetiphiancore-1.16-3.8.4.jar
 swingthroughgrass-1.16.4-1.5.3.jar
 worldedit-forge-mc1.16.3-7.2.1-dist.jar

</details>
 
**Additional context**  
I removed the Handcart from the middle and it stopped doing the thing.

**Comment by cam72cam** [comment]
I'm going to leave this open, but I'd recommend increasing the turn radius.
