### ISSUE TITLE
Universal Mod Core has failed to load

### ISSUE THREAD

**Issue by XPromus** [TeamOpenIndustry/ImmersiveRailroading#896]
**Describe the bug**  
After starting the game (Version 1.15.2), it shows an error which says: "Universal Mod Core has failed to load correctly". This however only happens when the Immersive Railroading Jar is in the mods folder. When UMC and Track API are in there alone it all starts up like it is supposed to.
 
**Expected behavior**  
The game should start up like normal without the error message.

**System Information**  
 OS: Windows 10
 <br>System Memory: 16 GB
 <br>Allocated Memory: 4 GB
 <br>CPU: Intel i5 7600K
 <br>GPU: GTX 1060 6 GB
 <br>IR-Version: 1.15.2-forge-1.8.0.1
 <br>Forge-Version: 1.15.2 - 31.2.0

**Modlist**  
Immersive Railroading
Track API
Universal Mod Core
(All the latest Versions)
 
**latest.log**
https://pastebin.com/Z2JxehU8

**Comment by Bredbear36** [comment]
This happens in 1.16.5 also

**Comment by cam72cam** [comment]
Should be fixed in the next version
