### ISSUE TITLE
rendering crash

### ISSUE THREAD

**Issue by MageWolf93** [TeamOpenIndustry/ImmersiveRailroading#897]
Template goes here
every now and then i have been getting a crash with immersive railroading due to rendering texture issue
this is the only logs we get
[hs_err_pid10592.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5759749/hs_err_pid10592.log)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5759750/latest.log)

im also getting 
[cam72cam.mod.render.BlockRender$2:getQuads:149]: null
spaming the client console

**Comment by PantsWP** [comment]
Can confirm this is happening to me and a friend as well.
Latest crash: [hs_err_pid4936.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5774129/hs_err_pid4936.log)

**Comment by SadisticalSatan** [comment]
Yup, same thing here [hs_err_pid8788.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5855109/hs_err_pid8788.log)

It doesn't matter if Optifine is installed or not, simply scrolling thru IR's tabs in creative is enough to crash JAVA.
I have the latest nvidia driver installed. I've also tested this in both Valhelsia 3 and in a stand alone instance of IR, so there is definitely something going on with the rendering.

**Comment by malte0811** [comment]
@MageWolf93: Your log file looks like you were not using FerriteCore when you opened this issue. Can you confirm that this is the case? In that case I could stop looking into how FerriteCore could possibly cause this.

**Comment by MageWolf93** [comment]
I can confirm that I wasn’t as I didn’t know that was a  thing plus that
wasn’t around when I posted this

**Comment by MageWolf93** [comment]
just to comfirm i got the same issue again with FerriteCore

**Comment by delucain** [comment]
I am seeing this in my group's server quite consistently as well (some players crashing to desktop every 3-15 minutes). We are not using FerriteCore.

**Comment by Nina268** [comment]
I've been trying to figure this out for over a month (I'm the friend PantsWP refers to) and the only thing I can say with absolute certainty is that Ferrite Core is not the main cause, it doesn't happen when the only mod installed is IR and its dependencies, and it crashes in Enigmatica 6 and ATM6, which were the modpacks we'd tried it with when PantsWP made his post.

**Comment by delucain** [comment]
We've seen that when we remove the machines (steam hammer, boiler roller, casting basin, track roller, and plate rolling machine) that we no longer see OpenGL errors in our logs and the crashes stop entirely. We've only tested this for two days, but we weren't been able to go more than 3 hours without a crash previously.

**Comment by Nina268** [comment]
We didn't have any of those machines because we were testing in creative, I tried testing in survival and it crashed there too, still no machines. Based on what you've said I might have an idea, not sure if it'll go anywhere but it's worth a look.

**Comment by cam72cam** [comment]
There is a good chance this is fixed in the next version.
