### ISSUE TITLE
Add Versioning to model.json format

### ISSUE THREAD

**Issue by hayesj1** [TeamOpenIndustry/ImmersiveRailroading#899]
**Describe the suggestion**  
For future proofing and additional flexibility, the format of model.json should be versioned, ideally using semantic versioning.

**Applications of the suggestion**  
This will enable more flexibility, better error handling, and more resilient backwards-compatibility w.r.t. changes to the format.

**Comment by cam72cam** [comment]
I'm not planning on breaking compatibility between versions
