### ISSUE TITLE
Using "mechanical user" on casting basin drops nothing

### ISSUE THREAD

**Issue by Pavelsvt** [TeamOpenIndustry/ImmersiveRailroading#900]
When I tried to use mechanical user from the extra utilities 2 to drop item from the casting basin, it basically voids the item. The casting basin still doesnt support an item outlet (not even immersive engineering´s extraction belt works!), and it doesnt even store the items, so when I try to get enough rails for a decent railway, I need to do that ultra-tedious job of grabbing it manually for at least an hour! 
Anyway, I use the newest 1.12.2 version (1.8.0), together with newest according version of TrackAPI, UMC and Immersive engineering.

**Comment by latibro** [comment]
Looks like a dublet of #738 and #763
