### ISSUE TITLE
(not only) IR American steam pack

### ISSUE THREAD

**Issue by Pavelsvt** [TeamOpenIndustry/ImmersiveRailroading#901]
First, Im not sure if this is a bug. But it really looks like it is.
Im also not sure if I can ask here because its mostly a resource pack problem.
However, here it is:
It seems impossible to properly heat up some steam engines from the IR American steam pack. If I put in just a single bucket of water (so it heats up faster), and full grate of coal, it quickly heats up to some 93 degree Celsius and then it stops. You can basicaly never get the water in the boiler to boil and create steam, no matter how long you wait. The grate just looks like it doesnt have enough slots for fuel. Can I do anything about it, or are those engines simply useless?
Edit: I have 1.12.2 with newest version of all required mods.
Edit 2: A5 Switcher in the original mod has the same problem! The vehicle works with settings "fuel required" as "false", because it removes the need for steam pressure in the boiler. But I´d really like to use those engines normaly.

**Comment by Pavelsvt** [comment]
!
I have found out that deleting the main config file of this mod and letting the game create a new one solves this! 
I have created a backup of my edited config file and now Im trying to find out which edit created this mess.

**Comment by cam72cam** [comment]
This has been fixed in newer versions
