### ISSUE TITLE
Can't free move in latest 1.7.10 release 

### ISSUE THREAD

**Issue by LavaHoleD** [TeamOpenIndustry/ImmersiveRailroading#902]
**Describe the bug**  
So a couple of days ago I just found out that finally a downgrade release for 1.7.10 came out. I was incredibly excited. I downloaded it, got some random add-ons for 1.7.10 and run. Entered a locomotive and well...I cannot free move as intended. Like, when I enter it I go to a precise position, then when I try to free roam I "walk" and after 1.5 seconds I go back to the first position. It does also with any other types of rideable cars.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Get a loco or any type car.
 2. Enter it.
 3. Try to move around.

**Screenshots**  
I decided to make a gif from a recording I made.

**System Information**  
 OS: [Windows 10 Pro 64 bit]
 <br>System Memory: [16 gb]
 <br>Allocated Memory: [6 gb]
 <br>CPU: [AMDfx(tm)-6300 Six-core Processor 3.50Ghz]
 <br>GPU: [NVIDIA Gtx 1060 6 GB]
 <br>IR-Version: [ImmersiveRailroading-1.7.10-forge-1.8.0-7e0f82]
 <br>Forge-Version: [1.7.10-10.13.4.1614]

**Modlist**  
https://pastebin.com/beB30fQz
 
**latest.log**
It's not a crash and don't think this could be helpful since this cannot be seen throught the latest.log

**Comment by km00700** [comment]
It's impossible to say for certain without duplicating the modpack, but it's possible some other mod there also tries to influence player position and is intercepting some of the movements.

**Comment by LavaHoleD** [comment]
> It's impossible to say for certain without duplicating the modpack, but it's possible some other mod there also tries to influence

I think then its Player API. Except that....

**Comment by LavaHoleD** [comment]
> It's impossible to say for certain without duplicating the modpack, but it's possible some other mod there also tries to influence player position and is intercepting some of the movements.

Since this is my testing client I cannot give the modpack but I can give you a copy of my mods (without Flan's Mod and IR packs)

**Comment by cam72cam** [comment]
Should be fixed in the next release.  There was a Single Player bug I had overlooked.
