### ISSUE TITLE
Option to disable 3D Icons in config

### ISSUE THREAD

**Issue by LavaHoleD** [TeamOpenIndustry/ImmersiveRailroading#903]
**Describe the suggestion**  
I suggest to make a feature in the config that lets you disable the 3D icons so:
1. If you have detailed addons it won't take years to load
2. If you have NEI or JEI it doesn't lag your game

I've heard there is this option but I have already checked in the config if there was this option, but didn't.
I'm using ImmersiveRailroading-1.7.10-forge-1.8.0-7e0f82.
**Applications of the suggestion**  
Add the feature in normal config and maybe put it in the first page.

**Comment by km00700** [comment]
There are no 3D icons anymore. From IR version 1.7.0 and later, they're all 2D images.

**Comment by LavaHoleD** [comment]
> There are no 3D icons anymore. From IR version 1.7.0 and later, they're all 2D images.

Why then it takes much time to load them?

**Comment by km00700** [comment]
On the first startup, IR will pregenerate them and cache them for future use. This takes some time.

**Comment by km00700** [comment]
most of IR's loading time is actually calculating the procedural heightmaps and uploading actual model data to the graphics card.

**Comment by LavaHoleD** [comment]
> most of IR's loading time is actually calculating the procedural heightmaps and uploading actual model data to the graphics card.

Oh ok thank you for your responses

**Comment by LavaHoleD** [comment]
Do you have time to check my other issues? They're more serious than this
