### ISSUE TITLE
Freezing and crashing the game when getting a turntable blueprint shown (when holding the track blueprint on the ground)

### ISSUE THREAD

**Issue by LavaHoleD** [TeamOpenIndustry/ImmersiveRailroading#904]
Hello, so I was playing in my world and got the idea to add a turntable to my test railway.
Got the track blueprint and selected concrete ties. I didn't know why turntable wasn't showing at all, but proceeded.
Pointed the turntable to the ground (to then place it) and my game froze. After some seconds, crashed.
For some reasons, crash report didn't generate. Maybe because I after some time repeately pressed mouse on the screen cause was blocked in F11. Here's however the log (not latest because i accidentaly relaunching the game, so latest.log is regenerating) 
https://drive.google.com/file/d/1mb-T7clOgIR5KscOVFEWZbda3j1LXMH1/view?usp=sharing

**Comment by km00700** [comment]
Nothing there explicitly calls-out a crash, but one thing that's happening is some loco from IR is reporting improper fluid transfer. Although I'm not sure why or if that was trigged by the turntable somehow.

**Comment by LavaHoleD** [comment]
> Nothing there explicitly calls-out a crash, but one thing that's happening is some loco from IR is reporting improper fluid transfer. Although I'm not sure why or if that was trigged by the turntable somehow.

ok so with normal turntable I can, with concrete ties turntable i cannot

**Comment by LavaHoleD** [comment]
> > Nothing there explicitly calls-out a crash, but one thing that's happening is some loco from IR is reporting improper fluid transfer. Although I'm not sure why or if that was trigged by the turntable somehow.
> 
> ok so with normal turntable I can, with concrete ties turntable i cannot or it crashes
