### ISSUE TITLE
Switch tracks switching randomly by itself

### ISSUE THREAD

**Issue by Vodulm** [TeamOpenIndustry/ImmersiveRailroading#905]
**How to reproduce**  
https://vimeo.com/500328227
https://vimeo.com/500328338

**System Information**  
 OS: Windows 10
 <br>System Memory: 8 gb
 <br>Allocated Memory: 2gb
 <br>CPU: Intel i7-3720QM
 <br>GPU: Nvidia geforce gt 650m
 <br>IR-Version: 1.8.0_1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2854

**Modlist** 

![Capture](https://user-images.githubusercontent.com/73194834/104554422-d5d1e680-5644-11eb-8dd2-f656c5d16aa0.PNG)

**latest.log**
[2020-12-24-1.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5812750/2020-12-24-1.log)

**Comment by ekg98** [comment]
I seem to be having this same issue I believe.  My switches in my yard are 10 in size and at the shallowest angle setting.  Some of them work perfectly.  I had one that was the same size as the others but 4 oil tankers and the fef kept splitting the points and derailing.  I changed it to size 12 and ran around it a few times and it seemed to fix it.  It was the only one giving me issues.  Strange.  Does IR take into account radius for bogies?
