### ISSUE TITLE
ability to use items, interact with blocks from train

### ISSUE THREAD

**Issue by Vodulm** [TeamOpenIndustry/ImmersiveRailroading#906]
**Applications of the suggestion**  
for example, switching levers or buttons without leaving and stopping train to trigger some other actions in world
including but not limited to choosing train goes next (switching switch tracks);
eating, drinking in train; using WR-CBE remote controllers

**Comment by Vodulm** [comment]
maybe make train fuel gui opening only when looking to specific part of locomotive. Or keyboard key

**Comment by Appw0** [comment]
I can second this issue. I'd love to be able to use my OC tablet while riding a train.
