### ISSUE TITLE
Villager Payout Still Broken

### ISSUE THREAD

**Issue by Doublehelix13** [TeamOpenIndustry/ImmersiveRailroading#909]
**Describe the bug**  
I took some villagers well over 1000 blocks and was not paid emeralds.  I set villager payout in the configs to 0.01 emeralds per meter and did the same thing again as a test and again was not paid.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Create a train with passenger cars
 2. Load the train with villagers with the conductor's whistle
 3. Drive the train at least 1000 blocks from starting position
 4. Use the conductor's whistle to get villagers off the train
 
**Expected behavior**  
You should get one emerald per villager, but you get nothing.

**System Information**  
 OS:  macOS
 <br>System Memory: 8 GB
 <br>Allocated Memory: 6 GB
 <br>IR-Version: 1.12.2-forge-1.8.0-7e0f82
 <br>Forge-Version: 14.23.5.2854

**Modlist**  
AE2 Stuff
AE2WTLib
AI Reducer
AppleSkin
Applied Energistics
Aroma1997Core
AromaBackup
BD Lib
Better Questing
Better FPS
Biomes O' Plenty
Born in a Barn
Building Gadgets
Carry On
ChickenChunks
Chisel
Clumps
CodeChicken Lib
CoFH Core
CoFH World
Construct's Armory
Controlling
CraftTweaker2
ConnectedTexturesMod
Ender Storage
Fast Leaf Decay
Flux Networks
FoamFix
Forestry
GenDustry
Geographicraft
Immersive Cables
Immersive Engineering
Immersive Railroading
Immersive Technology
Industrial Foregoing
Inventory Tweaks
Iron Chest
JEI Bees
JourneyMap
JustEnoughEnergistics
JustEnoughItems
Malisis Core
Malisis Doors
Mantle
McJtyLib
Measuring Compass
Millenaire
Minecraft Comes Alive
MmmMmmMmmMmm
Mod Name Tooltip
ModTweaker
MouseTweaks
MTLib
Natura
Nature's Compass
Not Enough Items 1.8+
The One Probe
Open Computers
p455w0rd's Library
Phosphor
xXx_MoreToolMats_xXx
RadixCore
Redstone Flux
RFTools
Shadowfacts' Forgelin
Simple Harvest
Better Questing - Standard Expansion
SwingThroughGrass
Tesla Core Lib
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers' JEI
Tinkers Tool Leveling
Tinkers' Construct
ToroHealth Damage Indicators
Track API
Tweakers' Construct
UniversalModCore
VanillaFix
Wireless Crafting Terminal 2
 
**latest.log**
https://pastebin.com/iz848gyf

**Additional context**  
Latest.log file was generated after loading up a flat creative world, using the conductor's whistle to load up some villagers into a train, carrying them over 1000 blocks, unloading them with the whistle, then loading them back on the train and bringing them back to the starting point and unloading them again.  The config file was still set to 0.01 emeralds per meter.  No emeralds were received.

**Comment by AndMattBurt** [comment]
Having the opposite issue in IR 1.9.1 today, beta testing for a server that wishes to use the payouts as part of the economy but currently you can just collect infinitely for one journey

I used 5k track, travelled with a bunch of villagers and then just spam whistle and shift whistle to get infinite drops!
had drop set to 1.0 for testing if that matters

**Comment by cam72cam** [comment]
Huh, this code is just completely broken.  What MC version are you using?

**Comment by AndMattBurt** [comment]
1.12.2
Forge 14.23.5.2855
Its the "New Street Railway Server" Pack on Curseforge (In case other mods are interfering)

**Comment by AndMattBurt** [comment]
that doesnt appear to have fixed it.....are there any logs or things that would help you find the problem?
really appreciate the support btw!
