### ISSUE TITLE
SimpleChannelHandlerWrapper exception

### ISSUE THREAD

**Issue by LavaHoleD** [TeamOpenIndustry/ImmersiveRailroading#910]
Hello, I have recently updated my server modpack with Immersive Railroading (for 1.7.10) and well...when I tried to connect on my server I "crashed". Like the game didn't close but I get disconnected. Before I get disconnected I can only see the GUI. 
Here's what I get on my console:
https://pastebin.com/KSexijb5

**Comment by cam72cam** [comment]
Does this happen every time or just occasionally?
