### ISSUE TITLE
Crash when upgrading from 1.6.1 to 1.8.0

### ISSUE THREAD

**Issue by EverettSummer** [TeamOpenIndustry/ImmersiveRailroading#912]
I tried to load my saved world once played with 1.6.1 to 1.8.0, I then it crashed on startup.

I also added every need mod, like UniversalModCore

[crash-2021-01-23_20.49.16-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5860234/crash-2021-01-23_20.49.16-server.txt)

**Comment by cam72cam** [comment]
You need to take a backup of your world from 1.6.1, run it with 1.7.4, and then upgrade to 1.8.0
There's a bug where 1.6.1 and earlier worlds don't upgrade safely.

**Comment by EverettSummer** [comment]
Thanks for the info, I know that that risk, I know when I upgrade to 1.7.x it won't be able to downgrade anymore. So I do this locally with a backup world archive. 
I will try to upgrade to 1.7.4 first tomorrow. Thanks for reply.

**Comment by EverettSummer** [comment]
OK, I have to say I can't find 1.7.4 which is not listed in Curseforge. the last 1.7.x is 1.7.3
I tried upgrading to 1.7.0 then 1.7.3 it's a smooth upgrade. but when I load the save 1.8.0 the Minecraft client froze.

**Comment by EverettSummer** [comment]
I think I have solved the freezing issue when upgrading from 1.7.3 to 1.8.0, but after I upgraded to 1.8.0, the texture of all stocks is broken. Don't know why.
