### ISSUE TITLE
Machines don't work

### ISSUE THREAD

**Issue by Togysaur** [TeamOpenIndustry/ImmersiveRailroading#914]
**Describe the bug**
Machines such as the Casting Basin and the track roller wont work with a redstone signal (note Immersive engineering is not installed and i do not wish to install it)
**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. build Casting basin
 2. attach lever
 3. Put in iron/locomotive parts *ie Wheels, Boilers
 
**Expected behavior**  
the casting basin should fill up with molten iron

**Screenshots**  
 
![2021-01-24_12 38 56](https://user-images.githubusercontent.com/77937167/105641510-890abe80-5e41-11eb-9693-04e2d672262a.png)

 

**System Information**  
 OS: Windows 10 Home
 <br> 16gb ram
 <br>Allocated Memory: 4gb
 <br>CPU: Intel(R) Core(TM) i5 -10400F CPU @ 2.90GHz
<br>GPU: NIVIDIA GeForce GTX 1660 SUPER
 <br>IR-Version: 1.16.4-forge-1.8.0.1
 <br>Forge-Version: 1.16.4 - 35.1.37

**Modlist**  
![Screenshot 2021-01-24 124818](https://user-images.githubusercontent.com/77937167/105641658-7d6bc780-5e42-11eb-9458-19fc3b472e1f.jpg)
![Screenshot 2021-01-24 124909](https://user-images.githubusercontent.com/77937167/105641669-93798800-5e42-11eb-90d0-635096562eae.jpg)

**Additional context**  
Track Roller also doesn't work when i click on it with a rail casting it just spits the item out on the other side and then becomes unusable

**Comment by km00700** [comment]
You need a source of Forge Energy (i.e. Redstone Flux or similar), not a lever to power it.

**Comment by Togysaur** [comment]
@km00700 the lever is the redstone power ive also tried of things like blocks of redstone and dust

**Comment by km00700** [comment]
Redstone dust isn't the same as Redstone flux.

**Comment by Togysaur** [comment]
@km00700 is redstone flux a Immersive engineering thing because i don't have it installed as i said in the post

**Comment by Doublehelix13** [comment]
Redstone Flux isn't exclusive to Immersive Engineering; you don't have to install it.  But you will have to install some other mod that gives Redstone Flux/Forge Energy generation and transfer like Mekanism, Powah, RFTools, ect.  You're going to run into a similar issue with Simply Jetpacks 2 - you have no way to power your jetpacks.

**Comment by Togysaur** [comment]
oh ok Thanks!
