### ISSUE TITLE
track spliter not working with tiny roads

### ISSUE THREAD

**Issue by SirHoward** [TeamOpenIndustry/ImmersiveRailroading#916]
**Describe the bug**  
spliter of tiny tracks arnt working correctly. when the train should move to the left or right it always goes straight.
no matter if its powered with redstone or locked to move to the side. all other track sizes are working fine.

**mod-Version**
ImmersiveRailroading-1.16.4-forge-1.8.0.1

**Comment by Ghostizockt** [comment]
that's because the small track spliter have so close tracks that the locomotive always comes on the middle track despite everything, sorry I use a translator
