### ISSUE TITLE
Add support for doors / animated parts

### ISSUE THREAD

**Issue by yaBobJonez** [TeamOpenIndustry/ImmersiveRailroading#917]
**Describe the suggestion**  
I would be happy to see animated doors. For example, on the right-click in-train GUI there may be buttons for opening left and right doors. Those doors should be defined by packs by denoting their model parts or just location, and translation vectors or rotation degree, possibly via .json files of trains.

**Applications of the suggestion**  
As of now, I noticed, that as the models are "collidable", it's impossible to walk into trains (or at least in some packs, I haven't checked all of them), even through doors. I think it would be good to make doors more realistic.

_Note_: this system may look similar to how it is implemented in RTM (Real Train Mod).

P.S: This is my first Issue here, so sorry if I violated something, just tell me, please. I tried to search before opening, but I haven't found anything related to doors yet.

**Comment by km00700** [comment]
All of this is planned. The precursor is incorporating raycasting into the UMC core mod, so that interactions with specific parts can be processed. Eventually, the hope is to be able to export animation info for parts from a Blender plugin, and configure those to trigger on interaction.

**Comment by cam72cam** [comment]
At least at the moment I am not planning on adding support for internal collisions.
