### ISSUE TITLE
Rolling stock does not exist.

### ISSUE THREAD

**Issue by ferbidin** [TeamOpenIndustry/ImmersiveRailroading#921]
I know you have gotten this a lot, I am just mega dumb and can't find out how to fix it. Every time I try and spawn stock trains it says "Rolling stock does not exist"

1.12.2-forge-14.23.5.2854
 ImmersiveRailroading-1.7.3_1.12.2

I know it's probably not a bug but it's as close as I can get to an issue

**Comment by km00700** [comment]
You need to install the resource pack zip files into the server's "config/immersiverailroading" folder.

**Comment by ferbidin** [comment]
Where would I find the resource pack good sir

**Comment by km00700** [comment]
The one for whichever stock you're trying to place down

**Comment by ferbidin** [comment]
If I go to the resource packs link on the git hub page it sends me to the curse forge page, I am sorry but I do not follow, where exactly do I find resource packs?

**Comment by km00700** [comment]
What are you placing down that it causes it to say that?

**Comment by ferbidin** [comment]
Like 90% of the trains

**Comment by km00700** [comment]
From the base mod?

**Comment by ferbidin** [comment]
Indeed

**Comment by km00700** [comment]
Send your latest.log file from a game session where you try and place some of the stuff.

**Comment by ferbidin** [comment]
Server logs?

**Comment by km00700** [comment]
client and server, if possible.

**Comment by ferbidin** [comment]
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5899325/latest.log)

**Comment by ferbidin** [comment]
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5899326/latest.log)

**Comment by km00700** [comment]
That first one does not look like a complete log.

**Comment by ferbidin** [comment]
It was like 33 mb I couldnt upload it

**Comment by ferbidin** [comment]
I can provide more though

**Comment by km00700** [comment]
could you upload it via pastebin or a similar service?

**Comment by ferbidin** [comment]
I can try

**Comment by km00700** [comment]
Wait. Are you trying to place UNU trains?

**Comment by km00700** [comment]
Base mod stuff seemed to work fine (from your client log)

**Comment by ferbidin** [comment]
I think it may be

**Comment by km00700** [comment]
UNU needs to be setup differently because the pack creator bundled the stock into a jar instead of the way IR prefers them

**Comment by ferbidin** [comment]
Can you tell me how, I have a lot of time

**Comment by km00700** [comment]
Please be patient, I'm working on it.

**Comment by ferbidin** [comment]
Alright thank you!

**Comment by km00700** [comment]
Stop the server. Make a copy of the UNU and blackthorne jar files. Put them somewhere that's not the mod folder. Change the file extension from ".jar" to ".zip" Install this pack in the "/config/immersiverailroading/" folder for the server. Launch the server.

**Comment by ferbidin** [comment]
I am of the stupid, where are the UNU and blackthorne files, I'm sorry I'm new to this stuff, (I use filezilla)

**Comment by km00700** [comment]
UNU and Blackthorne will be mods located in your "/mods/" folder

**Comment by km00700** [comment]
either on client or server.

**Comment by km00700** [comment]
using the set from your client should be easiest.

**Comment by ferbidin** [comment]
I do not have blackthorne and I assume I do not have UNU but I have the UNU Parts, military, and civilian pack.

**Comment by km00700** [comment]
Blackthorne is the UNU military.

**Comment by ferbidin** [comment]
yes, it works, thank you! Is there a possible way to make them have functional textures? it is just kinda grey with weird shapes (i mean the item not model)

**Comment by km00700** [comment]
Your client is out of GPU memory right now. If you have a dedicated graphics card, try making javaw.exe run using that card. Then delete your client's "/cache" folder and launch MC.

**Comment by ferbidin** [comment]
Thank you! All works, sorry for putting you through this pain or stupidity, I appriciate it!
