### ISSUE TITLE
Make the modification's customer function more custom Individual

### ISSUE THREAD

**Issue by touhourailway** [TeamOpenIndustry/ImmersiveRailroading#922]
/*Before: The mod has been update for several times after last year. But There's nothing for new functions especially the electrified railroading, so does it makes the mod discordant?*/
To enable new carrier of the railroad such as bridge with pier or tunnel:
Add new mechanism to loading the resource pack, enable a kind of rail include more model and set them with sequence in game.
enable more size, collision and use of rail.
To enable more kind of rolling stock:
Enable custom the height for get off (in now version the height is the rail model).
Enable more dynamic part such as door.

**Comment by SadisticalSatan** [comment]
The hard part isn't implementing electricity into IR, it's how to transmit it across unloaded chunks.

**Comment by touhourailway** [comment]
> The hard part isn't implementing electricity into IR, it's how to transmit it across unloaded chunks.
If it's hard to across unloaded chunk, why not just deal the problem in chunk? Just like the red stone signal can only spread 16 blocks, the electricity may spread 64 blocks.
The things locomotive need to do is detecting the hot catenary but not running on the catenary.
Also, if its possible, can author change the train operation system form simple operation to operate with distance like the ATO system in real life?

**Comment by biauk** [comment]
Authors of this mod don't even seem to care about plenty of bugs, you really expect them to do something like this?

**Comment by touhourailway** [comment]
> Authors of this mod don't even seem to care about plenty of bugs, you really expect them to do something like this? They even don't respond to most of issues!

That's the problem, I've propose the similar suggestion before in the TeamOpenIndustry/ImmersiveRailroading
and the author reply soon. Besides, I haven't seen this suggestion show on the page. Are they different projects?
By the way, I trust the project is the best project in mcrailroads.

**Comment by Larky2k** [comment]
The author of the mod is very busy IRL building a shed/house so at the moment is very sporadic with there free time they have. Cam will have more free time soon to work on the mod when he does he will very quickly squish bugs, so all we ask is just be patient.
