### ISSUE TITLE
Allow Getting UUID from Detector's Info Method

### ISSUE THREAD

**Issue by andrewlalis** [TeamOpenIndustry/ImmersiveRailroading#927]
As of right now, the only way of obtaining a rolling stock's UUID is via and `ir_train_overhead` event, and this means that is difficult to deal with scenarios where a computer system boots up and needs to detect a piece of rolling stock directly overhead. Aside from a custom tagging "cookie" system for rolling stock which is quite overkill in my opinion, the UUID is the only way of getting a unique identifier for a rolling stock.

This would make things a lot simpler for systems which need to track and report information about individual rolling stock; for example a cargo management application could use it. Also I don't think it's that much effort to implement.

**Comment by cam72cam** [comment]
At this point they can use the tag system instead
