### ISSUE TITLE
Add isStockOverhead Method to Controller and Detector Augments

### ISSUE THREAD

**Issue by andrewlalis** [TeamOpenIndustry/ImmersiveRailroading#928]
It would be very helpful to have a method like `isStockOverhead()`, so that we don't have to do a more expensive, less intuitive method call such as `detector.info() ~= nil`.

It feels to me like something that is rather simple to implement, and would provide a nice convenience to the people using the augments.

**Comment by cam72cam** [comment]
I'm going to recommend you use the ir_train_overhead event in  CC/OC (CC will be available in the next release)
