### ISSUE TITLE
"Crossover track" type in the "track type" selector

### ISSUE THREAD

**Issue by watch4martels** [TeamOpenIndustry/ImmersiveRailroading#930]
**Description of my suggestion**
My suggestion is to create crossover track types, because I'm having so much trouble doing it with track switches. I even asked on how to build it properly but I still cannot do that. I think that if we would have a track blueprint with a crossover track it would be much easier for everybody to build crossover tracks of any size.
For the parameters in the track selector GUI I would have **Distance** and **Radius**, both of which have values to be assigned by the player, and a "mode selector" called **Mode**. Every parameter explained below.
*(I included some photos to make my point here, better add something than to omit it right?)*

**Distance**
This parameter sets the distance (in blocks) between the two pieces of track in the crossover track. The minimum value is 1. This might be used to simulate stations with truncated tracks: when a loco arrives on a platform, it can then detach and go back using a crossover track to go to the adjacent track.

**Radius**
This parameter sets the radius (in blocks) of the curve used to cross the tracks in the crossover: less radius means a steeper angle of the curve (like switches), and you need a big radius and angle so that big locos like "UP Big Boy" or "BR Class 66" don't glich out with their animations. This is a little detail to make it more realistic: gentle curve means happy loco and the loco doesn't derail, and the same can be applied for switches and for this crossover track. I would say the minimum value should be 50, since it's a steep angle for big locos but gentle (kindasorta) for shunter locos.

**Mode**
This parameter can only have two values: *Single* and *Double*. I dunno how to explain it properly with words, so I used my  good ol' LEGO railway instead.

**Applications of my suggestion**  
I think this would save time to everybody that tries to make this type of crossover track using normal witches and the golden spike: the answer that I got most of the time was "you have to fiddle with the golden spike to get youd desired crossover with switches", so if this track type was to be released, it would save a lot fo trouble for everyone and a lot of time "fiddling with the golden spike". Since the crossover track is actually two switces at each opposite end, One extra feature would be the "fix left - fix right - flexible" mode that comes with switches.

Thank you so much for your attention and if you choose to add this track type, I will be very grateful to you. Sorry if my english is not good and if I made some mistakes.
![modeDouble](https://user-images.githubusercontent.com/78472664/106735728-e1e21000-6614-11eb-96ff-5666826010d8.jpeg)
![modeSingle](https://user-images.githubusercontent.com/78472664/106735733-e27aa680-6614-11eb-95ad-9fdf01b82597.jpeg)

**Comment by cam72cam** [comment]
The golden spike is the preferred method to do this.  I plan on releasing a IR video tutorial over the next month or two
