### ISSUE TITLE
IR standalone without IE (HELP)

### ISSUE THREAD

**Issue by EricDrb** [TeamOpenIndustry/ImmersiveRailroading#931]
Help!

I want to play with friends on a server using the IR mod. Thing is, we started with a Vanilla server and just wanted to add mods AND keep our world. But that means we can't use Immersive Engineering because we don't have access to all the resources, because they weren't generatet in the first place. Now we figured everything out and everything is operational without IE or other mods. For energy we use the Quirky Generators mod, because it works with Vanilla stuff. The only goddamn thing that doesn't work are the tracks. Because they require treated wood. Which we don't have.
Why, just why can't the tracks work with Vanilla planks or something? Please, I need a light at the end of the tunnel. I just want this to work and I spent two weeks trying to get everything up and runnig because I want this mod. Help, save my soul and sanity...

Sincerely
Eric

**Comment by km00700** [comment]
IR does use vanilla resources if IE is not present. Although IIRC there are some bugs in the some MC versions for latest version of IR that prevent this from working properly.

**Comment by km00700** [comment]
Also, IE resource generation isn't physical, so excavators can still extract resources because they don't actually mine physical blocks. New ungenerated chunks will also generate with IE resources if you were to install it.

**Comment by EricDrb** [comment]
> IR does use vanilla resources if IE is not present. Although IIRC there are some bugs in the some MC versions for latest version of IR that prevent this from working properly.

I know, and everything works with iron and it's great for us! Only thing that's getting in our way is the fact, that IR requires treated wood specifically. And I just hoped there would be a workaround... because IE is no option for us

**Comment by EricDrb** [comment]
> Also, IE resource generation isn't physical, so excavators can still extract resources because they don't actually mine physical blocks. New ungenerated chunks will also generate with IE resources if you were to install it.

I actually didn't know that, and I'll keep it in my head. Thanks for the info! We still would like to find a way not involving IE

**Comment by Animatical** [comment]
I'm also having this issue, but with the casting basin.
If I attach a lever to the side and throw iron or train parts in, they just sit on the surface and do nothing. I use optifine so I cant use immersive engineering either, nor do I want to.

**Comment by jhayes2-chwy** [comment]
> > IR does use vanilla resources if IE is not present. Although IIRC there are some bugs in the some MC versions for latest version of IR that prevent this from working properly.
> 
> I know, and everything works with iron and it's great for us! Only thing that's getting in our way is the fact, that IR requires treated wood specifically. And I just hoped there would be a workaround... because IE is no option for us

You _might_ be able to get around this by using CraftTweaker to add regular planks as into the OreDictionary for Treated Wood (`plankTreatedWood` in 1.12.2 at least).

**Comment by jhayes2-chwy** [comment]
> I'm also having this issue, but with the casting basin.
> If I attach a lever to the side and throw iron or train parts in, they just sit on the surface and do nothing. I use optifine so I cant use immersive engineering either, nor do I want to.

All the IR Multiblocks require a source of FE/RF energy, not redstone "power". There are countless generator mods out there (for example, Quirky Generators or Eric mentioned).

**Comment by Animatical** [comment]
> > I'm also having this issue, but with the casting basin.
> > If I attach a lever to the side and throw iron or train parts in, they just sit on the surface and do nothing. I use optifine so I cant use immersive engineering either, nor do I want to.
> 
> All the IR Multiblocks require a source of FE (Forge Energy, aka RF/Redstone Flux) energy, not redstone "power". There are countless generator mods out there (for example, Quirky Generators or Eric mentioned) which create FE energy.

Oh thanks, I got a mod called "powah" and it's exactly what I wanted, thanks
