### ISSUE TITLE
Please add a way to automate the machines :)

### ISSUE THREAD

**Issue by samuelvergeiner** [TeamOpenIndustry/ImmersiveRailroading#933]
In older versions it was possible to retrieve items from the casting basin, etc, by using some block that right clicks like a player. The items were then dropped and thus automation of the machines was possible. In 1.12.2 this isn't the case, the items simply get deleted. It would be so much more fun, if it was possible to automate the rail making

Thank you!

**Comment by cam72cam** [comment]
Fixed in https://github.com/TeamOpenIndustry/ImmersiveRailroading/pull/979
