### ISSUE TITLE
Strange smoke visuals

### ISSUE THREAD

**Issue by thonkinator** [TeamOpenIndustry/ImmersiveRailroading#934]
**Describe the bug**  
I don't even know how to describe it. The smoke looks strange, I guess?

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Run IR 1.16.4-forge-1.80
 2. Use any steam locomotive.
 3. Look at the smoke.
 
**Expected behavior**  
 Normal looking smoke.

**Screenshots**  
![2021-02-13_11 53 46](https://user-images.githubusercontent.com/51034477/107855873-11520300-6df3-11eb-980c-17890b9d3962.png)

**System Information**  
 OS: Win10
 <br>System Memory: 32gb
 <br>Allocated Memory: 8gb
 <br>CPU: Intel i7-10700K
 <br>GPU: NVIDIA GeForce RTX 2070 Super
 <br>IR-Version: 1.16.4-forge-1.80
 <br>Forge-Version: 1.16.4-forge-35.1.37

**Modlist**  
Immersive Railroading (obviously)
universalmodcore
TrackAPI
Immersive Engineering
CC:Tweaked
JEI

**Comment by cam72cam** [comment]
Fixed in the next version
