### ISSUE TITLE
Item Loaders not working

### ISSUE THREAD

**Issue by Useydess** [TeamOpenIndustry/ImmersiveRailroading#937]
so basically on a server i'm on the item loaders don't seem to load items and we on the server are not enjoying this much
we are also on 1.12.2

 1. place down track
 2. place down a loader
 3. place down a conveyer belt to load to the items on
 4. watch no items load onto the freight cars
 
the item does not load at all

**Comment by cam72cam** [comment]
You did not provide nearly enough information (created a ticket beforehand with the template so I know you saw it).  I am closing this for now.
