### ISSUE TITLE
Disable trains and gauges for mod packs

### ISSUE THREAD

**Issue by TheWerdOfRa** [TeamOpenIndustry/ImmersiveRailroading#939]
Hi, I am trying to make a themed mod-pack that uses certain assets from a given place and time (specifically I would like to use a resource pack and nothing else). The default game comes with trains that span from early steam in the UK to modern diesel in the US. I would like to be able to turn off trains that I do not want to help reduce options on the design screen and keep the focus of the pack. I am really struggling to figure out how to do this. Currently I have to repackage the JAR every time I update and this is becoming pretty hateful to do. Ideally this would be as simple as setting a config to 'false' so that it can be packaged with the pack and distributed without players needing to do anything to have the correct load out. 

In addition to trains, I would like to be able to select for the desired gauge as well. Again, the goal is to reduce options and focus the player's experience with the pack. 

An aside, the goal of the pack is to make playing with Immersive Railroading easier to get into by using a questing system to quickly get people into a train and then explain the more complex elements of train building after the fun has already begun to be had.

If this capacity already exists, then if you would kindly point me in the direction of how to do this it would be much appreciated.

**Comment by Larky2k** [comment]
you can make a blacklist pack so it doesn't load the stock you don't want

**Comment by Larky2k** [comment]
just make a blacklist pack then take the stock.json and location and rename it blacklist.json and what ever you add to it wont load
so the pack will contain assets/immersiverailroading/rolling_stock/blacklist.json
pack.mcmeta
and nothing else

**Comment by TheWerdOfRa** [comment]
Thank you for explaining this option. This is much easier, it didn't work as you said though: I needed to keep the stock.json in there and with all the original entries.

Is there anyway to restrict gauge for building engines and track so that there is only one option? (or no option if possible)

**Comment by Larky2k** [comment]
if your on survival you can enable gauge lock in config

**Comment by TheWerdOfRa** [comment]
Amazing, this was so helpful. Thank you :)

**Comment by hh775** [comment]
Someone Please Check my Issue "https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1535"
