### ISSUE TITLE
Texture go funky with models when returning from other dimensions/respawning

### ISSUE THREAD

**Issue by SpaceCat97** [TeamOpenIndustry/ImmersiveRailroading#940]
**Describe the bug**  
Models don't have their original texture when I respawn from another dimension.
So far, this has been consistent with returning from the end and nether. First case did it with a train and second case did it with the rail track (all tracks)

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to a different dimension
 2. Explore
 3. Return to overworld. Either by dying or using a portal.
 
**Expected behavior**  
Textures should be normal.

**Screenshots**  
![image](https://user-images.githubusercontent.com/12462443/108511443-d3a01f00-72b7-11eb-9fa7-956faad4a096.png)

**System Information**  
 OS: Win 10 x64
 <br>System Memory: 16GB
 <br>Allocated Memory: 10GB
 <br>CPU: Intel i7 6700k 4GHz
 <br>GPU: Gigabyte GTX 1060
 <br>IR-Version: 1.16.4-1.8.0.1
 <br>Forge-Version: 1.16.4-35.1.37

**Modlist**  
https://pastebin.com/XVhgCkUW
 
**latest.log**
https://pastebin.com/dzbLubks

**Comment by TheSnowyChickens** [comment]
hehe, same here. xd
(but this time, I just placed tracks)

![grafik](https://user-images.githubusercontent.com/29357962/129250159-9852eb87-64da-476d-875a-e47575386757.png)

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/129457990-9849a5f0-7023-4da8-b96f-a2090750fe91.png)

It's getting even more worse.

**Comment by cam72cam** [comment]
I think I found the issue, are you also on 1.16.5 @TheSnowyChickens ?

**Comment by TheSnowyChickens** [comment]
all in 1.16.5

**Comment by cam72cam** [comment]
Give https://teamopenindustry.cc/maven/cam72cam/universalmodcore/UniversalModCore/1.16.5-forge-1.1.2-dec3e0/UniversalModCore-1.16.5-forge-1.1.2-dec3e0.jar a try

**Comment by TheSnowyChickens** [comment]
okay, after some testing (placing tracks, switching dimensions, placing trains, driving with mrCrayfishs cars and bikes), I got no texture issues so far.
👍
