### ISSUE TITLE
Getting error: Missing 3 when trying to place tracks

### ISSUE THREAD

**Issue by SSchnardthorst** [TeamOpenIndustry/ImmersiveRailroading#946]
Everytime I try and place a track in survival I keep getting the error: Missing 3, I have plenty of rail segments and wood planks and it's not letting me place them

**Comment by noa557** [comment]
Make sure you have "TrackAPI" Installed, it is what adds the tracks to the mod, hope this helps!

**Comment by Larky2k** [comment]
Track API doesn't add track. Missing 3 is a bug if you don't have IE installed. It should use vanilla items but doesn't

**Comment by cam72cam** [comment]
Fixed in the next release
