### ISSUE TITLE
Track material jumped sky high

### ISSUE THREAD

**Issue by NitroRunner222** [TeamOpenIndustry/ImmersiveRailroading#947]
**Describe the bug**  
The cost of the materials became an unbelievable amount and i cannot figure out how i got it like that or how to fix it.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to N/A
 2. Do N/A
 3. N/A
 
**Expected behavior**  
 I thought that the tracks only costed 3 treated wood planks and 5 rails for a section of 10 block of rails. 

**Screenshots**  
![2021-03-16](https://user-images.githubusercontent.com/80796816/111395874-78c5d180-8683-11eb-90ba-e3533e940eb4.png)

**System Information**  
 OS: [e.g. Windows]
 <br>System Memory:  32GB
 <br>Allocated Memory:   18GB
 <br>CPU: AMD Ryzen 7 1700x Eight-Core Processor GHz
 <br>GPU:  GeForce GTX 1060 3GB
 <br>IR-Version: 1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2854

**Modlist**  
bspkrsCore-universal
Treecapitator
Additional pipes
Advanced X-ray
Applied Energetics
Better builders wands
biomes o'plenty
Buildcraft
code chicken lib
cofhcore
cofhworld
doomlike dungeons
ender compass
extra utilities
fps reducer
galacticraft
galacticraft planets
Hwyla
immersive engineering
immersive Railroading
in game wiki
inventory tweaks
iron chests
just enough items
journeymap
limelib
mantle
mekanism core
mekanism generators
mekanism tools
micdoodle core
multihotbar
multihotbar core
open computers
player storage
Redstone flux api
thermal dynamics
thermal foundation
tinkers construct
tinkers reforged
total tinkers
track api
waila harvestability
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
started after I had gotten stuck in a Buildcraft pump line and had to remove the mod to get unstuck.

**Comment by cam72cam** [comment]
Can you post a screenshot of the track GUI of the track you are trying to place?
