### ISSUE TITLE
I cant change rail types or controll trains,also I cant remove them,I need to use tnt.

### ISSUE THREAD

**Issue by madmagic2005** [TeamOpenIndustry/ImmersiveRailroading#948]
**Describe the bug**  
I use an aternos server to play with my friends.I am unable to change the settings for rails in the rail blueprint and I cant control trains whilst they can.We use the same mods with the same versions.In singleplayer Im able to use them.

**How to reproduce**  
I dont know how to reproduce this,it seems to only happen to me.
 
**Expected behavior**  
 A clear description of what you expected to happen.

**Screenshots**  

**System Information**  
 OS: Windows
CPU: AMD Ryzen 5 24000G
GPU:AMD Radeon RX Vega 11 Graphics
RAM: 24 GB DDR4

**Modlist**  
Camera Mod
Immersive Engineering
Immersive Railroading
Dynamic Surroundings
Terra Forged

 
**latest.log**
https://pastebin.com/Bau7rgd6

**Additional context**  
Im sorry but Im using TLauncher,I cant currently afford Minecraft.

**Comment by Larky2k** [comment]
IR doesn't play well with Aternos, and the fact your playing a cracked copy of MC we can't really help
