### ISSUE TITLE
Exceptions caught every frame on render thread

### ISSUE THREAD

**Issue by Sukasa** [TeamOpenIndustry/ImmersiveRailroading#952]
**Describe the bug**  
Seemingly every frame, Minecraft is logging an exception in rendering

**How to reproduce**  
Steps to reproduce the unwanted behavior:

1. Start game, join Multiplayer server
2. Check log
 
**Expected behavior**  
No errors

**Screenshots**
None 

**System Information**  
 OS: Windows 10 Pro
 <br>System Memory: 32GB
 <br>Allocated Memory: 6GB
 <br>CPU: i7-7700k
 <br>GPU: GTX 1080ti
 <br>IR-Version: 1.16.4-forge-1.8.0.1
 <br>Forge-Version: 1.16.5 36.0.42

**Modlist**  
 Modpack: Automation Nation! version 1.3.0
 
**latest.log**
Log snippet because the log is too big to upload in entirety:
[error.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6194151/error.txt)

**Additional context**  
No IR stuff has even been built in this world yet

**Comment by cam72cam** [comment]
For now downgrade java to 1.8.  Newer java versions removed a feature I rely on.
