### ISSUE TITLE
1.16.5 Bug in Jei

### ISSUE THREAD

**Issue by Senyum** [TeamOpenIndustry/ImmersiveRailroading#956]
Hi, I saw a small bug and decided to report it, the wrenches are out of the gui
Forge 1.16.5-36.1.0
ImmersiveRailroading-1.16.4-forge-1.8.0.1
Jei-1.16.5-7.6.1.75
![Screenshot_3](https://user-images.githubusercontent.com/36424845/113523272-80f09d00-95af-11eb-8fc6-85719c9670aa.png)

**Comment by cam72cam** [comment]
It's exaggerated by design
