### ISSUE TITLE
Slopes not working properly in Minecraft Gauge

### ISSUE THREAD

**Issue by GamingCrafthd** [TeamOpenIndustry/ImmersiveRailroading#957]
(I think this issue doesn't need much text)

![grafik](https://user-images.githubusercontent.com/49761607/113607652-ba75e680-9649-11eb-9ed3-941d4ea3f37e.png)
![grafik](https://user-images.githubusercontent.com/49761607/113607672-c2358b00-9649-11eb-8734-dee1e78ba47e.png)

This issue is for the Minecraft Gauge and maybe for others too, didn't test that tho.

**Comment by cam72cam** [comment]
@GamingCrafthd version numbers are always appreciated

**Comment by GamingCrafthd** [comment]
![grafik](https://user-images.githubusercontent.com/49761607/113751467-45b7b080-970c-11eb-8f49-29a354ca83d8.png)
@cam72cam

**Comment by cam72cam** [comment]
thanks
