### ISSUE TITLE
ComputerCraft/CC:Tweaked Event compatibility

### ISSUE THREAD

**Issue by Enlight3ned** [TeamOpenIndustry/ImmersiveRailroading#959]
**Describe the suggestion**  
So you know how OpenComputers has support for Detector augment Events? How about adding compatibility with ComputerCraft/CCTweaked? I mean, everything else works, it's just events that are screwed up.

**Applications of the suggestion**  
Allows for much more optimized code. For example: Instead of having a while loop constantly running getTag() to... get the tag... I can use:
os.pullEvent("ir_train_overhead")
print(BlahBlahBlah.getTag())

While testing this out in a world, I do manage to get "peripheral" and "peripheral_detach" while a train is overhead or not respectively. This means that the detector events already (kinda) work, but the event names are broken. (bug?)

Anyways, I hope you can add/fix the events for CC.

**Comment by cam72cam** [comment]
Will be released in the next version
