### ISSUE TITLE
Minecart Gauge tracks do not work with minecarts

### ISSUE THREAD

**Issue by DestroyerMCE** [TeamOpenIndustry/ImmersiveRailroading#960]
Minecarts will not travel along IR minecart gauge rails

Steps to reproduce the unwanted behavior:
    Make a minecart gauge rail.
    Try to put minecart on rail.
    Witness it not work.

Expected:
The minecart would use the rail.

i feel like further info is not necessary, and i am not even sure if this is a bug

**Comment by Larky2k** [comment]
Not a bug
