### ISSUE TITLE
Not letting me create world

### ISSUE THREAD

**Issue by noa557** [TeamOpenIndustry/ImmersiveRailroading#963]
I am using Biomes o Plenty, Immersive Engineering, and Immersive railroading, Engineering and Biomes work fine together but when I add Immersive Railroading (And TrackAPI and Universal Modcore) it just says "Safe Mode" (Vanilla Minecraft) and "Go back to main menu to try to fix problem manually" I try removing Immersive Railroading, and once again, works fine, I try removing Biomes O Plenty and adding Immersive Railroading back in, but nope! Same error! I have no idea what to do, any ideas?

**Comment by Larky2k** [comment]
Delete Config folder and restart MC

**Comment by noa557** [comment]
> Delete Config folder and restart MC

Thank you so much! I have been trying to fix this since yesterday and I finally decided to ask for help!
