### ISSUE TITLE
Can we get some click-clacking sounds for trains moving along the tracks?

### ISSUE THREAD

**Issue by Tanukipack** [TeamOpenIndustry/ImmersiveRailroading#965]
It's as simple as the titles says, the click-clack sound of trains going over the gaps between rail sections (note: this is at a 39-foot (~12 meters/blocks) intervals, so maybe the frequency of the sound could be dependent on speed?)

It's just kind of eerie when you're standing next to a moving train and there's no sound at all from it (and the engine is too far to be heard)

**Comment by Aeris1One** [comment]
Maybe depending on locomotive age, the sound can change (suppose "recent locomotives are on recent tracks so there's no more gaps and no more click-clack sound")

**Comment by andrboot** [comment]
There is that kind of sounds presently, depends on track/stock I believe and speed.

**Comment by cam72cam** [comment]
This already exists.  If you are playing in newer versions of minecraft, the sound system may be slightly bugged
