### ISSUE TITLE
THAT NOISE

### ISSUE THREAD

**Issue by Anhilowasntavailabewhotookit** [TeamOpenIndustry/ImmersiveRailroading#971]
For some reason, when it literally just moves on the tracks, it plays the noise that plays when you place a train down. CONSTANTLY.

**How to reproduce**  
Literally drive a train

 1. Go to minecraft
 2. Make a train
 3. drive it
 
**Expected behavior**  
 i dunno, i expected it to be a normal train sound?

**Screenshots**  
 N/A

**Modlist**  
 This mod and the voxel trains IR resourcepack
 
**latest.log**
 Its... not a crash.

**Additional context**  
it seems to play when it transfers to a different track, as in, when you place down another straight, curved, any kind of track thats somehow connected to another, then the train will play the sound when moving on to the connected track.

**Comment by andrboot** [comment]
What version of IR are you using, what version of forge?
Can you potentially record the problem and upload a short clip of it?

**Comment by andrboot** [comment]
This issue has been fixed in the latest test build, hopefully will be released soon as mainline.
You can get it temporary from the test-build channel on discord, though always backup your world before applying test-builds.
