### ISSUE TITLE
Shader Issue? Any workarounds or compatible shaders?

### ISSUE THREAD

**Issue by JCraven94** [TeamOpenIndustry/ImmersiveRailroading#974]
Hello, reporting what I believe is a known shader issue which causes the railbed fill texture to get pretty out of hand, also causes an issue with the turntable. 
![2021-05-11_21 06 33](https://user-images.githubusercontent.com/84052686/117903221-24168f80-b29d-11eb-8ff7-0368e6205683.png)
![2021-05-11_21 06 40](https://user-images.githubusercontent.com/84052686/117903233-27aa1680-b29d-11eb-9e1c-fa925968e9a0.png)
![2021-05-11_21 06 43](https://user-images.githubusercontent.com/84052686/117903241-2b3d9d80-b29d-11eb-9ea2-c32380412247.png)
![2021-05-11_21 06 48](https://user-images.githubusercontent.com/84052686/117903252-2f69bb00-b29d-11eb-9799-86cedea39947.png)

I understand the limitations of mods, so I'm not really upset. This is a really awesome mod, would just love to see it with shaders to! Any info on a work around or compatible shader?

**Comment by Larky2k** [comment]
the issue is due to the way shaders work in 1.15+

**Comment by JCraven94** [comment]
> the issue is due to the way shaders work in 1.15+

No workarounds? Just limitations of the game I'm guessing.

**Comment by Larky2k** [comment]
none at moment part form not use shaders or turn road bed off

**Comment by Larky2k** [comment]
Fix will be coming in next update :), not sure on turntable one

**Comment by Wilson159** [comment]
> Fix will be coming in next update :), not sure on turntable one

Eta on that next update? ;)

**Comment by cam72cam** [comment]
In the next few days
