### ISSUE TITLE
Once the train is built, things broke. Machinery and trains are inaccessible for the host.

### ISSUE THREAD

**Issue by EvrenFrostwind** [TeamOpenIndustry/ImmersiveRailroading#975]
My friend (Host) and I have a survival modded world (With 93 mods) and when my friend started building the train parts, the world started breaking. 

* When placing train tracks they act as full blocks and not what shape they are suppose to be
* My friend couldn't access the machines 
* Couldn't see train parts being placed down
* Couldn't enter train
* Some times the trains would move, but you couldn't see them moving
* Would constantly get the OpenGl: 1281 error (Only appears around immersive engineering and railroading stuff)

This is all we could remember happening, I will update this when more problems arise. (In creative worlds, we would still get the OpenGl errors but not the otrher problems listed)

**Comment by andrboot** [comment]
Please provide the modlist, forge version, minecraft version as well.
In terms of errors generally indicates you don't have enough memory/graphics memory to process.
We would need to know your server/pc cpu, memory and GPU as well.

**Comment by EvrenFrostwind** [comment]
All the mods we use are in this drop box https://www.dropbox.com/sh/f7sa8d9o8ozzvsu/AADUV7H2gVUSc8FWA0CsxlpFa?dl=0
We're using 1.16.5
The Forge version we are using is 1.16.5-forge-36.1.13
I have already allocated 14GB of Ram and my friend has 16GB 
My friend's specs is i5 9600k, gtx 1060 6gb, 16 gb ddr4 ram

**Comment by Larky2k** [comment]
Is the server just a normal Forge server or is it a bukkit style API?

**Comment by EvrenFrostwind** [comment]
normal Forge, it's a LAN server

**Comment by Larky2k** [comment]
Ok have you switched it around where you Host and your friend joins and see if the issue switches user.

**Comment by EvrenFrostwind** [comment]
We switched the worlds and It's still the same problem even when I host. I could access the trains even with the error but my friend still can't, and in a creative world we found out the plate stamper was the one that started creating the 1281 errors.

**Comment by Larky2k** [comment]
So this issue is purely your friends end
