### ISSUE TITLE
Functional Lighting

### ISSUE THREAD

**Issue by novacheri** [TeamOpenIndustry/ImmersiveRailroading#978]
May just be me, but something I'd like to see in the future is functional lighting for head-lights, tail-lights, and possibly interior lighting for passenger cars and locomotive cabs being possible. I'd think this would help a lot with track visibility at night when your lighting is set low, but more importantly I think it would help with immersion, since locomotives with head lights have zero functionality for them, currently. I didn't see anything about this in the projects page, nor issues, sorry if this has already been brought up before.

**Comment by km00700** [comment]
This is planned, but there are many backend features to be upgraded first.

**Comment by cam72cam** [comment]
Closing as a duplicate
