### ISSUE TITLE
Fix Config Folder Language Injection 

### ISSUE THREAD

**Issue by km00700** [TeamOpenIndustry/ImmersiveRailroading#982]
**Describe the suggestion**  
On startup, search config folder RPs for lang files and concatenate their contents. Move the contents into a lang file in an "ImmersiveRailroading" resource pack located in the resource pack directory. IR RP would be auto-assigned an mcmeta version number based on the MC for the installed UMC.

**Applications of the suggestion**  
Lang files are not loaded if the resource pack is loaded via the config folder method. They must be loaded via the resource pack menu to work properly.

**Comment by cam72cam** [comment]
I don't thing there's a good way to do this unfortunately
