### ISSUE TITLE
Hello! Hope you are having a great day. But I want to ask about why can't I get on the train. I tried right clicking on it and the screen will just freeze.

### ISSUE THREAD

**Issue by SillyGuy1234** [TeamOpenIndustry/ImmersiveRailroading#983]

**Comment by km00700** [comment]
send latest.log and your mod-list.

**Comment by Shambler14** [comment]
I'm having the same problem, in which I go to use a locomotive, and it either kicks me out, or I end up getting stuck in air. this only happens on the server I am playing on, as I've tested it in a private world and it works fine.

[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6518020/latest.log)

mod list
![mod list](https://user-images.githubusercontent.com/84538141/119030061-a7ec0e00-b966-11eb-822a-69ddf13eaeb6.png)

**Comment by Shambler14** [comment]
also the server owner just gave me the plugin list

 we're currently working through them to see if their affecting it

![image](https://user-images.githubusercontent.com/84538141/119039271-4a10f380-b971-11eb-9f23-0e8c92f37f0a.png)

**Comment by Larky2k** [comment]
Cant use plugin API with IR it highjacks the packets and breaks IR, can only use Forge only servers at the moment

**Comment by Shambler14** [comment]
Ok, thanks for the info, we'll see if we can remove the plugins and replace them with mods that fill in their role

**Comment by BrownXu321123456** [comment]
Hello. Will this be fix in the future? My server has many necessary plug-ins that cannot be replaced by mods, and I really want to build a railway that can be use by me and other players in my server.

**Comment by Larky2k** [comment]
IR isn't compatible with plugin servers as it breaks IR. If you can't live without plugins them you got to remove IR

**Comment by BrownXu321123456** [comment]
Yep I know they are not compatible at the moment, I'm asking will they be compatible in the future. Thanks!

**Comment by Larky2k** [comment]
They won't unless the plugins change the way they handle packets

**Comment by BrownXu321123456** [comment]
Ok, that's sad. Thanks for the reply anyway.

**Comment by Bogdan7200** [comment]
I have _MohistMC_  [https://mohistmc.com/](url)
#1002
