### ISSUE TITLE
Tracks can't be build in Survival when playing without Immersive Engineering

### ISSUE THREAD

**Issue by YouFancyMe** [TeamOpenIndustry/ImmersiveRailroading#985]
**Describe the bug**  
Whenever the mod is installed without Immersive Engineering (IE) there is no alternative given to IE block "Treated Wood".
Additionally, there is no way to implement or change the default block like there is with fuel.

**How to reproduce**  

 1. Install Immersive Railroading without Immersive Engineering
 2. Try to place Tracks in Survival Mode
 
**Expected behavior**  
 Alternative to "Treated Wood"

**Screenshots**  
![2021-06-04_17 06 43](https://user-images.githubusercontent.com/85358872/120837128-a32e7900-c566-11eb-9a4f-ef776fd3b999.png)

**Comment by cam72cam** [comment]
Please include the minecraft version and IR version

**Comment by YouFancyMe** [comment]
Minecraft 1.16.5
IR 1.8.0.1

**Comment by cam72cam** [comment]
Will be fixed in the next release
