### ISSUE TITLE
RTX3090 only give me 20-30FPS around railroad

### ISSUE THREAD

**Issue by ink717** [TeamOpenIndustry/ImmersiveRailroading#987]
We used IR in a server and whenever we build train tracks or placing trains, the surrounding chunks suffer FPS drop of nearly 20-30, the same with or without shaders, never exceeding 60.  With my RTX3090 I only get 20-30 FPS nearly all the time near train stations. Tried change around the config and had no success. 

I saw that railroads were actually blocks, not entities, is there anything to do with how these special blocks work in-game? 
Another member with a new RTX3080Ti also reported exactly the same issue.

Also, crash happens when driving the train (in some rare occasion. I believe it's an Optifine issue instead of IR itself.

[debug-report-2021-06-12_11.04.45.zip](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6642416/debug-report-2021-06-12_11.04.45.zip)

[profile-results-2021-06-12_11.01.43.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6642414/profile-results-2021-06-12_11.01.43.txt)

**Comment by Larky2k** [comment]
Need system information and server information

**Comment by ink717** [comment]
[server details.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6642568/server.details.txt)
[system info.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6642569/system.info.txt)

**Comment by Larky2k** [comment]
For starters you don't need 25gb allocated to MC java is really really bad when it has to much RAM 8-10gb is fine.
When I say info I need server specs and client specs.

**Comment by ink717** [comment]
Client (mine): 
i9-10850K CPU, MSI Z490, EVGA FTW3 RTX3090, 64GB DDR4 3200 RAM, using NVME M2 drive for MC.

Server:
i5-10400 CPU, ASUS H470, 32GB DDR4 2666 RAM, main drive using NVME M2.

[client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6642595/client.txt)
[server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6642597/server.txt)
