### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by UrHeadset** [TeamOpenIndustry/ImmersiveRailroading#992]
When I put Immersive Railroading and try to load or create a world minecraft tells me something is wrong with my data packs and just refuses to load anything, even pressing the safe mode button does nothing at all and when I take the mod out everything works fine. It doesn't work regardless of what other mods are present and it also doesn't create a crash-log. I have no idea what is going on here and for other people it seems to work fine. Please help

**Comment by Larky2k** [comment]
Close MC down, delete config folder, restart MC

**Comment by cam72cam** [comment]
Larky's suggestion should work, and this bug should be fixed in the next version
