### ISSUE TITLE
Train icons not showing

### ISSUE THREAD

**Issue by NightmareYT46** [TeamOpenIndustry/ImmersiveRailroading#995]
**Describe the bug**  
The train icpns are black and white

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go to the inventory
 2. Go to the train area in the inventory
 3. Then it shows
 
**Expected behavior**  
 I expected it to actually work

**Screenshots**  
 

**System Information**  
 OS: Linux (debian based)
 <br>System Memory: 4gb
 <br>Allocated Memory: 544mb
 <br>CPU: AMD Dual-Core A4-9120
 <br>GPU: AMD Radeon R3 integrated 
 <br>IR-Version: cant find
 <br>Forge-Version: 1.7.10 10.13.4.1614

**Modlist**  
 Optifine 1.7.10_HD_U_E7
 
**latest.log**
 No useful info

**Additional context**  
Sometimes the trains have a little bit of detail in the icons but not much

**Comment by km00700** [comment]
Disable Optifine Fast Render. Delete your .minecraft/cache folder. Then launch MC.
