### ISSUE TITLE
Game crashes when opening an inventory

### ISSUE THREAD

**Issue by DJ-Yellowie** [TeamOpenIndustry/ImmersiveRailroading#996]
**Describe the bug**  
Sometimes when opening an inventory of machine from IR or an inventory containing an item from IR the game will crash with no stack trace of the error

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. open an inventory of machine from IR or an inventory containing an item from IR,
 
**Expected behavior**  
the game opens the inventory

**Screenshots**  

**System Information**  
 OS: windows 10
 <br>System Memory: 32Gb
 <br>Allocated Memory: 20Gb
 <br>CPU: AMD Ryzen 7 3700X 8-Core Processor - 3.59 GHz
 <br>GPU: AMD Radeon RX 5700 - 8Gb Vram
 <br>IR-Version: 1.8.1 - 1.16.4
 <br>Forge-Version: 1.16.5 - forge 36.1.23

**Modlist**  
[modpack.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6697861/modpack.txt)

 
**latest.log**
[2021-06-21-1.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/6697863/2021-06-21-1.log)

**Additional context**  
it only does it sometimes. cant seem to find anything more than opening an inventory.
is client side as I (host) play on a lan server with a mate. They get the same crash (i assume. same cause and no stack trace) but i dont then crash.
seems to be after being in the world for about 5 min or so, some times more, never less. When logging back in game goes back to the last autosave, so when it crashes it doesnt save the world.

**Comment by Larky2k** [comment]
Hi DJ-Yellowie
try the work around from this issue raised and see if that fixes it
#803

**Comment by DJ-Yellowie** [comment]
No quite sure what I am meant to do or what jar files I'm meant to modify. If you have more information that would be appreciated. :). I do get the issue of it only giving me 1024MB of VRAM but sometime in the log it shows 6144MB/6144MB VRAM. I have a 8GB video card. So idk where 6144MB is coming from.

**Comment by Larky2k** [comment]
Its your AMD Drivers you edit nothing to do with jar. Did you look at the post I refrenced

**Comment by DJ-Yellowie** [comment]
yeah I wasn't sure exactly what they were editing

**Comment by Larky2k** [comment]
Do a search for those .class files and edit it and see what happens

**Comment by DJ-Yellowie** [comment]
searched my entire C drive for GPUinfo_6144.class and nothing came up

**Comment by Larky2k** [comment]
Hmm, all I can say see if there an option with AMD drivers to tell it to use your card for Java and see if that forces it to use it all

**Comment by DJ-Yellowie** [comment]
ooh thats a good shout ill try that. thank you

**Comment by DJ-Yellowie** [comment]
its using my AMD card, according to the f3 screen
