### ISSUE TITLE
1.7.10 Casting Basin Not working

### ISSUE THREAD

**Issue by Searchcat37** [TeamOpenIndustry/ImmersiveRailroading#997]
**Describe the bug**  
Whenever I drop steel into a Casting basin nothing happens the steel items just sit there

**How to reproduce**  
1. Fully assemble a Casting basin
2. Connect power using Immersive Engineering LV/MV/HV connectors
3. Drop Steel into the basin
4. Watch as the items just sit there
 
**Expected behavior**  
The Casting basin takes in the steel and melts it

**Screenshots**  
<a href="https://ibb.co/3sWFgdL"><img src="https://i.ibb.co/W3Fzm5Y/Screenshot-2021-06-24-093055.png" alt="Screenshot-2021-06-24-093055" border="0" /></a>

**System Information**  
 OS: Windows
 <br>System Memory: 16G
 <br>Allocated Memory: 6G
 <br>CPU: Ryzen 5 1600
 <br>GPU: GTX 1050TI
 <br>IR-Version: 1.8.0-7e0f82
 <br>Forge-Version: 1.7.10 - 10.13.4.1614

**Modlist**  
[Mods](https://pastebin.com/yiSjactg)

**latest.log**
[Log](https://zerobin.net/?6b41d5407761136f#H3EFUWJ5kA55R1d+vtw52apfa1QykiWicU6MStqInL8=)

**Additional context**  
N/a

**Comment by Larky2k** [comment]
Would help if you used HV wire instead of Steel wire

**Comment by km00700** [comment]
IR machines should work with LV systems.

**Comment by Searchcat37** [comment]
I used HV

**Comment by Searchcat37** [comment]
I switch to a Flux plug to make sure there were no power problems, but nothing changed

<a href="https://imgbb.com/"><img src="https://i.ibb.co/sQX1wWJ/Screenshot-2021-06-24-120328.png" alt="Screenshot-2021-06-24-120328" border="0"></a>

**Comment by km00700** [comment]
iirc Flux plugs don't work

**Comment by Searchcat37** [comment]
Well I had to try

**Comment by Searchcat37** [comment]
Anyone have any ideas?

**Comment by Searchcat37** [comment]
It works if I go back to ImmersiveRailroading-1.7.3_1.7.10 but I don't exactly like using beta versions

**Comment by Searchcat37** [comment]
Welp, I found a solution and it sucks
[Video](https://www.youtube.com/watch?v=gj01S5FD8_A)

**Comment by cam72cam** [comment]
This will be fixed in the next version (ref 96f93dda)
