### ISSUE TITLE
No temperature! I want to take a train, but Disel trains take a long time to warm up. I've waited 1 hour and it's 16.7 ° C.

### ISSUE THREAD

**Issue by GamingMaus20** [TeamOpenIndustry/ImmersiveRailroading#999]

**Comment by GamingMaus20** [comment]
Ich habe gerade eine Dampflokomotive aufgeheitzt und wolte fahren aber sie fährt nicht die tempratur ist bei 100 und ich habe voll gas gegeben aber es passiert nichts ich habe manchmal 0.2 PSI (mit vollgas). Was soll ich machen

**Comment by GamingMaus20** [comment]
Ich habe jetzt mehr als 22 PSI werde aber ich werde sofort wieder aus den Zug geworfen

**Comment by Larky2k** [comment]
Bug Report needs to be in English

**Comment by GamingMaus20** [comment]
sometimes i'm thrown off the train

**Comment by Larky2k** [comment]
With diesels if you open the throttle it will hear up faster, with steam fill all fire box with coal once steam is made all you need is 1 slot. Steam will take a long time

**Comment by GamingMaus20** [comment]
I have powerd a Steam locomotive it had take 10 min. I have waiting for 3 hours but the disel locomotive taks very long. I will try to give a litelbit thorttle. Thank you for your help :D

**Comment by GamingMaus20** [comment]
I have lookt and I have seen that all my Disel locomotive have 17,2°C (with full throttle). What can i do?

**Comment by Larky2k** [comment]
Have you turned them on? + On numpad

**Comment by GamingMaus20** [comment]
Yes i did
